### ISSUE TITLE
`lexical` and `fast-float` might soon not be needed.

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#1010]
#### Describe your feature request

`lexical` and `fast-float` might soon not be needed anymore as fast-float like algorithm is merged in the standard library.

https://github.com/rust-lang/rust/pull/86761
https://www.reddit.com/r/rust/comments/omelz4/making_rust_float_parsing_fast_libcore_edition/

**Comment by ritchie46** [comment]
I saw! :slightly_smiling_face: 

We still need `lexical` for the integer parsing, but `fast-float` is out.

**Comment by Alexhuszagh** [comment]
> I saw! slightly_smiling_face
> 
> We still need `lexical` for the integer parsing, but `fast-float` is out.

I'll be working on making lexical lighter for integer parsing. So compile times should increase. And, ideally, bring those back into Rust core as well.

**Comment by ritchie46** [comment]
> I'll be working on making lexical lighter for integer parsing (as in, using workspaces for each different component). So compile times should decrease. And, ideally, bring those back into Rust core as well.

Very nice. Great work on the float parsing. :rocket:

**Comment by Alexhuszagh** [comment]
Just an FYI: the optimized versions of the new integer and float-parsers have been implemented as of [v0.8](https://crates.io/crates/lexical-core), and the API is identical. However, it does require a fairly recent Rust compiler (1.51.0), due to the requirement of const generics. I'm currently also trying to integrate the further improvements back into Rust core now.

**Comment by ritchie46** [comment]
> Just an FYI: the optimized versions of the new integer and float-parsers have been implemented as of v0.8, and the API is identical. However, it does require a fairly recent Rust compiler (1.51.0), due to the requirement of const generics. I'm currently also trying to integrate the further improvements back into Rust core now.

Great! I will update! Thank you for your great work on lexical. 
I don't know the ins and outs, so I have a few questions:

* How does lexical float parsing now compares to `fast-float`.
* Is the lexical float parsing algorithm the one that gets embedding in rust std?

**Comment by Alexhuszagh** [comment]
> > Just an FYI: the optimized versions of the new integer and float-parsers have been implemented as of v0.8, and the API is identical. However, it does require a fairly recent Rust compiler (1.51.0), due to the requirement of const generics. I'm currently also trying to integrate the further improvements back into Rust core now.
> 
> Great! I will update! Thank you for your great work on lexical.
> I don't know the ins and outs, so I have a few questions:
> 
>     * How does lexical float parsing now compares to `fast-float`.

They're practically identical, except for rare cases. The extensive benchmarks compared to rust std can be found [here](https://github.com/Alexhuszagh/rust-lexical/blob/main/lexical-parse-float/docs/Benchmarks.md), and the results for rust std are practically identical to fast-float-rust.

>     * Is the lexical float parsing algorithm the one that gets embedding in rust std.

Yes it is, except for the slow algorithm. In fact, I currently have issues (in [core](https://github.com/rust-lang/rust/issues/88656) and [fast-float-rust](https://github.com/aldanor/fast-float-rust/issues/32)) and will be writing PRs (and an upstream PR for the reference C++ [implementation](https://github.com/fastfloat/fast_float/pull/96)). This can be quite a difference in performance for very rare cases, but can have impacts on a few real-world datasets (as shown below, in mesh).

So short term, they're similar, but lexical has a few optimizations the others don't have. Long-term, they will ideally be identical, because I want everyone to benefit.

# Detailed Benchmarks

The most relevant result is this, which benchmarks against a few real-world datasets:
![Real Benchmark](https://raw.githubusercontent.com/Alexhuszagh/rust-lexical/main/lexical-parse-float/assets/real.svg)

Canada is practically identical, while for earth and most important mesh, lexical is faster. The datasets can be found here:

- [canada.txt](https://github.com/Alexhuszagh/rust-lexical/blob/main/lexical-benchmark/data/canada.txt)
- [earth.csv](https://github.com/Alexhuszagh/rust-lexical/blob/main/lexical-benchmark/data/earth.csv)
- [mesh.txt](https://github.com/Alexhuszagh/rust-lexical/blob/main/lexical-benchmark/data/mesh.txt)

The biggest difference is in near-halfway cases, otherwise, the performance is nearly identical. The near-halfway cases with differing digit counts are as follows:

![Contrived Data](https://raw.githubusercontent.com/Alexhuszagh/rust-lexical/main/lexical-parse-float/assets/contrived.svg)
![Large Data](https://raw.githubusercontent.com/Alexhuszagh/rust-lexical/main/lexical-parse-float/assets/large.svg)
![Denormal Data](https://raw.githubusercontent.com/Alexhuszagh/rust-lexical/main/lexical-parse-float/assets/denormal.svg)

These are obviously contrived cases, but meant to demonstrate worst-case scenarios and performance of specific algorithms.
