### ISSUE TITLE
issues due to new project structure

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#10199]
I think we need to revert the new project structure until these problems are solved. 

Currently there are 2 problems. 

1. the build.rs file isn't applied anymore. Local `pre-commit` will fail because of new lints. They are somehow not triggered in CI.
2. The integation tests fail locally, but not in CI. `cargo t --features=test --test=it` has failed tests locally that were not happening before.

I think those changes are related to the new structure.

@stinodego, tuning you in here.

**Comment by stinodego** [comment]
I'll take a look at these, thanks. Just revert for now!

**Comment by ritchie46** [comment]
No opposition. If the issues are resolved happy to gor forward with this.

**Comment by stinodego** [comment]
The reason for the discrepancy between clippy in the CI and locally is because the CI runs `clippy` with default features on stable, and `clippy` on all features on nightly. Locally it now runs `clippy` with default features on nightly. So there's the issue. Looking into `build.rs` atm.

**Comment by stinodego** [comment]
I believe this can now be closed.

The reason for these issues popping up is that we're now operating on a Cargo workspace instead of on a single crate in a Cargo workspace. There are a few things to iron out still, I'll keep working on those. Feel free to tag me in this issue if you run into anything.
