### ISSUE TITLE
Support Datetime with seconds resolution

### ISSUE THREAD

**Issue by jerr0328** [pola-rs/polars#10299]
### Problem description

I have data where the timestamps are Unix timestamps in seconds, not ns/us/ms. I want to be able to specify a datatype like `pl.Datetime("s")`. I found that #2543 had a change to support that from underlying Arrow data, but that seconds are not able to be set in Polars. These timestamps are generated from standard Python datetime objects using their `.timestamp()` function (and serialized as an integer in my case) so if I wanted to use it with Polars I'd have to first multiply all the times by 1000 before casting to `pl.Datetime("ms")` which is not ideal when there are several timestamps all around.

**Comment by orlp** [comment]
Do you feel your usecase is sufficiently addressed by using [`polars.from_epoch`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.from_epoch.html#polars-from-epoch) instead of casting?

**Comment by jerr0328** [comment]
I was hoping to be able to provide the column types in schema/schema_overrides when creating the DataFrame. At least the `from_epoch` would make it so I don't need to multiply and cast, but I do wish there was a more "native" way to define those immediately as datetimes (especially since I don't want/need any precision beyond integer seconds)

**Comment by orlp** [comment]
> I was hoping to be able to provide the column types in schema/schema_overrides when creating the DataFrame.

Polars schemas specify the actual physical types the data has in the machine, not semantics. If your data comes in a different format that does not directly correspond to one of those, there will be a conversion step.

It *may* seem like the unit parameter on the `DateTime` field is meant to support arbitrary time units for a semantically useful perspective, but this is not the case. It is purely an engineering trade-off of precision vs. range.

The only reason it is like it is is now because a 64-bit integer of nanoseconds only supports ~300 years, which is not enough for all use cases. That is why microseconds and milliseconds were added, for efficiently supporting larger date ranges at the cost of precision, *not* to store some sort of time unit semantics in the datatype. Since milliseconds already supports ~300 million years of time range, we see no reason to further complicate things with adding seconds.

I could easily see users confuse the purpose of the unit parameter to be semantics if we add seconds, leading to inadvertently imprecise data processing.

**Comment by MarcoGorelli** [comment]
> Since milliseconds already support ~300 million years of time range

Yup - and a far biggest limitation is that [chrono ](https://docs.rs/chrono/latest/chrono/) only* supports years +/- 262,000, so even if second resolution were added, it wouldn't be able to get around that

*I'd have thought this was enough for any use case, but then I worked with some paleoclimatologists last year 😄

**Comment by jerr0328** [comment]
Thank you @orlp for the explanation, it makes sense. I'm thinking if it would be helpful to add that explanation to the docs, especially to help cement it early on that the types are not meant to be the semantic type?

I'm also thinking about the User Guide having a section as well to introduce the `from_epoch` function in the [Parsing](https://pola-rs.github.io/polars-book/user-guide/transformations/time-series/parsing/) section, which would have been very helpful for me to find it (I didn't think to check "epoch" as a term)
