### ISSUE TITLE
n_unique with Utf8 vs IntXX

### ISSUE THREAD

**Issue by MariusMerkleQC** [pola-rs/polars#10565]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl

df_int = pl.DataFrame(data={"a": []}, schema={"a": pl.Int16})
df_int.filter(pl.col("a").n_unique().over("test") == 1)


df_str = pl.DataFrame(data={"a": []}, schema={"a": pl.Utf8})
df_str.filter(pl.col("a").n_unique().over("test") == 1)

```

### Issue description

For an empty dataframe, if the `dtype` is `Utf8`, the comparison == 1 throws an error.

### Expected behavior

For an empty dataframe, if the `dtype` is `Int16` (also `Int8`, `Int32`, and `Int64`) the comparison == 1 works perfectly fine and I would expect the behavior to be the same if `dtype = pl.Utf8`.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            macOS-13.5-arm64-arm-64bit
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.0
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.12
sqlalchemy:          1.4.49
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
None
```

</details>

**Comment by orlp** [comment]
There certainly is something bugged here, but I feel in both cases you should be getting an error because you're grouping over a column that doesn't exist.

**Comment by MariusMerkleQC** [comment]
Well yes, let's say we group over the column `"a"`, then I would expect the comparison to not cause an error.

**Comment by mcrumiller** [comment]
It still does for `utf8`:

```shell
>>> df_int.filter(pl.col("a").n_unique().over("a") == 1) # OK
shape: (0, 1)
┌─────┐
│ a   │
│ --- │
│ i16 │
╞═════╡
└─────┘

>>> df_str.filter(pl.col("a").n_unique().over("a") == 1) # Fail
exceptions.ComputeError: cannot compare utf-8 with numeric data
```

**Comment by mcrumiller** [comment]
I believe that `n_unique().over()` isn't propagating the integer `dtype` out. This works, and it shouldn't:

```shell
>>> df_str.filter(pl.col("a").n_unique().over("a") == 'a')
shape: (0, 1)
┌─────┐
│ a   │
│ --- │
│ str │
╞═════╡
└─────┘
```

**Comment by orlp** [comment]
It works correctly for the lazy API:

```python
>>> df_str.lazy().filter(pl.col("a").n_unique().over("a") == 1).collect()
shape: (0, 1)
┌─────┐
│ a   │
│ --- │
│ str │
╞═════╡
└─────┘
```

**Comment by mcrumiller** [comment]
The problem also exists for `.count().over()`. It doesn't exist for `arg_max()` and `arg_min()`.

**Comment by reswqa** [comment]
> I feel in both cases you should be getting an error because you're grouping over a column that doesn't exist

It seems that the reason for returning an empty `DataFrame` instead of an error here is the following special branch:

https://github.com/pola-rs/polars/blob/9b3007ebb2afd8acb9e4bfa7cd30724b9a011e05/crates/polars-lazy/src/physical_plan/expressions/window.rs#L405-L408

> The problem also exists for .count().over(). It doesn't exist for arg_max() and arg_min().

Referring to the above code, the left side(i.e. `Over` side) type of `Binary eq` is derived from `phys_function`.

- `n_unique` and`count` case: 

The `phys_function` is:
```rust
pub(crate) struct AggregationExpr {
    pub(crate) input: Arc<dyn PhysicalExpr>,
    pub(crate) agg_type: GroupByMethod,
    field: Option<Field>,
}
```
If `field` is not `None`, it will become the result data type. Otherwise, it derived from input expr. That is, the type `Utf8` of `col ("a")`.

- `arg_max` and `arg_min` case:
It's type is `AnonymousFunction`'s `output_type` which already defined to `IDX_DTYPE(`UInt32` or `UInt64`)` when creating this expr.


> To expand on this, it goes right with optimization, but wrong without optimization.

When we enable optimization, the `filter` was pushed down to `DataFrameScan`. On the contrary, creating the physical expr in the filter is the responsibility of `Selection`, and we may accidentally forget to pass `input_schema` for it. As a result, we get a `AggregationExpr` with a `None` filed. This led to a comparison between `utf-8` and numerical data finally.

https://github.com/pola-rs/polars/blob/9b3007ebb2afd8acb9e4bfa7cd30724b9a011e05/crates/polars-lazy/src/physical_plan/planner/lp.rs#L167-L171

https://github.com/pola-rs/polars/blob/9b3007ebb2afd8acb9e4bfa7cd30724b9a011e05/crates/polars-lazy/src/physical_plan/planner/lp.rs#L294-L311
