### ISSUE TITLE
Deprecate read_* functions (e.g. read_csv)?

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#10592]
Another discussion topic at EuroScipy

Should `polars.read_csv` be deprecated?

Motivation:
- by "forcing" users to use `scan_csv` instead, this nudges them towards the lazy api
- some users are doing `pl.read_csv(...).lazy()`, which is probably the definition of "footgun" 😄 
- smaller API

**Comment by alexander-beedie** [comment]
When you're exploring a dataset (something you'll do  a lot of in the research stage) you don't want to be be constantly re-reading your source data from scratch with each new iteration; you want to read it all in once and explore from that point. Not being able to do so is just a different footgun waiting to happen (because then you'll just have people _forgetting_ to do `pl.scan_csv(…).collect()` in place of the current footgun of `pl.read_csv(…).lazy()` during the research phase and cursing polars' name instead :)

Seems like this would be a _very_ disruptive (and likely unpopular as a result) change for marginal real world benefits; if there was something really compelling driving it then that would be one thing as you'd be able to say _"look what you're getting in return"_, but I'm not sure theoretical purity in itself is a feature that's being actively requested 😄

(I've also heard plenty of grumbling at work about the much smaller breaking changes we've been making in advance of the 1.0, and that's with me actively upgrading our entire codebase so that the users almost never have to deal with it; I can only imagine the response to taking away all of the `read_*` functions, heh).

**Comment by mcrumiller** [comment]
I agree with @alexander-beedie.

I get that using lazy is generally faster, but it's also *much* harder to debug and develop in general. If I build a massive query plan and there's a bug in the middle, it takes a long time to figure it out, placing `.collect()` all over the place. Instead, I build in eager mode and switch to lazy at the end, almost as if I'm flipping on a compiler optimization.

I think we should provide eager mode to make development in polars easier, otherwise people won't want to use it as much.

**Comment by zundertj** [comment]
To add what has been said, Polars without lazy is already a major improvement over other libraries, including performance, taking that away seems user unfriendly to me for all the reasons mentioned above. In particular the points about exploring data and building a first working version of your data pipeline before moving to lazy.  Note that for parquet and csv, the `read` versions are also not equivalent to `scan().collect()` at the moment, so it is actually taking away  functionality, not a mere syntax change.

I would prefer to keep advertising lazy in the documentation/user guide as is done right now. Removing eager methods will not automatically lead to a better understanding / proper usage of the lazy API, which is I assume the key motivation for the change. If I were to guess, suppose you took away `read_csv` from the API, you would very quickly see SO answers/blog posts telling others about using `pl.scan_csv(..).collect()` to read a csv file. That is technically not wrong , and even the most correct answer, to the question "how do I read a csv file in Polars?", but it does not help the user in learning about the lazy concept.

**Comment by ritchie46** [comment]
I think we should set a python flag on the `DataFrame` if we the dataframe comes from a `read_{csv, parquet, ipc, ..}`. If that flag is still set on a `.lazy()` call, we know a user typed `pl.read_().lazy()` and issue a warning.

**Comment by zundertj** [comment]
That is an interesting idea, more like the `apply` hints. Setting the flag on `read` and checking for it on `lazy` is straightforward. However, am concerned about the more general case where other operations happen in-between; on many methods, we return a new Python object, and have the choice to copy the flag or not.

And there also methods where we do not return a new Dataframe class, the flag will thus remain, and that may be an issue. Suppose a user has this code:

```python
import polars as pl

df = pl.DataFrame({"a": [1,2]})  # suppose this is read_csv
df._is_eager_loaded = True  # happens within read_* functions

assert 2 in df["a"]

dfl = df.lazy()  # print warning if  hasattr("_is_eager_loaded") and self._is_eager_loaded
```

The user will now change to lazy, and in this case, it is `__getitem__` that fails, can't do lazy. Should we make `__getitem__` reset the flag, so the warning is not printed? There may be quite a few of these methods where a decorator would be needed to decide if a flag should be copied over or reset.

**Comment by ritchie46** [comment]
Fair point. I guess there is no other solution than making a polars linter. :smile:

**Comment by MarcoGorelli** [comment]
Ruff are open to adding a plugin for Polars, so let's address this there - thanks all for input
