### ISSUE TITLE
consolidate several related functions

### ISSUE THREAD

**Issue by Sage0614** [pola-rs/polars#10618]
### Problem description

currently there are several functions that have a few very similar variants, they should be consolidate into one function with additional arguments, rather than separate functions. 

for example, 
clip, clip_max, and clip_min should be just clip, clip(lower_bound = -math.inf) ,clip(upper_bound = math.inf)

min, nan_min should just be min(nan_actions = "propagate")

and there are many similar things like those.

polars api's design sometimes looks like datatype.action_aboutWhat where many other data frame operation packages is more like datatype.action(aboutWhat=argument) 

the disadvantage of this design I can see is, 1. there are probably too much function as you expose another layer of options as different functions, 2. finding what I need exactly is harder, like when I type max(), I don't see it gives me options to handle how I want to deal with NaN, then some people will just assume polars' max just don't handle NaN, and other will need to refer to the api web page, and exactly because of (1), there are too many functions there and hard to find what I need exactly. 

This seems only to work with people who already know polars well, but makes the newcomers more frustrated.

**Comment by stinodego** [comment]
There's definitely a case to be made for the two examples you give here.

I'd prefer it if you could make a separate issue for each example of functions that you think should be combined, rather than have a single issue that basically comes down to "fix your public API". This issue cannot really be accepted or assigned.

**Comment by Sage0614** [comment]
sure I will open separate issues for each case, and maybe keep this open and let them point to this?

**Comment by mcrumiller** [comment]
What do you all think about using `.ne(missing=True)` and `.eq(missing=True)` instead of the new `ne_missing` and `eq_missing`? Those both tend to trip people up (granted, they'll still be just as tripped up without knowing about the arg, but at least if they go look at the `eq` documentation they'd see it immediately), and represent more functions that could just be a parameter.

**Comment by avimallu** [comment]
@mcrumiller, wholeheartedly agree. The argument name is going to be a good discourse though, I feel. 😛

**Comment by Sage0614** [comment]
@mcrumiller @avimallu I don't know, this one is a little bit tricky, as .ne() and .eq() are also linked to expression != and ==, from IEEE 754 the logical comparison with NaN is a defined behavior and is always False, and ne_missing and eq_missing doesn't respect IEEE 754 so I suppose it might make sense that it is explicitly a separate function and is not associated with an operator.

and again, if ne() and eq() support other NaN behavior, then other comparison like gt() ,lt() should also support other NaN behavior as well, then the nature of this discussion might be slight beyond consolidation API but also what should be the consensus of logical comparison with NaN and perhaps null as well, which should be a separate thread and link to this issue.

**Comment by mcrumiller** [comment]
> .ne() and .eq() are also linked to expression != and ==

They are because we decided they should be, but actually it's `__ne__` and `__eq__` in Python that links them to the operators. Our definition for `ne` for example is:

```python
def ne(self, other: Any) -> Self:
    return self.__ne__(other)
```

**Comment by mcrumiller** [comment]
FYI in general I have no qualms with having an operator like `+` mean `__add__` but having a `.add()` as the more robust version with additional features. For example, in pandas, you can do `df1.add(df2, fill_missing=0)` and it'll align on index and add the dataframes, filling in missing rows with 0.

**Comment by adarshchbs** [comment]
> What do you all think about using `.ne(missing=True)` and `.eq(missing=True)` instead of the new `ne_missing` and `eq_missing`? Those both tend to trip people up (granted, they'll still be just as tripped up without knowing about the arg, but at least if they go look at the `eq` documentation they'd see it immediately), and represent more functions that could just be a parameter.

For me `.eq(missing=True)` is much more intuitive than `eq_missing`.

**Comment by stinodego** [comment]
Just for a bit of context, the reason functions/methods are designed this way is because Rust APIs usually work this way.

In Rust, functions do not have default values for parameters. So if you add a flag argument in a Rust function, you would always have to call your default case as `func(False)`. It would be cleaner to have two functions, `func` and `func_flag`, and have the IDE autocomplete show the user the two options when they type `func`.

Flag arguments are also considered an anti-pattern in some contexts. See [this chapter](https://martinfowler.com/bliki/FlagArgument.html).

Not saying that we shouldn't have flag arguments, but this is just to offer some perspective.

**Comment by stinodego** [comment]
I'm closing this as the proposed changes have been addressed in separate issues.
