### ISSUE TITLE
Preserve whitespace in notebook html output

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#10643]
## Problem

- for text column with whitespace (multiple spaces, tabs, newlines) you do **not get a correct data representation** (due to html whitespace collapse)
- if you want to copy&paste a value you see in your rendered output and use that to filter your Dataframe **you will not find it**

## Example

```python
DATA = {'text': ['nospace', '     before', 'after     ', '     both     ', 'bet     ween', 'tab-after\t', '\ttab-before', 'new\nline',]}
df = pl.DataFrame(data=DATA)
df.filter(pl.col('text') == '<PASTED FROM RENDERED OUTPUT>')  # will NOT work because whitespace collapsed
```

![image](https://github.com/pola-rs/polars/assets/25177421/37410d64-0ccd-4603-b19f-f2f5fe0d7226)

## Solution

there seems to be an easy css solution using `white-space: pre;` . Fix coming right up

**Comment by stevenlis** [comment]
@JulianCologne I definitely agree that the current HTML output can be improved. Thank you for finally pointing this out. However, I think the proposed change might not be ideal in some cases.
 
I would say those non-whitespace characters should be displayed as is, like `\t` and `\n`. Otherwise, they can be misleading at times.

In the example you provided, it is difficult to distinguish between four white spaces and a tab. Often, when reading text data from a CSV or similar source, it is challenging to discern the distinction.

Regarding the newline character, Notebook wraps text, which can make it difficult to differentiate. For example, there is no `\n` in `col2`:
<img width="675" alt="CS-siJ8Mxkm@2x" src="https://github.com/pola-rs/polars/assets/33796896/9ef820cb-7667-4f1a-876d-3e4870767929">

Another problem is that the plain text output will display two lines for a single cell, making it difficult to determine if there are two rows or only one. Additionally, when there is another column adjacent to it, it becomes unclear whether it is empty 
`""` or not. (which is why I think display a `""` for `str` in plain text output could make sense like you proposed).

Generally, I believe we should adopt the display strategy utilized in pandas' dataframe.
<img width="733" alt="CS-WeT9wBZr@2x" src="https://github.com/pola-rs/polars/assets/33796896/4237c1b3-2e57-4c58-8131-dc3346593dd1">



Based on your screenshot, I assume you are also using VSCode. I suggest we should also test/display those changes in the original Jupyter notebook and JupyterLab UI, as the VSCode UI is not entirely the same as Jupyter.

**Comment by JulianCologne** [comment]
Hi @stevenlis 
thanks for your feedback

I would say that my current solution is a good fix to show the **correct data** in the notebook cell output without ever touching the real data.
Problem beeing that html collapses all spaces, tabs and newlines into a single space which is really bad because the data you see does not always represent the actual data.

Is this solution perfect? 
Probably not. But I would say it is better than the current state and everything you need in most cases.

---

Regarding your suggestions:

Using `\t` and `\n`:
- yes, this ist also a good idea and would also work together with my solution to also preverse multiple spaces

Newline wrapping:
- with my css solution there will be no text wrapping. The css property prevents this. The only way to go to the next line is `\n` and `<br>`

Plain text output:
- my solution does not touch the plain text output.
- But you are right that there is a problem with newlines in plain text output. This is why I suggested to use quotes like you mentioned around the text.

Pandas strategy:
- I think we should improve upon the pandas style
- copy: `\t` and `\n` 
- addition: keep quotes `"`
- addtiion: preserve mutiple whitespace before, inside and after to still reflect correct data!
