### ISSUE TITLE
The name of `is_first` maybe does not match its actual behavior well

### ISSUE THREAD

**Issue by reswqa** [pola-rs/polars#10770]
### Problem description

This is emerged from the [PR](https://github.com/pola-rs/polars/pull/10760#issuecomment-1696192030) to support `is_last` and I have decided to focus it here to gather everyone's point.

Simply put, @orlp found that `is_first` and `is_last` rather non-descript names.

**Comment by cmdlineluser** [comment]
`is_first_seen` was what initially came to mind as in: *"Is this the first time this value has been seen?"*

**Comment by JulianCologne** [comment]
You are right. `is_first` could really mean/do anything and I just needed to check what is actually does :D 

My first thought was also `is_first_occurence`.

On the same line I would also update the documentation which is also very hard to understand:
- current: Get a mask of the first unique value.
- suggestion: Get a boolean mask marking each value's first occurence as true (false otherwise)
