### ISSUE TITLE
`str.concat` should skip `nulls` and be `null` for empty groups

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#10814]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

`str.concat` coerces `null` to a string when concatenating:

```python
>>> pl.DataFrame({'group': ['group1', 'group2'], 'to_concat': ['foo', None]})\
        .with_columns(pl.col('to_concat').str.concat(','))
 group   to_concat
 group1  foo,null
 group2  foo,null

>>> pl.DataFrame({'group': ['group1', 'group2'], 'to_concat': ['foo', None]})\
        .with_columns(pl.col('to_concat').str.concat(',').over('group'))
 group   to_concat
 group1  foo
 group2  null  # <--- this is a string "null", not an actual null
```

What if you `drop_nulls()` within each group, so that `group2` is empty? Then you get an empty string:

```python
>>> pl.DataFrame({'group': ['group1', 'group2'], 'to_concat': ['foo', None]})\
        .with_columns(pl.col('to_concat').drop_nulls().str.concat(',').over('group'))
 group   to_concat
 group1  foo
 group2
```

### Issue description

See above

### Expected behavior

1. `str.concat` should exclude `null`s rather than coercing them to a string. If the user wants to include `null`s in the concatenated string, they can `fill_null('null')` before concatenating.
 
2. `str.concat` should be `null`, not `''`, for empty groups.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

**Comment by ion-elgreco** [comment]
There should be a `null strategy` for this, and then the default behavior should be to not include these nulls during concatenation.

**Comment by cmdlineluser** [comment]
Some previous discussion here: #6919

**Comment by orlp** [comment]
> str.concat should be null, not '', for empty groups.

I strongly disagree with this, the empty string is the identity element for string concatenation, and aggregations should return the identity element for empty aggregations.

**Comment by orlp** [comment]
I definitely think that filling with `'null'` by default is the wrong strategy. I think we should have two behaviors toggleable by an option (bikeshedding about names can be done later):

 - Nulls are treated as completely absent elements, as if they aren't there. So `["foo", null, "bar"].str.concat() == "foobar"` and `[null, null].str.concat() == ""`.
 - Nulls are propagated, so if a single element is null the result is null. So `["foo", null, "bar"].str.concat() == null`.

There a potential third behavior we'd want, which is return an error on `null`. However I'm a bit wary of adding an option for this on every single function, and am starting to think perhaps we just need a `.raise_null()` function which raises an error when a null occurs and is the identity otherwise.

**Comment by Wainberg** [comment]
This has been fixed, closing
