### ISSUE TITLE
Undefined numerical aggregates should return NaN instead of null

### ISSUE THREAD

**Issue by orlp** [pola-rs/polars#10829]
Right now our numerical aggregates that are undefined (e.g. the mean, standard deviation or variance on an empty array) return null. But null represents 'missing data', not 'undefined answer'. I think it would probably be better overall if they returned NaN by default to reduce the chance of such undefined answers being silently viewed as missing data elsewhere.

I have fixed https://github.com/pola-rs/polars/issues/10820 to be consistent with `mean` for now (returning null when undefined), but after thinking about it some more perhaps all of them should be changed.

**Comment by orlp** [comment]
As a counterargument, if these functions return null you can distinguish between 'result was undefined because of a NaN in the input' and 'result was undefined because there wasn't enough data', which you can't anymore if it returns NaN. And you can always get the NaN behavior by using .mean().fill_null(float('nan')).

Just curious what the community thinks, perhaps the current behavior is what we want after all, perhaps not, I am unsure.

**Comment by deanm0000** [comment]
I can't see a need for it but maybe I'm not understanding the use case.

If I do `pl.select(pl.Series([1,2,3, None]).std())` I don't get null. 

If I do `pl.select(pl.Series([1,2,3, None]).alias('a')).filter(pl.col('a')>5).select(pl.col('a').std())` then I do get null.

I guess in the latter example, your argument is that it should be NaN? I guess that could be relevant if I do a complicated groupby otherwise you're not doing my contrived example.

Is NaN a subset of null or would I need to check for both?

Could you give some examples that help me see what you're after?

**Comment by cjackal** [comment]
Some supporting observations:
- `pyarrow` do return `nan` for undefined numerical aggregations
- Most scientific libraries (e.g. `numpy`) return `nan` for undefined numerical aggregations
  - though this is mainly because of lack of the concept of `null`, it is undesirable to make more disparity from those libraries: users often expect `Expr.mean() == Expr.apply(np.mean)` etc
- `nan` is mathematically correct way of representing "the value evaluated outside the domain of an analytic function" (e.g. fraction evaluated at denominator zero, ...)

**Comment by ritchie46** [comment]
I am inclined to follow databases in this regard. They are designed with null values and are most akin to polars.

I also like that in most examples the Null can be explained as not enough data to determine the statistic. Which to me is very similar to missing data.

Another benefit is that we can return null with integers and float return types, making it easier to be consistent.

And lastly. Dealing with nulls is much easier in polars.

**Comment by orlp** [comment]
@ritchie46  Alright, I will close this then. Both ways have their own pitfalls, so I don't feel particularly strongly either way.
