### ISSUE TITLE
Dispatch attributes on `col` as `col("foo")`

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#10866]
### Problem description

This is one of the most requested features for `col` and I think we should go for this.

This will allow more succinct column selection.

```python
from polars import col as C

df.select(
   C.foo,
   C.bar
)
```

*Edited snippet: after @orlp s clarification*

I don't foresee `col` ever having attributes, so I don't this should not produce a problem in the future. Anybody interested in implementing and documenting this one?

**Comment by orlp** [comment]
Just to clarify, this should be `from polars import col as C`, this won't be a dedicated module.

I'm all for it (as we've discussed :P), I do think we should have some bikeshedding on whether we recommend people (and show in our documentation) to use `C.foo`, `pl.col.foo`, or `col.foo` (or something else).

**Comment by jcmkk3** [comment]
A couple of things. I think that if a column is selectable through `__getattr__` (dot access), then it should also be selectable through `__getitem__` (bracket access). Having dot access and `__callable__` (parenthesis) is a bit weird to me.

I might not be thinking it through fully, but in my mind, I'd love to just have this sort of functionality added to the selectors object.
```python
import polars.selectors as cs

cs.temporal()  # Select all temporal columns
cs.starts_with("e")  # Select all columns starting with `e`
cs.species  # Select `species` column
cs["flipper size"]  # Select `flipper size`
```

**Comment by orlp** [comment]
@jcmkk3 Putting this behavior on the selectors rather than on `pl.col` is highly problematic precisely because the selectors have a lot of attributes. E.g. `cs.temporal` wouldn't be the column temporal, but the method `temporal`.

**Comment by jcmkk3** [comment]
> @jcmkk3 Putting this behavior on the selectors rather than on `pl.col` is highly problematic precisely because the selectors have a lot of attributes. E.g. `cs.temporal` wouldn't be the column temporal, but the method `temporal`. It is possible to resolve this with even more magic (not making `cs.temporal` be a method but some kind of callable class that resolves to the `temporal` name if not called and passed into polars), but I don't know if we want that.

I only see functions on `polars.selectors` and not attributes.

**Comment by orlp** [comment]
@jcmkk3 <https://docs.python.org/3/tutorial/classes.html#python-scopes-and-namespaces>

> By the way, I use the word attribute for any name following a dot — for example, in the expression z.real, real is an attribute of the object z.

This is the terminology I meant for 'attribute'.

```python
>>> [attr for attr in dir(pl.col) if not attr.startswith("_")]
[]
>>> [attr for attr in dir(pl.selectors) if not attr.startswith("_")]
['Any', 'Categorical', 'Collection', 'Datetime', 'Duration', 'Expr', 'F', 'FLOAT_DTYPES', 'INTEGER_DTYPES', 'Mapping', 'NUMERIC_DTYPES', 'SIGNED_INTEGER_DTYPES', 'SelectorType', 'TEMPORAL_DTYPES', 'TYPE_CHECKING', 'TypeVar', 'UNSIGNED_INTEGER_DTYPES', 'Utf8', 'all', 'annotations', 'by_dtype', 'by_name', 'contains', 'datetime', 'deprecate_function', 'duration', 'ends_with', 'expand_selector', 'first', 'float', 'integer', 'is_polars_dtype', 'is_selector', 'last', 'matches', 'numeric', 're', 'selector_column_names', 'signed_integer', 'starts_with', 'string', 'temporal', 'timezone', 'unsigned_integer']
```

**Comment by jcmkk3** [comment]
The documented function list is much shorter so if it were cleaned up, there would be less potential conflicts. It could either be accepted that there could be some chance of collisions and folks would need to use `__getitem__` access instead (like pandas) or the object could be implemented similar to the way that some decorators are implemented to give different behavior when called (parenthisis) or not.

My preference would be no attribute access at all and only adding `__getitem__` lookup on the `selectors` object, but it seems that there has been enough pressure/requests from users to make attribute access happen.

I just dislike how both polars and ibis have two different selection objects (single and multi) and encouraging users to create an import alias for both of them.

**Comment by ritchie46** [comment]
@orlp's rationale explains what I meant by *"I don't foresee col ever having attributes, so I don't this should not produce a problem in the future. Anybody interested in implementing and documenting this one?*.

We will not put this on selectors, nor dataframes. Anything that can have possible attributes is a very bad fit and I don't want that.

> I just dislike how both polars and ibis have two different selection objects (single and multi) and are encouraging users to create an import alias for both of them.

Having naming and functionality collisions/ambiguity is much worse than two imports.

**Comment by jcmkk3** [comment]
Having attributes that are not possible to autocomplete or inspect is just a weird API in general. It is one thing when it is on the dataframe object of pandas (which I don't like either), but just blindly typing a column's name as an attribute is not my cup of tea.

**Comment by ritchie46** [comment]
`col("name")` also hasn't got autocompletion.
We need a language server for both to get autocompletion.

On a `DataFrame` it is worse as it **does** have attributes. 

I any case, we don't remove functionality. You can still keep using `col("name")` if that's your cup of tea. :)

**Comment by adarshchbs** [comment]
I would prefer having  only one way to refer to the column expression. Since I hate pandas dot notation for columns. In any large project with multiple people will lead to both types of expression.

Since column names are not supported by LSPs. The only way to find or rename them is through find and replace functionality of editors. Which don't like combinations of dots and quotes.

I will prefer col with quotes only since you can easily find or replace with editor find and replace functionality.


If I am working single on a project. I generally define a single dataclass `Col` with  fields as column names and values as pl.col("column_name")

For ex

`
@dataclass
Class Col:
    column_name = pl.col("column_name")
    ...
    ...
`

With this I don't have to write the quotes and brackets at the same time I get autocomplete as well.

One thing to note here is that, since a single dataclass contains all the columns for all the possible dataframes in a project, it does not provide any static typing checks for column existence within a particular dataframe.
But this static typing check is not yet possible in any other way.

Apart from autocomplete, you also get easy renaming of columns. And you can find all the references using LSP help.

**Comment by cjackal** [comment]
I have no strong feelings on this addition, but rather think that `C.feature_name` pattern is a bit useless? In the given example, we currently support the shorter
```python
df.select(
   "foo",
   "bar",
)
```
and if one starts to use the polars fancy `Expr` expressions it would be advised to use `pl.col("foo").is_null()...` which LSPs can autocomplete (and there is little typing egronomic in `C.foo.is_null()...` and `pl.col("foo").is_null()..` at any rate, especially when one can set variable to oft-used column names - `pl.col(c).is_null()...`).

**Comment by alexander-beedie** [comment]
> Anybody interested in implementing and documenting this one?

I can do this; I already implemented the identical syntax in our in-house data language, which has an uncannily polars-esque syntax already, so I know where all the bodies are buried here  ;)

@cjackal: you might think it doesn't offer much, but it was wildly popular at work and is now our standard way of referring to fields (we use `f` instead of `c`, but it's otherwise an uncannily polars-esque syntax).

**Comment by alexander-beedie** [comment]
> I'd love to just have this sort of functionality added to the selectors object.

The ideal import is probably this:
```
from polars import c, cs
```
It standardises the aliases (by not making the user responsible for aliasing `col` each time and it reads very logically: 
* `c` is column
* `cs` is column**s** (or **c**olumn **s**elector)

**Comment by stinodego** [comment]
This will be a fun one to build, let me take a stab at it :)

**Comment by stinodego** [comment]
After looking at this more, I think this is a good idea, but we should clearly document that the dot notation is intended for quick prototyping in notebooks and not for writing good production code. Here's some observations about readability:

#### Observations

If I write a 'naked' expression with just `col`, the dot syntax indeed looks a lot cleaner:

```python
from polars import col

df = ...

df.select(col("foo"))
df.select(col.foo)       # Saves some keystrokes!
```

However, you almost never need to write just `col("foo")`, because we parse strings as though they are columns. 

```python
df.select(col("foo"))
df.select(col.foo)
df.select("foo")      # Even shorter, more readable
```

So we only need to use `col` when starting an expression chain:

```python
col("foo").str.strip()
col.foo.str.strip()     # Saves keystrokes, but less readable
```

The new syntax saves some keystrokes, but it's much less clear where the column name is. Is `foo` an operation or a column name? The advantage of the old syntax is that you clearly see which part of the chain is the column name.

Let's look at a longer expression chain, wrapped over multiple lines (I just threw together some random expressions here):

```python
expr = (
    col("Product") 
    .sum()
    .str.strip()
    .abs()
    .unique()
    .eq(col("Store").product().list.any().unique().alias("Date"))
)

expr = (
    col.Product.sum()      # the sum operation is autoformatted onto the same line
    .str.strip()
    .abs()
    .unique()
    .eq(col.Store.product().list.any().unique().alias("Date"))      # alias takes a string input - doesn't match col
)
```

Again, I would argue the first example is more readable. I like that I can pick out the names by looking at string literals, including the `alias` input. And the autoformatter puts the `col("Product")` on a separate line, which I think is nice.

### Conclusions

Personally, I would **not** be happy to see dot notation in my code base. But I would probably be happy to use it when trying some stuff in a notebook or in the Python interpreter.

So I would suggest clearly documenting that the 'classic' parenthesis notation is the idiomatic Polars style, and keep this notation for all our docstrings and other documentation.

**Comment by alexander-beedie** [comment]
> So I would suggest clearly documenting that the 'classic' parenthesis notation is the idiomatic Polars style, and keep this notation for all our docstrings and other documentation.

Yup, nicely explained; agree with everything - available because it's nice as a quick & easy option, but not considered default/idiomatic, for all the reasons given 😎👍 

Plus one more: the idiomatic/default method can't be the one that doesn't handle colnames containing spaces, non-ascii chars, etc. If it is then you're immediately forced into mixed-syntax usage by default, which is just... unpleasant.
