### ISSUE TITLE
Inconsistent select behaviour with list of strings

### ISSUE THREAD

**Issue by djbarker** [pola-rs/polars#10995]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

x = pl.DataFrame({"A": [1, 2, 3], "B": ["x", "y", "z"]})

print(x.select(["A", "B"]))  # 1
print(x.select(pl.col(["A", "B"])))  # 2
print(x.select(["A", "B"], pl.col("B").alias("C")))   # 3 <--- this produces a column "literal" with the literal list ["A", "B"] in each row
print(x.select(pl.col(["A", "B"]), pl.col("B").alias("C")))  # 4
```

### Issue description

When passing a raw list of strings to `DataFrame.select` we see different output depending on if any other `pl.Expr` are passed or not.

### Expected behavior

To be consistent with examples 1 & 2 I would expect examples 3 & 4 should produce the same output.

(That being said, I'm not sure what the expected call is if you did want a column with the list duplicated in each place since `pl.lit` seems to put each entry on each row, so the lengths must match)

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Linux-5.14.0-162.6.1.el9_1.x86_64-x86_64-with-glibc2.34
Python:              3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by avimallu** [comment]
I don't think this is inconsistent. [The typing hints for `select`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.select.html#polars-dataframe-select) indicate for unnamed arguments,

> `*exprs: IntoExpr | Iterable[IntoExpr]`

I'm not an expert at reading typing hints, so take what I say to be based more on practical usage of Polars rather than a strict interpretation of the hint.

1. When only `["A", "B"]` is present, they are interpreted as column names after unpacking. I believe this is just for convenience, because older versions of Polars required you to type `df.select([...])`, while now it is preferred to just use `df.select(...)`.
2. When you specify `pl.col(["A", "B"]))`, you go into *expression expansion*, which results in the same as (1) for this case because you don't have additional operations after the expansion (eg. `pl.col(["A", "B"]).sum()`).
3. When you specify `["A", "B"], pl.col("B").alias("C"))`, you trigger the "other non-expression inputs are parsed as literals" part of the doc-string.
4. When you specify `pl.col(["A", "B"]), pl.col("B").alias("C"))`, then all the inputs are expressions. The first one follows *expression expansion*, and the second one is a simple expression.

**Comment by avimallu** [comment]
This preference was changed in this [issue](https://github.com/pola-rs/polars/issues/6451).

**Comment by djbarker** [comment]
The change to the user guide you linked to updates some example but I didn't see that it explicitly says the splatting style is now preferred over a list. My personal view is that it's not necessarily preferable, _but_ I haven't spent time thinking about this like you guys so I'm happy to accept I'm wrong. As it happens I found the breaking change [mentioned here](https://github.com/pola-rs/polars/pull/9512) in the release notes for [0.19.0](https://github.com/pola-rs/polars/releases/tag/py-0.19.0). I didn't spot this when creating the issue.

In the first issue you linked to it explicitly says that passing a list and then other args should raise an exception. The examples were given with `.groupby` but I guess this should hold for all methods that fit this pattern. However it seems like this wasn't what was settled on in the end. In any case it was document and I just missed it so I'll close this issue. 

Anyway, thanks for the hard work! Polars is great.
