### ISSUE TITLE
Can't access lazyframe struct field by name if generated from `to_struct`

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#11143]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

ldf = pl.LazyFrame({"first_col": [[1.0, 2.0], [1.5, 3.0]]})
ldf = ldf.select(pl.col("first_col").list.to_struct(fields=["a", "b"], upper_bound=2))
print(ldf.collect().select(pl.col("first_col").struct.field("a"))) # This works
df = ldf.select(pl.col("first_col").struct[0]).collect() # Strangely this works
print(df)
df = ldf.select(pl.col("first_col").struct["a"]) # But not this
df = ldf.select(pl.col("first_col").struct.field("a")) # Neither does this work
print(df.collect())

```

### Issue description

Not 100% if this is a bug or fundamental limitation, given I pass a sequence which is used as the field names, I would've expected that this is theoretically solvable.

### Expected behavior

Query runs and produces the same result as:
`df = ldf.select(pl.col("first_col").struct[0]).collect()`

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.0
Index type:          UInt32
Platform:            Linux-5.4.254
Python:              3.11.5 (main, Aug 31 2023, 23:10:05) [GCC 7.3.1 20180712 (Red Hat 7.3.1-15)]

----Optional dependencies----
adbc_driver_sqlite:  0.6.0
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.10.1
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            2.3.0
sqlalchemy:          2.0.20
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
shape: (2, 1)```

</details>

**Comment by cmdlineluser** [comment]
I'm not sure if this is supposed to work or not, but I've had a brief attempt to debug what's going on.

If I add a `dbg!()` call here:
https://github.com/pola-rs/polars/blob/7c83592d3dc0a87f75514fc96e70d2a321d0de66/crates/polars-plan/src/dsl/list.rs#L279
```python
ldf = pl.LazyFrame({"first_col": [[1.0, 2.0], [1.5, 3.0]]})

ldf.select(
   pl.col("first_col").list.to_struct(fields=["a", "b"], upper_bound=2)
).collect()
```
It still seems to think the field names are the default at that stage:
```rust
[/Users/user/git/polars/crates/polars-plan/src/dsl/list.rs:280] dt.clone() = Struct(
    [
        Field {
            name: "field_0",
            dtype: Float64,
        },
        Field {
            name: "field_1",
            dtype: Float64,
        },
    ],
)
```
However by the time the lookup is done, the names is incorrect:
```python
ldf.select(
   pl.col("first_col").list.to_struct(fields=["a", "b"], upper_bound=2)
     .struct["field_0"]
).collect()
# StructFieldNotFoundError: field_0
```
It does seem to work if `fields=` is omitted
```python
ldf.select(
   pl.col("first_col").list.to_struct(upper_bound=2)
     .struct["field_0"]
).collect()

# shape: (2, 1)
# ┌─────────┐
# │ field_0 │
# │ ---     │
# │ f64     │
# ╞═════════╡
# │ 1.0     │
# │ 1.5     │
# └─────────┘
```

It seems that when `fields=` are set, it ends up in this `name_generator` 
https://github.com/pola-rs/polars/blob/7c83592d3dc0a87f75514fc96e70d2a321d0de66/crates/polars-plan/src/dsl/list.rs#L258

Because `fields` can be a Callable 
```python
Expr.list.to_struct(
    n_field_strategy: ToStructStrategy = 'first_non_null',
    fields: Sequence[[str] | Callable[[[int]], [str](https://docs.python.org/3/library/stdtypes.html#str)] 
```
The names only become available after the `name_generator` "function" is evaluated at the "polars-ops" level:

https://github.com/pola-rs/polars/blob/7c83592d3dc0a87f75514fc96e70d2a321d0de66/crates/polars-ops/src/chunked_array/list/to_struct.rs#L65

Which makes it seem like it cannot be visible before `.collect()` runs? 

Hopefully someone with the knowledge can give a definitive answer.

**Comment by cmdlineluser** [comment]
Yeah, it looks like the `Sequence[str]` is actually wrapped in a function before being passed to the Rust side of things.

https://github.com/pola-rs/polars/blob/7c83592d3dc0a87f75514fc96e70d2a321d0de66/py-polars/polars/expr/list.py#L949-L953

Also, I just realized if you use [`.rename_fields()`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.struct.rename_fields.html#polars.Expr.struct.rename_fields) instead, it works.

```python
ldf.select(
   pl.col("first_col").list.to_struct(upper_bound=2)
     .struct.rename_fields(["a", "b"])
     .struct["a"]
).collect()

# shape: (2, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ f64 │
# ╞═════╡
# │ 1.0 │
# │ 1.5 │
# └─────┘
```
