### ISSUE TITLE
Allow per-sheet `schema_overrides` and `read_csv_options` via dict of dicts when multiple sheets are read

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#11274]
### Description

`pl.read_excel(file, sheet_name=[...])` reads each sheet specified. Different sheets may have the same column name but different intended dtypes. `schema_overrides` should allow for a dict of dicts in order to specify a per-sheet schema.

The same is true for `read_csv_options` and `xlsx2csv_options`.

**Comment by alexander-beedie** [comment]
Hmm, it's an interesting one; it may be cleaner to simply call `read_excel` once per sheet - otherwise we'll have a gnarly/nested `schema_overrides` here, but nowhere else? I'm going to be revisiting these params shortly as there are a number of options currently living in `read_csv_options` that I'd like to pull out and make available to _all_ engines at the top level. Will experiment a bit with the API then to see how this looks - might be ok, but I want to "feel" it in action first :)

**Comment by alexander-beedie** [comment]
Mulling this over I think this gets too confusing too quickly; will make an explicit note in the docstring suggesting the use of multiple calls for this use-case and explaining that options are set globally on the read.
