### ISSUE TITLE
nulls produced by `map_dict()` cannot be filled with `.fill_null` in `LazyFrame`

### ISSUE THREAD

**Issue by moritzwilksch** [pola-rs/polars#11332]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# eager works OK
df = pl.DataFrame({"a": ["one", "two"]})
print(df.select(pl.col("a").map_dict({"one": 1})).fill_null(999))
# shape: (2, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 999 │
# └─────┘

# lazy is wrong
ldf = pl.DataFrame({"a": ["one", "two"]}).lazy()
print(ldf.select(pl.col("a").map_dict({"one": 1})).fill_null(999).collect())
# shape: (2, 1)
# ┌──────┐
# │ a    │
# │ ---  │
# │ i64  │
# ╞══════╡
# │ 1    │
# │ null │
# └──────┘


```

### Issue description

The `LazyFrame.fill_null()` method *does not work* on nulls that are created by a preceding `.map_dict()` call. The method works fine on an eager frame.

### Expected behavior

The result of the query on the `LazyFrame` should be the same as the result on the `EagerFrame`: The nulls should be filled.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Linux-5.15.0-83-generic-x86_64-with-glibc2.35
Python:              3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              2.1.0
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by ritchie46** [comment]
@alexander-beedie can you take a look at this one? This hits a special branch in `def fill_null` where you determined the supertype.

I think all this logic should live in rust, as we now have different implementations.

**Comment by alexander-beedie** [comment]
Interesting... looks like it's because `map_dict` fails to propagate the schema, so "a" is assigned a type of `Unknown` at the frame-level, leading to undetermined supertypes 🤔 

@moritzwilksch, in this case you'd be better-off using an expression-level `fill_null`, which will work fine:
```python
ldf.select( pl.col("a").map_dict({"one": 1}).fill_null(999) ).collect()
```

**Comment by moritzwilksch** [comment]
Thank you, yes that's how I circumvented the issue in my code for now 👍

**Comment by cmdlineluser** [comment]
I think I ran into the same issue as @ElisabethBrockhausQC with #12410

It looks to me like `return_dtype` is ignored and not passed on to `.map_batches()`

https://github.com/pola-rs/polars/blob/86978f1077ef7f472f86630a028ad0b3b1a15ace/py-polars/polars/expr/expr.py#L9413

However, now I'm confused. Is there a reason why `return_dtype` is needed for `.map_dict()` at all?

If we are passing in a mapping, can't we just compute the dtype from that and pass it along so that the schema is correct?

```python
return_dtype = pl.Series(remapping.values()).dtype

return self.map_batches(func, return_dtype)
```

Doing that seems to fix all the issues mentioned. 

```python
ldf = pl.DataFrame({"a": ["one", "two"]}).lazy()

print(ldf.select(pl.col("a").map_dict({"one": 1})).fill_null(999).collect())

# shape: (2, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# │ 999 │
# └─────┘
```

Am I missing something obvious here?

**Comment by alexander-beedie** [comment]
> It looks to me like `return_dtype` is ignored and not passed on to `.map_batches()`

Meant to get back to this - you are completely correct, this is indeed the problem. I'll patch with some unit test coverage shortly.

> Am I missing something obvious here?

Just that the return dtype can't be inferred as accurately as it can be provided; for instance, a map containing ints would always end up as `Int64` when inferred, but you might know that it only needs to be `UInt8`, for instance.

**Comment by alexander-beedie** [comment]
FYI: not quite as straightforward as it looks after all ;)

Will fix the missing `return_dtype` passthrough as that's a clear win; however, inferring the result_dtype from map values doesn't actually work in many cases. For instance, not only can you infer a supertype (eg: `Int64` instead of `Int8`), you can also infer the _wrong_ dtype, eg: `Utf8` instead of `Categorical`. 

Not entirely sure how best to handle this yet, but at least we'll shortly be able to guarantee that we'll do the right thing _if_ `result_dtype` is given.

**Comment by cmdlineluser** [comment]
Ah, that would be part of what I was missing.

Thanks for the explanation @alexander-beedie - it's quite the rabbit hole.

I did have a separate issue #12410 which can be closed with the new fix.

**Comment by moritzwilksch** [comment]
Though the behavior of `map_dict` aka `replace` also changed to not defaulting to `None`. Still, this seems fixed!
