### ISSUE TITLE
Misleading `from_dicts` error message

### ISSUE THREAD

**Issue by jonashaag** [pola-rs/polars#11366]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame([{"x": datetime.date(2023, 1, 1)}, {"x": ''}])
```

```
ComputeError: could not append value: 2023-01-01 of type: date to the builder; make sure that all rows have the same schema or consider increasing `schema_inference_length`
```

### Issue description

In the example, the problem isn't the date but the empty string.

### Expected behavior

Should warn about the empty string.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.22.4
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            2.3.0
sqlalchemy:          1.4.49
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
The error looks ok to me? There's no way for the code to know which type you _actually_ wanted to end up with after all (for example, maybe the first/date value is the error because you meant to pass it as a string but forgot to stringify) ;)

**Comment by jonashaag** [comment]
3 things to note here

- The first value was a date object, so I would expect the column to be inferred as date and then error message is wrong. 
- There is no input `2023-01-01`, as I am passing a date object. Probably mostly a formatting issue but slightly misleading. 
- There is no mention of the builder's inferred type, and the only mention of a concrete type is `date`. If you read message as this being the builder's type then the error message is wrong.

**Comment by deanm0000** [comment]
The first thing is a date, the second thing is a string. Those are not compatible data types. When you say the error is wrong, are you arguing for a more verbose error or are you maintaining that it should only give you a warning. If that's the case then should it turn your date into a string or should it interpret an empty string as a None? The whole point of the error is that it doesn't know what it should do and it needs your attention.

**Comment by jonashaag** [comment]
I'm trying to say that error message can and should be improved.

**Comment by alexander-beedie** [comment]
A few things to note:

- _The first value was a date object, so I would expect the column to be inferred as date and then the error message is wrong._ 

That is an assumption - we may consider strings to be the relevant supertype here; without an explicit schema it cannot be determined which value type is "expected".

- _There is no input `2023-01-01`, as I am passing a date object. Probably mostly a formatting issue but slightly misleading._ 

The full message says 2023-01-01 is "of type: date", so that's covered (it won't show python class formatting as the error comes from Rust).

- _There is no mention of the builder's inferred type, and the only mention of a concrete type is `date`. If you read message as this being the builder's type then the error message is wrong._ 

We might be able to add some more colour for the last of these, but the other two look fine as the relevant information _is_ in the message. I'd have to go look at the code to see what level of abstraction the builder is at when it raises this 🤔

**Comment by stinodego** [comment]
Closing this as the error message looks fine-ish to me and we are looking to overhaul the parsing logic here anyway.
