### ISSUE TITLE
(python) add `pl.Datetime("s")`

### ISSUE THREAD

**Issue by svaningelgem** [pola-rs/polars#11689]
### Description

Hi,

Right now within polars there exist a datatype `pl.Datetime("ms")`, `pl.Datetime("us")` and `pl.Datetime("ns")`.
You could do something like this:
```python
pl.DataFrame({"s": [1e10], "ms": [1e10], "us": [1e10], "ns": [1e10]}).select(
    pl.from_epoch(pl.col("s")),
    pl.col("ms").cast(pl.Datetime("ms")),
    pl.col("us").cast(pl.Datetime("us")),  # The default
    pl.col("ns").cast(pl.Datetime("ns")),
)            

shape: (1, 4)
┌─────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┐
│ s                   ┆ ms                  ┆ us                  ┆ ns                  │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---                 │
│ datetime[μs]        ┆ datetime[ms]        ┆ datetime[μs]        ┆ datetime[ns]        │
╞═════════════════════╪═════════════════════╪═════════════════════╪═════════════════════╡
│ 2286-11-20 17:46:40 ┆ 1970-04-26 17:46:40 ┆ 1970-01-01 02:46:40 ┆ 1970-01-01 00:00:10 │
└─────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┘
```

As you can see from the example it is strange how you need to convert to seconds. Strange, as in "s" not being supported by pl.Datetime.
My question here is if it would be ok to implement the seconds as well in a similar way (ie: implementing "s" within the pl.Datetime type)?

Thanks

**Comment by mcrumiller** [comment]
FYI [numpy](https://numpy.org/doc/stable/reference/arrays.datetime.html#datetime-units) has units of `h`, `m`, and `s`, which we don't have. They also have much more precise time units that I don't feel we should necessarily have. But I think `s` seems appropriate at least, @MarcoGorelli what do you think on this one? It's probably a fairly easy addition since it'll fit right in with all the other time conversion code.
