### ISSUE TITLE
`DataFrame.drop(<missing column>)` silently no-ops

### ISSUE THREAD

**Issue by Gattocrucco** [pola-rs/polars#11913]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
x = pl.DataFrame(dict(a=[1]))
x.drop('cippolino')
```

### Issue description

It surprised me that dropping a nonexistent column did not raise an error. I was trying to drop the wrong column and did not notice immediately because the subsequent code was column-agnostic.

### Expected behavior

`DataFrame.drop` should raise an exception if a column does not exist. Or if for some reason this can't be done, say for compatibility with some database coding custom I don't know about, at least document the behavior.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.10
Index type:          UInt32
Platform:            macOS-13.6-arm64-arm-64bit
Python:              3.11.2 (v3.11.2:878ead1ac1, Feb  7 2023, 10:02:41) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.26.0
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

**Comment by stinodego** [comment]
Thanks for the report, this should indeed error.

**Comment by cmdlineluser** [comment]
Just for reference: It was previously raising an "unrelated" exception that was just fixed https://github.com/pola-rs/polars/issues/11697

The no-op or raise behaviour didn't get much discussion at the time.

**Comment by alexander-beedie** [comment]
I think this could probably be a flag (can default to raise an error), as it can be a very useful/convenient op to be able to say _"drop **any** of the following columns"_, without having to carefully work out which ones are (or are not) present.

**Comment by ion-elgreco** [comment]
`raise_on_missing` is to me the clearest of them all.

**Comment by stinodego** [comment]
Hm... I don't know that we would need a parameter for that.

If you really don't want to get an error, you can easily do:

```python
df = df.drop({"b", "c"} & set(df.columns))
```

**Comment by daviskirk** [comment]
I also often have the problem that I would like there to be a cleanly chainable no-op for such things as it allows us to write more reusable functions that accept and return expressions instead of always having to deal with a concrete dataframe.

I'm aware that the current behavior might not be desirable for some as  `drop` does not error, but select or the selector cs.by_name or such do but I at least wanted to highlight a usecase that makes writing reusable functions much easier if the frame isn't known beforehand.

**Comment by stinodego** [comment]
`drop` is a DataFrame/LazyFrame method; you cannot call it without a frame. So I don't see how that is relevant.

**Comment by daviskirk** [comment]
My point is more that having clean noops in both DataFrame/LazyFrame method and expressions makes many use cases more chainable and readable.

In the case of drop/exclude  especially, I don't see any disadvantage of having the operation being a no-op: The desired result is that these columns are not longer in the dataframe which is accomplished.

**Comment by stinodego** [comment]
The problem with doing a silent no-op is that a user could write `df.drop("colunm_name")` and find out later that the column they intended to drop was never dropped at all due to a spelling mistake.

If I `select` a non-existent column I get an error. You wouldn't want to find out later the column you intended to select was never selected for whatever reason.
