### ISSUE TITLE
Explicitly list arguments to Config class

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#11939]
### Description

Currently there's no autocomplete there, as the argument is just `**options`

https://github.com/pola-rs/polars/blob/46e70094af11f92d7a6f64069118712171e8bd55/py-polars/polars/config.py#L96-L131

This is kinda inconvenient when working in an interactive environment, when users are most likely to want to set `Config` and are unlikely to be able to be able to remember the names.

Personally, I'd have no chance of remembering `fmt_table_cell_list_len` by heart and typing it out correctly...

**Comment by alexander-beedie** [comment]
I can experiment with this; the one thing that makes me hesitate is that we'd then have repetition of all the static methods as init methods; they do serve a (slightly) different purpose in that they are typically bound to a context manager when called like this, but it would necessarily make the init a lot clunkier/repetitive internally - but that's something for us to worry about rather than the user, so... Let's see if there's some way of doing this reasonably cleanly 🤔

**Comment by cmdlineluser** [comment]
I sometimes wonder if it is possible to create an extra "namespace" in the Config just for "formatting" options.
```python
pl.Config.display(
    cols = 10,
    rows = 20,
    list_len = 10,
    str_len = 120
)
```

**Comment by alexander-beedie** [comment]
Closing this one as being superseded by #12252 (which I started to poke at last night).
