### ISSUE TITLE
Rename `melt` to `unpivot` and make parameters consistent with `pivot`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#11974]
### Description

I guess the name `melt` and the parameter names were originally copied from pandas.
I think however, that they should be consistent with the `pivot` parameter names and fit in with polars naming conventions.

I have 2 suggestions (see resoning at the bottom)
- rename `melt` parameters to be consistent with `pivot` which is the inverse
- possibly rename `melt` to `unpivot` or create an alias

# Examples

```python
df = pl.DataFrame(
    {
        "foo": ["one", "one", "two", "two"],
        "bar": ["y", "x", "y", "x"],
        "baz": [1, 2, 3, 4],
    }
)
```

## Current

```python
df.pivot(
    columns='bar',
    index='foo',
    values='baz',
)

df_piv.melt(
    value_vars=['x', 'y'],
    id_vars='foo',
)
```

## NEW: 

```python
df.pivot(
    on='bar',
    index='foo',
    values='baz',
)

df_piv.unpivot(
    on=['x', 'y'],
    index='foo',
)
```

# Reasoning

`melt` -> `unpivot`
- most poeple know `pivot` and have heard of `unpivot`
- the first word in the pandas & polars documentation of `melt` is actually "`unpivot` a DataFrame" so I would argue that `unpivot` describes the function best
- other libraries like duckdb also use `pivot`/`unpivot`

renaming arguments
- `melt` arguments shold be consistent with `pivot` as an inverse function
- `melt` arguments are not "polars style"
- `columns` -> `on`: this would be in line with other functions like join or with duckdb; you pivot/unpivot `on` a column(s)

**Comment by alexander-beedie** [comment]
I have to agree about the naming of `melt` vs `unpivot`; the former means absolutely _nothing_ to me. There is nothing about the name that helps you understand what it's going to do - might as well be `df.munge` 😅

**Comment by cmdlineluser** [comment]
Not sure how the name `melt` came about in Pandas, it made me think of "icicles", where the melting results in a *"long, narrow structure"*. 

The name [`.wide_to_long()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.wide_to_long.html) made more sense to me, but it's a bit different.

**Comment by markfairbanks** [comment]
The naming in R's tidyr are pretty straightforward to understand - `pivot_wider()` and `pivot_longer()`

**Comment by deanm0000** [comment]
I disagree about unpivot. I think if you didn't already know what pivot does that it wouldn't seem so intuitive and hence neither would unpivot.

The term melt predated pandas by at least a few years in the r package reshape circa 2005. In that package the "inverse" was a cast. Eventually data.table came about and deprecated external packages and used dcast instead of cast but kept melt. Similarly, the tidyverse came into being which had more verbose names for everything. (Credit to Doyle and Hadley)

I don't really see pivot and melt as being inverses. If you pivot with an aggregation then there's no inverse to undo the aggregation.

In SQL there is both pivot and unpivot but the pivot in that case is more restrictive as it requires knowing the new columns in advance. Even unpivot requires the columns to values as part of the query.

Ultimately I don't think anything different is so much better as to justify renaming any methods. I do think there's a good case to syncing the input parameter names between pivot and melt but that's just either index to id_vars or id_vars to index as the only parameter in common.

Lastly, I'd just flag this other pivot issue that might be tangentially related https://github.com/pola-rs/polars/issues/11592

**Comment by JulianCologne** [comment]
> I disagree about unpivot. I think if you didn't already know what pivot does that it wouldn't seem so intuitive and hence neither would unpivot.

in my experience everyone working in data knows or has heard of pivot-tables or pivoting data. You find it in excel, sql, powerbi, r packages, python libraries, ... (just did a small survey within data teams and 95%+ knew `pivot` but **no one** knew `melt`)


> I don't really see pivot and melt as being inverses. If you pivot with an aggregation then there's no inverse to undo the aggregation.

They are no perfect inverses (for a lot of use cases they definetely are!) I agree, but they are generally seen as inverse-like operations
Microsoft: "UNPIVOT carries out the opposite operation to PIVOT"; Duckdb: "The PIVOT statement is the inverse of the UNPIVOT statement."


> In SQL there is both pivot and unpivot but the pivot in that case is more restrictive as it requires knowing the new columns in advance. Even unpivot requires the columns to values as part of the query.

Depends on your sql flavor. Duckdb's pivot/unpivot are very flexible ;)

> Ultimately I don't think anything different is so much better as to justify renaming any methods. I do think there's a good case to syncing the input parameter names between pivot and melt but that's just either index to id_vars or id_vars to index as the only parameter in common.

the value of a good and clean api should by no means be underestimated. Polars is doing a great job here and is really polishing its api and not afraid of breaking things for the better.

---

Thinking about this a bit more I really come to like the idea of `pivot_wider` / `pivot_longer` (thanks @markfairbanks)
It has the `pivot` name which is known by many people in combination with the direction of the transformation

**Comment by deanm0000** [comment]
> (just did a small survey within data teams and 95%+ knew pivot but no one knew melt)

Frankly, all this tells me is that your data teams are people who mostly use Excel and isn't particularly persuasive.

Getting back to the point at hand, renaming function names, just because there's a more verbose or subjectively intuitive name isn't really making the api cleaner or better. Making it cleaner is doing things like "hey guys we said we're doing snake case so let's rename groupby to group_by to be consistent with that". There's nothing "unclean" about melt and pivot not having a word in common between them.

As far as pivot_wider and pivot_longer are concerned, when tidyr came up with those names, it wasn't just that they renamed their predecessors but made new syntax and the new names are meant, in part, to signal the change in usage.

melt is a standard term that has existed long enough that I think it should take considerably more reasoning to change it.

**Comment by JulianCologne** [comment]
> Getting back to the point at hand, renaming function names, just because there's a more verbose or subjectively intuitive name isn't really making the api cleaner or better. Making it cleaner is doing things like "hey guys we said we're doing snake case so let's rename groupby to group_by to be consistent with that". There's nothing "unclean" about melt and pivot not having a word in common between them.

I disagree.

I think there are 2 important factors when naming functions:
1. consistency
  - this is nice to have; it just feels good to use a library that has well defined guidelines and ensures them across all functions; 
2. semantics
  - this is arguable much more important
  - teams nowadays are more cross functional than ever. We have different roles (data analysts, scientists, engineers, business analysts, database people, product owners, managers) all with different backgrounds (excel, sql, python, r, javascript, ...) working together
  - it is incredibly advantageous if apis/functions describe semantically what they do in terms most people understand. Most team members that do not know python/polars can often read and understand polars data transformation code because it is so expressive!! =)

> melt is a standard term that has existed long enough that I think it should take considerably more reasoning to change it. That's all I'll say on this topic, you can have the last word

it might be true that this term existed for a long term but as I shown above almost all tools use unpivot. This is about people and using terms that people know to make it discoverable.

---

My proposal is nothing personal / subjective. I just want to make polars better for everyone out there and I thought this is a positive change. 
I myself remember having trouble to find `melt` because I was looking for `unpivot`. Using modern editors like VSCode and autocompletion you would just type `.piv` and would get suggestions like `pivot_wider/pivot_longer`. This makes the functionality discoverable and there is no need to check which direction they go because it is in the name.

We are not the ones with the final decision so there is no need to fight about this. Still, I always appreciate discussion ;)

**Comment by mgirlich** [comment]
When tidyr introduced `pivot_longer/pivot_wider` things got so much easier for me and many people on Twitter claimed the same. The names communicate so much better what they do compared to the previous `spread/gather` or in polars case `pivot/melt`. Quoting from the [documentation](https://tidyr.tidyverse.org/dev/articles/pivot.html):

> For some time, it’s been obvious that there is something fundamentally wrong with the design of [spread()](https://tidyr.tidyverse.org/dev/reference/spread.html) and [gather()](https://tidyr.tidyverse.org/dev/reference/gather.html). Many people don’t find the names intuitive and find it hard to remember which direction corresponds to spreading and which to gathering. It also seems surprisingly hard to remember the arguments to these functions, meaning that many people (including me!) have to consult the documentation every time.

**Comment by vankesteren** [comment]
I cannot add much to what has been said, but I just want to show support for the renaming side of this discussion. 

Naming is important, especially for new users, and can make or break a first-time experience with a new package. From my point of view, I haven't seen better names for these operations than `.pivot_wider()` and `.pivot_longer()`: relatively short, unambiguous, and clearly related.

**Comment by MarcoGorelli** [comment]
In PySpark, [melt is an alias for unpivot](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.melt.html#pyspark.sql.DataFrame.melt)

"melt" also means nothing to me tbh 😄

I'm not usually a fan of aliases, but maybe here it'd be OK, given the PySpark precedent and the desire to cater to users coming from a variety of backgrounds (pandas, R, pyspark, duckdb)

I'd rather not rename to `pivot_wider` / `pivot_longer` to be honest - first, because `pivot` is widely used (pyspark, pandas, duckdb), and second because Polars' users are growing rapidly and so I think deprecations should now be done very carefully and only when there's a clear advantage

So, I'd support a `DataFrame.unpivot` alias for `DataFrame.melt`

**Comment by eitsupi** [comment]
IIUC, `pivot_longer`/`pivot_wider` also can be used in DuckDB.
In other words, `pivot_longer` is an alias for `pivot`, and `pivot_wider` is an alias for `unpivot`.
See duckdb/duckdb#6387.

**Comment by datenzauberai** [comment]
I would also love to see something along `pivot_longer` and `pivot_wider`, because I would never have a doubt, if I want to go longer or wider.

**Comment by stinodego** [comment]
We want to add `unpivot` and align the parameters with `pivot`.
