### ISSUE TITLE
Provide a way to de-conflict columns that come from hive partitioning vs what's in a physical file

### ISSUE THREAD

**Issue by kszlim** [pola-rs/polars#12041]
### Description

For context see:
https://github.com/pola-rs/polars/issues/12036

I propose that we either deprecate `hive_partitioning` in favor of `hive_partitioning_strategy` (alternatively maybe even repurposing the old name, but that might be more confusing) in `scan_parquet`  which takes in `"favor_partition"` (means drop the physical column/don't read it), "`favor_physical`" (idk about this name, but means ignore the partition key), "`favor_none`" (which should throw an error if there are conflicts and should be the default + maps to the old parameter set to `True`) and `None` for no hive partitioning (equivalent of `hive_partitioning=False`)?

I think it's a pretty important feature, as the person querying the data often has no control over how it's written.

Created a feature as per @ritchie46 's request. Thanks!

**Comment by jrothbaum** [comment]
This would be super helpful. As it is, I can't use polars to load the hive partitioned files I work with and have to fall back to duckdb. I lose the benefit of lazy loading for the files that would most benefit from it.

**Comment by stinodego** [comment]
Not sure about the proposed API, but this feature would definitely be nice to have.

**Comment by jrothbaum** [comment]
I work with hive partitioned data that has the partition key in the file, which I suspect is done to avoid the casting/type issue from https://github.com/pola-rs/polars/issues/13892 and https://github.com/pola-rs/polars/issues/14838 while taking ~0 space (since, by definition, the key is the same for all rows in each partition file).  I'm indifferent about the API implementation details.

**Comment by stinodego** [comment]
> I work with hive partitioned data that has the partition key in the file, which I suspect is done to avoid the casting/type issue from #13892 and #14838 while taking ~0 space (since, by definition, the key is the same for all rows in each partition file). I'm indifferent about the API implementation details.

If that is done consistently, you can just set `hive_partitioning=False` and you're good to go.

**Comment by ritchie46** [comment]
@nameexhaustion this one might also be a good data point in the design for the hive partition redesign.

**Comment by ritchie46** [comment]
Right. Can we make a new feature request for the reduced scope. Then we can make a decision about that.

**Comment by Veiasai** [comment]
I still met duplicated columns on polars 1.6.0 when the column exists in both hive path and parquet.

How could I send you the parquet file for reproducing?

**Comment by gwerbin-tive** [comment]
For anyone exporting data from Snowflake and feeling very confused about this: the columns in the schema will (by default) be written as `UPPER_CASE`, so you need to write your Hive partitioning with `UPPER_CASE=123` as well. Otherwise, Polars interprets `foo=123` in the directory name as distinct from `FOO` in the Parquet schema. Then if you naively rename all columns to lower case like I did, you end up with duplicate column names.
