### ISSUE TITLE
`corr()` diagonals not guaranteed to be equal to 1

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#12078]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.DataFrame({'a': [1, 2, 3] * 1000, 'b': [4, 6, 5] * 1000}).corr()[0, 0]
0.9999999999999999
```

### Issue description

The diagonal entries of the correlation matrix returned by `corr()` are not guaranteed to be equal to 1 due to floating-point error. 

### Expected behavior

Polars should automatically set the diagonals to 1 without computing the correlation. This is more efficient and also ensures that testing for exact equality works correctly.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.11
Index type:          UInt32
Platform:            Linux-3.10.0-1160.99.1.el7.x86_64-x86_64-with-glibc2.17
Python:              3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.26.0
openpyxl:            3.1.2
pandas:              2.1.2
pyarrow:             13.0.0
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          3.1.7
```

</details>

**Comment by cjackal** [comment]
`pl.DataFrame.corr` is just a wrapper of `np.corrcoef` (thus the same floating-point error), so there wouldn't be a performance gain in setting the diagonal to 1 (as we can't help but first compute `np.corrcoef` and then set diagonal to 1). To achieve performance gain we need to internalize `corr` (I mean, rewrite `corr` in rust which must be comparable or faster than `np.corrcoef`) which requires a nontrivial work (BLAS yoga off my head) I guess. Supporting all the keywords in `np.corrcoef` would add more burden, though it may be possible to make disparity from numpy's signature?

And probably because of the same reason many well-established scientific libraries (`torch` at least...?) have the same floating-point error, so current behavior in `polars` is kind of admissible I think.

**Comment by Wainberg** [comment]
Ah cool - so in that case maybe we just add an `np.fill_diagonal(correlation_matrix, 1)` before returning the correlation matrix?

**Comment by stinodego** [comment]
I think this can be closed as per the discussion in the linked PR.
