### ISSUE TITLE
Add .div() to the pl.Expr namespace as an alias to .truediv()

### ISSUE THREAD

**Issue by mkleinbort-ic** [pola-rs/polars#12450]
### Description

We currently have `pl.Expr.add`/`.sub`/`.pow`/`.mod`/`.mul`/ ..., but no `.div`.

I understand the expectation is that users will use `.truediv`, but I feel having `.div` as an alias to `truediv` would be:

1. Clean
2. Intuitive
3. Consistent
4. Newcomer friendly

We currently allow

```python
pl.col('A')/pl.col('B')
```

So why not have

```python
pl.col('A').div(pl.col('B'))
```

implement the same logic.

> PS. I still write `.div` in my code and re-write it when I see my failing tests.

**Comment by alexander-beedie** [comment]
We have two div functions because they do two different things - `truediv` and `floordiv`. Introducing a third `div` that is really just an alias for `truediv` just causes lack of clarity for no meaningful/substantial gain.

**Comment by mkleinbort** [comment]
To clarify, the issue is not the typing, it is explaining truediv to new users (/ programer surprise)

I agree having div and truediv would be redundant. How about renaming truediv to div? 

On the one hand it's a very shallow change, but on the other it may be a good investment in usability in the long run.

**Comment by alexander-beedie** [comment]
> On the one hand it's a very shallow change, but on the other it may be a good investment in usability in the long run.

I think this just allows people to assume that `div` means what they _think_ it means, rather than what it _does_ mean. I don't mind people seeing there are two div methods and having to think about it (but only once or twice) to know which one they want, because it will likely lead to improved clarity over the long run.
