### ISSUE TITLE
read_sas() functionality

### ISSUE THREAD

**Issue by codydance** [pola-rs/polars#12546]
### Description

I am interested in functionality that would allow the creation of lazyframes/dataframes from sas7bdat files. Admittedly, the use case is a little niche. I am working on a secure server where Spark/PySpark are not allowed, the datasets are too large for memory (so no pandas read_sas()), the SAS version on the server doesn't support parquet exports, and using the sas7bdat python package to create a dataframe line by line takes several hours.

If there is interest in this feature, I would be interested to start working on it.

**Comment by jrothbaum** [comment]
An option is to read them in chunks with pandas (https://stackoverflow.com/questions/62830718/how-to-read-sas-file-in-chunks-in-python-pandas), and
have polars save them to separate parquet files.  It's not optimal but there aren't a lot of sas file readers because I don't think the documentation is very good for the file format.

**Comment by universalmind303** [comment]
This seems too niche for the core polars lib. This seems like a good candidate for a community supported plugin/library.

**Comment by jrothbaum** [comment]
Does this help: https://github.com/jrothbaum/polars_readstat, https://pypi.org/project/polars-readstat/
