### ISSUE TITLE
Custom calendar and lag by date

### ISSUE THREAD

**Issue by julian-sieber** [pola-rs/polars#12726]
### Description

Polars has some functionality for working with `DateTimes` (e.g., offsets, join_asof, group_by_rolling, ...). However, those
are based on the standard calendar. It would be great if we could use these methods on a custom calendar. In addition,
I propose to implement `Expression.lag` for datetime strings. For example, `pl.col("val").lag("1d", by='datetime_col')` would give me the value of `val` at 1 day ago over a (custom) calendar, rounding it down to the last valid value previous to that time, in case it doesn't exist.

**Comment by MarcoGorelli** [comment]
Can you show an example with expected output please?

**Comment by NekoApocalypse** [comment]
An example of a custom calender would be: a work day calendar for a particular country/ company, or trading days for a specific stock.

I think this situation is fairly common for time-series analysis for business / financial data.

What I currently do is to convert the custom calendar into an i64 index, and look up the exact date in that index.

However, it becomes quite complicated when I'm doing aggreagation over intra-day data because I cannot use `group_by_rolling` to aggregate N work days.

**Comment by MarcoGorelli** [comment]
Thanks for the request - I think you're looking for https://github.com/MarcoGorelli/polars-business (this came up before, and the general preference was for this to be a Polars plugin rather than a core functionality)

Closing then, if you have any requests please post them there in https://github.com/MarcoGorelli/polars-business/issues
