### ISSUE TITLE
Text in search bar not visible

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#12776]
### Description

when searching in the polars docs the text in the search bar becomes almost invisible because of bad contrast
https://pola-rs.github.io/polars/py-polars/html/search.html?q=filter#

![image](https://github.com/pola-rs/polars/assets/25177421/d646862c-f1c7-44f4-8c91-fe85846a4404)

![image](https://github.com/pola-rs/polars/assets/25177421/66a87f8c-d3fb-4738-9666-007ae6557624)

### Link

https://pola-rs.github.io/polars/py-polars/html/search.html?q=filter#

**Comment by stinodego** [comment]
You're right - it becomes legible again when you place your cursor in the search box.

I would welcome a PR that fixes this.

**Comment by SamKnightGit** [comment]
This should be fixed once the docs website is rebuilt with pydata-sphinx-theme v0.15.1 following the [docs dependency bump](https://github.com/pola-rs/polars/pull/17199/files).

The fix for the text styling is [here](https://github.com/pydata/pydata-sphinx-theme/pull/1524) and was first rolled out in [pydata-sphinx-theme v0.14.2](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.14.2).

**Comment by stinodego** [comment]
@SamKnightGit Thanks for the heads-up. Indeed, this is now fixed in de dev docs, and on the next release will be fixed on the stable docs as well.

Thanks, closing then!
