### ISSUE TITLE
Feedbacks regarding the release process

### ISSUE THREAD

**Issue by Vincent-Maladiere** [pola-rs/polars#12892]
### Description

Hey team,

Thank you for working on this project.

I'm a developer of skrub, a library operating on dataframes, and we are progressively adding support to Polars. We often notice that our CI breaks due to the latest release of Polars, which might get yanked down the road.

This is not exactly a feature request but feedback regarding our developer experience. Should we pin the latest working version in our CI and update it regularly, or keep the latest and wait for a new release? WDYT?

**Comment by mcrumiller** [comment]
> Should we pin the latest working version in our CI and update it regularly, or keep the latest and wait for a new release? WDYT?

I would pin and manually update only when you've purposefully updated. Keep in mind that until polars hits 1.0.0 its API is in pretty constant flux, and while there is effort to be good about deprecations prior to removal, often there are changes that are indeed breaking (for example, the conversion to three-way boolean logic changed the way logical comparisons work, and `is_in` no longer returns `False` comparisons to null values), in addition to versions maybe getting yanked. If you leave it to your CI to grab the latest release, you're going to hit bad surprises every single time.

For this reason, for my team we are very strict about specifying the associated polars version with each update of our project, so that every version is tied to a specific Polars version and can be replicated without much fuss. It also means when bumping up polars, we run a pretty big test suite and iron out all the differences.

**Comment by stinodego** [comment]
We can't make that decision for you. There are pros and cons to pinning versions, as you will know. If the broken CI is causing issues, pin it. If it's manageable, don't pin it to make sure your library works with the latest Polars.
