### ISSUE TITLE
to_pandas() breaks Python objects in object column

### ISSUE THREAD

**Issue by unarist** [pola-rs/polars#13021]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import pandas as pd
import polars as pl
from pathlib import Path

df = pl.DataFrame([Path("index.html")], schema={"path": pl.Object})
print(df.to_dicts())
print(df.to_pandas().to_dict(orient="records"))
```
Output:
```
[{'path': WindowsPath('index.html')}]
[{'path': b'\x80\x1bbJ\xdf\x01\x00\x00'}]
```

### Issue description

Both of Polars and Pandas can hold Python objects like `pathlib.Path` in `dtype=object` column.

Converting those dataframe by `to_pandas()` doesn't throw errors, but values seems broken.

### Expected behavior

```
[{'path': WindowsPath('index.html')}]
[{'path': WindowsPath('index.html')}]
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Windows-10-10.0.22621-SP0
Python:               3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
matplotlib:           3.7.1
numpy:                1.24.2
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              11.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It seems to be happening during the pyarrow conversion:

https://github.com/pola-rs/polars/blob/0e34695acd32c705d4f45c06a87d887d16843315/py-polars/src/dataframe.rs#L879

Which does some low-level stuff:

https://github.com/pola-rs/polars/blob/2aa3bae4c21ae5cd9efbcd1ebb252e75a1e52e75/py-polars/src/arrow_interop/to_py.rs#L9

The Path ends up as a `fixed_size_binary` type:

```python
pl.DataFrame([Path("index.html")]).to_arrow()
# pyarrow.Table
# column_0: fixed_size_binary[8]
# ----
# column_0: [[60BA073201000000]]
```

Does anybody know what this binary value represents and if the original object can be reconstructed from it?

**Comment by barak1412** [comment]
Same.
My workaround is:
```
import pandas as pd
df = ...
print(pd.DataFrame(df.to_dicts()))
```

**Comment by itamarst** [comment]
* [ ] Fix with `use_pyarrow_extension_array=True`
* [ ] Fix with `use_pyarrow_extension_array=False`
* [ ] See what other column types are lacking tests (presuming this is the case here), add tests or file separate issue

**Comment by itamarst** [comment]
What I've learned so far:

* Polars stores Python objects as a `Extension("POLARS_EXTENSION_TYPE", FixedSizeBinary(8), Some("1705683441296583929;124507012827808"))` type.
* `FixedSizeBinary` is what ends up in the PyArrow-controlled table.
* This then gets turned into a binary string once it hits Pandas.
* Pandas doesn't have an Arrow-based representation for an object dtype.

#### Option #1: Casting

* For 64-bit platforms the `Extension` could use a int64 instead of 8 bytes.
* When exported via PyArrow, the result would be a Pandas Series of int64s.
* That memory could then be reinterpreted as `PyObject*` by changing the dtype. Which you can't do from Python, the APIs don't have this use case exposed, would have to be done via Pandas low-level API (if that even exists? seems like maybe not) or more likely NumPy C API. This is not a well-supported use case.
* If I'm understanding correctly the pointers are being copied from Arrow to a NumPy array. That effectively means an additional reference to all the Python objects, so they'd all have to be incref-d.

#### Option #2: Bypass PyArrow

`pl.Series.to_numpy()` _does_ do the right thing for the `pl.Object` dtype, so can just use that for these particular columns.

**Comment by itamarst** [comment]
I got Option 2 working pretty easily, so just need to write tests.
