### ISSUE TITLE
Remove fast-float crate?

### ISSUE THREAD

**Issue by jqnatividad** [pola-rs/polars#13035]
### Description

The Eisel-Lemire algorithm at the heart of the fast-float crate has been merged into std.

https://github.com/rust-lang/rust/pull/86761

Does polars still need fast-float?

See https://github.com/aldanor/fast-float-rust/issues/34

**Comment by orlp** [comment]
I can run a quick benchmark today to see if there's a significant performance difference if we remove the dependency, and if not we can just remove it.

**Comment by orlp** [comment]
A bit late, I did do the benchmark and there was essentially no difference between the stdlib parse and `fast_float` parse.

There is however another problem:
```rust
        unsafe {
            // SAFETY: this is technically not ok, but the first line of
            // the stdlib parse implementation calls s = s.as_bytes()...
            std::str::from_utf8_unchecked(bytes).parse().ok()
        }
```

We directly want to parse bytestrings which `fast_float` supports but the stdlib doesn't. So either we do this thing which isn't really kosher, or keep using the stdlib. @ritchie46 Thoughts?

**Comment by orlp** [comment]
Relevant stdlib proposal: https://github.com/rust-lang/libs-team/issues/287.

**Comment by ritchie46** [comment]
I believe the bytes is the reason we use fast-float indeed. I'd say let's wait.

**Comment by ritchie46** [comment]
Yes, if `std` would accept bytes we could remove fast floats. We parse floats directly from bytes that may have invalid utf8. Having to do utf8 checking first makes it more costly than needed. Why is the `fast_float` dep a problem?

**Comment by jeadorf** [comment]
I went through a code review process when importing dependencies of Polars. Some questions/cocnerns popped up about `fast_float`, around some of the `unsafe` uses in `fast_float`. This then prompted me to find out about the state of this issue: since if the `fast_float` dependency were removed, we would need to look no further. Thanks for helping me understand.

**Comment by Manishearth** [comment]
@ritchie46 would it be acceptable to make `fast-float` an optional dependency and use _checked_ `from_utf8` as the alternative? This way people can have safe-but-slightly-slower code.

Or even a manual impl copied from the stdlib.

**Comment by ritchie46** [comment]
To my knowledge `fast-float` is sound. There are many dependencies that use `unsafe` and to create feature flags and alternatives for all of them would be a maintenance nightmare. What is it specific on `fast-float`? Is there something unsound?

**Comment by Manishearth** [comment]
Someone needs to file an issue about it with detail (sorry, IMO that should have happened first), but basically in the process of an unsafe audit we discovered that `fast-float` is rather careless with unsafe: it checks safety invariants with `debug_assert!()`, invariants that _might_ be upheld elsewhere in the codebase but not in a proximate, obvious manner. It's unclear to me at this time if there is any actual UB in the crate, but it is a bit of an outsize burden on a dependency tree to have crates that have nonlocal safety invariants (since you have to check them again every time you update)

**Comment by Manishearth** [comment]
Filed an issue with some detail: https://github.com/aldanor/fast-float-rust/issues/37

Doing a proper safety audit of that code will take much longer and is not really worth it for me, at least.
