### ISSUE TITLE
pl.ones & pl.zeros fail with pl.Boolean dtype in eager mode

### ISSUE THREAD

**Issue by radugrosu** [pola-rs/polars#13121]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.zeros(3, pl.Boolean, eager=True)
```
produces a series with nulls (same happens for `pl.ones`)

### Issue description

However, 
```python
pl.zeros(3, eager=True).cast(pl.Boolean) 
```
works.

### Expected behavior

So does

```python
pl.repeat(False, 3, eager=True)
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.1
Index type:           UInt32
Platform:             Linux-6.2.0-39-generic-x86_64-with-glibc2.35
Python:               3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              10.0.1
pydantic:             2.5.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
This isn't a bug; the functions are pretty explicit that they create 1s or 0s, not boolean True/False ;)  However, I'll tag it as a feature request instead so that we can have a think about it, as it isn't exactly unusual to treat 1/0 as equivalent to boolean. And in any case we should raise an error on incompatible dtypes, not return nulls 🤔

**Comment by alexander-beedie** [comment]
> 1. It used to work, so it's a regression.

You didn't actually mention that it might be a regression 😉 

> 2. Why would they take a dtype argument if they only returned 0s or 1s.

Because we have quite a lot of numeric types (eg: signed/unsigned floats in sizes ranging from 8-32 bit, two flavours of float, and a decimal dtype); instantiating with the correct one of these up-front is much more efficient than requiring a post-init cast from a default dtype.

> 3. The `pl.Utf8` dtype actually works and returns what you'd expect! It's only `pl.Boolean` that fails.

This (slightly) surprises me (the ones/zeros are syntactic sugar for `repeat(1.0)` and `repeat(0.0)`), so it's probably being done less efficiently than if it were declared with the correct type internally - which I can also look at so that it doesn't need to do an internal cast (_if_ that's happening).

Anyway, my intention is to make this work as it seems like reasonable behaviour, but if it was doing so before that was (probably) something of an accident 🤔

**Comment by alexander-beedie** [comment]
> I have opened a PR to show this, but feel free to take over it, if you have a better idea. :)

Nice one! I'll add a small tweak on the python side to codify what we consider a valid one/zero cast 👍
