### ISSUE TITLE
Preserve name when passing a Series to pl.Series(), and allow passing a DataFrame to pl.DataFrame()

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13338]
### Description

Passing a Series to `pl.Series()` removes its name:
```python
>>> pl.Series(pl.Series('a', [1])).name
''
```
and passing a DataFrame to `pl.DataFrame()` doesn't work at all:
```python
>>> pl.DataFrame(pl.DataFrame({'a': [1]}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wainberg/miniforge3/lib/python3.12/site-packages/polars/dataframe/frame.py", line 417, in __init__
    raise TypeError(
TypeError: DataFrame constructor called with unsupported type 'DataFrame' for the `data` parameter
```
These should both be allowed and should preserve the name and columns, respectively.

**Comment by alexander-beedie** [comment]
No, you are creating a _new_ Series here; if you want a clone of the original that's what `.clone()` is for. Otherwise you are simply providing the data to a new/different object, which should have its own name. 

I'm also curious what the use-case is for passing a DataFrame to a DataFrame? This also just sounds like you want `.clone()`, no? (It can be supported easily enough, for consistency with Series if nothing else, but am wondering what the pattern is that gets you here?)

**Comment by Wainberg** [comment]
This kind of thing happens when the input could be a Series already, or could be something of a different type like a NumPy array. Of course, you can always do an isinstance check, but it's reasonable to expect the name of the Series to default to what was passed in. And it works in pandas:
```python
>>> pd.Series(pd.Series([1, 2], name='foo'))
0    1
1    2
Name: foo, dtype: int64
```

**Comment by alexander-beedie** [comment]
> it's reasonable to expect the name of the Series to default to what was passed in

It's not, because you are creating a _new_ object - there is nothing about initialising a new object that implies you are special-casing the clone of an existing object, and this can lead to problems elsewhere with a profusion of identically-named (but different) objects.

I'm fine adding support for initialising a DataFrame from another DataFrame though, as we already allow Series init from Series, and DataFrame init from Series, so there is established consistency here 👌

**Comment by Wainberg** [comment]
I mean, this is just blatantly inconsistent:

```python
>>> pl.Series(pd.Series([1, 2], name='foo')).name
'foo'
>>> pl.Series(pl.Series('foo', [1, 2])).name
''
```

**Comment by alexander-beedie** [comment]
Not really; if you are creating a new Series from an external type (pandas) then there is no overlap with existing polars objects. If you init a polars Series from another polars Series, you are going out of your way _not_ to call `clone()`, implying that you don't want that behaviour. It's arguable, but I don't think it's inconsistent.

@stinodego: Any thoughts on this? I could go either way, with a preference to keeping the existing behaviour (don't inherit the existing Series name as we have `clone()` for that, and you're creating a new object), but if we already do it for pandas Series then I can see the argument for doing it for polars Series too 🤷

**Comment by stinodego** [comment]
If we can infer the column name(s) from the data, and no names were passed to the constructor, we should use the names present in the data.

So we should use the name of the Series passed to the Series constructor, if the name wasn't provided to the constructor.

I think we should also accept a DataFrame passed to the DataFrame constructor. And the same logic applies: unless `schema` was specified, we use the names/dtypes of the DataFrame that was passed in.
