### ISSUE TITLE
Arithmetic resulting data type is incorrect in some cases

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#13804]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

lf = pl.LazyFrame({"a": [1, 2, None]}, schema={"a": pl.Float32})

result = lf.select(pl.lit(0) - pl.col("a"))

print(result.schema)  # {'literal': Float64}
print(result.collect().schema)  # {'literal': Float32}

```

### Issue description

The supertype is used in the query plan, but during materialization, the literal data type is disregarded.

Weirdly enough, if I alias the result, the data type is correct:

```python
result = lf.select(a=pl.lit(0, dtype=pl.Int32) - pl.col("a"))
```

### Expected behavior

Data type of the query plan should match the data type after collecting.

### Installed versions

main

**Comment by ritchie46** [comment]
At the moment there is something that's not easily fixable and that is that we have python dynamic types whom we don't want to coerce columns. The `type-coercion` pass tries to fix that. That's why there can be a difference in the schema before and after optimizations in dtypes.

What we need to add are new `LiteralValue::Int` and `LiteralValue::Float` where we regard them as coming from a dynamic language and thus we can later determine what the `dtypes` of those will materialize to.

**Comment by stinodego** [comment]
This has been resolved.
