### ISSUE TITLE
Casting from `Date` to `Time` should raise

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#14124]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import date

s = pl.Series([date(1970, 1, 1), date(2000, 12, 31)])
result = s.cast(pl.Time)
print(result)
```

### Log output

```shell
shape: (2,)
Series: '' [time]
[
        00:00:00
        00:00:00
]
```

### Issue description

Apparently the result is always `00:00:00`.

### Expected behavior

I would say the time for a `date` is undefined so this should raise.

### Installed versions

main

**Comment by MarcoGorelli** [comment]
agree (`s.dt.time` raises)

**Comment by mcrumiller** [comment]
@stinodego I brought this one up a while back regarding temporal castings that make sense and those that don't--perhaps we should have a few more issues around this topic. Here is my list of what logically (to me) makes sense:

From dtype | to Date | to Datetime | to Time | to Duration
-----------|---------|-------------|---------|-------------
Date       |   -     | Yes         | No      | N
Datetime   |   Yes   | -           | Yes     | N
Time       |   No    | No          | -       | maybe
Duration   |   No    | No          | maybe   | -

The "maybe" is between time and duration. I could see time of day being the duration since day start, so mapping back and forth could make sense if duration < 24h, but that's a bit "maybe."

**Comment by stinodego** [comment]
The problem is that logical casting falls back to simply casting the physical type. I'm taking another look and disabling some invalid casts.
