### ISSUE TITLE
ability to set logRetentionDuration and deletedFileRetentionDuration in write_delta in delta_write_options 

### ISSUE THREAD

**Issue by 0xdarkman** [pola-rs/polars#14332]
### Description

It would be great to be able to set logRetentionDuration and deletedFileRetentionDuration when creating an empty DeltaTable with polars. I see this is the only way to initialize an empty DataFrame without pyspark/spark but I am missing retention config.

```
schema: pyarrow.lib.Schema
partition_by: list[str]
table_path: str
storage_options: dict[str,str]

data = []
df = pl.DataFame(data)
df.columns = [x.name for x in schema]

df.write_delta(
            table_or_uri=table_path,
            storage_options=storage_options,
            mode="append",
            delta_write_options={"schema": schema, "partition_by": partition_by},
        )

```

**Comment by ion-elgreco** [comment]
These questions belong here: https://github.com/delta-io/delta-rs/issues

And you can set the logRetentionDuration on first write. `write_deltalake` uses configuration parameter to set the table configuration on the first write.

So that would be `df.write_delta(delta_write_options={"configuration: {"logRetentionDuration": "<value>"}})`

**Comment by 0xdarkman** [comment]
this is gr8.

**Comment by 0xdarkman** [comment]
just one thing to note here:

it should be:
{"configuration: {"delta.logRetentionDuration": "<value>"}}

and not 

{"configuration: {".logRetentionDuration": "<value>"}}

@ion-elgreco
