### ISSUE TITLE
calling `.head()` after `with_columns(ser)` results in ShapeError

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#14349]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1]*12}).lazy()

print(
    df.with_columns(b=pl.Series([0]*12))
    .head(5)
    .collect()
)
```

### Log output

```shell
$ POLARS_VERBOSE=1 python t.py
Traceback (most recent call last):
  File "/home/marcogorelli/tmp/t.py", line 8, in <module>
    .collect()
  File "/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1940, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ShapeError: unable to add a column of length 12 to a DataFrame of height 5
```

### Issue description

Swapping `.head(5)` with `collect`, it works fine

### Expected behavior

```
shape: (5, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 0   │
│ 1   ┆ 0   │
│ 1   ┆ 0   │
│ 1   ┆ 0   │
│ 1   ┆ 0   │
└─────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.7
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               <not installed>
hvplot:               0.9.1
matplotlib:           3.8.2
numpy:                1.26.3
openpyxl:             <not installed>
pandas:               2.1.0
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.25
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by cmdlineluser** [comment]
It runs with `slice_pushdown` disabled if it helps narrow things down:

```python
(df.with_columns(b=pl.Series([0]*12))
   .head(5)
   .collect(slice_pushdown=False)
)

# shape: (5, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ i64 ┆ i64 │
# ╞═════╪═════╡
# │ 1   ┆ 0   │
# │ 1   ┆ 0   │
# │ 1   ┆ 0   │
# │ 1   ┆ 0   │
# │ 1   ┆ 0   │
# └─────┴─────┘
```

**Comment by deanm0000** [comment]
well you found the bug in what I thought was purely user error.

That said, does it really make sense to allow adding a Series to a LazyFrame? The schema doesn't know how long the frame is until collection so there are probably other ways similar issues can manifest.

Consider this:
```
df=pl.select(a=pl.int_range(0,15)).lazy()
df=df.with_columns(z=pl.int_range(0,20))
df.collect()
ShapeError: unable to add a column of length 20 to a DataFrame of height 15
```

**Comment by mcrumiller** [comment]
@deanm0000 in my opinion, it should work because we have no representation of a lazy Series really (it's just an expression) and there's no `pl.Expr.from_data()` that would mimic a real-life series.

Your example fails because the series is not appropriate for the operation (it's the wrong size). If it *is* appropriate, then it should work. If someone hands me a list of cities then I should be able to use it with laziness. The following is valid:

```python
def do_polar_stuff(list_of_cities):
    pl.LazyFrame({
        "a": list_of_cities
    }).with_columns(...).collect()
```

shouldn't using a materialized Series later be too?

**Comment by deanm0000** [comment]
I have two cases in mind when I ask why adding Series to LazyFrames is allowed.

One are the trivial small row count DataFrames turned lazy. In those cases it would be trivial to add the column in the dataframe context, that is to say

```
df.collect().with_columns(pl.Series(...)).lazy()
```

The other is scanning parquet files

```
pl.scan_parquet("/hive/*/*/*.parquet")
.with_columns(pl.Series(...))
```

in which case you should probably do a proper join rather than counting on the order of scanned rows.

That said, far be it for me to tell people what to do so I'm not _earnestly proposing_ to take away the ability to add literals to lazyframes. It was just a passing thought.

As a workaround instead of using `with_columns`, this works

```
df = pl.DataFrame({"a": [1]*12}).lazy()

print(
    pl.concat([
        df,
        pl.select(b=pl.Series([0]*12)).lazy()
    ], how='horizontal')
    .head(5)
    .collect()
)
```

Caveat (or maybe for bonus points): it won't raise for ShapeError it'll just have nulls.
