### ISSUE TITLE
A method to get arrow RecordBatch from Polars Dataframe for polars-rs Rust

### ISSUE THREAD

**Issue by willisfusu** [pola-rs/polars#14687]
### Description

Hi, 

I am trying to use the polars Rust to do some data analysis and want to save the data to database. It's seems that RecordBatch is required for most of the crates to save arrow format data to database. 

I found there is a similar method to convert dataframe to arraw table for [python polars](https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.to_arrow.html#polars.DataFrame.to_arrow).  I would like to know is it possible to have a method to get RecordBatch from polars Dataframe for polars Rust?

Thank you for your efforts.

**Comment by ritchie46** [comment]
Can you ask a question on StackOverflow? We have that functionality.

If you post that question in our discord, our team or our community will answer that question. We do it that way because we drown in usage questions and really want to build up an answer database, eg SO.

**Comment by willisfusu** [comment]
Hi @ritchie46 ,

Thank you for your reply. 

No problem, I posted[ a question on SO](https://stackoverflow.com/questions/78058517/polars-rust-convert-dataframe-to-arrow-rs-recordbatch-save-dataframe-to-database)

**Comment by kcullimore** [comment]
Hi @ritchie46, @jorgecarleitao,

Apologies for posting in this location, but I’m struggling to find a supported way to convert between Polars DataFrames and Arrow’s RecordBatch in Rust. While the Python API has to_arrow() and from_arrow(), the Rust equivalent isn’t obvious. I do understand the difference in arrow crates. 

If there’s a recommended approach—whether via the C Data Interface or another method—I’d really appreciate any guidance. If no direct method exists, what’s the best workaround?

Posting here since @willisfusu S.O. question didn't seem to be properly answered and I find it unlikely the general community will have enough familiarity to do so. Didn't want to reopen an issue either. 

Thanks!

Kane
