### ISSUE TITLE
Parity in methods between `polars.Series` and `polars.Expr`

### ISSUE THREAD

**Issue by wangkev** [pola-rs/polars#14686]
### Description

It would be great to have parity in the methods available for `polars.Series` and `polars.Expr` (e.g. `polars.Series` does not have the operator methods that `polars.Expr` has). Especially as the documentation states that "Polars expressions are a mapping from a series to a series," I think it would make sense to make the two as consistent as possible.

**Comment by ritchie46** [comment]
Expression and `Series` have a different goal. It isn't encouraged to do data processing with `Series`. They are a mere data structure that help you get some insight in a final materialized result. 

Doing data processing on `Series` instead of on expressions is very very bad. This will allow now optimizations, late materializations and have no benefit from the query engine. 

Having full parity is therefore not a goal and processing on a pure `Series` is discouraged.

**Comment by stinodego** [comment]
I'll close this since we do not aim for parity.

If there are specific Expr methods that you need on Series, please feel free to open an issue for those use cases.
