### ISSUE TITLE
[Python] Shouldn't the argument name `include_key` of `polars.DataFrame.partition_by` be changed to `include_keys`?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#14949]
There may be more than one key, so `include_keys` may be more appropriate than `include_key`.

**Comment by mcrumiller** [comment]
There is only one key. The key may be a tuple (i.e. a collection of columns), but a collection is still a singular item.

**Comment by eitsupi** [comment]
> There is only one key.

However, elsewhere it is written in the plurals as `keys`.
https://github.com/pola-rs/polars/blob/25d0a2f028bd2de0bdc140a2c040f2e2b4c2f46e/py-polars/polars/dataframe/frame.py#L7683-L7686

**Comment by mcrumiller** [comment]
This is a difference in usage. Imagine that the "key" to entering a secret club is a passcode, and each week that passcode changes. There is one key--the passcode--but the collection of passcodes form multiple key values, which one might refer to as "the keys."

In other words, there are two usages of the word "key" here: one is the key definition, the other is the key values. For the `partition_by` parameter, it makes sense to say "include the key associated with each element," because each element has only one key. It would also make sense to say "include the keys associated with the various values". But both are equally valid and I don't find one more confusing than the other.

**Comment by eitsupi** [comment]
Thank you for the explanation. I think that explanation makes sense.
