### ISSUE TITLE
str.to_datetime - support date format "%d.%m.%Y" , // 31.12.2021

### ISSUE THREAD

**Issue by MarcusJellinghaus** [pola-rs/polars#14990]
### Description

Would it make sense to add 
`%d.%m.%Y", // 31.12.2021`
to polars.Expr.str.to_datetime?

Maybe it can be just added to the [source code](https://github.com/pola-rs/polars/blob/main/crates/polars-time/src/chunkedarray/string/patterns.rs#L6C1-L6C30) ?

This would then support the date notation in Austria, Switzerland and Germany :-) ( see also [Wikipedia article](https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe#Austria,_Germany,_Switzerland) ).

( The time format is similar to other countries, eg `%H:%M:%S`, `%H:%M`. )

Or would you prefer a pull request for this?

**Comment by MarcoGorelli** [comment]
Seems reasonable to support this if it's common, thanks for the request

**Comment by JulianCologne** [comment]
I am not 100% sure about this.

I guess you mean adding `%d.%m.%Y` to the auto infer date formats?
Because using this format is no problem right now
```python
pl.DataFrame({"str": ["31.12.2021"]}).with_columns(
    date=pl.col("str").str.to_datetime(format="%d.%m.%Y"),
)
# shape: (1, 2)
# ┌────────────┬─────────────────────┐
# │ str        ┆ date                │
# │ ---        ┆ ---                 │
# │ str        ┆ datetime[μs]        │
# ╞════════════╪═════════════════════╡
# │ 31.12.2021 ┆ 2021-12-31 00:00:00 │
# └────────────┴─────────────────────┘
```

The "problem" is where to start and where to stop and how to make it unambiguous?
The iso standard is clear but for example German and US dates are ambiguous for days <= 12
- 01.01.2020 -> 1st Jan 2020
- 12.12.2020 -> 12th Dec 2020
- 01.07.2020 -> 1st Jul (DE); 7th Jan (US) 💥 
- 31.01.2020 -> only valid for DE (31st Jan)
- 01.31.2020 -> only valid for US (31st Jan)

My view is usually to either use the standard (iso format) or be explicit what you have because otherwise you often get unexpected results

**Comment by MarcusJellinghaus** [comment]
Right - I overlooked the collision with the US format.
