### ISSUE TITLE
Reading parquet files from different filesystems in azure blob storage returns "Client error with status 404 Not Found: No Body"

### ISSUE THREAD

**Issue by SDubrulle** [pola-rs/polars#15436]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl

storage_options = {
    "account_key": "<azure_storage_account_key>",
}

df1 = pl.read_parquet(
    "abfss://container1@mystorageaccount.dfs.core.windows.net/dataset1.parquet", storage_options=storage_options
)

df2 = pl.read_parquet(
    "abfss://container2@mystorageaccount.dfs.core.windows.net/dataset2.parquet", storage_options=storage_options
)
```

### Log output

```shell
POLARS PREFETCH_SIZE: 20
querying metadata of 1/1 files...
reading of 1/1 file...
POLARS ROW_GROUP PREFETCH_SIZE: 128
Traceback (most recent call last):
  File "debug.py", line 11, in <module>
    df2 = pl.read_parquet(
          ^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 171, in read_parquet
    lf = scan_parquet(
         ^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/io/parquet/functions.py", line 311, in scan_parquet
    return pl.LazyFrame._scan_parquet(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 472, in _scan_parquet
    self._ldf = PyLazyFrame.new_from_parquet(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: Object at location dataset2.parquet not found: Client error with status 404 Not Found: No Body
```

### Issue description

The issue started appearing in the bump from v0.20.10 to v0.20.13 (skipping the deleted versions 0.20.11 & 0.20.12) and has been present in all subsequent versions.

### Expected behavior

Since the storage options is applicable to both containers, there should be no issue in reading in both parquet files.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.18
Index type:           UInt32
Platform:             macOS-14.2-arm64-arm-64bit
Python:               3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           0.3.2
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             2.6.4
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             0.8.2
xlsxwriter:           <not installed>
```

</details>

**Comment by deanm0000** [comment]
You should be able to just do `"abfss://container2/dataset2.parquet"`

**Comment by SDubrulle** [comment]
Thanks, with a minor change in the code, that does indeed work. 

`
import polars as pl

storage_options = {
    "account_name": "mystorageaccount",
    "account_key": "<azure_storage_account_key>",
}

df1 = pl.read_parquet(
    "abfss://container1/dataset1.parquet", storage_options=storage_options
)

df2 = pl.read_parquet(
    "abfss://container2/dataset2.parquet", storage_options=storage_options
)`

**Comment by deanm0000** [comment]
A couple troubleshooting ideas:

1. What happens if you load `df1` from `storage_options_1` and then try to load another parquet from `storage_options_2` from a path that doesn't exist in `storage_options_1`, does that work?

2. What happens if you do: 
```
df1 = pl.scan_parquet'(path, storage_options=storage_options_1)
print(json.loads(df1.serialize())['Scan']['scan_type']['Parquet']['cloud_options']['azure'])
df2 = pl.scan_parquet'(path, storage_options=storage_options_2)
print(json.loads(df2.serialize())['Scan']['scan_type']['Parquet']['cloud_options']['azure'])
```
Do those show the different account names?

(btw in thinking through that I noticed that the accountkey is in plain text and I think that should be changed by default so I made https://github.com/pola-rs/polars/issues/15475)

**Comment by deanm0000** [comment]
I think you're right that it's a cache issue.

@ritchie46 Could you take a look at this one? 

I'm not good with rust but I think the issue is here

https://github.com/pola-rs/polars/blob/31df06d668d81aa04da975b2f66f5c6711e0572b/crates/polars-io/src/cloud/object_store_setup.rs#L52-L60

and 

https://github.com/pola-rs/polars/blob/31df06d668d81aa04da975b2f66f5c6711e0572b/crates/polars-io/src/cloud/object_store_setup.rs#L118-L123

I think that initial `key=url_to_key(&parsed);` can be made more robust by making it something like

`key=url_to_key(&parsed) + options['account_name']` but, of course, that's pseudo code at the `options['account_name']` part otherwise I'd just do myself. It seems like the cache read would need to get moved all the way to the `build_aws`, `build_gcp`, `build_azure` functions after the options are unpacked or else unpack the options early.

@SDubrulle 
The cache is Hashmap (like a dict in python) where the key is "abfss://container1" so if you have two accounts with the same container name then they'd each use the same cache value.

As a workaround I think you can trick the cache by using a different prefix for each account. All of these prefixes should work for azure: "az" | "azure" | "adl" | "abfs" | "abfss". Try using a different one for each of your accounts

For instance:
```
df1 = pl.read_parquet(
    "abfss://container1/dataset1.parquet", storage_options=storage_options
)
df2 = pl.read_parquet(
    "az://container2/dataset2.parquet", storage_options=storage_options
)
```
