### ISSUE TITLE
Add skipfooter to scan_csv

### ISSUE THREAD

**Issue by mdavis-xyz** [pola-rs/polars#16160]
### Description

I want to process large CSV files with polars. The dataset I'm using includes files like [these](http://www.nemweb.com.au/Data_Archive/Wholesale_Electricity/MMSDM/2024/MMSDM_2024_01/MMSDM_Historical_Data_SQLLoader/DATA/), which have an extra header and footer row that I want to skip.

When using pandas I can do:

```
pd.read_csv(
            path,
            skiprows=1, 
            skipfooter=1, 
            engine='python', # required for skipfooter
        )
```

I want to do the same thing with polars. (Since some of these files are too large to fit into memory.)

So I would like a `skipfooter` argument.

I could use `n_rows`. But first I would have to read the file myself and count the total number of lines. That's slow, and inconvenient. 

(That would be a useful workaround for now. Although I'm not sure what the exact behavior is, in terms of whether it includes `skip_rows` and the header.)

**Comment by ritchie46** [comment]
I doubt we'll do this. This would be very expensive as you'd need a lookahead on every line that can determine if that line is a foot (which may be invalid). The fact that pandas requires the python engine for this seems they have come to the same conclusion.

**Comment by mdavis-xyz** [comment]
Ah, fair enough. I was half expecting that to be the answer. I was just being hopeful.

**Comment by cmdlineluser** [comment]
There is a fast path for the count https://github.com/pola-rs/polars/pull/14574

```python
>>> pl.scan_csv("big.csv").select(pl.len()).explain()
'FAST COUNT(*)\n  DF []; PROJECT */0 COLUMNS; SELECTION: "None"'
```

It is an extra pass as you say, but it softens the blow somewhat.

```python
>>> pl.scan_csv("big.csv").select(pl.len()).collect()
shape: (1, 1)
┌─────────┐
│ len     │
│ ---     │
│ u32     │
╞═════════╡
│ 6454824 │
└─────────┘
# Elapsed time: 0.73849 seconds
```

```python
>>> pl.scan_csv("big.csv").with_row_index().select(pl.col.index.last() + 1).collect()
shape: (1, 1)
┌─────────┐
│ index   │
│ ---     │
│ u32     │
╞═════════╡
│ 6454824 │
└─────────┘
# Elapsed time: 11.50408 seconds
```

**Comment by mullimanko** [comment]
What you mean with 

> The data type inferencing might not work (giving str because the header/footer aren't int)...

is cumbersome. Using an argument in `n_rows`, to remove the last line doesn't really work, I received the error `ComputeError: could not parse 'THIS IS AN EXAMPLE LAST LINE.' as dtype 'i64' at column 'first_col' (column number 1)`. I guess it is because of that sentence in the docs 
> During multi-threaded parsing, an upper bound of n_rows rows cannot be guaranteed.

When using [mdavis-xyz](https://github.com/pola-rs/polars/issues/16160#issuecomment-2124664696)'s approach one could easily come to the situation where it is necessary to use `pl.scan_csv(..., schema_overrides={"first_col": pl.String})` and then to change the dtype back to it's appropriate dtype.

All in all, I find it more readable and straightforward to remove the last line before `scan_csv` with `StringIO` (although I didn't compare the performance):

```
import polars as pl
from io import StringIO

with open(path_read, encoding="utf-8") as file_handle:
    io_obj = StringIO(file_handle.read()
                      .replace("THIS IS AN EXAMPLE LAST LINE.\n", ""))  # Note the extra \n, you have to insert it at the end of the string.

df = pl.read_csv(io_obj, skip_rows=1)
```
For this to work, note that `THIS IS AN EXAMPLE LAST LINE.\n` should only occur at the footer row(s) you want to skip. Credit goes to: https://stackoverflow.com/a/49825636/13968392.

**Comment by mdavis-xyz** [comment]
My use case was for a file which is too large to fit into memory, so this wouldn't work for me.

For the speed issue, I think this is approximately 100x slower, because now the dataplane goes through python.

**Comment by mullimanko** [comment]
Ok, I think you're right. If it should be faster, I would do the following:

```
import polars as pl

path_read = r"home\example.csv"
skip_at_start = 10
skip_at_end = 1

# FAST COUNT (as mentioned by cmdlineluser) is only available for scan_csv, not for read_csv.
n_raw_total = pl.scan_csv(path_read).select(pl.len()).collect().item()

# If the first column is pl.String, use this:
df = pl.scan_csv(
    path_read,
    skip_rows=skip_at_start,
    n_rows=n_raw_total - skip_at_start - skip_at_end,
)

# If the first column is anything other than pl.String, use this 
# (it is required to `cast` the proper data type of the first column then, e.g., `pl.Int64`):
df = (
    pl.scan_csv(
        path_read,
        skip_rows=skip_at_start,
        schema_overrides={"first_col_name": pl.String},
        n_rows=n_raw_total - skip_at_start - skip_at_end,
    )
    .cast({"first_col_name": pl.Int64})
)
```
Then at the end use `df.collect()`.

Just a side note: It seems that currently, using the FAST COUNT `scan_csv` as shown above (`pl.scan_csv(path_read).select(pl.len()).collect().item()`) but with the parameter `skip_rows` doesn't passes on `skip_rows` so that it is ignored. It seems that there is a pull request for something very similar (`skip_lines`) https://github.com/pola-rs/polars/pull/22949, maybe `skip_rows` gets also fixed sometimes.

**Comment by raghav415** [comment]
Isn't it better to take input as string and then cast type to int64 later after removing the footer instead of reading the file twice?

Would appreciate for any reply...

**Comment by mdavis-xyz** [comment]
Do you mean read the input with the first column(s) as a string type, but with multiple columns in total, then `.tail(-1)` (or something like that), then cast it to Int?

I'm not sure whether that would work, because the last row would have a different number of columns to the others. Pandas throws an exception for that. I don't recall what Polars' behavior is.

**Comment by raghav415** [comment]
It is working for me. In my case footer has same no of cols as the rest. And we have truncate_ragged_lines option in polars which we can use if the col length is more or less than actual.

But my dbt is which process is optimal because I believe casting later would have some over head as it needs to reallocate space as we change type. Would be great if any info on that.

**Comment by mullimanko** [comment]
I tested the idea of of reading the file once (read file then remove footer) instead of twice (firstly, read file with FAST COUNT `scan_csv`, secondly, read file with `scan_csv(n_rows=...)`) by @raghav415. Please see the following snippets with the timings, tested on a csv file that has approx. 5 million rows. It turned out that reading the file once is most performant (at least for this number of rows) and that reading the file twice is inappropriate here (i.e. the use of FAST COUNT initially suggested by [cmdlineluser](https://github.com/cmdlineluser) is falsified).

1.
```
%%timeit
import polars as pl

df = (
    pl.read_csv(
        "a_file.csv",
        schema_overrides={"first_col_name": pl.String}
    )
    .head(-1)
    .cast({"first_col_name": pl.Int64})
)

# 5 s ± 588 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

2.
```
%%timeit
import polars as pl

df = (
    pl.scan_csv(
        "a_file.csv",
        schema_overrides={"first_col_name": pl.String}
    )
    .collect()
    .head(-1)  # Note that using `head()` with negative values is only supported in eager mode.
    .cast({"first_col_name": pl.Int64})
)

# 5.19 s ± 913 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

3.
```
%%timeit
import polars as pl

n_raw_total = pl.scan_csv("a_file.csv").select(pl.len()).collect().item()

df = pl.scan_csv(
    "a_file.csv",
    n_rows=n_raw_total - 1,
    schema_overrides={"first_col_name": pl.String},
).cast({"first_col_name": pl.Int64}).collect()

# 6.03 s ± 948 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
