### ISSUE TITLE
Add argument to `Series.value_counts` to set the name of the new column created

### ISSUE THREAD

**Issue by DeflateAwning** [pola-rs/polars#16425]
### Description

In a similar way to how you get to set the name of the new column created in `.with_row_count()` (or whatever the "add a row number column" method is called), it would be nice if you could do that with `df['color'].value_counts(name='number_of_occurrences_of_this_color')`.

**Comment by stinodego** [comment]
We do not add `name` parameters to operations on a single column.

`DataFrame.with_row_index` needs a name parameter because the name may clash with an existing column in the dataframe.

`Series/Expr.value_counts` don't need a name parameter because you can just use alias before:

```python
df["count"].alias("my_custom_name").value_counts()
```

**Comment by alexander-beedie** [comment]
`Series/Expr.value_counts` don't need a name parameter because you can just use alias before:
> 
> ```python
> df["count"].alias("my_custom_name").value_counts()
> ```

Actually, I think we should add a `name` param here, as we force the result name to "count" - you shouldn't have to change your "real" column names to account for us forcing one that you have not control over on to your frame 🤔 I'll make a PR and you can see what you think.

**Comment by stinodego** [comment]
Oh yeah I think you're right..

**Comment by DeflateAwning** [comment]
Awesome, thanks! Good lesson about aliasing a Series's name though; didn't know I could do that  :)
