### ISSUE TITLE
Create `pl.lit` from a Python `set` object?

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#17012]
### Description

This came up when using `list.set_intersection` where trying to pass a `set` raises a TypeError.

```python
other = {'a', 'c'}
pl.select(pl.lit(['a', 'b', 'c']).list.set_intersection(other))

# TypeError: cannot create expression literal for value of type set: {'a', 'c'}
```

The caller must explictly convert it to a list/tuple, which feels a little awkward.

```python
pl.select(pl.lit(['a', 'b', 'c']).list.set_intersection(list(other)))

# shape: (1, 1)
# ┌────────────┐
# │ literal    │
# │ ---        │
# │ list[str]  │
# ╞════════════╡
# │ ["a", "c"] │
# └────────────┘
```

Should Polars allow this and just treat it as if it were a list?

**Comment by alexander-beedie** [comment]
Since we don't currently have a `Set` dtype, doing that conversion automatically isn't a good idea as the element order is unstable. While the op _is_ `set_intersection` it's still a `List` op at heart, and we don't know that's the only op that's going to be called following the `lit` conversion. Most `List` ops will expect stable order (which `pl.lit(<set>)` can't provide), so I think we really have to leave it up to the caller to decide if unstable sort order is acceptable.

**Comment by ritchie46** [comment]
I don't think we should. It are `set` operations doen on "lists", not on "sets". Polars doesn't have a set type and making an exception for 1 expression is not something the IR should deal with.
