### ISSUE TITLE
Fix broken links to unpivot (was melt)

### ISSUE THREAD

**Issue by mdavis-xyz** [pola-rs/polars#17264]
### Description

In #11974 `unpivot` was renamed to `melt`.

But there is still a documentation page [called "Unpivots"](https://docs.pola.rs/user-guide/transformations/unpivot/#eager-lazy). It does not mention the word `melt`, and contains a broken link to the now missing [page for `unpivot`](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.unpivot.html).

### Link

https://docs.pola.rs/user-guide/transformations/unpivot/#eager-lazy

**Comment by cmdlineluser** [comment]
Yeah, I think it's due to the larger issue of a lack of versioning in the user guide: https://github.com/pola-rs/polars/issues/11105

The broken links point to `/stable/` but unpivot only exists in `/1/` | `/dev/` currently.

- https://docs.pola.rs/api/python/dev/reference/dataframe/api/polars.DataFrame.unpivot.html

**Comment by mdavis-xyz** [comment]
Ah, I misunderstood which way around the renaming was. Ok, so unpivot is the newer one. Ok, that makes the broken link more understandable.

**Comment by Sherwin-14** [comment]
@mdavis-xyz Hey could you provide some clarification on this issue? I am willing to take it up if you permit :)

**Comment by mdavis-xyz** [comment]
It looks like this broken link is now fixed. The link breakage was probably temporary, due to #11105.
