### ISSUE TITLE
Add `pl.rank(method=..., reverse=False,True)`

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#1734]
#### Describe your feature request

Add `reverse` argument to `pl.rank()`

```python
pl.rank(method=..., reverse=False,True)
```

Options for ordering nulls/NaN like proposed in: https://github.com/pola-rs/polars/issues/1729 should be considered too.

**Comment by marcvanheerden** [comment]
Can I help with this?

**Comment by ghuls** [comment]
@marcvanheerden As noted in https://github.com/pola-rs/polars/issues/1729- sorting of nulls is added recently to sort, but is not exposed yet. Exposing this option for sort and in a similar ways for rank (also with reverse and sort option of nulls) would be great.

**Comment by mhconradt** [comment]
@marcvanheerden @ghuls I'd like to cut my teeth on this if no one else is working on it.

**Comment by marcvanheerden** [comment]
Yes, I'm taking longer than expected on another issue. Fine by me

**Comment by ritchie46** [comment]
@mhconradt. Note that we don't have to modify the rank alogoritm. We could compute `rank(1 - x)` to get reverse ranking. Fo unsized ints we firts could cast to floats.

**Comment by ghuls** [comment]
@ritchie46 wouldn't it be easier to pass the reverse=True argument to argsort?
(altought argsort does not support the sort null options yet, I guess).

**Comment by ghuls** [comment]
@ritchie46 But you need the argsort operation anyway at the start.

**Comment by ritchie46** [comment]
> @ritchie46 But you need the argsort operation anyway at the start.

Ah right. Good observation.

**Comment by mhconradt** [comment]
Thanks for the information @ritchie46 @ghuls! I'd like to add `reverse` to `rank`, and also `nulls_first` to both `sort` and `rank` as suggested by @ghuls. The defaults would be `reverse=False` and `nulls_first=True` in both methods. 
This would be a breaking change that comes with some design trade-offs:

1. Having a `nulls_first` parameter in `rank` is an alternative to a setting similar to `na_option` on [pd.Series.rank](https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L8407-L8532). This would be easy enough to implement, but feels a bit clunky. If we use `nulls_first`, then the signatures of `rank` and `sort` would be similar, which would be nice. However, `RankMethod` already uses an enum so using an enum `RankNullPosition` would be self-similar.
2. We could either add an `argsort_with` method to `ChunkSort` similar to `sort_with`, or just fill null values using `MaxBound` or `MinBound` before calling `argsort` depending on the values of `reverse` and `nulls_first` (or `RankNullPosition` if we go that route). To minimize the footprint of this change I think it's best to do the latter, but am open to either.
3. Currently, `rank` behaves as if `nulls_first=False` because it fills nulls using `MaxBound`. However, `sort` behaves as if `nulls_first=True`. It seems the two should be consistent and default to `nulls_first=True`. Changing this behavior would introduce a silent error if code depended on `rank` behaving as if `nulls_first=False`.

Alternatively, I can just add `reverse` to `rank`, which could be a nice place to start anyway.

I'm curious to get your thoughts on the best route forward; this seems like an interesting project!

**Comment by ritchie46** [comment]
Thanks for #2030 @mhconradt 🚀
