### ISSUE TITLE
ComputeError: this expression cannot run in the group_by context

### ISSUE THREAD

**Issue by AtollRewe** [pola-rs/polars#17356]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    {
        "X": [
            pl.Series(
                "Y",
                [
                    {"a": 1, "b": 2},
                    {"a": 3, "b": 4}
                ]
            ),
        ]
    }
)
df["X"].list.eval(pl.element().struct.with_fields())
```

### Log output

```shell
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[17], line 15
      1 os.environ["POLARS_VERBOSE"] = "1"
      2 df = pl.DataFrame(
      3     {
      4         "X": [
   (...)
     13     }
     14 )
---> 15 df["X"].list.eval(pl.element().struct.with_fields(c=pl.element().struct.field("a") + 1))

File ~/git/MOSAIC/ml-pipelines/.venv11/lib/python3.11/site-packages/polars/series/utils.py:107, in call_expr.<locals>.wrapper(self, *args, **kwargs)
    105     expr = getattr(expr, namespace)
    106 f = getattr(expr, func.__name__)
--> 107 return s.to_frame().select_seq(f(*args, **kwargs)).to_series()

File ~/git/MOSAIC/ml-pipelines/.venv11/lib/python3.11/site-packages/polars/dataframe/frame.py:8615, in DataFrame.select_seq(self, *exprs, **named_exprs)
   8592 def select_seq(
   8593     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
   8594 ) -> DataFrame:
   8595     """
   8596     Select columns from this DataFrame.
   8597 
   (...)
   8613     select
   8614     """
-> 8615     return self.lazy().select_seq(*exprs, **named_exprs).collect(_eager=True)

File ~/git/MOSAIC/ml-pipelines/.venv11/lib/python3.11/site-packages/polars/lazyframe/frame.py:1942, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, no_optimization, streaming, background, _eager, **_kwargs)
   1939 # Only for testing purposes atm.
   1940 callback = _kwargs.get("post_opt_callback")
-> 1942 return wrap_df(ldf.collect(callback))

ComputeError: this expression cannot run in the group_by context

Error originated in expression: 'col("").with_fields([[(col("").struct.field_by_name(a)()) + (1)].alias("c")])'
```

### Issue description

There is no `group_by` in my user code, so the error messages seems cryptic. 

The MRE shows a call to `with_fields` with no arguments, which should be a noop, but of course the error also exists when arguments are given.

### Expected behavior

In the MRE above, the expected behavior would the original created DataFrame (or a copy thereof).

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             macOS-14.2.1-arm64-arm-64bit
Python:               3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.6.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.0
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              15.0.2
pydantic:             2.7.4
pyiceberg:            <not installed>
sqlalchemy:           2.0.30
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by abstractqqq** [comment]
I am getting the same error in polars_ds. 

The function call that is having this problem happens in explicit group by context:

```
df.group_by(pl.col("categories")).agg(
    pds.query_lstsq(pl.col("x1"), pl.col("x2"), target = "y")
)
```

Setting 
```python
pl.Config.set_verbose(True)  
```
I get the following message:
keys/aggregates are not partitionable: running default HASH AGGREGATION

**Comment by cmdlineluser** [comment]
@abstractqqq Polars is checking the function can run here:

<blockquote>

https://github.com/pola-rs/polars/blob/82b638826a30d7ac53af055b5d1273e227599350/crates/polars-expr/src/expressions/apply.rs#L348-L351

</blockquote>

`struct.with_fields` has this flag disabled:

<blockquote>

https://github.com/pola-rs/polars/blob/82b638826a30d7ac53af055b5d1273e227599350/crates/polars-plan/src/dsl/struct_.rs#L101

</blockquote>

So while the error message is the same, this issue is essentially a feature request to have this flag enabled for `.with_fields` i.e. https://github.com/pola-rs/polars/issues/17749


It seems in your case, you are saying something has changed in 1.2.1 -> 1.3.0 causing polars plugins to hit the error?

It's not clear if that means it's just an issue specifically with `pyo3-polars` or not.

**Comment by abstractqqq** [comment]
> @abstractqqq Polars is checking the function can run here:
> 
> > https://github.com/pola-rs/polars/blob/82b638826a30d7ac53af055b5d1273e227599350/crates/polars-expr/src/expressions/apply.rs#L348-L351
> 
> `struct.with_fields` has this flag disabled:
> 
> > https://github.com/pola-rs/polars/blob/82b638826a30d7ac53af055b5d1273e227599350/crates/polars-plan/src/dsl/struct_.rs#L101
> 
> So while the error message is the same, this issue is essentially a feature request to have this flag enabled for `.with_fields` i.e. #17749
> 
> It seems in your case, you are saying something has changed in 1.2.1 -> 1.3.0 causing polars plugins to hit the error?
> 
> It's not clear if that means it's just an issue specifically with `pyo3-polars` or not.
> 
> **Update:** It seems #17723 introduced the change you are experiencing.

Yes it definitely happened during 1.2.1 ---> 1.3 and the commit you pointed out seems to be the problem, although I cannot pinpoint the place of error. 

I checked the following: in register_plugin_function, collect_groups should be GroupWise because is_elementwise is False.

```rust
    let collect_groups = if is_elementwise {
        ApplyOptions::ElementWise
    } else {
        ApplyOptions::GroupWise
    };
```
register_plugin_function returns a PyExpr, which is then translated to Expr and then to ApplyExpr and finally we hit the error at the location you pointed out.

My suspicion is that somewhere from the PyExpr ->> ApplyExpr, this flag is not set correctly. I found that in this function  create_physical_expr_inner the options are simply copied over.. Not really sure what is happening.

However, after more testing I think all plugins with return_scalar=True might be having this problem. They cannot be executed in group by. 

I will dig deeper once I get more time.

**Comment by MarcoGorelli** [comment]
> However, after more testing I think all plugins with return_scalar=True might be having this problem. They cannot be executed in group by.

I'm seeing the same for plugins with `is_elementwise=False`

> Update: It seems https://github.com/pola-rs/polars/pull/17723 introduced the change you are experiencing.

From `git bisect`, I agree, that's the one 🎯

**Comment by anatolix** [comment]
>It seems in your case, you are saying something has changed in 1.2.1 -> 1.3.0 causing polars plugins to hit the error?

IMO it changed between 0.20.30 (works for me) and 0.20.31 (not works for me)

**Comment by abstractqqq** [comment]
Yes in my case my plugin worked before 1.2 and didn’t work in 1.3… Then
probably different issues.

**Comment by TinoSM** [comment]
This bug is quite taxing as all other alternatives to perform operations of lists-of-structs are much slower (an operation that takes a 5 seconds takes like 1.5minutes with the others), will probably end creating plugins for our side.

It is caused because list.eval runs as a group_by in some/most scenarios (you can see polars eval implementation)
https://github.com/pola-rs/polars/blob/1eb2fcca3cf1d99072d3d19588279abf563bbc38/crates/polars-lazy/src/dsl/list.rs#L198

For those who are struggling with this error, maybe this alternative function can help meanwhile, you need to know the fields which exist in the struct beforehand though, as there's no way to select struct.fields(NOT('X',Y')), negative lookaheads are not supported in regexps.

```
def polars_struct_with_fields( base_struct : pl.Expr,
                    current_fields : list[str],
                    new_fields : dict[str, pl.Expr]) -> pl.Expr:
    """
    TODO: Wait for polars to fix with_fields inside list.eval, meanwhile we recreate the structs 
    https://github.com/pola-rs/polars/issues/17749
    """
    fields_to_add = []
    for col in current_fields:
        if col not in new_fields:
            fields_to_add.append(base_struct.struct.field(col))
        else:
            fields_to_add.append(new_fields[col].alias(col))

    for col, value in new_fields.items():
        if col not in current_fields:
            fields_to_add.append(value.alias(col))

    return pl.struct(fields_to_add)
    
```

**Comment by cmdlineluser** [comment]
@TinoSM 1.5 minutes sounds extremely slow.

Exploding the list and horizontally concatting the result back should be an efficient operation. 

```python
pl.concat(
    [
        df.drop("my_list_column"),
        (df.with_row_index()
           .select("index", "my_list_column")
           .explode("my_list_column")
           .with_columns(pl.col("my_list_column").struct.with_fields(c = pl.field("a") + 10))
           .group_by("index", maintain_order=True) # order required for horizontal concat
           .all()
           .drop("index")
        )
    ],
    how = "horizontal"
)
```
---

>  there's no way to select struct.fields(NOT('X',Y'))

There was a PR to add struct selection: https://github.com/pola-rs/polars/pull/14249

Which I'm guessing would have enabled the use of `pl.exclude` to emulate `.struct.drop()`

**Comment by TinoSM** [comment]
> @TinoSM 1.5 minutes sounds extremely slow.
> 
> Exploding the list and horizontally concatting the result back should be an efficient operation.
> 
> ```python
> pl.concat(
>     [
>         df.drop("my_list_column"),
>         (df.with_row_index()
>            .select("index", "my_list_column")
>            .explode("my_list_column")
>            .with_columns(pl.col("my_list_column").struct.with_fields(c = pl.field("a") + 10))
>            .group_by("index", maintain_order=True) # order required for horizontal concat
>            .all()
>            .drop("index")
>         )
>     ],
>     how = "horizontal"
> )
> ```
> 
> > there's no way to select struct.fields(NOT('X',Y'))
> 
> There was a PR to add struct selection: #14249
> 
> Which I'm guessing would have enabled the use of `pl.exclude` to emulate `.struct.drop()` - but it seems to have gone stale awaiting further feedback.

That's my previous code but sadly my amount of data is big and my schema is quite complex. In your example if one has a row with a null lists it will become a list with one null element (you can fix that but then it becomes slower too).

I moved from that to list eval+ that function and runtime went from 30 minutes to 2 minutes :/. I wanted to open a ticket but sadly my data is propietary

**Comment by cmdlineluser** [comment]
> runtime went from 30 minutes to 2 minute

Ah :-/

> I wanted to open a ticket but sadly my data is propietary

Can you add in code to create a dataset with the same schema perhaps?

hypothesis[^1] or Faker[^2] could also help.

[^1]: https://docs.pola.rs/api/python/dev/reference/api/polars.testing.parametric.dataframes.html
[^2]: https://pypi.org/project/Faker/

**Comment by TinoSM** [comment]
> > a row with a null lists it will become a list with one null element
> 
> Good point - didn't think of that, thank you.
> 
> > runtime went from 30 minutes to 2 minute
> 
> Ah :-/
> 
> > I wanted to open a ticket but sadly my data is propietary
> 
> Can you add in code to create a dataset with the same schema perhaps?
> 
> hypothesis[1](#user-content-fn-1-b684cb83f85394d92b978967eba5eb2a) or Faker[2](#user-content-fn-2-b684cb83f85394d92b978967eba5eb2a) could also help.
> 
> ## Footnotes
> 1. https://docs.pola.rs/api/python/dev/reference/api/polars.testing.parametric.dataframes.html [↩](#user-content-fnref-1-b684cb83f85394d92b978967eba5eb2a)
> 2. https://pypi.org/project/Faker/ [↩](#user-content-fnref-2-b684cb83f85394d92b978967eba5eb2a)

I can, however I'm not sure if there is a need for another ticket, I mean the bug is in this ticket, a groupby+few with columns/selects taking one minute over 500k elements (each element of my list contains a struct with over 100 fields) is not something that can be considered a bug in my opinion (at least I would not say it's a priority now), it's just that is not as fast as what we need (list eval transforms)

Thanks though, I do have some other non performance related tickets where those tools can be handy

**Comment by cmdlineluser** [comment]
If I remove `& !FunctionFlags::ALLOW_GROUP_AWARE` from here

https://github.com/pola-rs/polars/blob/0b0a914a868fcf8d3d0ff652c13b5cbe4db9f61a/crates/polars-plan/src/dsl/struct_.rs#L108

`make test` still passes.

```python
df["X"].list.eval(pl.element().struct.with_fields(c = pl.element().struct.field("a") + 10))
# shape: (1,)
# Series: 'X' [list[struct[3]]]
# [
#	 [{1,2,11}, {3,4,13}]
# ]
```

I'm not sure if there is a specific reason why it is currently disabled.
