### ISSUE TITLE
Can we add param types in the API param explanation section?

### ISSUE THREAD

**Issue by liufeimath** [pola-rs/polars#17416]
### Description

Currently, there's no param types in the explanation section, e.g.:
https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html
For the param `index`, the function signature mentions the type:
`index: ColumnNameOrSelector | Sequence[ColumnNameOrSelector] | None = None,`
However in the detailed `Parameters` section below the signature, it only says:
```
index
One or multiple keys to group by. If None, all remaining columns not specified on on and values will be used. At least one of index and values must be specified.
```
without mentioning about the types again. I find it quite inconvenient as I need to scroll the API page back and forth to remind myself what is a legal type as input. This causes fragmentation.

Request: can we reiterate the param type in the detailed `Parameter` explanation section? It helps the reader to grab useful context in a more convenient fashion.

### Link

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html

**Comment by stinodego** [comment]
I don't think there's really a good solution for this.

We do not write out the data types in the docstring, because that would be duplication and prone to becoming outdated. It doesn't add anything because the type signature already tells you the types.

We do not expand the type aliases, because that would lead to an unreadable mess in many cases.

The best thing to do is to work out the type aliases and use public type aliases as much as possible, so that users can click and see what those types actually mean. As well as use sensible names for the type aliases.
https://github.com/pola-rs/polars/issues/17420

**Comment by liufeimath** [comment]
I understand that putting things in docstring makes the source code comment appear redundant, and is probably not the best way to solve this. That said, I just want to mention that pandas documentation is easier to read (e.g. [this one](https://pandas.pydata.org/docs/reference/api/pandas.date_range.html)) as I can easily know which param is of which type and for what purpose in the "Parameters" section. It is better in the sense of "code locality".

@stinodego what do you mean by "type alias" ? Do you mean that there's some annotation method so that one can click into / hover mouse icon onto the param (in "Parameters") and type annotation will pop up?
