### ISSUE TITLE
Series.is_in called with a mixed list of Python integers and floats fails

### ISSUE THREAD

**Issue by wesm** [pola-rs/polars#17771]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
s = pl.Series([1, 2, 3, 4])
s.is_in([2, 2.5])
```

### Log output

```shell
TypeError: unexpected value while building Series of type Int64; found value of type Float64: 2.5

Hint: Try setting `strict=False` to allow passing data with mixed types.
```

### Issue description

This is a regression from polars 0.20.x. Unless there is a possibility of data loss when promoting values (e.g. from int64 to float64), it seems like this code should work

### Expected behavior

As with pandas

```
In [3]: pd.Series([1,2,3,4]).isin([2, 2.5])
Out[3]: 
0    False
1     True
2    False
3    False
dtype: bool
```

If data originated from a web application (where there are only "numbers"), it is burdensome for the user to have to sanitize it manually before using these functions. It seems like rather than failing, the case of is_in(Int64, Float64) should instead be implemented and only error when there is a possible loss of precision.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

**Comment by ritchie46** [comment]
The python list get passed to the `Series` constructor which defaults to `strict=True` since 1.0.

You can directly pass it to the `Series` constructor with more lenience: 

```python
>>> s = pl.Series([1, 2, 3, 4])
>>> s.is_in(pl.Series([2, 2.5], strict=False))
shape: (4,)
Series: '' [bool]
[
	false
	true
	false
	false
]
```

I think we should expose the `strict` argument to the `is_in` expression so that we can do `s.is_in([2, 2.5], strict=False)`.

**Comment by wesm** [comment]
Implicit casting from integer to float64 (when the integer is inside the exact-representable range for a float64) is a standard in many systems (e.g. NumPy, base R, both do this -- Python and many programming languages implicitly cast integers to float in arithmetic operations, etc.), do you have anything written up on what motivated this decision so I can understand the reasoning? 

Given how I was impacted in a very innocuous setting of passing a deserialized JSON array of numbers to `is_in`, I would guess that this become a sharp edge for many users.

**Comment by ritchie46** [comment]
Polars is strict about data types. And dynamic user input can lead to data type bugs down the line. We want to catch those bugs at the source.

E.g. if you read in `[1]` you get a `Int64` column, then next time you run the query on other json data and you get `[1, 2.0]` and the data is inferred to be `Float64`, but Polars will fail somewhere else because you expected a integer type. 

Polars will guard you from that by being strict by default. You can opt-out of it, or even better set the `dtype` you want the input to be parsed as.

**Comment by wesm** [comment]
Thank you for the explanation.
