### ISSUE TITLE
Right-align numerical headers in `write_excel`

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#17852]
### Description

Table headers should be aligned to their data. Numerical data is right-aligned, as should be the headers.

```python
import polars as pl

df = pl.DataFrame({
    "Text": ["Hi there", "longer sentence", "this is left aligned"],
    "Number": [1.0, 2.345, 31859135.331441],
})

df.write_excel("out.xlsx", autofit=True)
```
![image](https://github.com/user-attachments/assets/1d37662b-ec3e-4298-b80b-3dcb3d24278e)

**Comment by alexander-beedie** [comment]
Unfortunately if you do that then the autofilter covers the header text, which isn't a good default formatting experience; for example, with the right-aligned numeric headers "bbb" and "ccc" below... If you can spot a good way to avoid that we could look again, but otherwise it's not a good move.

<img width="271" alt="Screenshot 2024-07-25 at 08 22 35" src="https://github.com/user-attachments/assets/a7a8b7f8-16e7-41ac-b5e2-d6fa3bd47eae">

**Comment by mcrumiller** [comment]
Ahh indeed, I have run into this myself, and it's a frustrating Excel issue.

I am noting that Excel cells have an `indent` property, which a setting of 2 seems to do the trick:

![image](https://github.com/user-attachments/assets/d606279a-c962-412f-ba8c-10bae669b2c8)

usable via [`xlsxwriter.set_index`](https://xlsxwriter.readthedocs.io/format.html#set_indent).

Of course, if you turn off the filter it looks ugly (although still not as bad as left-aligned), but we could set the indentation to be conditional on `filter=True` perhaps.

**Comment by mcrumiller** [comment]
As per the discussion in #17877, I'm closing this, with the possibility of amending header formats to allow for simpler alignment of numeric columns headers.
