### ISSUE TITLE
passing a nested list to DataFrame crashes python with no output

### ISSUE THREAD

**Issue by ggggggggg** [pola-rs/polars#17960]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
a=[]
a.append(a)
pl.DataFrame({"a":a})
print("done")
```

### Log output

```shell
Python exits with no output.
```

### Issue description

I accidentally tried to create a `DataFrame` with a nested list, and kept crashing python. Since it kept crashing, it made it hard to figure out what I had done wrong. 

### Expected behavior

I don't expect this to make a useable `DataFrame`, it should throw an `Exception`.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.3.0
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.10.0
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.2
pyarrow:              14.0.2
pydantic:             2.5.3
pyiceberg:            <not installed>
sqlalchemy:           2.0.30
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>```

</details>

**Comment by cmdlineluser** [comment]
(I think the term for this is: *"self-referential list"*)

I get a segfault.

```python
Segmentation fault: 11
```

Interestingly, pandas seems to allow creation:

```python
>>> pd.DataFrame({"a":a})
               a
0  [[[[[...]]]]]
```

`pl.from_pandas` also segfaults.

```python
>>> pl.from_pandas(pd.DataFrame({"a":a}))
Segmentation fault: 11
```

(It seems to cause trouble for other tools, duckdb also segfaults.)

**Comment by ggggggggg** [comment]
Yes a better error message as in any error message instead of segfaulting. I feel that you should be able to cause a default from the python api.

**Comment by ritchie46** [comment]
This isn't something we are not going to fix. It is absolute nonsense to support infinite self referential lists. The segfault is because of a stackoverflow because it is an infinite data structure. It's either overlowing, the heap or looping infinitely.

**Comment by david-cortes** [comment]
> This isn't something we are going to fix. It is absolute nonsense to support infinite self referential lists. The segfault is because of a stackoverflow as it is an infinite data structure. It's either overflowing the heap, or looping infinitely.

I'd say supporting those objects is probably not useful at all, but what would be useful is to avoid crashing the whole process when those are accidentally encountered. For example, when python runs into too many recursions, it throws an exception instead of terminating the process.

**Comment by leoschwarz** [comment]
Dear maintainers, I would ask to reopen this issue to have a discussion around a proper exception being rased with a potentially better error message in this scenario rather than a segfault. I don't know the codebase but maybe it could even be done entirely in the Python side of things?

I ran into this today by trying to create a polars dataframe from a self referential list, which was due to a bug in my code.

My concerns for Python users of Polars are:

1. Discoverability: Generally, Python stacktraces are used for debugging rather than external debuggers. This is a tooling issue, but unless you are developing native extensions for Python chances are you might never have had to use GDB/LLDB on a Python process before. In my case, I thought Marimo Notebook had a bug because I did not realize immediately where the segfault came from. 
2. Familiarity: Out of bounds access also does not cause a segfault here (but of course the problem is a bit different and less common).
3. I did not run polars on untrusted data, but I do have some concerns that this could in very exotic cases be abused. (I realize this is not considered a security issue according to security.md otherwise I would not write it here.)

If performance is a concern, my proposal would be to borrow from [`json.dump`](https://docs.python.org/3/library/json.html#json.dump) API in Python and make it optional (but enabled by default):

> check_circular ([bool](https://docs.python.org/3/library/functions.html#bool)) – If False, the circular reference check for container types is skipped and a circular reference will result in a [RecursionError](https://docs.python.org/3/library/exceptions.html#RecursionError) (or worse). Default True.
