### ISSUE TITLE
Should the user guide have a section on using a column in the same context it is created, if so where should it go?

### ISSUE THREAD

**Issue by deanm0000** [pola-rs/polars#18004]
### Description

There are a few SO questions that are essentially "how do I use a column that I just made in the same `with_columns`"

In a very direct sense, it can't be done. However, it is possible to use the walrus operator to sort-of do it like this:
```
df.with_columns(
(a:=pl.col('b')+pl.col('c')).alias('a'),
(a+pl.col('d')).alias('e')
)
```
Should that be in the guide?

I know that if we do that in lazy context that CSE will only calculate `a` one time but does eager get the same benefit? I think it does but I'm not 100% sure.

**Comment by rodrigogiraoserrao** [comment]
The user guide chapter on Expressions is getting a decent rework (#19360) and part of the rework focuses on manipulating expressions.
While this very specific case isn't explicitly mentioned, that section gives a better sense of how expressions can be manipulated and it shows users they can do something like

```py
bc = pl.col("b") + pl.col("c")
df.with_columns(
    bc.alias("a"),
    (bc + pl.col("d")).alias("e"),
)
```

As for whether the eager API does common subexpression elimination, I am not sure, but the core of this issue is whether the docs should be changed and the PR linked will address this issue.
