### ISSUE TITLE
Cannot load CSV file with single column and empty lines at start

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#18071]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from pathlib import Path

path = ".env/data.csv"
Path(path).write_text(
    """


a
1

"""
)
lf = pl.scan_csv(path)

print(pl.scan_csv(path).collect())
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/Users/nxs/git/polars/py-polars/polars/lazyframe/frame.py", line 2027, in collect
#     return wrap_df(ldf.collect(callback))
#                    ^^^^^^^^^^^^^^^^^^^^^
# polars.exceptions.ComputeError: could not parse `a` as dtype `i64` at column 'a' (column number 1)

# The current offset in the file is 1 bytes.

# You might want to try:
# - increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
# - specifying correct dtype with the `dtypes` argument
# - setting `ignore_errors` to `True`,
# - adding `a` to the `null_values` list.

# Original error: ```remaining bytes non-empty```

print(pl.scan_csv(path, infer_schema=False).collect())
# shape: (2, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ str │
# ╞═════╡
# │ a   │
# │ 1   │
# └─────┘

```

### Issue description

It will either error, or if `infer_schema=False` it will duplicate the column name into the first row.

### Expected behavior

`scan_csv(path).collect()` should give:
```python
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```

### Installed versions

1.4.1

**Comment by EricTulowetzke** [comment]
Your current CSV file looks like this 

```

a
1
```
This issue happens but if the file looks like this 

```
a
1
```
No error happens see code below

```
import polars as pl
from pathlib import Path

path = "./data.csv"
Path(path).write_text(
    """a
1
"""
)
lf = pl.scan_csv(path)
pl.scan_csv(path).collect()
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```

So when `infer_schema=False` then `infer_schema_length=0` and the empty space at the start of file is removed. I'm currently looking through the rust code to get the issue fix when `infer_schema=False`  is not used.

**Comment by EricTulowetzke** [comment]
I can look into this issue

**Comment by EricTulowetzke** [comment]
I don't think this edgle case is an issue or at least we need to define how we want to handle it.

When `infer_schema=False` all values are string so no issue with casting as string. 

In the other cases we try to infer_file_schema the data types and link them to field but finding the first value as header/field in bytes. So in above case 'a' is the field with data type being int64. In most cases if there was multiple columns we would just remove the blank lines at the start see code below 

```
// crates/polars-io/src/csv/read/read_impl.rs
// line 281 

// \n\n can be a empty string row of a single column
// in other cases we skip it.
if self.schema.len() > 1 {
  bytes = skip_line_ending(bytes, eol_char)
}
...
// skip header row
if self.has_header {
    bytes = skip_this_line(bytes, quote_char, eol_char);
}
```

Though since we don't want remove \n\n empty string row of a single column we get the data in the columns as [a,1] which why we get the above error as above.

If we remove the if check of `self.schema.len() > 1` then the below works

```
import polars as pl
from pathlib import Path

path = "data.csv"
Path(path).write_text(
    """

a
1
"""
)

out =pl.scan_csv(path).collect()
out
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```

But then this case doesn't work as before

```
path = "data.csv"
Path(path).write_text(
    """

1
"""
)

out =pl.scan_csv(path).collect()
out
shape: (1, 1)
┌─────┐
│ 1   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```
Now we would get this:

```
path = "data.csv"
Path(path).write_text(
    """

1
"""
)

out =pl.scan_csv(path).collect()
out
shape: (0, 1)
┌─────┐
│ 1   │
│ --- │
│ str │
╞═════╡
└─────┘
``` 

What case is more preferable where we allow empty string row of a single column and get type issues if shouldn't be there, or don't allow empty string row of a single column  and no type issues but some behavior changes?

I'm open to other ideas but becomes tricky infer if that emptry row should be there are not.

**Comment by nameexhaustion** [comment]
Thanks @EricTulowetzke 

From the git blame it seems the current behavior is intentional and intended

ref https://github.com/pola-rs/polars/pull/2622
ref https://github.com/pola-rs/polars/issues/2619
