### ISSUE TITLE
Remove the `nightly` feature-gate for `to_titlecase`?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#18094]
### Description

Currently, `to_titlecase()` requires the `nightly` feature enabled: https://docs.rs/polars/latest/polars/prelude/trait.StringNameSpaceImpl.html#method.to_titlecase

This was added in https://github.com/pola-rs/polars/pull/12325 but since the Rust version used has been bumped multiple times in the meantime, I'm just wondering if this feature-gate can now be removed.

**Comment by mcrumiller** [comment]
This function requires the `nightly` feature because it uses [core::unicode](https://doc.rust-lang.org/core/unicode/index.html) [here](https://github.com/pola-rs/polars/blob/34f538785cf215cad9529669c59cb1ac3e6f506e/crates/polars-ops/src/chunked_array/strings/case.rs#L79) which is still experimental.
