### ISSUE TITLE
read_csv trimming white space on first line when file has no headers and is single column

### ISSUE THREAD

**Issue by ekul135** [pola-rs/polars#18128]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from io import StringIO
import polars as pl

DATA="""  John Smith         WA        418-Y11-4111
  Mary Hartford       CA        319-Z19-4341
Evan Nolan          IL        219-532-c301
"""

df = pl.read_csv(
    StringIO(DATA),
    has_header=False,
    new_columns=["full_str"]
)

print(df)

```

### Log output

```shell
file < 128 rows, no statistics determined
no. of chunks: 1 processed by: 1 threads.
shape: (3, 1)
┌─────────────────────────────────┐
│ full_str                        │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ John Smith         WA        4… │
│   Mary Hartford       CA      … │
│ Evan Nolan          IL        … │
```

### Issue description

when reading a txt file for fixed width processing into a single column, if the first line contains leading whitespace, polars will trim. this only occurs if the file does not contain headers. Note this problem does not occur if the file was to have multiple columns.

### Expected behavior

In the example above, I would expect to see the whitespace still preserved in front of John Smith, similar to the second line.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.4.1
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
```

</details>

**Comment by mcrumiller** [comment]
From the code this looks intentional, although I'm not sure the rationale behind it. It's a very easy fix but I don't want to step on the toes of prior decisions here: after a little digging, it looks like this is related to #13934, where it was determined that all whitespace in a CSV should belong to the data. A fix was put in place but seems it may have missed this case with a single column. See also some discussion in at https://github.com/pola-rs/polars/issues/14530#issuecomment-1948077840.

@Julian-J-S may have a better informed opinion here since he seems to have been involved in a lot of CSV whitespace discussions/PRs.

**Comment by ekul135** [comment]
Thanks @mcrumiller.

**Comment by Julian-J-S** [comment]
Yes 🙌🏻 100% agrees this should be fixed.

All whitespace belongs to the data and should be preserved and not removed.
If deletion is desired you can always remove after loading the dataset or fix the csv file 🤓
