### ISSUE TITLE
Should `str.to_titlecase()` capitalize the letter after an apostrophe?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/polars#18260]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.DataFrame({"x": ["john's office"]}).with_columns(tc=pl.col("x").str.to_titlecase())
```

### Log output

```shell
shape: (1, 2)
┌───────────────┬───────────────┐
│ x             ┆ tc            │
│ ---           ┆ ---           │
│ str           ┆ str           │
╞═══════════════╪═══════════════╡
│ john's office ┆ John'S Office │
└───────────────┴───────────────┘
```

### Issue description

Converting to titlecase now also capitalizes the letter after the apostrophe, which was not the case in 1.4.0.

I don't know if there's a proper standard for conversion to titlecase, but [this website](https://titlecaseconverter.com/) shows the output of several variants and in none of them is the `s` after the apostrophe capitalized.

This was likely introduced in https://github.com/pola-rs/polars/pull/18122.

### Expected behavior

```
shape: (1, 2)
┌───────────────┬───────────────┐
│ x             ┆ tc            │
│ ---           ┆ ---           │
│ str           ┆ str           │
╞═══════════════╪═══════════════╡
│ john's office ┆ John's Office │ # <---------------- "s" is not capitalized
└───────────────┴───────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.5.0 
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0       
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.9.2
matplotlib:           3.7.1
nest_asyncio:         1.5.6
numpy:                1.24.3
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.1
pydantic:             2.6.4
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by ritchie46** [comment]
@alexander-beedie I think this is a regression.

**Comment by alexander-beedie** [comment]
We are actually doing the right thing now - while the result in this case may not look pleasing, it is consistent with respect to every other title-case implementation that you can find. If you try title-case in Python or Rust you'll see the same result ("John'S"). This is because correctly title-casing words with apostrophes is actually VERY hard, and relies on context/language nuance (for instance: while you might want "John's", you wouldn't want "O'brien" - no algorithm is going to recognise "O'Brien" as a surname - and then if you try to tweak the rules to cover that, you're going to run into problems with French and "l'argent" vs "L'Argent", etc...)

Note that the linked website is the American Psychological Association's style guide for writing - it is not representative of what _code_ does with title-case 😉

There is an interesting thread on the Python dev list where they were thinking about trying to make `title()` smarter by default [^1], but eventually it was decided not to because there are sooooo many edge-cases that are context/language dependent.

This isn't to say we can't do better; we could consider a new (and more expensive) method that uses more elaborately defined word boundaries and we can make it clear in the docs what the differences are between that and `tot_title_case`. We could use Rust's `unicode_segmentation` crate, which will do a _much_ better job than misc regex's or any home-grown logic. Maybe we can call it `str.capitalize_words` - I could likely get that working today if there is interest?

But, right now, our current `to_title_case` implementation looks to be correct/consistent with everyone else's.

[^1]: https://bugs.python.org/issue7008

**Comment by etiennebacher** [comment]
Thanks for the explanation, indeed I didn't notice there were so many (language-specific) corner cases.

> while the result in this case may not look pleasing, it is consistent with respect to every other title-case implementation that you can find.

Just want to mention that it's not entirely true. Some implementations in R do not capitalize the "s":

``` r
tools::toTitleCase("john's office")
#> [1] "John's Office"
stringr::str_to_title("john's office")
#> [1] "John's Office"
```

Worth noting that the `stringr` implementation is based on `stringi`, which itself claims following the [ICU specification](https://unicode-org.github.io/icu/userguide/transforms/casemappings.html) (though I haven't checked whether in this case they actually do follow it).

Doesn't change the fact that no results will be perfect.

**Comment by alexander-beedie** [comment]
I should have better-constrained my claim of "every other" title case implementation, as obviously some set out to specifically solve this problem (but very _very_ rarely in the case of a language's _default_ method for doing so) 😉

> Worth noting that the `stringr` implementation is based on `stringi`, which itself claims following the [ICU specification](https://unicode-org.github.io/icu/userguide/transforms/casemappings.html) (though I haven't checked whether in this case they actually do follow it).

Yup - this is along the lines of what I'm thinking about with respect to Rust's `unicode_segmentation` crate (though I'm not sure how heavy an import that is). Can make better decisions about what constitutes a word.

**Comment by etiennebacher** [comment]
> We could use Rust's unicode_segmentation crate, which will do a much better job than misc regex's or any home-grown logic. Maybe we can call it str.capitalize_words - I could likely get that working today if there is interest?

I didn't see this part that you added later. I only found this behavior change in one of the unit tests  of an R package relying on Polars, so I don't know if there's an interest for this. Maybe we can reopen this and change it to a feature request instead?

**Comment by alexander-beedie** [comment]
>  Maybe we can reopen this and change it to a feature request instead?

Sounds like a plan; can gauge interest 👍
