### ISSUE TITLE
read_csv failure: provide line number not just column and bytes on parse failure

### ISSUE THREAD

**Issue by seanv507** [pola-rs/polars#18363]
### Description

polars version 0.20.2 and 1.5.0

When read_csv fails, no line number is provided to pinpoint the error, only a bytes offset.  This seems painful to debug.

```
ComputeError: could not parse `Talk-Show` as dtype `i64` at column 'runtimeMinutes' (column number 8)

The current offset in the file is 840480565 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `Talk-Show` to the `null_values` list.
```

The file I am trying to read is https://developer.imdb.com/non-commercial-datasets/ title.basics.tsv.gz

`titles2 = pl.read_csv("data/title.basics.tsv", separator="\t",  null_values="\\N", dtypes={"endYear": int, "genres":str}, skip_rows_after_header =  853_560)` . the skip rows is just me trying to identify where in the file the error is occurring.

**Comment by alexander-beedie** [comment]
Parallelising the reads (as we do) means that the code raising the error doesn't _know_ what the line number is - in order to work it out it would have to keep track of every chunk that has already been processed _and_ every chunk currently being processed, and synchronise all of this information. Given that an error is being raised you can't rely on having good information for any of this, even if you wanted to try and compute it all. Knowing how many bytes have been chunked for processing, on the other hand, is a _lot_ simpler, as that's directly tied to how the chunks are distributed into the processing pool.

**Comment by seanv507** [comment]
Thanks yes I now realise.  I was using command line tools and hadn't realised I could do `tail -c +offset file |head -c 1000`
