### ISSUE TITLE
CI issue when installing NumPy

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#18543]
`make requirements` fails, as well as installation of requirements in the CI, e.g. the `mypy` job:
https://github.com/pola-rs/polars/actions/runs/10698494147/job/29658821996

Has to do with the new `NumPy 2.1.1` release. Needs some investigation. Will pin NumPy for now.

**Comment by wence-** [comment]
numba-0.6 (the latest release) [has a dependency on `numpy < 2.1`](https://github.com/numba/numba/blob/53e976f1b0c6683933fa0a93738362914bffc1cd/setup.py#L26). Because numpy comes before numba in requirements-dev.txt, it looks like `uv` first picks a valid numpy package, which happens to be `2.1.1`, then when trying to find a version of `numba` that is installable the most recent release is not compatible with numpy 2.1, so it backtracks through older numba versions. Since numba still encodes things in `setup.py`, the install must execute setup.py. No older version of numba will support numpy 2.1 so we keep going backwards "forever", until we hit a version that is old enough that it `raise`s in `setup.py`, and `uv` transitively crashes.

Workaround fix: reorder `numba` to appear before `numpy` in `requirements-dev.txt`:

```
uv pip install numba numpy # succeeds
uv pip install numpy numba # fails
```

**Comment by stinodego** [comment]
Thanks for investigating - let's do that then. Seems fine as a temporary fix.

**Comment by wence-** [comment]
https://github.com/astral-sh/uv/issues/7020
