### ISSUE TITLE
Add `include_file_paths` parameter to `read_parquet`

### ISSUE THREAD

**Issue by nameexhaustion** [pola-rs/polars#18962]
### Description

Add the parameter and docstring and it when calling `scan_parquet`

**Comment by LukasFolwarczny** [comment]
Hello! When the `use_pyarrow` parameter in `read_parquet` is set to `True`, the function `_read_parquet_with_pyarrow` is called instead of `scan_parquet`. However, the pyarrow function does not support the `include_file_paths` parameter. Would it be acceptable to add `include_file_paths` as incompatible with `use_pyarrow` and document this behavior accordingly?

**Comment by nameexhaustion** [comment]
> Would it be acceptable to add include_file_paths as incompatible with use_pyarrow and document this behavior accordingly?

You can raise an error under the `if use_pyarrow:`section in the code
