### ISSUE TITLE
`pl.duration(days=pl.all())` also passes values to `hours=`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#19007]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1], "b": [2]})

df.select(pl.duration(days=pl.all()))
# shape: (1, 1)
# ┌──────────────┐
# │ literal      │
# │ ---          │
# │ duration[μs] │
# ╞══════════════╡
# │ 1d 2h        │
# └──────────────┘
```

### Issue description

I think this may actually be another form of: 

- https://github.com/pola-rs/polars/issues/18968

It seems to be doing

```
pl.duration(col(a), col(b))
```

Instead of

```
pl.duration(col(a))
pl.duration(col(b))
```

### Expected behavior

I was expecting a `literal` duplicate error, but thought adding `.name.keep()` would be the same as:

```python
df.select(
    pl.duration(days="a").name.keep(),
    pl.duration(days="b").name.keep()
)

# shape: (1, 2)
# ┌──────────────┬──────────────┐
# │ a            ┆ b            │
# │ ---          ┆ ---          │
# │ duration[μs] ┆ duration[μs] │
# ╞══════════════╪══════════════╡
# │ 1d           ┆ 2d           │
# └──────────────┴──────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.8.2
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by mcrumiller** [comment]
All the args make it in:

```python
df = pl.DataFrame(
    {
        "a": [1, 2],
        "b": [3, 4],
        "c": [5, 6],
        "d": [7, 8],
        "e": [9, 10],
        "f": [11, 12],
        "g": [13, 14],
    }
)
df.select(pl.duration(days=pl.all()))
# shape: (2, 1)
# ┌─────────────────────┐
# │ literal             │
# │ ---                 │
# │ duration[μs]        │
# ╞═════════════════════╡
# │ 1d 3h 5m 7s 9011µs  │
# │ 2d 4h 6m 8s 10012µs │
# └─────────────────────┘
```

**Comment by cmdlineluser** [comment]
@mcrumiller Yeah, it looks like it is the same thing as the issue with some of the `.list.*` methods.

This should output 7 columns, right?

```python
df = pl.DataFrame(
    {
        "a": [[1, 2]],
        "b": [[3, 4]],
        "c": [[5, 6]],
        "d": [[7, 8]],
        "e": [[9, 10]],
        "f": [[11, 12]],
        "g": [[13, 14]],
    }
)

df.select(pl.all().list.concat(539)) 
# shape: (1, 1)
# ┌──────────────────────────────────────────────────────┐
# │ a                                                    │
# │ ---                                                  │
# │ list[i64]                                            │
# ╞══════════════════════════════════════════════════════╡
# │ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 539] │ 
# └──────────────────────────────────────────────────────┘
```

It seems to be related to the `INPUT_WILDCARD_EXPANSION` flag during expr_expansion.

**Comment by cmdlineluser** [comment]
Not sure if I'm on the right track here - but this also seems to be the cause of the linked struct issue:

```python
df = pl.DataFrame({"X": {"a": 1}, "Y": {"a": 3}})

df.select(pl.all().struct.with_fields())
# shape: (1, 1)
# ┌───────────┐
# │ X         │
# │ ---       │
# │ struct[2] │
# ╞═══════════╡
# │ {1,{3}}   │
# └───────────┘
```

From what I can tell, it looks like if `INPUT_WILDCARD_EXPANSION` is enabled, it ends up with a recursive call in `rewrite_projections` which seems to end up "flattening" eveything into a single expression.

https://github.com/pola-rs/polars/blob/cafc163f1c72d5926a3500d072115a137f7f6468/crates/polars-plan/src/plans/conversion/expr_expansion.rs#L660

```
rewrite_projections()
  expand_function_inputs()
    rewrite_projections()
```

It's a bit tricky trying to debug what's happening.

**Comment by siddharth-vi** [comment]
I was looking into this and other issues with pl.all() (#18968). What is happening is that for these functions `INPUT_WILDCARD_EXPANSION` is set to true, as @cmdlineluser has mentioned.
The definition of this flag is here - 
https://github.com/pola-rs/polars/blob/ee9bafbdef7d62baa06d469f42e6cec0755eb544/crates/polars-plan/src/plans/options.rs#L145-L155
For these functions I think the second expansion is correct i.e this flag should be disabled.
>It's a bit tricky trying to debug what's happening.

Below is my understanding .
There are two places where wildcard expansion happens :-
https://github.com/pola-rs/polars/blob/ee9bafbdef7d62baa06d469f42e6cec0755eb544/crates/polars-plan/src/plans/conversion/expr_expansion.rs#L673
and 
https://github.com/pola-rs/polars/blob/ee9bafbdef7d62baa06d469f42e6cec0755eb544/crates/polars-plan/src/plans/conversion/expr_expansion.rs#L682

The first expansion is conditional on the flag being true.
With flag set as true, the inputs to the function get expanded ; F(\*,other) becomes F(a,b,c,other). When it reaches the second line there are no wildcards left hence nothing happens.
 With the flag disabled, the first expansion does nothing; F(\*,other)  stays F(\*,other). In the second expansion F(\*,other) becomes F(a,other), F(b,other), F(c,other). 

I tried removing this flag and it seems to be working correctly. All tests are also passing.
```
df = pl.DataFrame({"a": [1], "b": [2]})

df.select(pl.duration(days=pl.all()).name.keep() )


# shape: (1, 2)
# ┌──────────────┬──────────────┐
# │ a            ┆ b            │
# │ ---          ┆ ---          │
# │ duration[μs] ┆ duration[μs] │
# ╞══════════════╪══════════════╡
# │ 1d           ┆ 2d           │
# └──────────────┴──────────────┘



df = pl.DataFrame({"a": [[1, 2]], "b": [[3, 4]]})
df.select(pl.all().list.count_matches(3))


# shape: (1, 2)
# ┌──────────────┬──────────────┐
# │ a            ┆ b            │
# │ ---          ┆ ---          │
# │ u32 ┆ u32] │
# ╞══════════════╪══════════════╡
# │ 0           ┆ 1           │
# └──────────────┴──────────────┘

If this sounds sensible I can raise a PR for this.

```

**Comment by barak1412** [comment]
I get the "argument overflow" thing, but I still don't get -

When you see `pl.func(pl.all())`, as a user, what do you expect to see as a result?
- [`pl.func(col1)`, `pl.func(col2)`, ...]
or
- ``pl.func(col1, col2, ..)`

**Comment by siddharth-vi** [comment]
We can make a distinction on how `pl.func(pl.all())` should behave :-

- If it is a function which conceptually can take infinite arguments, such as max_horizontal,concat_list, the result should be `pl.func(col1, col2, ..)`
-  If it is a function which has fixed number of arguments, such as pl.duration, the result should be `[pl.func(col1), pl.func(col2), ...]`

I think this is how the functions have been designed till now, based on the docs for these functions. If required, we can make the docs more clear there so that users know how the wildcard expansion will behave.

**Comment by mcrumiller** [comment]
In general, the first one, but the Polars API often allows for (and even prefers) the second when we're dealing with *variadic* arguments. For example, `pl.col(...).function().over(a, b, c, d, ...)`. In that case, `pl.all()` is more a less a stand-in for `[a, b, c, d, ...]`. The issue here is that `pl.all` is itself a singular expression, and the expansion is not happening in python.

Most polars functions that accept variadic columns do something like the following (but not always):

```python
def foo(a, *extra_args):
    if isinstance(a, list):
        args = a
        if extra_args:
            raise ValueError("Must supply single list or args individually")
    else:
        args = [a, *extra_args]
    return sum(args)

my_list = [1, 2, 3]

foo(1, 2, 3)  # 6
foo(my_list)  # 6
foo(*my_list)  # 6
```

This is fine, because `foo` expects all of the inputs to be the same type and are used as if they were a single list. But if instead we had:

```python
def foo(a, b=None, c=None):
    ...
```
then calling `foo(pl.all())`, one would not expect `b` and `c` to be overwritten, as `pl.all()` is a single expression. But it's overflowing.

**Comment by barak1412** [comment]
@mcrumiller @siddharth-vi thanks.

In my opinion, generally, for consistency, we need make a clear distinction -

1. `pl.all().<namespace>.<function>()`, should be translated  to [`col('c1').<namespace>.<function>()`, `col('c2').<namespace>.<function>()`, ..].
2. `pl.<function>(pl.all())`, should be translated to `pl.<function>(col('c1'), col('c2', ...)`.
3. `over(pl.all())`, should be translated to `over(col('c1'), col('c2'), ...)`.


The issue about python keyword arguments should be fixed with the above in mind, in my opinion.
For instance, `pl.duration(pl.all())` may be disallowed, but `pl.all().dt.duration()` does.

@ritchie46 @orlp Do you have any clear statement about this subject? thanks.

**Comment by mcrumiller** [comment]
`pl.all()` is just an expression that means "all columns" and its usage depends on the context, but it is not meant to interact at all with the way python parses arguments, variadic or not. Due to an implementation detail, right the internal expansion of `pl.all()` spills over into other arguments when it shouldn't. The distinction you spelled out is already the intended usage and doesn't require any modification of behavior, aside from the bug fix.
