### ISSUE TITLE
Plotting not interacting well with Altair schema wrappers (x=alt.X(...))

### ISSUE THREAD

**Issue by AdrienDart** [pola-rs/polars#19159]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
import polars as pl
import altair as alt
import numpy as np

np.random.seed (42) 

df =pl.DataFrame({
"value": np.random.normal(0,1,1000)
})

df.plot.bar(x=alt.X("value", bin=alt.BinParams(step=1)), y="count()") # bad behavior

alt.Chart(df).mark_bar().encode(x=alt.X("value", bin=alt.BinParams(step=1)), y="count()") # good behavior (similar to hvplot.hist)
```

### Issue description

Polars plot not using the altair wrapper the right way.

### Expected behavior

We should get a usual histogram plot.

### Installed versions

<details>

```
Polars 1.9.0
Python 3.9.13
```

</details>

**Comment by MarcoGorelli** [comment]
Thanks for the report, will take a look

**Comment by dangotbanned** [comment]
Following up as promised in https://github.com/vega/altair/issues/3635#issuecomment-2404686904

The issue is stemming from https://github.com/pola-rs/polars/pull/18625#discussion_r1750863929

## Retrospective read
@joelostblom flagged `_add_tooltip()`, providing [link](https://github.com/vega/altair/pull/3394/files#diff-bbe4e187b18d242a366c820d023afd89041759cb96e4ec66c3f34559a72c2f9dR3917-R3922) as an alternative.
However, that appears to be pointing to the wrong place, it should be [api.py#L3994-L3999](https://github.com/vega/altair/blob/d9f88500d59c74c25f7a662982b4c01ddf511d0a/altair/vegalite/v5/api.py#L3994-L3999)

Applying that change would have looked like:

<details><summary>Expected diff</summary>
<p>

```diff
def _add_tooltip(chart: alt.Chart, /) -> alt.Chart:
-    chart.mark = {"type": chart.mark, "tooltip": True}
+    if isinstance(chart.mark, str):
+        chart.mark = {"type": chart.mark, "tooltip": True}
+    else:
+        chart.mark.tooltip = True
     return chart
```

</p>
</details> 

In the same thread, I was focusing on the testing aspect in (https://github.com/pola-rs/polars/pull/18625#discussion_r1750893306) and (https://github.com/pola-rs/polars/pull/18625#pullrequestreview-2293568879)

I definitely overlooked the change from `alt.Chart.mark` -> `alt.Chart.encoding`, really dropped the ball on that one.
Sorry @MarcoGorelli 

# Suggestion
As mentioned in https://github.com/vega/altair/issues/3635#issuecomment-2404686904, simply pass in `tooltip=True` for calls like

```py
self._chart.mark_...(tooltip=True).encode(**encodings, **kwargs).interactive()
```

I don't think the [consideration](https://github.com/pola-rs/polars/pull/18625#discussion_r1750863929) of `alt.Chart.mark`'s type is relevant for you; since you're simply calling the `alt.Chart.mark_...` method(s) directly.

You would *only* need to handle that case if you parameterized this:

https://github.com/pola-rs/polars/blob/44439d961e9a0a5236175702bdcc0e4fac076f00/py-polars/polars/dataframe/plotting.py#L48-L52

Like:

```py
alt.Chart(df, mark="bar")
```

**Comment by MarcoGorelli** [comment]
thanks so much @dangotbanned ! can confirm this works well

**Comment by AdrienDart** [comment]
Thank you @MarcoGorelli @dangotbanned for looking into this!
