### ISSUE TITLE
python: Shouldn't `ExprDateTimeNameSpace.add_business_days`'s arguments are keyword only?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#19390]
### Description

In looking at the documentation, I was curious as to why the arguments of methods with this complex set of arguments are not keyword-only.
https://github.com/pola-rs/polars/blob/4932666974e48720e7a17cceef2d83f37da286a5/py-polars/polars/expr/datetime.py#L38-L44

**Comment by stinodego** [comment]
Guidelines for keyword-only args are here: https://github.com/pola-rs/polars/issues/6993

I'd say that `n` should be allowed to be positional but the rest should be keyword only. Mostly because `week_mask` is a bunch of booleans. But I'll leave the final say to @MarcoGorelli .

We have a deprecation decorator for this, so we could do this transition 'nicely'.

**Comment by MarcoGorelli** [comment]
> n should be allowed to be positional but the rest should be keyword only

sounds good!
