### ISSUE TITLE
Support for logarithms

### ISSUE THREAD

**Issue by koaning** [pola-rs/polars#1952]
You can now `.sqrt()` an expression. Could we also have `.log()`. I need to perform many products of small numbers that I'd like to turn into an addition for numerical stability.

**Comment by ritchie46** [comment]
Polars expressions support numpy `ufuncs`. So you can write `np.log(pl.col("foo")`, numpy will release the GIL, so all is still parallel and fast.

**Comment by koaning** [comment]
While that'll work in python-land, this won't work if you're only using Rust right? That might also mean that if polars ever supports making small binaries for specific queries that it also won't support `.log()`.

**Comment by ritchie46** [comment]
In rust its all much easier. You can write a lambda (closure in rust) for free. So in Rust I don't want to add it, because it increases compile cost and when you need it you just write

```rust
s.apply(|value| value.log())`
```

But, given that its so easy to add in Python, I've added the `log, log10 and exp` expression. I think it will reduce someones time downstream.
