### ISSUE TITLE
python: `Expr.truediv` and `Expr.floordiv` should be renamed to `true_div` and `floor_div`?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/polars#19531]
### Description

I found this comment: https://github.com/pola-rs/polars/issues/6120#issuecomment-1374911565

> underscore over concatenated words

The lack of underscores in the method names `truediv` and `floordiv` seems odd and should be changed?
Or is this common in the Python world and should be retained?

**Comment by orlp** [comment]
This is intentional. All [operator expressions](https://docs.pola.rs/api/python/stable/reference/expressions/operators.html) follow Python's naming scheme. Python's name for the `+` operator is `__add__`, so we call it `add`. Python calls `<` `__lt__` so we call it `lt`. Python calls it `__truediv__`, so we call it `truediv`, etc.
