### ISSUE TITLE
Vertical Fold

### ISSUE THREAD

**Issue by blackblitz** [pola-rs/polars#1959]
#### Vertical Fold

We could fold horizontally by using `DataFrame.fold`. It would be great if we could fold vertically as well. Related to this is `GroupBy.agg`, but it can only be used with `groupby` and predefined folds (such as `sum` and `mean`). The vertical fold should accept a starting value and a custom function.

For example, `df.sum` should be equivalent to `df.fold(acc=0, f=lambda xs, x: xs + x)`. To distinguish between the horizontal fold and the vertical fold, the following may be considered:

1. Including `axis` as an optional argument as in `sum` 
2. Naming the methods differently (e.g. `foldh` vs `foldv` or `fold` vs `agg`)

The counterpart in the lazy API should also be implemented. However, it should not require the `exprs` argument.

I believe that this is also an opportunity to consider the consistency of the APIs, e.g. the eager `sum` has `axis` argument but the lazy `sum` only sums vertically.

**Comment by ritchie46** [comment]
This would just run python bytecode. So why not use python:

```python
>>> import polars as pl
>>> from functools import reduce
>>> a = pl.Series([1, 1, 2, 3, 2])
>>> reduce(lambda acc, x: acc + x, a)
9
```

**Comment by blackblitz** [comment]
`functools.reduce` does not do a vertical fold with `DataFrame`. For example, the following sums horizontally.

```python
>>> from functools import reduce
>>> import polars as pl
>>> df = pl.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
>>> reduce(lambda xs, x: xs + x, df)
shape: (3,)
Series: 'A' [i64]
[
	5
	7
	9
]
```

The expected result is
```python
shape: (1, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 6   ┆ 15  │
└─────┴─────┘
```

**Comment by ritchie46** [comment]
You could apply the reduce vertically.

```python
df = pl.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

df.select([
    pl.all().map(lambda s: pl.Series(s.name, [reduce(lambda a, b: a + b, s)]))
])
```

I don't see much value in adding it to the API, because it would be syntactic sugar for the snippet above. And the snippet above is terribly slow because we run python bytecode for all elements.

In a horizontal fold, we only python bytecode for a whole column. The rest operations is pushed down into the polars engine.

For this reason we have the polars expressions. A Vertical sum is written as:

```python
df.select([
    pl.all().sum()
])
```

**Comment by ritchie46** [comment]
#1964 will allow for slightly more ergonomic syntax.

**Comment by blackblitz** [comment]
Thank you. This should be mentioned in the "Folds" subsection in the user guide.

However, this does not seem to work with `GroupBy` or `LazyGroupBy` objects. Essentially, `reduce`, `fold` and `agg` are different terms with the same meaning. Would it be possible to allow custom functions in `agg`? Some call such functions "User-Defined Aggregate Functions" (UDAF). For example, to collect lists by group, we would like to write something similar to the following.

```python
df = pl.DataFrame({'G': ['A', 'B', 'A', 'C', 'B'], 'N': [1, 2, 3, 4, 5]})
df.groupby('G').agg(f=lambda xs, x: [*xs, x], acc=[])
```

The expected result is

```python
shape: (3, 2)
┌─────┬────────────┐
│ G   ┆ N          │
│ --- ┆ ---        │
│ str ┆ list [i64] │
╞═════╪════════════╡
│ A   ┆ [1, 3]     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ B   ┆ [2, 5]     │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ C   ┆ [4]        │
└─────┴────────────┘
```

**Comment by blackblitz** [comment]
Thank you for the clarification. It seems that the features are there but I didn't see them.

I understand that the "Folds" subsection is about the `fold` expression. Then, maybe this should be included in the "Apply" subsection. More clarification of `apply` vs `map` with examples would also be great.

**Comment by ibash-corpusant** [comment]
This would be useful to have. In my use case I'm using a LazyFrame. If I use map then it means I'll blow my memory.

I do in fact want my computation to run in a single thread, because it's fundamentally a single threaded computation. The only solution I've found is setting `POLARS_MAX_THREADS=1` and then using `map_elements`. Which is even worse because it means a bunch of other steps are now single threaded that don't need to be.

**Comment by ibash** [comment]
This would be useful to have. In my use case I'm using a LazyFrame. If I use map then it means I'll blow my memory.

I do in fact want my computation to run in a single thread, because it's fundamentally a single threaded computation. The only solution I've found is setting `POLARS_MAX_THREADS=1` and then using `map_elements`. Which is even worse because it means a bunch of other steps are now single threaded that don't need to be.
