### ISSUE TITLE
'Expr' object has no attribute 'apply'

### ISSUE THREAD

**Issue by suyongfan** [pola-rs/polars#20410]
### Description

pl.col('fild1').apply( base64解密的代码 ) 会报错'Expr' object has no attribute 'apply'是为啥

**Comment by kalekundert** [comment]
For anyone else who comes across this in the future, I found `Expr.apply()` in the version 0.18 docs.  I did a search for "polars apply", since I knew I wanted to apply a function to a column but couldn't remember the polars syntax for that, and I didn't realize that my search engine took me to an out-of-date documentation page.

Note that starting in the version 0.19 documentation, `Expr.apply()` has a deprecation warning, which would've been enough for me to realize what was happening.

Anyways, I don't think that there's really any problem to fix here, but I thought it might be helpful to explain how someone could get confused by this error message.
