### ISSUE TITLE
Parallel reading parquet files from S3

### ISSUE THREAD

**Issue by a-agmon** [pola-rs/polars#2077]
is read_parquet capable of parallel reading from S3? 
I saw an issue stated this was implemented but haven’t seen this documented

Alon

**Comment by ritchie46** [comment]
Maybe it can be done with pyarrow. But I am not really sure:

https://stackoverflow.com/questions/45082832/how-to-read-partitioned-parquet-files-from-s3-using-pyarrow-in-python

If you have an arrow table, you can zero copy create a polars DataFrame with `pl.from_arrow`

**Comment by ldacey** [comment]
@ritchie46 all of my data is stored on Azure Blob which I did not see in the documentation for polars. I generally write datasets using `ds.write_dataset(path, filesystem, partitioning)` and read datasets with `ds.dataset(path, filesystem, partitioning="hive").to_table(filter=ds.field("date_id") >= 20210101)` using pyarrow. It seems like I can continue to do this and just copy to a polars DataFrame instead of a pandas DataFrame for transformation steps.

Are there optimizations I am missing out on since polars does not read from Azure Blob partitioned parquet datasets directly? And is there a plan for Azure Blob support?

**Comment by jorgecarleitao** [comment]
Since:
* polars is optimized for CPU-bounded operations
* polars does not support `async` executions
* reading from s3 is IO-bounded (and thus optimally done via `async`)

I would recommend reading the files from s3 asynchronously in Python (pure blobs) and push then to polars via e.g. `io.BytesIO` for deserialization. You do lose the filter and predicate pushdown (as you need to read the whole file into memory / disk).

AFAIK, to do everything within Polars / Rust, we need to introduce `async` to the query engine, which is non-trivial (and has its share of associated tradeoffs ^_^)

**Comment by a-agmon** [comment]
Thanks for the great answers. 
Just putting here the solution I found to be most effective for the common good. 
I used `turbodbc` to read the files in S3 efficiently using a query engine (Trino). 
`turbodbc` exposes a method called `cursor.fetchallarrow()` which then allows me to run this 

```python
cursor.execute(query)
arrow_table = cursor.fetchallarrow()
polar_table = pl.from_arrow(arrow_table)
```
I can then further parallel the processing using 
```python
polar_table.groupby('account_id').apply(merge_sessions)
```

My only concern, and please let me know if im wrong, is that since the actual reading of the data using the `fetch' method will be the bottleneck and will have to fit in memory in full at the same time.

**Comment by ritchie46** [comment]
What do you mean with at the same time?

**Comment by a-agmon** [comment]
> 

Sorry, it wasn't clear. 
I meant that there is no way to make the actual reading of all the dataset into one polar table parallel - only one thread will have to deal with it (in contrast to clustered computing methods in which each of multiple workers reads and process a portion of the data)
