### ISSUE TITLE
Allow mixing string and type selection using `col(["x", pl.Int64])`

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#2261]
_**Edited request**_

Can polars allow mixing string and type selection using `col(["x", pl.Int64])`

See suggestion [here](https://github.com/pola-rs/polars/issues/2261#issuecomment-1005037990).

_**Initial request**_

Any thoughts on an `.include()` method that is the opposite of `.exclude()`?

That way these would both work:

```python
df.select(col('x').include(pl.Int64))

df.select(col(pl.Int64).include('x'))
```

**Comment by ritchie46** [comment]
`col` itself is already inclusive. 

```python
df.select([col('x'), col(pl.Int64)])

df.select([col(pl.Int64), col('x')])
```

`exclude` was specifically added because we could not express some selections. I believe we can already with `col`.

**Comment by markfairbanks** [comment]
This was the sort of use case I had in mind - something where you're extending the expression syntax beyond simple selection. This is a pretty small example, but with more columns I figured this might be useful.

```python
import polars as pl
from polars import col

df = pl.DataFrame(dict(x = ['a', 'b'], y = ['a', 'b'], z = range(2)))

# Current syntax
df.select([col('x').take(1), col(pl.Int64).take(1)])

# Proposed syntax
df.select(col('x').include(pl.Int64).take(1))
```

**Comment by ritchie46** [comment]
We can use list comprehensions for that

```python
df.select([col(a).take(1) for a in ["x", pl.Int64]])
```

But I think it would be most ergonomic to make `col` more inclusive.

```python
df.select(col(["x", pl.Int64]).take(1))
```

**Comment by markfairbanks** [comment]
> But I think it would be most ergonomic to make col more inclusive.
`df.select(col(["x", pl.Int64]).take(1))`

This would be very handy 👍

**Comment by ngriffiths13** [comment]
@ritchie46 are you looking for someone to work on this still? I would love to find a good first issue to contribute to.

**Comment by uchiiii** [comment]
@ritchie46 
I am trying this and have a few questions.
1. Do you think this feature should be available on [Rust's `col` function](https://docs.rs/polars/latest/polars/prelude/fn.cols.html)  as well as on Python's? 
2. As far as I consider, there are two ways to implement this as below. I guess the first one seems easier and the second one could mess up the code only for this feature. Which do you think is better? (or do you have any other approach?)
  - Convert `datatype` into column name and then convert it to `Expr`. e.g.) `["x", pl.Int64]` -> `["x", "z"]` -> Expr
  - Add `MixedColumn`  into [Expr](https://github.com/pola-rs/polars/blob/4d6b5ae4947715fb4ec7d722dda516797029abc2/polars/polars-lazy/polars-plan/src/dsl/expr.rs#L310) so that [Python's `Expr`](https://github.com/pola-rs/polars/blob/e5f76df513d85725ff4d6e4e1d9cde15bc66c25c/py-polars/polars/expr/expr.py#L88) can treat it directly.

Thank you for your reply in advance.

**Comment by mkleinbort** [comment]
Can this be closed in light of selectors?

```python
cs.by_name('x') | cs.by_dtype(pl.Int64)
```

**Comment by stinodego** [comment]
> Can this be closed in light of selectors?

Yes. I prefer not to overload the `col` function further like this. Please use selectors to achieve this!
