### ISSUE TITLE
compatible with pycharm

### ISSUE THREAD

**Issue by ylyang** [pola-rs/polars#2598]
In interactive development by pycharm or spyder or other IDEs, we usually need to view the dataframes from time to time

polars dataframe is not compatible with pycharm, we need do pl.to_pandas() to convert pl.DataFrame to pandas.DataFrame to view the data

if we can support the scientific view of pycharm to view pl.dataframe or pl.series directly?

![1](https://user-images.githubusercontent.com/1475968/153352347-e15db4f0-7406-499c-888c-17b0aec794fd.png)

**Comment by ritchie46** [comment]
Do you know what is required to do so? Don't they internally chech the objects for bring one of pandas? 

If si, I think the issue should be opened at the IDE'd

**Comment by ghuls** [comment]
There is an issue: https://youtrack.jetbrains.com/issue/PY-50861

**Comment by alexander-beedie** [comment]
Looks like they literally check for the classname "DataFrame" (not an instance), and then assume it is pandas, and issue pandas-specific calls to get the schema/cols to setup the grid and retrieve data. That's why `pl.DataFrame` gets _recognised_, but then cannot actually display - it also fails to recognise a real pandas frame if you subclass ;p

```python
import pandas as pd

class NotAFrame( pd.DataFrame ):
    """I actually AM a DataFrame - surprise!"""

# this will now fail to display in PyCharm's scientific grid/view.    
df = NotAFrame( {"x":[1,2,3]} )

```

We could shim the necessary functions on our side, but the problem is doing so without _actually_ exposing them (eg: we don't _really_ want an `iloc`, etc). Bit tricky. Ideally they would have a generic mechanism for adding support, because it's not complicated.

**Comment by ritchie46** [comment]
> Looks like PyCharm literally just checks that the classname is "DataFrame", then assumes it must be pandas, and issues pandas-specific calls thereafter to get the schema/cols/etc.

Wow. :smiling_face_with_tear:

**Comment by ritchie46** [comment]
> (I found the source code that handles the grid display and took a look; it's handled by dataframe_to_thrift_struct in their pydev helpers plugin/lib).

Do they accept PRs? That would be great. :D

**Comment by alexander-beedie** [comment]
> Do they accept PRs? That would be great. :D

I'll try and find out - I may know a guy that knows the devs 🤣

**Comment by sm-Fifteen** [comment]
This was one of their big advertized features [in 2023.2](https://blog.jetbrains.com/pycharm/2023/07/2023-2/) (they have [definitely taken notice of Polars](https://blog.jetbrains.com/dataspell/2023/08/polars-vs-pandas-what-s-the-difference/)), and dataframes now display properly in their Jupyter frontend, but don't seem to work in the SciView dataframe viewer yet.

**Comment by stinodego** [comment]
This now works correctly.
