### ISSUE TITLE
Tensor contraction, matrix multiplication and ndarray calculations

### ISSUE THREAD

**Issue by hyiltiz** [pola-rs/polars#2707]
Is it possible/planned to add support for basic (2D) matrix computations, such as matrix multiplication? I see `Series.dot()` now, but that only works for 1D arrays. Maybe supporting ndarrays/tensors and providing tensor contraction, kronecher product, map, fold and filter (along specified dimension*s*) can be part of the library design so matrix arithmetic is just a special case.

I know we can still throw ndarrays into `numpy` (or others), but would love to see an `arrow2`-based library providing an efficient, lazy and safe computing tensor computation environment.

**Comment by ritchie46** [comment]
Arrow memory is columnar and is not really suited for tensor operations from a cache perspective. Tensor operations also have seen years of performance tuning with BLAS/LAPACK which is what numpy dispatches to. You really want to use that. 

Given that you can better copy to numpy for those operations. Maybe there is room for a few basic operations, but generally matrix operations are out of scope, because our memory is not a matrix.

**Comment by slonik-az** [comment]
The beauty of polars is that is based on arrow. Frameworks like `pytorch` can convert arrow based dataframes into tensors [0] and perform efficient GPU bound tensor algebra (including matrix operations) on them. Much better that cooking up make-shift linear algebra in polars.

[0] https://github.com/facebookresearch/torcharrow

**Comment by sdrap** [comment]
@slonik-az  @ritchie46  I understand the fundamental difference in design, but I am kind of between column and row.

Indeed, when you work with large time series of vectors/matrices/ndarrays (time is way larger than respective dimensions) I had the feeling that it would probably make sense to have some columnar type of storage for `series` of `ndarrays` where for given time $t$ linear algebra or other math transformation are performed with the different `ndarrays` in each columns for close times $t-s$ to $t$.

I am not sure if that makes sense, and that would surely complexify the apache arrow in terms of storage design (as well as polars, since closedness in memory should be ensured in terms of time  (row) and space (cols)  even if the type of the columns can be fixed (ndarrays with given dimension and type).

In any case polars and arrow are truly great pieces of work.
