### ISSUE TITLE
"Illegal instruction (core dumped)" with pip installation on non-AVX CPU

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#2922]
I installed polars 0.13.12 with pip in Python 3.10. When I try to import it (e.g. with `python -m polars`), it segfaults with `Illegal instruction (core dumped)`:

```
$ pip install polars
Collecting polars
  Downloading polars-0.13.12-cp37-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (10.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 26.4 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.0 in ./.anaconda3/lib/python3.10/site-packages (from polars) (1.21.5)
Installing collected packages: polars
Successfully installed polars-0.13.12
$ python -m polars
Illegal instruction (core dumped)
```

I'm guessing the polars pip wheel uses AVX instructions, which my (very old) CPU doesn't support:

```
$ grep avx /proc/cpuinfo | wc -l
0
```

**Comment by ritchie46** [comment]
Right. I was wondering how long that would take. How old is your machine? ^^

**Comment by Wainberg** [comment]
It's an Intel Xeon X5660 from 2010. (Not my personal machine, it's a compute cluster.)

**Comment by ritchie46** [comment]
Wow that is really old. We already don't support python 3.6 anymore, which was released at 2016.

Would compiling from source be an option for you? That will still work.

**Comment by Wainberg** [comment]
Sure, but I could also just stick with pandas ;) Maybe if you made a conda package, it would be more compatible with different CPU architectures, I'm not sure.

**Comment by DOakville** [comment]
Not sure if this issue is related, issues with primary laptop and trying to work usng an older machine. Ubuntu 20.04, Python 3.9. Using Spyder 5.3. Is there a solution or should I give up trying? 

Unable to load Polars and get this error:
import polars as pl

Fatal Python error: Illegal instruction

Main thread:
Current thread 0x00007f56c234e180 (most recent call first):
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1173 in create_module
  File "<frozen importlib._bootstrap>", line 565 in module_from_spec
  File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "/home/dboak/anaconda3/envs/dashenv/lib/python3.9/site-packages/polars/__init__.py", line 4 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 850 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "/tmp/ipykernel_4128/3889388348.py", line 1 in <module>


Restarting kernel...

**Comment by ritchie46** [comment]
We have released a less optimized version of polars for older cpus. See: https://pypi.org/project/polars-lts-cpu/

**Comment by DOakville** [comment]
Amazing and thanks! Fixed the problem.

**Comment by sauerburger** [comment]
I encountered the same issue when importing polars inside a VM that exposes only a limited set of CPU features. Is there a list of extensions required for polars? Obviously, AVX was not exposed in my VM, but is enabling it enough to solve the issue?

**Comment by sauerburger** [comment]
FYI: I've used https://github.com/pkgw/elfx86exts to analyze the polars.abi3.so file:

```
% cargo run polars-0.18.4-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64/polars/polars.abi3.so
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/elfx86exts polars-0.18.4-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64/polars/polars.abi3.so`
MODE64 (call)
AVX (vmovups)
NOVLX (vmovups)
SSE2 (mfence)
CMOV (cmovb)
BMI (tzcnt)
AVX2 (vpmovmskb)
SSE1 (movaps)
AVX512 (kmovw)
BWI (vpaddw)
PCLMUL (vpclmulqdq)
BMI2 (shlx)
CPU Generation: Unknown
```

It does list AVX512. However, this seems to be optional. I was able to use polars on a machine satisfying [microachitecture level v3](https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level#background_of_the_x86_64_microarchitecture_levels) which comes with AVX and AVX2 but not AVX512.
