### ISSUE TITLE
Should `From<&AnyValue<'a>> for DataType` handle `Utf8Owned`?

### ISSUE THREAD

**Issue by cigrainger** [pola-rs/polars#2941]
https://github.com/pola-rs/polars/blob/d183a847becc1b83ea70989ce93f4a968d5ddd83/polars/polars-core/src/frame/row.rs#L276

I noticed that `DataFrame::from_rows` was panicking when trying to use `AnyValue::Utf8Owned`. Should the above implementation handle `Utf8Owned`?

**Comment by ritchie46** [comment]
Hmm.. Yes, maybe it should. `Utf8Owned` was added recently because I thought I needed it (but I did not). 

Do you use that variant? I think it has merit, but I am not sure many people use the `from_rows` API directly as it is discouraged. But I can understand that from a use case like explorer you need more control.

So, yeah, if we keep it in the public API it should also be handled in `from_rows`.

**Comment by cigrainger** [comment]
Ah that makes sense! Now that I'm thinking about it, perhaps I can take a different approach. I'm converting a list of hashmaps to a dataframe, so I found it natural to iterate through and create rows. Perhaps it would be more performant to just accumulate Vecs on the pass through the Vec of hashmaps and construct the dataframe from that?

**Comment by ritchie46** [comment]
> Perhaps it would be more performant to just accumulate Vecs on the pass through the Vec of hashmaps and construct the dataframe from that?

Yes, that would definitely be more performant. Rows are very expensive because we create columnar memory, so we hop all over memory when transposing rows to columns.

There are a few things you could try:

* use a `Vec` of builders, where every element is a column
* iterate the hashmap multiple times per column
* Use the rows, but don't allocate a new string and keep the original buffer around until the rows are consumed.

I think I would try it in that order.

**Comment by cigrainger** [comment]
Fantastic. Thanks @ritchie46! Is there any way to make a dataframe from Vecs of AnyValue? Or something similar. For context, the type I've got coming in as values of the hashmaps is an enum of possible value types and it's easy to implement From for that enum to AnyValue. How do you handle similar situations in the Python bindings? I imagine you can create a dataframe from a list of dicts?

Thanks!

**Comment by ritchie46** [comment]
So every hashmap is a row?

**Comment by cigrainger** [comment]
Exactly.

**Comment by ritchie46** [comment]
Depending how you collect the items from the hashmap, either by getting a value by column name, or iterating the map (but this is in random order). I would create a collection of builders.

If you access the hasmaps in the same order every row, this can be `Vec<Box<dyn Builder>>`. This is what we do in csv parsing for instance.

You could also use the rows approach in this case. It would be less code, but a bit slower. In any case this requires a pivot, so the rows case make sense indeed. I will add the `Utf8Owned` as well.

To save allocations, I would still try to use `AnyValue::Utf8` that holds a reference into the hashmap.

**Comment by cigrainger** [comment]
That makes tons of sense. I was trying to figure out which trait to use for Box -- Builder! Thanks again, I think that gives me everything I need. I can open up a PR for supporting Utf8Owned tonight or tomorrow (I'm on Australia time) even if we don't end up using it in Explorer. 👍
