### ISSUE TITLE
Reindex and Relevel Categoricals

### ISSUE THREAD

**Issue by kdkavanagh** [pola-rs/polars#2956]
Apologies if this already exists, could not find it in the API docs... I'm looking for the best way to both reindex (ie replace the index values using some mapping of string -> int) and relevel (ie replace strings using some mapping) a categorical series. 

My current approach is to cast to a Utf8 first and then back to a categorical, however this is obviously quite inefficient with large dataframes.

**Comment by ritchie46** [comment]
Polars doesn't have index values. Do you mean the integers that represent the categories?

The categorical integers are an implementation detail and are not meant to be reindexed. What is the rationale behind this question? Maybe I can help on designing it more natural to polars.

**Comment by kdkavanagh** [comment]
Correct, the integers underlying the category strings. 

I'm working to serialize rows of the DataFrame as C-structs for use elsewhere.  I treat Categorical columns as C++ enums, so before serialization I must grab the raw integer value for that column rather than the string.

For cases where the Categorical indices match the C++ enum values directly, I could get by with just obtaining the Categorical mapping dictionary first, and then just casting the Series to `Int8`.  That said, I'm not sure I see a way to grab that dictionary from the Categorical series either.  In any case, if the values dont align, I'd need to re-level.

RE: "getting the dictionary", with native pyarrow, I can do something like this:
```
>>> arr = pa.array(["A", "B"], pa.dictionary(pa.int8(), pa.string()))

>>> dict(zip(arr.dictionary, arr.indices))
{<pyarrow.StringScalar: 'A'>: <pyarrow.Int8Scalar: 0>, <pyarrow.StringScalar: 'B'>: <pyarrow.Int8Scalar: 1>}
```

**Comment by ritchie46** [comment]
You can cast the categorical to a `UInt32`. This exposes the categorical indices. If you combine that with a call to unique, you have a mapping.

**Comment by KasperLin** [comment]
Hi there, this issue has been closed for several months, but I truly believe part of it is still unsolved. 

*Because I cannot find an efficient way to [rename categories](https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.rename_categories.html).*

I understand that we'll never need a "re-index" , but "re-level" is definitely a frequently-used feature. 
> As @kdkavanagh [described](https://github.com/pola-rs/polars/issues/2956#issue-1178540340) : 
> * "re-index" means changing the underlying integer category index 
> * "re-level" means rename a category while it's integer category index remains the same

Given the memory structure of polars Categorical, I understand it might be difficult to achieve this (if not impossible), especially without a global string cache. 
But at the end of the day, my polars implementation (cast & join) of this is way slower than [the pandas equivalent](https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.rename_categories.html), to the point that it's worth it to convert to pandas, rename the categories, then convert back to polars. 

@ritchie46 Could you please let us know if "rename categories" is possible ? If so, can we have it implemented ? By adding this feature, we're finally able to replicate *every method* under [pandas Categorical](https://pandas.pydata.org/docs/reference/api/pandas.CategoricalIndex.html) by this amazing library.

**Comment by ritchie46** [comment]
Why do you want the integer to remain the same? What's wrong with replacing the category with a new one?

**Comment by KasperLin** [comment]
( Thanks for the quick reply! )

I don't actually need the integer to remain the same, and there's nothing wrong with replacing by a new category per se, it's just that it seems slower than simply modify the underlying mapping? If I'm understanding correctly here. 

Correct me if I'm wrong, as far as I know, to "rename categories" in polars, one can either:

1. Use a when-then-otherwise expression
2. Left join with a mapping table
3. Cast to UTF8, replace string, cast back to Categorical

But both seems significantly slower than [the pandas equivalent](https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.rename_categories.html), which I suspect is simply playing with [the categories](https://pandas.pydata.org/docs/reference/api/pandas.CategoricalIndex.categories.html) instead of going through the whole series, which is way more efficient when it comes to super long categorical series. 

> Let me know if you need a minimal benchmark example from me.

**Comment by KasperLin** [comment]
@ritchie46

**Comment by KasperLin** [comment]
@ritchie46 
Sorry to bother again, just a kindly reminder here, in case you've somehow missed my reply since it's a "closed" issue.
