### ISSUE TITLE
[question] Is complete pandas-independence a goal for polars?

### ISSUE THREAD

**Issue by cnpryer** [pola-rs/polars#2971]
First I just want to say this project is super interesting. Thanks for all the hard work here.

I couldn't find any discussions related to my question, so I apologize if this has been asked already. I checked both here and on stackoverflow.

**Is complete pandas-independence a goal for polars?**

For context, `pandas` has been a big part of a stack of mine professionally for the past 6 years. I'd really like to start contributing, but I'm kind of interested in checking `polars` out more before I do.

It makes sense for `polars` to not aim to have complete parity with `pandas`, but I'm curious if there are motivations I'm not aware of that help draw that line in the sand.

An example would be reading Excel files. 

Personally, I think it makes a lot of sense to just lean on `pandas` instead of adding unnecessary maintenance to `polars`, but as someone who's coming to `polars` with fresh eyes, I have this natural reaction to compare _completeness_ of the two projects for those super surface-level implementations.

While not everyone is going to care about these details, it's possible there are other potential new `polars` users that notice this and maybe get turned off.

Regardless, again, I'm very curious of this project. I really love [your design goals](https://pola-rs.github.io/polars-book/user-guide/#goals-and-non-goals). I'm looking forward to tinkering with it on both Python and Rust fronts :).

**Comment by ritchie46** [comment]
Polars aims to be complete, but not in the obvious way. As in you should be able to do everything you can do in pandas regarding to data manipulation.

However, polars might not expose all methods available in pandas, but polars will give you the expressions needed to compose the same result. Similar to how a programming language gives you the tools to be turing complete.

With regard to IO, polars has a lot more native than pandas does, think about reading parquet, and feather files. Pandas has a double copy here, because they first read with pyarrow into arrow memory.

Polars also accepts some double copies for files we don't deem too important, think about excel files. Polars supports this in `pl.from_pandas(pd.read_excel(..))` :smile: 

If I have to define hard lines, I would thin something like this:

* is it core to our goal (e.g. plotting is not
* is it explicit /readable / consistent with our API?
* If this logic belongs to another third party tool maybe add a few example showing interop.

I like the unix philosophy, do one thing and do one thing good.

**Comment by cnpryer** [comment]
Wow thanks for the detail. Pretty much all of this makes me want to play around with `polars` even more.

> If I have to define hard lines, I would thin something like this:
> - is it core to our goal (e.g. plotting is not
> - is it explicit /readable / consistent with our API?
> - If this logic belongs to another third party tool maybe add a few example showing interop.

> I like the unix philosophy, do one thing and do one thing good. The goal of polars API is predictability and composability. How we achieve that, will be open for discussion one step at a time.

This specifically is what has me interested in moving away from `pandas`. I really like this.

> Polars also accepts some double copies for files we don't deem too important, think about excel files. Polars supports this in pl.from_pandas(pd.read_excel(..)) 😄

I noticed this. This specifically is actually what originally got me curious.

So just to make sure I understand where to draw the line before I really dig, Excel isn't considered an important file type? 

Maybe it's just me, but historically I've worked on models as part of consulting engagements, and during those projects chances are high that I'd work with teams who are religious with Excel.

Personally I always prefer something like Parquet, but since I often have to collaborate with people using Excel, it's a file type I try to consider more during projects (at least the peripheral work). Being generally Excel-compatible I guess is more important in my world than I'd like for it to be.

imo my concern is super nit-picky, so no need to get hung up on this. This kind of discussion helps me understand what parts I should probably care more about than others. This sounds like an area I might need to move on from.

**Comment by ritchie46** [comment]
Well my rationale considering excel is that I don't see it as a blocker for polars usage. 

For instance pandas deals for a lot of IO by depending on arrow.

This works by letting pyarrow read into arrow memory and then copy into pandas. So that is a double copy there.

Most polars readers are natively and directly read into arrow/polars memory. 

For excel files I don't expect these to get really big, as excel cannot really deal well with it/ becomes bloated. 

So in that case. the idiomatic polars support for reading excel is:

```python
pl.from_pandas(pd.read_excel(..))
```

Having an extra copy from pandas memory. Which I think will not hurt too much.

**Comment by cnpryer** [comment]
Yea I don't want to beat a dead horse, but 

> I don't see it as a blocker for polars usage

For some people it might be.

> letting pyarrow read into arrow memory and then copy into pandas. So that is a double copy there.

Makes sense. I wouldn't want to tell you how to build your project. You've done such a good job with it.

Maybe I'm alone with this take. I'm curious if that's the case.

**Comment by ritchie46** [comment]
> For some people it might be.

Maybe we could document `pl.from_pandas(pd.read_excel(".."))` as the idiomatic way to read excel files? I am not joking. I cannot believe there are excel files that big that we need to ship native parsers.

**Comment by cnpryer** [comment]
> pl.from_pandas(pd.read_excel(".."))

😬 

> I cannot believe there are excel files that big that we need to ship native parsers

Would this even need to be the motivation to ship one? It sucks because Excel files would add a bunch of overhead, but unfortunately a lot of people use them. I've considered looking into this if enough people were interested.

**Comment by cnpryer** [comment]
FYI polls are now available in GitHub Discussions. Maybe it's worth creating a poll for this to get a feel for whether this is even worth anyone's time. Could redirect people who submit issues like #2088 and #635 there. 

If it's a small percentage of users then the polls will be a nice way to be like, "this would be nice, but based on feedback from our users we suggest just using `pl.from_pandas(pd.read_excel(".."))` since this is not a high-demand feature. check out this poll [link]".

**Comment by datainvestor** [comment]
Yeah that would be cool. We use Pandas a lot in our projects that involve reading tons of excel files, however I have been eyeing to switch to Rust in some and Polars seems to be the best alternative to Python's Pandas library. Its great to use wtih csv (as far as Rust is concerned) however reading excel files and then passing them into Polars.rs was a nigthmare.

**Comment by ritchie46** [comment]
@cnpryer I am willing to accept a python only solution based on something like `xlrd` which then is an optional install requirement.

If we flag that as experimental we don't have string maintenance commitments and could explore what it means to support this.

I don't really want to do this on the rust side because it bloats our binary with something I find not worth it.

**Comment by cnpryer** [comment]
What about one that using Python bindings for https://github.com/tafia/calamine

**Comment by stinodego** [comment]
The original question was answered. And we have `read_excel` now. Closing this.
