### ISSUE TITLE
Bug in bool not filter and Nulls

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#3062]
#### What language are you using?

Rust

#### Which version and feature gates did you use?

```
polars = { git = "https://github.com/pola-rs/polars", rev = "5d9d9bd0171064fa6e18c126ad0b35522f02901d", features = ["lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "round_series"] }
```

#### What operating system are you using polars on?

OSX

#### What language version are you using
Rust 1.59.0 

#### Describe your bug.

A filter on a bool column, only tested it for bool, might be other `data_types` too, handles nulls weird.
When creating a filter for `true` rows and putting `not()` around it null values are dropped.

#### What are the steps to reproduce the behavior?

```rust
    #[test]
    fn filter_true() -> Result<()> {
        let inp = df! {
            "a" => [Some(true), Some(false), None],
            "b" => ["1", "2", "3"]
        }?;
        let filter = col("a").eq(lit(true));
        let with_true = inp.clone().lazy().filter(filter.clone()).collect()?;
        let with_not_true = inp.clone().lazy().filter(not(filter)).collect()?;
        dbg!(&with_true, &with_not_true);
        let res = with_true.vstack(&with_not_true)?;
        assert!(res.frame_equal_missing(&inp));
        Ok(())
    }
```

#### What is the actual behavior?

The dataframe `with_not_true` does not contain the row which should have been matched `"a" = None`. 
```
[src/filter/polars.rs:437] &with_true = shape: (1, 2)
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ bool ┆ str │
╞══════╪═════╡
│ true ┆ 1   │
└──────┴─────┘
[src/filter/polars.rs:437] &with_not_true = shape: (1, 2)
┌───────┬─────┐
│ a     ┆ b   │
│ ---   ┆ --- │
│ bool  ┆ str │
╞═══════╪═════╡
│ false ┆ 2   │
└───────┴─────┘
```

#### What is the expected behavior?

I believe all rows should either match the filter or the inverse of the filter. The test is a little larger than needed to highlight this fact.

**Comment by cbilot** [comment]
I think what we're seeing is the paradox of so-called [three-valued logic](https://en.wikipedia.org/wiki/Three-valued_logic#Kleene_and_Priest_logics).  That is, there are three truth values: True, False, and NULL.

It might be helpful to look at what the filter statement itself is seeing.  In Python:
```python3
df = pl.DataFrame({"a": [True, False, None]})

(df
 .with_column((pl.col("a") == pl.lit(True)).alias("filter"))
 .with_column(pl.col("filter").is_not().alias('not_filter'))
 )
```
```
shape: (3, 4)
┌───────┬─────┬────────┬────────────┐
│ a     ┆ b   ┆ filter ┆ not_filter │
│ ---   ┆ --- ┆ ---    ┆ ---        │
│ bool  ┆ i64 ┆ bool   ┆ bool       │
╞═══════╪═════╪════════╪════════════╡
│ true  ┆ 1   ┆ true   ┆ false      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ false ┆ 2   ┆ false  ┆ true       │
├╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null  ┆ 3   ┆ null   ┆ null       │
└───────┴─────┴────────┴────────────┘
```
In row 3, we see a `null` value for both the `filter` and `not_filter` columns, rather than True or False.  (In 3-value logic, not (NULL) == NULL.)  

The issue becomes, should we select `null` values, in addition to True values?  If so, then rows 1 and 3 will both be selected for `filter`.  But by that same logic, then we must select both rows 2 and 3 for `not_filter`.  Thus, the results of "filter" and "not_filter" overlap; both include row 3.

It seems intuitive that `filter` and `not_filter` should produce mutually disjoint sets whose union is all rows.  That is, `filter` and `not_filter` should partition the rows.  And that `not_filter` should capture the rows missed by `filter`.  But that's only true of 2-value logic.  In 3-value logic, this is not so.

Three-value logic can be incredibly frustrating at time, especially when `null` values permeate the data.  But three-value logic is widely used in database logic, and as such, users will likely expect Polars to follow the same principles.

Was this helpful?

**Comment by SimonSchneider** [comment]
Thank you for the insightful reply. My intuition was that the results would be disjoint sets but it there is a strong precedence for the opposite and that's what a larger part of the userbase expects then I'm not one to argue. I guess one solution is add a `or(null)` to the inverse of the filter.

Thanks again!

**Comment by ritchie46** [comment]
I did make an adaptation on the logic. It turns out the we way we deal with `literal`s is different from full array comparisons. This inconsistency is something I will fix.

We still have three value logic. But I will make it follow this rule in exact comparissons `null == true = false` `null == false = false`. On a `filter`, nulls will remain interpreted as `false` values.
