### ISSUE TITLE
`DataFrame.to_pandas` should support struct fields

### ISSUE THREAD

**Issue by physinet** [pola-rs/polars#3176]
Pandas dataframes involving struct-like objects can be converted to polars dataframes that contain struct fields:
```
>>> import pandas as pd
>>> df = pd.DataFrame([{"a": {"b": 2}}])
>>> df = pl.from_pandas(df)
>>> df.dtypes
[<polars.datatypes.Struct object at 0x7f9fee36bf10>]
```
However, the inverse (`DataFrame.to_pandas`, or `DataFrame.to_arrow`) does not seem to be possible. Continuing from the above snippet,
```
>>> df.to_pandas()
thread '<unnamed>' panicked at 'this operation is not implemented/valid for this dtype: Struct([Field { name: "b", dtype: Int64 }])', /github/workspace/polars/polars-core/src/series/series_trait.rs:282:9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vadmin/.venv-dev/lib/python3.10/site-packages/polars/internals/frame.py", line 1067, in to_pandas
    record_batches = self._df.to_pandas()
pyo3_runtime.PanicException: this operation is not implemented/valid for this dtype: Struct([Field { name: "b", dtype: Int64 }])
```
Users would benefit from having seamless conversion between pandas and polars for dataframes involving structs. This does not seem to be possible currently.

**Comment by cjermain** [comment]
This error occurs because [`StructChunked`](https://docs.rs/polars/0.20.0/polars/datatypes/struct.StructChunked.html) does not have a `chunk_lengths()` method (or `chunk_id()`) unlike the other types of [`ChunkedArray`](https://docs.rs/polars/0.20.0/polars/chunked_array/struct.ChunkedArray.html), since it is composed of `Series`. The code fails on the following line:
https://github.com/pola-rs/polars/blob/66f0b275abe8f489fdc8e3ffb44ba6489a595486/polars/polars-core/src/frame/mod.rs#L390

I think the solution is likely to re-write `DataFrame::rechunk` to gracefully handle structs and nested structs, which might require looking at the underlying fields to check the nested chunks within. Another approach would be to add a `chunk_lengths()` method to mock the API of the other array types.

**Comment by cjermain** [comment]
I think this is explicitly a bug, not a feature request.
