### ISSUE TITLE
Support nulls in struct columns

### ISSUE THREAD

**Issue by ishmandoo** [pola-rs/polars#3207]
Currently, trying to create a dataframe with a struct column that contains any nulls results in an error saying that validity is not supported. It would be very useful to have some kind of support for this.
```
import polars as pl
import pyarrow as pa
data = [{"a": {"b": 1}}, {"a": None}]
df = pa.Table.from_pylist(data)
df = pl.from_arrow(df)
```
```
PanicException: polars struct does not support validity]()
```

This was originally noticed by @physinet

**Comment by cjermain** [comment]
I think this is a bug. `StructChunked` [does not have it's own validity](https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/chunked_array/logical/struct_/mod.rs#L9) (null mask), since it relies on the underlying list of `Series` to handle that. However, when going to and from existing Arrow data, I think there needs to be a translation of the `arrow2::array::StructArray` validity or we need to ensure that the underlying fields have the correct validity.

**Comment by ritchie46** [comment]
You are right @cjermain. Especially in this example the `"a"` field should have a validity and note the struct itself.
