### ISSUE TITLE
List of columns versus multiple arguments syntax

### ISSUE THREAD

**Issue by physinet** [pola-rs/polars#3283]
In libraries such as PySpark, a list of columns/expressions/column names can be passed either as a list or as multiple arguments to a function. For example, these two are equivalent in PySpark:
```python
df.select("a", "b")
df.select(["a", "b"])
```
This syntax would also be convenient to have throughout polars. Examples of where this could be used are `DataFrame.select` and `DataFrame.sort`. `DataFrame.select` will likely be the most common use case.

**Comment by zundertj** [comment]
It could be supported for `select`, but `sort` is tricky because it takes multiple arguments. Now those arguments take at the moment only bools (`reverse`, `nulls_last`, `in_place` for `sort`), whilst column names should be strings, so we could probably separate the two cases, at the cost of some additional complexity. However, there are places in the api where we use string parameters to denote something else than columns (`fill_null` and `fill_nan` come to mind), so it is not impossible that at some points this starts to clash. So I'm personally against doing this in cases where it may clash.

Could you elaborate on the convenience for `select`, that is not having to type the square brackets, or is there more to this? If the number of characters is the reason, why not use:

```python
df[["a", "b"]]
```
which I think is a neat syntax?

**Comment by physinet** [comment]
I'd argue that for `sort`, those extra arguments should be keyword-only arguments which helps to sort out the ambiguity. Only positional arguments are interpreted as columns. I don't think the types should be inspected.

The square bracket syntax is nice and convenient for users coming from pandas, but users coming from pyspark might prefer the syntax I'm proposing. Plus, the square bracket syntax is only relevant for select and won't cover any of the other use cases.

**Comment by ritchie46** [comment]
Fwiw. i will deprecate the square bracket syntax in the future. I want it to be clear we are running `select` and only have one clear way to write things.

**Comment by zundertj** [comment]
My worry is that if we go and start rolling this out across the api , starting with `select` and `sort`, that at some point there will be choices to be made, which we may not be able to foresee right now, and we start having discussions on which consistency is more important. I'm not against making the additional parameters for `sort` keyword-only (although it would be a deprecation, and is "additional complexity"  in the sense that there will be users that will not immediately realize it is keyword only), but it is an example of such a discussion.

The other point, which funnily enough @ritchie46  brings up in response to my usage of square brackets, is that this introduces an another way to write the same thing.

**Comment by cbilot** [comment]
Let me preface by saying that I do not wish to disparage anyone's work.  I myself certainly cannot do what you all do.  (And I am very grateful for the work you all do.)

But as someone who answers questions on Stack Overflow, it would be helpful if these types of proposed syntax changes could be batched into a major point release, rather than a stream of changes.

It would also help when answering SO questions if I can link to a web page that clearly and persuasively documents these syntax changes and the reasons why.  For example, is there currently a clamoring from Polars users that the current syntax is confusing, or inconsistent, or overly cumbersome?  (I have not seen this on Stack Overflow so far ... but what I do see repeatedly is reluctance to leave "Pandas-style coding" and embrace the Expressions API.)

Perhaps more concerning (to me) than refining the existing syntax is the view that Polars is "not ready for prime-time".  (@ritchie46 provided a link in Discord to a Yahoo thread where some made that claim).  I doubt this view is because of insufficiently elegant syntax.  Instead, one reason might be concerns about the correctness of the existing API.  Indeed, if you look at the issues I have submitted, many are based on Stack Overflow questions, where a puzzled user could not figure out why something did not work.  And in some cases, I stumbled onto other bugs while attempting to propose a solution that works.

Please don't take this as criticism of anyone's hard work.  Instead, please consider this a viewpoint from someone who is sifting through SO questions, trying to help people harness the power of Polars to meet their objectives.

**Comment by ritchie46** [comment]
> But as someone who answers questions on Stack Overflow, it would be helpful if these types of proposed syntax changes could be batched into a major point release, rather than a stream of changes.

I understand that. It is a bit hard to do, as they come gradually, but the way I want to go about it is deprecating old solutions and on more major release, remove deprecated functions.

> It would also help when answering SO questions if I can link to a web page that clearly and persuasively documents these syntax changes and the reasons why. For example, is there currently a clamoring from Polars users that the current syntax is confusing, or inconsistent, or overly cumbersome? (I have not seen this on Stack Overflow so far ... but what I do see repeatedly is reluctance to leave "Pandas-style coding" and embrace the Expressions API.)

I don't think so. If any case I believe people who are accustomed to polars logic, tend to find it more consistent and well thought out. What I don't think we should do, is `implement X` because `Y` does it naively.

On this topic, I don't think we should do this change, as I am not convinced we can make it consistent across all our API surface. Normally where we accept expressions, we either accept `Union[List[Expr], Expr]` and I think we should keep it that way. To a user it is clear we provide a single argument without question.


## off topic for this issue
> Perhaps more concerning (to me) than refining the existing syntax is the view that Polars is "not ready for prime-time". (@ritchie46 provided a link in Discord to a Yahoo thread where some made that claim). I doubt this view is because of insufficiently elegant syntax. Instead, one reason might be concerns about the correctness of the existing API. Indeed, if you look at the issues I have submitted, many are based on Stack Overflow questions, where a puzzled user could not figure out why something did not work. And in some cases, I stumbled onto other bugs while attempting to propose a solution that works.

I also read that. It had me wondering if he was accidentally on the old reference guide. I believe the criticism was on documentation, which I agree is far behind that of pandas, but is not that bad. I will open another issue where we can set a goal that every expression/method etc. has a working example. That should fill the gap between pandas/numpy.

> Please don't take this as criticism of anyone's hard work. Instead, please consider this a viewpoint from someone who is sifting through SO questions, trying to help people harness the power of Polars to meet their objectives.

None taken. Thanks for all the help on SO. :raised_hands:

**Comment by cnpryer** [comment]
> even similar Python built-in functions do not seem to be consistent with each other (e.g. max can take a single or arbitrary number of inputs, sum requires a single input

But that doesn't really make it *good design*. imo the benefit here with a project like `polars` is that you're not a dynamic, super-flexible programming language meant to be used and consumed by a gigantic pool of people.

`polars` has a very explicit use case, and what's made me excited about it is that there's a clear effort to remain as consistent of an implementation as possible -- which i love.

btw this convo was a great read 👍

**Comment by ritchie46** [comment]
Thanks for the input everybody. I am closing this as I think the discussion is done.
