### ISSUE TITLE
How to sort within groups by polars?

### ISSUE THREAD

**Issue by yanyu2015** [pola-rs/polars#3330]
my dataset is as follows:
|id|code|tag|post_last_time|
|:----|:----|:----|:----|
|i64|str|str|datetime|
|855|110022|negative|2022-1-23 17:02|
|855|110022|negative|2020-1-10 10:43|
|289|008327|positive|2020-1-14 14:32|
|704|009046|negative|2020-9-2 14:53|
|704|005449|negative|2019-9-3 8:59|

I want sort post_last_time in every group（group by id）, the preferred format is as follows:
|id|code|tag|post_last_time|
|:----|:----|:----|:----|
|i64|str|str|datetime|
|855|110022|negative|2020-1-10 10:43|
|855|110022|negative|2022-1-23 17:02|
|289|008327|positive|2020-1-14 14:32|
|704|009046|negative|2019-9-3 8:59|
|704|005449|negative|2020-9-2 14:53|

How can I do it?
I have try code：
```python
q = (
    df.lazy()
    .groupby("id")
    .agg
    (
        pl.col('post_last_time').sort_by("post_last_time"),
    )    
)
df1 = q.collect()
df1
```
but the result is：
|id|code|tag|post_last_time|
|:----|:----|:----|:----|
|i64|str|str|datetime|
|855|110022|negative|[2020-1-10  10:43:52,2022-1-23  17:02:28]|
|289|008327|positive|[2020-1-14  14:32:46]|
|704|009046|negative|[2019-9-3  8:59:38,2020-9-2  14:53:33]|

I don't want it be listed.

additionally, I have tried it in pandas, it's easy to use but my groups is so large(about 30,0000) it spends too much time, is there a speed way to achieve my needs？

**Comment by cbilot** [comment]
https://stackoverflow.com/questions/71550005/sort-within-groups-on-entire-table

This may help.

Respectfully, it’s best to ask questions about how to use Polars on Stack Overflow.

**Comment by yanyu2015** [comment]
Thank you so much! I have read the user guide carefully, and can't find the answer on google, so I come here to ask questions. **I think the user guide is too concise, how can I learn similar knowledge?** Also, there are some minor errors in the user guide.

**Comment by cbilot** [comment]
> I think the user guide is too concise, how can I learn similar knowledge?

Looking at your code, you have clearly grasped the secret to using Polars - that is, to use the Expression API.  (Too many people try to write "Panda-style" code in Polars, which is not optimal.)  Also, you clearly understand using the `Lazy` mode in Polars to optimize your queries.  So you are off to a **great** start.

A couple of "next steps" I would recommend to help you learn more, if you haven't done these already:
* browse through the API documents, particularly the section on [Expressions](https://pola-rs.github.io/polars/py-polars/html/reference/expression.html).  Since Expressions are the heart of writing elegant, performant Polars code, you'll want to master the use of Expressions.  And right now, the Polars team is adding more and more examples for each method.  I realize it's a time investment to read through API docs, but the investment pays off when you consider how fast Polars runs. 
* browse through the Stack Overflow questions that are tagged with [[python-polars](https://stackoverflow.com/questions/tagged/python-polars)].  You can learn so many tips and tricks by reading the answers to the questions.

> Also, there are some minor errors in the user guide.

I'm sure the Polars team would welcome a PR to fix these  ;)

And if you have questions about how to accomplish something using Polars, feel free to post questions on Stack Overflow tagged with [python-polars].  There are many of us who are happy to help.

**Comment by yanyu2015** [comment]
Thank you again, there are so few examples in the api documentation at the moment. I would also like to ask why some methods start with a data variable (`df.select`)and some start with a package name(`pl.col`)? This makes me feel confused

**Comment by ritchie46** [comment]
I will close this as question for how to use polars should be asked on SO.
