### ISSUE TITLE
Why is indexing on groupby object depreciated

### ISSUE THREAD

**Issue by ParitoshSingh07** [pola-rs/polars#3509]
Hi. I come from python background with pandas, found out about polars yesterday and really impressed by what i've seen so far. Thanks for your amazing work.
While comparing syntax i noticed that polars has depreciated syntax that essentially looks like 
`df.groupby("a")['b'].sum()`, suggesting `.agg` instead.

I was just curious why this decision was made.
I traced this back to [this commit](https://github.com/pola-rs/polars/pull/2344/commits) but did not find any further clues there (i may have missed something).

Any insights into why this choice was made, or why this style of indexing is not desired?

**Comment by ritchie46** [comment]
Because I like to have one clear way of doing something. A codebase where there are various ways of doing a groupby + aggregation is bloated and leads to confusion as everybody will write it differently.

The other reason is this this syntax does not let you use the expression API, and thus if you change your mind and decide you not only want to `sum`, but also want to divide by the `first` value (I just make something up, read, I changed my mind, I want to do something else), then you need to rewrite your query to `.agg` anyway, as that method accepts the versatile expressions as arguments, e.g.:

```python
(df.groupby("a")
   .agg([
   # I want to sum
   pl.sum("b")
   # I also want to divide sum by first
   pl.sum("b") / pl.first("b)
])
```

The reason I want to nudge the users to the expression API is that that knowlegde propagates to all context in polars.

If you know expressions, you know how to:

- do complex column selections/ computations
- do complex (time) aggregations
- do complex filtering operations
- do complex horizontal operations

Having a separate API that allows for index access only complicates that.

**Comment by ParitoshSingh07** [comment]
Perfect, thanks for the explanation!
