### ISSUE TITLE
Enable memory-efficient row-wise scan of Parquet files

### ISSUE THREAD

**Issue by dclong** [pola-rs/polars#3513]
Some times we want to apply a function to each row of a very large Parquet file. Polars load the whole file into memory even if we use the LazyFrame API. It would be very appealing to enable memory-efficient row-wise scan of a Parquet file.

**Comment by ritchie46** [comment]
This is a columnar query engine. If you want to process values in a parquet file row by row, then there is no benefit in doing that via polars. You would be better off using `parquet2` directly. But not that even then it would not be very efficient because parquet itself is a column oriented data format.

> Polars load the whole file into memory even if we use the LazyFrame API

Not if we can proof that you only need `n` rows. If you write your query and you specify a limit, filters and columns you want to select, polars ensures it only reads the data it needs from the file.
