### ISSUE TITLE
expand `concat_str` input.

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#3519]
This snippet does not expand the regex column to an input of `concat_str`, but instead creates 3 instances of `concat_str`.

```python
pl.DataFrame({
    "a": [1, 1, 1],
    "b_a_1": ["a--", "", ""],
    "b_a_2": ["", "b--", ""],
    "b_a_3": ["", "", "c--"]
}).select([
    pl.concat_str(pl.col(r"^b_a_\d$"))
])
```

**Comment by cbilot** [comment]
Just a quick thought: would the order of the columns returned by the regex expression be sorted in lexical (column name) order, or the order in which the columns appear in the DataFrame?  (They may be different.)

We came across this kind of situation in a SO question about pivot tables.

For example, if columns are named: “str1”, “str2”, …, “str9”, “str10”, “str11”, … the user might be surprised when the result places “str10” and “str11” before “str2”.

This is one reason I hesitated to answer the SO question.  It wasn’t clear what the result “should” be, given that order is essential in a concat function.  For other uses, like select or with_columns, the result of a regex on columns is less important because columns can later be reordered, but for a concat, it’s too late.

just a thought …

**Comment by cbilot** [comment]
I was thinking a list comprehension that included a regex expression (or just a Python `str` method).  Something like ..
```python3
[col_nm for col_nm in df.columns if col_nm.startswith(‘b_a_’)]
```
This explicitly leaves the column ordering to the user.

**Comment by ritchie46** [comment]
I believe the result is in the order of the columns discovery.
