### ISSUE TITLE
Lazy join on categorical column not working for derived tables

### ISSUE THREAD

**Issue by thobai** [pola-rs/polars#3552]
#### What language are you using?

Python

#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

polars-0.13.40

#### What operating system are you using polars on?

macOS Big Sur, 11.6.5

#### What language version are you using
python 3.9

#### Describe your bug.

When doing a join using a categorical column on a "derived" table (i.e. the result of a groupby) and joining that back on to the original table, polars returns an error saying `joins/or comparisons on categorical dtypes can only happen if they are created under the same global string cache`.

#### What are the steps to reproduce the behavior?

```python
import polars as pl
df = pl.DataFrame(
    {
        'group': ['A', 'B', 'A', 'B', 'C'],
        'value': [1,1,2,1,2]
    }
).lazy()
df = df.with_column(pl.col('group').cast(pl.Categorical))
dfGroups = df.groupby('group').agg([pl.col('value').sum().alias('total')])
dfj = df.join(dfGroups, on='group')
dfj.collect()
```

#### What is the actual behavior?

`ComputeError: joins/or comparisons on categorical dtypes can only happen if they are created under the same global string cache`

#### What is the expected behavior?

```
group	value	total
cat	i64	i64
"A"	1	3
"B"	1	2
"A"	2	3
"B"	1	2
"C"	2	2
```

**Comment by ritchie46** [comment]
A lazy query that has a join builds a computation graph with branches. 

![image](https://user-images.githubusercontent.com/3023000/171365770-574b91d4-9afe-41c7-a45b-dbd3f726e230.png)

Because every node's computation flows into the next node, the state is not preserved. So both branches of the join have a different `Categorical` cache state. We can preserve the state, by adding a `cache` node.

This is actually always recommended on self joins. Maybe in the future we can add an optimization for self joins, but I am not really sure how to deal with them.

This snippet runs:

```python
df = pl.DataFrame(
    {
        'group': ['A', 'B', 'A', 'B', 'C'],
        'value': [1,1,2,1,2]
    }
).lazy()
df = df.with_column(pl.col('group').cast(pl.Categorical)).cache()

df_groups = df.groupby('group').agg([pl.col('value').sum().alias('total')])
q = df.join(df_groups, on='group')

q.collect()

```

And of course a global string cache always runs. 

```python
with pl.StringCache():
    q.collect()
```
