### ISSUE TITLE
Python: deprecate most indexing operations.

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#3749]
Which ones should we still allow?

**Comment by slonik-az** [comment]
Please keep the slicing operations. They are standard in Data Science since `numpy`. The easiest way to take every other row of a series or a dataframe is `df[::2]`. 

Moreover, it would be great to allow for negative steps in Series like `series[::-1]`. Currently, negative steps work fine for DataFrames but result in error for Series (probably a bug):

```python
import polars as pl
sr = pl.Series(name='int', values=np.arange(10,20))
sr[::-1]
```
```
OverflowError: can't convert negative int to unsigned
```

**Comment by ritchie46** [comment]
I agree, I want to remove predicates in index notation. That should always be a `filter` imo. 

I want to maintain support for slicing and selection by strings/index.

**Comment by ghuls** [comment]
I think other cases can indeed be removed. 
Slicing operations were greatly improved in
https://github.com/pola-rs/polars/pull/3904

**Comment by stinodego** [comment]
> I agree, I want to remove predicates in index notation. That should always be a `filter` imo.
> 
> I want to maintain support for slicing and selection by strings/index.

This is the status quo, so I think this can be closed.
