### ISSUE TITLE
LazyFrame join removes column specified by right_on

### ISSUE THREAD

**Issue by OneRaynyDay** [pola-rs/polars#3936]
#### What language are you using?

Python

#### Have you tried latest version of polars?

Yep

#### What version of polars are you using?

```
❯ pip freeze | grep polars
polars==0.13.51
```

#### What operating system are you using polars on?

Mac OS X:

```
❯ sw_vers -productVersion
10.15.7
```

#### What language version are you using

```
❯ python
Python 3.9.7 (default, Sep 16 2021, 08:50:36)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.9.7 (default, Sep 16 2021, 08:50:36) \n[Clang 10.0.0 ]'
```

#### Describe your bug.

Join discards right-side column in output.

#### What are the steps to reproduce the behavior?

```
import polars as pl
tbl1 = pl.DataFrame({"x": [1, 2], "y": ["a", "b"]}).lazy()
tbl2 = pl.DataFrame({"w": [2, 4], "z": ["c", "d"]}).lazy()
tbl1.join(tbl2, left_on="x", right_on="w", how="left").fetch(n_rows=10)
```

Yields the result:

```
x | y | z
-- | -- | --
i64 | str | str
1 | "a" | null
2 | "b" | "c"
```

#### What is the expected behavior?

Polars should preserve the column `w` here even though it's being joined on. Suppose we're doing a left join - we would lose the information on whether it actually matched on a `w` or whether there was no match and we got a null `y,w` in the output.

In Trino and friends:

```
trino> SELECT * FROM (VALUES (1,'a'),(2,'b')) "t1" ("x", "y") LEFT JOIN (VALUES (2,'c'),(4,'d')) "t2" ("w", "z") ON t1.x = t2.w;
 x | y |  w   |  z
---+---+------+------
 2 | b |    2 | c
 1 | a | NULL | NULL
(2 rows)
```

**Comment by zundertj** [comment]
Thank you for reporting this issue.

The behavior you are describing is intentional, and has been discussed before. In particular, https://github.com/pola-rs/polars/issues/2377 suggests the addition of an additional output field to indicate which entries are originally from left/right/both. For the time being, I would suggest to duplicate the column by doing the join as follows:

```python
tbl1.join(tbl2.with_column(pl.col("w").alias("w_duplicate"), left_on="x", right_on="w", how="left")
```

It should also be noted that the current implementation of dropping the join column is consistent across lazy and eager modes.
