### ISSUE TITLE
Request: cast unsigned types when doing math on them

### ISSUE THREAD

**Issue by david-cortes** [pola-rs/polars#4103]
This is probably not the result that people would expect:
```python
import polars as pl
df = pl.DataFrame({
    "col1" : ["good", "neutral", "bad", "bad"]
})
(
    df
    .lazy()
    .select([
        (
            (pl.col("col1") == "good").sum()
            - (pl.col("col1") == "bad").sum()
        )
    ])
    .collect()
)
```
<small style="color: rgb(212, 212, 212); font-family: system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">shape: (1, 1)</small>

col1
--
u32
4294967295

**Comment by ritchie46** [comment]
Polars requires you to be type aware on doing arithmetic. It is perfectly valid to do arithmetic on `UInt32` types and they may overflow/underflow. 

```python
>>> np.array([1], np.uint32) - np.array([2], np.uint32)
array([4294967295], dtype=uint32)
```

Maybe we should rethink the output type of summing boolean types though. :thinking:

**Comment by zundertj** [comment]
I think it is fine to have the dtype `u32` for summing bools. It is a count after all, can't be negative.

@david-cortes : I understand some of this is annoying, but Polars is strict about data types as Ritchie says. Let me try to clarify this stance a bit more, as it seems on first instance, that Polars could just do some automatic casting, as you are suggesting.

You start with casting unsigned arithmetic to signed (#4103).  Next person asks for joins to do automatic casting on the keys in case they don't match dtypes (#2815, #2292), then there is someone who wants concat to merge dtypes by default (#3237), followed by another request for X etc etc (you get the point). At the end of this process there are automatic casts everywhere in Polars, with typically lots of edge cases as well. For instance, one could ask for small floats to be upcasted to Float64 on doing arithmetic. But then there is the realization that if the result fits in the small float, the cast should not be done, because otherwise other users run into memory issues when everything becomes Float64 by default. 

Using such a library is great for a quick toy example, and becomes frustrating to use over time in larger code bases as you will sometimes trigger the casts without realizing.  The cost of this is that the user has to be more explicit about data types. Polars should give you all the tools to do that, from casting explicitly, `.cast()`, clear error messages when things are not right (see the join issues I referred to above for where the error message was improved based on the feedback), to showing the data types clearly at the top of the dataframe terminal output.
