### ISSUE TITLE
enable join between i32 and i64 column

### ISSUE THREAD

**Issue by leoliu0** [pola-rs/polars#4289]
Hi! 

It will be great if the i32 and i64 columns from two dataframes can be used as join keys.

**Comment by cbilot** [comment]
#2815

**Comment by ritchie46** [comment]
> #2815

Additional to that. Note that we can do this quite explicitly in the call itself:

```python
df_a.join(df_b, left_on=pl.col("a").cast(pl.Int64), right_on=pl.col("b").cast(pl.Int64))
```

**Comment by leoliu0** [comment]
Thank you. I saw the referenced issue that it won't be fixed. However, I think while it is good to be aware of type difference, such difference is not too relevant to most of the business logics. 

Also, it seems that from_pandas function often return i32 and read straight from CSV returns i64. Is this intended? I often run into this issue when joining df from pandas and other df reading from CSV.

**Comment by ritchie46** [comment]
In `from_pandas` we respect the schema pandas provides. In parsing of csv we don't know up front what the range of integers must be, so we are conservative and choose `i64`.

A feature that might be useful is a `map_dtype` that let's a caller map inferred datatypes to the types they'd like to parse.

**Comment by cbilot** [comment]
Here's something that may help make casting multiple columns easier (and done in parallel).  Let's say that we have this csv file:
```python3
my_csv = """col_int1,col_int2,col_float1,col_float2,col_str,
1,10,100.0,1000.0,"abc"
2,20,200.0,2000.0,"def"
"""
import polars as pl
from io import StringIO
df = pl.read_csv(StringIO(my_csv))
df
```
```
shape: (2, 5)
┌──────────┬──────────┬────────────┬────────────┬─────────┐
│ col_int1 ┆ col_int2 ┆ col_float1 ┆ col_float2 ┆ col_str │
│ ---      ┆ ---      ┆ ---        ┆ ---        ┆ ---     │
│ i64      ┆ i64      ┆ f64        ┆ f64        ┆ str     │
╞══════════╪══════════╪════════════╪════════════╪═════════╡
│ 1        ┆ 10       ┆ 100.0      ┆ 1000.0     ┆ abc     │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2        ┆ 20       ┆ 200.0      ┆ 2000.0     ┆ def     │
└──────────┴──────────┴────────────┴────────────┴─────────┘
```
You can use a datatype inside `polars.col` to cast all columns of a certain type to another type.  For example:
```python3
(
    df
    .with_columns([
        pl.col(pl.Int64).cast(pl.Int32).keep_name(),
        pl.col(pl.Float64).cast(pl.Float32).keep_name(),
    ])
)
```
```
shape: (2, 5)
┌──────────┬──────────┬────────────┬────────────┬─────────┐
│ col_int1 ┆ col_int2 ┆ col_float1 ┆ col_float2 ┆ col_str │
│ ---      ┆ ---      ┆ ---        ┆ ---        ┆ ---     │
│ i32      ┆ i32      ┆ f32        ┆ f32        ┆ str     │
╞══════════╪══════════╪════════════╪════════════╪═════════╡
│ 1        ┆ 10       ┆ 100.0      ┆ 1000.0     ┆ abc     │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2        ┆ 20       ┆ 200.0      ┆ 2000.0     ┆ def     │
└──────────┴──────────┴────────────┴────────────┴─────────┘
```
Since the expressions are inside a `with_columns` context, all four columns will be done in parallel (as long as your CPU has at least four cores).

**Comment by leoliu0** [comment]
Wow! Great workaround! If the team insists on not modifying the behavior. I think I will just close this issue.

**Comment by KronosTheLate** [comment]
I would like to have this re-opened. While I understand that the user should have a concious relationship to their data types, I disagree with the premise that types should match for a join. I would expect any values that are equal under `==` to match in a join, and I would concider the number 4 as an int32 to be equal to the number 4 as a an int64.

That logic can of course be flipped to saying that ints should be a valid basis for matching on floats, but this is a footgun, because floats are rarely excatly equal to whole numbers. Which is a good enough reason to disregard the argument for this case.

But in conclusion: I expect the join to be based on the value, not the bit representation, which means that types of different bit-sizes should match in a join. If nothing else, there should be a "strict" argument that defaults to true, but could be set to false to allow types that represent the same object with varying precision to match gracefully.

**Comment by cmdlineluser** [comment]
There is also a more general "upcast" issue that is open:

- https://github.com/pola-rs/polars/issues/15338
