### ISSUE TITLE
Q: why did you delete df.__setitem__?

### ISSUE THREAD

**Issue by jheok318** [pola-rs/polars#4430]
Hello Polars Team

I have any questions in python

why did you delete df.\__setitem__?

Sometimes df.\__setitem__is very effective

It is also very effective when using simple tests

**Comment by ritchie46** [comment]
Because there is a redundancy with `df.with_column` which is the ideomatic method for adding a column.

It also nudges the user in assigning multiple columns with `df.with_columns`. The latter parallelizes the work.

Odds are high you used `df.__setitem__`, where a `df.with_columns` could have parallelized the work.

**Comment by jheok318** [comment]
thank you 👍
