### ISSUE TITLE
How to read higher size DB from MySQL using Polars and ConnectoX?

### ISSUE THREAD

**Issue by myamullaciencia** [pola-rs/polars#4506]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/73420497/how-to-read-higher-size-db-from-mysql-using-polars-and-connectox

### Question about polars

I have been trying to get a connection done between polars and MySQL.

here is a connection parameter

```
uri="mysql://{0}:{1}@{2}:{3}/{4}".format(
            db_user_name , db_pass_word, db_host, db_port, db_name)
``` 

and query to get some of table data.

```
pl.read_sql('SELECT *FROM bolton_complete_list_rolled_up limit 5',uri)
```

Here on executing why it is giving an indexing output instead of actual text from a table as below.

![image](https://user-images.githubusercontent.com/37251032/185724669-f292dfd6-69ed-4d44-ae4e-d5e37b7f3d06.png)

**Comment by ritchie46** [comment]
I think you should ask this question in the connectorx repo. We simply take the arrow table we get from that lib.

**Comment by cbilot** [comment]
Suggestion: it may be helpful to include some of the output of `pl.show_versions()` when you do.  For example
```
>>> pl.show_versions()
---Version info---
Polars: 0.14.2
Index type: UInt32
Platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.35
Python: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.3
numpy: 1.23.0
fsspec: 2022.5.0
connectorx: 0.2.5
xlsx2csv: 0.7.8
```
In particular, the connectorx team will likely want to know which versions of `pyarrow` and `connectorx` you have installed.

**Comment by cbilot** [comment]
I can replicate this issue - and I may have a temporary workaround so that you can proceed with your analysis until the underlying issue is resolved.

#### Replicating the problem
I started with this data in a csv file in which I purposely chose some non-ASCII text:
```
text,text2,int,float,datetime
abc,䨹䨺䨻,1,1.1,2020-01-01T12:30:00
def,純紕紖,2,2.2,2021-01-01T12:30:00
cĬƐ,鴈鱕鱖,3,3.3,2022-01-01T12:30:00
```
Using the mySQL Table Data Import Wizard, I uploaded the csv file into MySQL.

I then ran the following database query in Polars:
```python3
import polars as pl

# connection parameters redacted
uri = "mysql://{0}:{1}@{2}:{3}/{4}".format(
    db_user_name, db_pass_word, db_host, db_port, db_name
)
uri

df = pl.read_sql("SELECT * FROM temp", uri)
df
```
```
shape: (3, 5)
┌────────────────────┬─────────────────────┬─────┬───────┬─────────────────────┐
│ text               ┆ text2               ┆ int ┆ float ┆ datetime            │
│ ---                ┆ ---                 ┆ --- ┆ ---   ┆ ---                 │
│ list[u8]           ┆ list[u8]            ┆ i64 ┆ f64   ┆ datetime[ns]        │
╞════════════════════╪═════════════════════╪═════╪═══════╪═════════════════════╡
│ [97, 98, 99]       ┆ [228, 168, ... 187] ┆ 1   ┆ 1.1   ┆ 2020-01-01 12:30:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [100, 101, 102]    ┆ [231, 180, ... 150] ┆ 2   ┆ 2.2   ┆ 2021-01-01 12:30:00 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [99, 196, ... 144] ┆ [233, 180, ... 150] ┆ 3   ┆ 3.3   ┆ 2022-01-01 12:30:00 │
└────────────────────┴─────────────────────┴─────┴───────┴─────────────────────┘
```
Non-text columns have the appropriate types, but the text columns appear as lists of uint8, just as in your screen shots

#### Looking more closely
If we look more closely at these lists of uint8, they are essentially byte strings: the encoded sequence of bytes underlying the utf8 encoded strings.

Indeed, if we concatenate and convert the Uint8 in each cell in the `text` column, we can reconstruct the bytes and then decode the utf8 string.
```python3
for vals in df.get_column('text'):
    print(bytes(vals))
    print(bytes(vals).decode('utf8','strict'))
```
```
b'abc'
abc
b'def'
def
b'c\xc4\xac\xc6\x90'
cĬƐ
```
And the same holds for the `text2` column:
```
>>> for vals in df.get_column('text2'):
...     print(bytes(vals))
...     print(bytes(vals).decode('utf8','strict'))
... 
b'\xe4\xa8\xb9\xe4\xa8\xba\xe4\xa8\xbb'
䨹䨺䨻
b'\xe7\xb4\x94\xe7\xb4\x95\xe7\xb4\x96'
純紕紖
b'\xe9\xb4\x88\xe9\xb1\x95\xe9\xb1\x96'
鴈鱕鱖
```

#### Temporary Workaround
The above suggests a temporary workaround, until the `connectorX` issue is resolved.

Try importing a small subset of your data, and then running code like the following:
```python3
uint8_cols = ['text', 'text2']
df.with_column(pl.col(uint8_cols).apply(lambda s: bytes(s).decode('utf8','strict')).keep_name())
```
```
shape: (3, 5)
┌──────┬────────┬─────┬───────┬─────────────────────┐
│ text ┆ text2  ┆ int ┆ float ┆ datetime            │
│ ---  ┆ ---    ┆ --- ┆ ---   ┆ ---                 │
│ str  ┆ str    ┆ i64 ┆ f64   ┆ datetime[ns]        │
╞══════╪════════╪═════╪═══════╪═════════════════════╡
│ abc  ┆ 䨹䨺䨻  ┆ 1   ┆ 1.1   ┆ 2020-01-01 12:30:00 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ def  ┆ 純紕紖  ┆ 2   ┆ 2.2   ┆ 2021-01-01 12:30:00 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ cĬƐ  ┆ 鴈鱕鱖  ┆ 3   ┆ 3.3   ┆ 2022-01-01 12:30:00 │
└──────┴────────┴─────┴───────┴─────────────────────┘
```
The `list[u8]` columns are replaced by unicode characters.

**Note:** This will be **very** slow, especially on large datasets.  (Any time we run Python bytecode using `apply`, expect single-threaded, slow performance.)  

This is certainly not a long-term fix.  My hope is that perhaps you can start your analysis, as we figure out what we need to do to get this resolved (likely with `connectorx`).

**Comment by ghuls** [comment]
What is the default encoding of the mysql table? Probably not utf8, I guess.

**Comment by ghuls** [comment]
Probably your columns have the wrong datatype:

https://github.com/sfu-db/connector-x/blob/55d80e658580685946f9b733a763391bdbdbee9b/connectorx/src/sources/mysql/typesystem.rs#L36-L57

Only `TinyBlob | Blob | MediumBlob | LongBlob` should map to a byte array.

**Comment by cbilot** [comment]
Thanks, @ghuls!  I can verify that that is the answer.

When I alter the database table to convert text columns to `VARCHAR`:
```
ALTER TABLE `myDB`.`temp` 
CHANGE COLUMN `text` `text` VARCHAR(10) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL ,
CHANGE COLUMN `text2` `text2` VARCHAR(10) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL ;
```
And then rerun the database query in Polars, we get strings instead of byte arrays (`list[u8]`).
```python3
pl.read_sql("SELECT * FROM temp", uri)
```
```
>>> pl.read_sql("SELECT * FROM temp", uri)
shape: (3, 5)
┌──────┬────────┬─────┬───────┬─────────────────────┐
│ text ┆ text2  ┆ int ┆ float ┆ datetime            │
│ ---  ┆ ---    ┆ --- ┆ ---   ┆ ---                 │
│ str  ┆ str    ┆ i64 ┆ f64   ┆ datetime[ns]        │
╞══════╪════════╪═════╪═══════╪═════════════════════╡
│ abc  ┆ 䨹䨺䨻  ┆ 1   ┆ 1.1   ┆ 2020-01-01 12:30:00 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ def  ┆ 純紕紖  ┆ 2   ┆ 2.2   ┆ 2021-01-01 12:30:00 │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ cĬƐ  ┆ 鴈鱕鱖  ┆ 3   ┆ 3.3   ┆ 2022-01-01 12:30:00 │
└──────┴────────┴─────┴───────┴─────────────────────┘
```

@myamullaciencia, it looks like you have two options:
1. Convert columns in your database that are `TinyBlob | Blob | MediumBlob | LongBlob` (displayed as type `text` in MySQL Workbench) to `VarChar`.  (You may need to talk to your DB Administrator as to the best approach to do this.)
2. Log a request at the [connectorX GitHub](https://github.com/sfu-db/connector-x) site, requesting support for mapping `TinyBlob | Blob | MediumBlob | LongBlob` to string for MySQL.

**Comment by zundertj** [comment]
I am closing this issue, as the question is about connector-x, not polars.
