### ISSUE TITLE
Sidebar on Python documentation reference needs to be wider (or the names abbreviated)

### ISSUE THREAD

**Issue by indigoviolet** [pola-rs/polars#4591]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

![image](https://user-images.githubusercontent.com/114010/187019299-7677b726-13c8-4dd9-a973-dfafd6bfcecd.png)

### Reproducible Example

```python
Not relevant
```

### Expected Behavior

Ideally: abbreviations like

![image](https://user-images.githubusercontent.com/114010/187019329-5d8f2cc4-bb68-4ddb-8b31-0ad03b9847fc.png)

or someway to make [this page](https://pola-rs.github.io/polars/py-polars/html/reference/series.html#lists), which is way more useful, replace the sidebar.

### Installed Versions

<details>
not relevant

</details>

**Comment by stinodego** [comment]
I think the best fix here would be to actually shorten the names -- not include the full module path for things like NameSpaces that people do not interact with directly anyway.

For example, instead of `polars.internals.expr.datetime.ExprDateTimeNameSpace.cast_time_unit`, it would be more clear to have `polars.Expr.dt.cast_time_unit`.

pyspark even does away with the sidebar pretty much entirely:
https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.filter.html

Related issue: #4156

**Comment by indigoviolet** [comment]
#4156 does a much better job of calling these issues out. I'll close in favor of that.
