### ISSUE TITLE
`apply` on DataFrame causes column names to change

### ISSUE THREAD

**Issue by pyrito** [pola-rs/polars#4851]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

Perhaps this is intended by design (but I couldn't find an existing issue on this), but an `apply` call on a polars DataFrame changes the column names.

### Reproducible Example

```python
import polars as pl
data = {
    "A": [1,2,3,4,5],
    "fruits": ["banana", "banana", "apple", "tomato", "apple"],
    "B" : [5,4,3,2,1],
    "cars": ["beetle", "audi", "beetle", "beetle", "toyota"],
 }
df = pl.DataFrame(data)
df1 = df.apply(lambda x: x)
assert df.columns == df1.columns
```

### Expected Behavior

Assertion should not fail.

### Installed Versions

<details>
---Version info---
Polars: 0.14.11
Index type: UInt32
Platform: macOS-12.2.1-x86_64-i386-64bit
Python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:27:05) 
[Clang 12.0.1 ]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.4
numpy: 1.22.4
fsspec: 2022.7.1
connectorx: 0.3.1_alpha.1
xlsx2csv: <not installed>
</details>

**Comment by alexander-beedie** [comment]
There is no mapping from a DataFrame-level `apply` back to the original column names, as the function could be doing _anything_ (reordering columns, omitting them, adding new ones, etc). As the function executes in Python, entirely outside of polars, the end-state column names cannot be determined. For instance:
```python
# omit a column and reorder the rest
df1 = df.apply( lambda x: (x[2],x[0],x[1]) )
```
Bit easier to see that the names cannot be inferred in this case. I'd _strongly_ advise against habitually using `apply` though, if you can possibly avoid it, as you'll be giving up all the performance/parallelisation available from the core engine ;)

**Comment by pyrito** [comment]
@alexander-beedie thanks for the response! I see, that makes sense. I assume it's probably hard to keep track of the names because there's no Index that is used (I come from the pandas world)? If I wanted to do a parallel apply, how would I go about doing that?

**Comment by alexander-beedie** [comment]
>  I assume it's probably hard to keep track of the names because there's no Index that is used

Nothing to do with indexes in this case - the function passed to `apply` is simply a black-box; tuples go in, tuples come out, and there is zero capability to infer anything about what the function did in between. 

The difference between pandas/polars here is that pandas broadcasts the function over individual frame _columns_ by default, whereas polars broadcasts over the frame's _rows_ (a bit like calling the pandas func with `axis=1`, except you are still able to return multiple cols instead of being forced to consolidate down to Series). So, as pandas is broadcasting the function over individual columns by default (and therefore _can't_ return more/less columns), it keeps the same column names.

> If I wanted to do a parallel apply, how would I go about doing that?

By using native Polars expressions (and not using `apply` ;) 

You can't do it with a Python function, because you are bound by the GIL. Hence the advice not use `apply` unless it is basically _impossible_ to construct your transform using native Polars expressions.

The [docs](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.apply.html) elaborate a bit further:

> Implementing logic using `apply` is generally slower and more memory intensive than implementing the same logic using the [polars] `expression` API because:
> 
> - with .apply the logic is implemented in **Python**, but with a polars expression the logic and execution is implemented in **Rust**.
> - with .apply the DataFrame is materialized in memory.
> - [polars] expressions can be parallelised.
> - [polars] expressions can be optimised.

**Comment by pyrito** [comment]
I appreciate the detailed explanation. I understand that `apply` calls are black-boxes - this is just the situation when dealing with UDFs in general since we allow users to possibly shoot themselves in the foot. I agree with most of your points that you've made here. I think in general preserving column names in pandas applies makes sense since the default is `axis=0`, but even with `axis=1`(row-wise, similar to polars) pandas makes the effort to preserving the column names. Take the following example:
```python
import pandas

df = pandas.DataFrame({'a' : ['a','b','c','d']})
In [58]: df.apply(lambda row: row.iloc[[0, 0]], axis=1)
Out[58]: 
   a  a
0  a  a
1  b  b
2  c  c
3  d  d
```
Furthermore, is there a reason why polars doesn't allow users to apply functions along the columns or rows explicitly? Is this one of those things where there is a better, parallelized version using native Polars expressions?

**Comment by mvashishtha** [comment]
> The difference between pandas/polars here is that pandas broadcasts the function over individual frame columns by default, whereas polars broadcasts over the frame's rows (a bit like calling the pandas func with axis=1 [[ref](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html)], except you are still able to return multiple cols instead of being forced to consolidate down to Series).

@alexander-beedie It's incorrect that pandas row-wise applies have to return a single column, and that the result is always a series. Each function can return any number of columns, e.g.

```python
import pandas as pd

df = pd.DataFrame([[1, 2], [3, 4]])
# returns 2x0 dataframe
print(df.apply(lambda row: row.loc[[]], axis=1))
# returns 2x2 dataframe
print(df.apply(lambda row: row, axis=1))
# returns 2x3 dataframe
print(df.apply(lambda row: row.loc[[0, 0, 0]], axis=1))
```

The same applies to column-wise applies.

But that's off topic. It seems that the conclusions for the original issue are:

1) stop using `apply` if you can avoid it
2) because the result of the user-defined function (UDF) is just a tuple and has no column labels, there is no meaningful way to associate the columns of the resulting dataframe with the original column labels. In the original example, even though the input and output both have 4 columns, it's unreasonable to assume that each UDF result represents a row of values for the 4 columns in their original order.

So there's nothing left to be done.

**Comment by alexander-beedie** [comment]
Thanks for the pandas example; your summary is pretty accurate, with one small tweak - there's nothing to do in this case, because the behaviour/feature you want exists, it's just in `expr.apply` rather than `frame.apply` ;)

This does make me think the docs around polars' `DataFrame.apply` can be improved though, as I imagine other pandas users may have similar thoughts. I'll make a PR with some additional clarification  and a "See Also" section that points to `expr.apply` and `expr.map`, with some additional explanations about the behaviour of each. Hope this all helps.
