### ISSUE TITLE
Unintuitive boolean behavior

### ISSUE THREAD

**Issue by marsupialtail** [pola-rs/polars#4926]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

The "and" operator between polars Boolean series doesn't produce expected behavior. This is caused by the fact that this expression doesn't throw an error, despite the intended behavior being (b['a'] == 1) | (b['b'] == 4). This could cause subtle runtime errors with unexpected results.

### Reproducible Example

```python
'''
import polars
import pandas as pd
b = polars.from_pandas(a)
a = pd.DataFrame({"a":["1","2","1"], "b":["3","4","3"]})
b = polars.from_pandas(a)
b['a'] == 1 and b['b'] == 4
'''


shape: (3,)
Series: 'b' [bool]
[
	false
	true
	false
]
```

### Expected Behavior

It should be false, false, false

### Installed Versions

<details>
0.13.54
</details>

**Comment by alexander-beedie** [comment]
This isn't a bug - you're just using the wrong "and" operator  ;)

Python's logical "and" cannot be overloaded, it's fundamental, which is why all DSL/Frame/etc libraries overload the binary "&" instead. This is what you actually want (also, note the parentheses, which you need due to operator precedence):

```python
(b['a'] == 1) & (b['b'] == 4)

# Series: 'a' [bool]
# [
# 	false
# 	false
# 	false
# ]
```
When you use "and", if the l.h.s. is implicitly True (eg: non-zero, not None, etc) then the result of the expression is just the r.h.s., returned as-is: in this case `b['b'] == 4`.
