### ISSUE TITLE
mean encoding, polars vs pandas

### ISSUE THREAD

**Issue by wiamadaya** [pola-rs/polars#5037]
### Research

- [X] I have searched the above polars tags on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/73903607/mean-encoding-polars-vs-pandas

### Question about polars

I'm trying to optimize pandas mean encoding calculation using polars, however the performance turns out to be slower, is this the correct way how to perform mean encoding in polars?

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10069612 entries, 0 to 10069611
Data columns (total 26 columns):
dtypes: float64(1), int16(2), int8(15), object(8)
memory usage: 873.9+ MB


%timeit df["product_avg_sales"] = df.groupby("product")["sales"].transform("mean")
219 ms ± 7.95 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


df_polar = pl.from_pandas(df)
%timeit df_polar.with_columns(pl.col('sales').mean().over(['product']).alias('product_avg_sales'))
1.19 s ± 24.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by ritchie46** [comment]
Can you add an example? Hard to tell on just numbers.

**Comment by mcrumiller** [comment]
Here's an example that uses a dataframe with the same dtype makeup as OP (with random numbers). I'm assuming that `"sales"` is one of the `int16` columns and that `"product"` is one of the `object` columns.

```python
import numpy as np
import pandas as pd
import polars as pl
import time

# RangeIndex: 10069612 entries, 0 to 10069611
# Data columns (total 26 columns):
# dtypes: float64(1), int16(2), int8(15), object(8)
N_rows = 10069612
N_float = 1
N_int16 = 2
N_int8 = 15
N_obj = 8

df = pd.concat(
    (
        # float
        pd.DataFrame(
            data=np.random.random_sample((N_rows, 1)),
            columns = [chr(x) for x in range(65, N_float+65)]
        ),

        # int8
        pd.DataFrame(
            data=np.random.randint(np.iinfo(np.int8).min, np.iinfo(np.int8).max, (N_rows, N_int8), dtype=np.int8),
            columns = [chr(x) for x in range(65+N_float, 65+N_float+N_int8)]
        ),

        # int16
        pd.DataFrame(
            data=np.random.randint(np.iinfo(np.int16).min, np.iinfo(np.int16).max, (N_rows, N_int16), dtype=np.int16),
            columns = [chr(x) for x in range(65+N_float+N_int8, 65+N_float+N_int8+N_int16)]
        ),

        # obj
        pd.DataFrame(
            data=np.random.randint(np.iinfo(np.uint8).min, np.iinfo(np.uint8).max, (N_rows, N_obj)).astype(str),
            columns = [chr(x) for x in range(65+N_float+N_int8+N_int16, 65+N_float+N_int8+N_int16+N_obj)]
        )
    ),
    axis=1)

df = df.rename(columns={
    "Q": "sales",
    "S": "product",
})

# time Pandas
start = time.process_time()
for i in range(10):
    df.groupby("product")["sales"].transform("mean")

stop = (start-time.process_time())/10
pd_time = (time.process_time()-start)/10
print(f"Pandas avg: {pd_time:0.1f}s")

# convert to polars
df = pl.from_pandas(df)

# time polars
start = time.process_time()
for i in range(10):
    df.with_columns(pl.col('sales').mean().over(['product']).alias('product_avg_sales'))

stop = (start-time.process_time())/10
pl_time = (time.process_time()-start)/10
print(f"Polars avg: {pl_time:0.1f}s")
```

#### Output
```
Pandas avg: 1.2s
Polars avg: 1.8s
```

**Comment by mcrumiller** [comment]
Here is a much more minimal example without the extra columns. Change `N_rows` to suit your machine accordingly.

```python
import numpy as np
import pandas as pd
import polars as pl
import time

N_rows = int(1e8) # 100M rows

df = pd.DataFrame({
    "key": np.random.randint(0, 100, N_rows).astype(str),
    "value": np.random.randint(np.iinfo(np.int16).min, np.iinfo(np.int16).max, N_rows, dtype=np.int16)
})

# time Pandas
start = time.process_time()
for i in range(10):
    df.groupby("key")["value"].transform("mean")
stop = time.process_time()
print(f"Pandas avg: {(stop-start)/10:0.2f}s")

# time polars
df = pl.from_pandas(df)
start = time.process_time()
for i in range(10):
    df.with_column(pl.col("value").mean().over(["key"]).alias("total"))
stop = time.process_time()
print(f"Polars avg: {(stop-start)/10:0.2f}s")
```

```
Pandas avg: 5.65s
Polars avg: 18.10s
```

**Comment by cbilot** [comment]
Let's see if I can help.  A couple of things.

#### `perf_counter` versus `process_time`
I believe the proper metric we want here is `perf_counter` (wall-clock/elapsed time), not `process_time` (sum of system plus user time):

From the Python docs: [`perf_counter`](https://docs.python.org/3/library/time.html#time.perf_counter):
> Return the value (in fractional seconds) of a performance counter, i.e. a clock with the highest available resolution to measure a short duration. It does include time elapsed during sleep and is system-wide. The reference point of the returned value is undefined, so that only the difference between the results of two calls is valid.

versus [`process_time`](https://docs.python.org/3/library/time.html#time.process_time):
> Return the value (in fractional seconds) of the sum of the system and user CPU time of the current process. It does not include time elapsed during sleep. It is process-wide by definition. The reference point of the returned value is undefined, so that only the difference between the results of two calls is valid.

The difference is important.  For example, I have a 32-core Threadripper Pro.  If a task occupies all 32 cores for 1 sec, the `perf_counter` would be 1 second; the `process_time` would be 32 seconds.

Let's see the difference on the example above.  Using `perf_counter` rather than `process_time`:
```
>>> # time Pandas
>>> start = time.perf_counter()
>>> for i in range(10):
...     _ = df.groupby("key")["value"].transform("mean")
... 
>>> print(f"Pandas avg: {(time.perf_counter()-start)/10:0.2f}s")
Pandas avg: 0.62s


>>> # time polars
>>> df = pl.from_pandas(df)
>>> start = time.perf_counter()
>>> for i in range(10):
...     _ = df.with_column(pl.col("value").mean().over(["key"]).alias("total"))
... 
>>> print(f"Polars avg: {(time.perf_counter()-start)/10:0.2f}s")
Polars avg: 0.20s
```
From a wall-clock/elapsed-time standpoint, Polars is faster.

However, reporting `process_time` yields:
```
>>> # time Pandas
>>> start = time.process_time()
>>> for i in range(10):
...     _ = df.groupby("key")["value"].transform("mean")
... 
>>> print(f"Pandas avg: {(time.process_time()-start)/10:0.2f}s")
Pandas avg: 0.62s


>>> # time polars
>>> df = pl.from_pandas(df)
>>> start = time.process_time()
>>> for i in range(10):
...     _ = df.with_column(pl.col("value").mean().over(["key"]).alias("total"))
... 
>>> print(f"Polars avg: {(time.process_time()-start)/10:0.2f}s")
Polars avg: 4.65s
```
Polars uses more user+system CPU to parallelize the task across processors.  But from the standpoint of most users, wall-clock/elapsed time is the important metric.  (Indeed, why else would I have a Threadripper Pro -- except to parallelize tasks to speed them up.)

#### Micro-benchmarking
Micro-benchmarking (running tiny atomic-level tasks in a loop) is appropriate for some tasks (e.g., system functions).  However, it's not really a good metric for dataset benchmarks.  (Indeed, if mere milliseconds on a query matters to you -- then why are you using Python in the first place, and not something like Rust?)

Let's increase the size of our benchmark to something more than a fraction of a second.  Let's increase the size of `N_rows` to 100 million.  That will make things more clear.
```
>>> N_rows = 100_000_000
>>> df = pd.DataFrame({
...     "key": np.random.randint(0, 1000, N_rows).astype(str),
...     "value": np.random.randint(-32768, 32767, N_rows, dtype=np.int16)
... 
... })
>>> # time Pandas
>>> start = time.perf_counter()
>>> for i in range(10):
...     _ = df.groupby("key")["value"].transform("mean")
... 
>>> print(f"Pandas avg: {(time.perf_counter()-start)/10:0.2f}s")
Pandas avg: 6.08s


>>> # time polars
>>> df = pl.from_pandas(df)
>>> start = time.perf_counter()
>>> for i in range(10):
...     _ = df.with_column(pl.col("value").mean().over(["key"]).alias("total"))
... 
>>> print(f"Polars avg: {(time.perf_counter()-start)/10:0.2f}s")
Polars avg: 2.20s
```
Clearly, Polars is performing much better.

#### Other Notes
In benchmarking, one should clearly state the computing platform used.  This allows a reader to understand whether the benchmark is applicable to their computing platform.

For example, my machine is a 32-core Threadripper Pro with 512 GB of RAM.  It's important to state that.  My machine will obviously run tasks differently than a laptop.  For tasks that can be parallelized, a Threadripper Pro will perform very well.  For tasks that are single-threaded, it might be **slower** than someone with a high-performance gaming rig.

**Comment by matteosantama** [comment]
@cbilot thanks for the breakdown, that was really informative! With regards to the OP, from what I can [find](https://docs.python.org/3/library/timeit.html#timeit.default_timer) `%timeit` does use `perf_counter`. 

Perhaps @wiamadaya can share the datatypes of `product` and `sales`. That would help us better replicate the issue.

**Comment by stinodego** [comment]
I am closing this as stale. Feel free to re-open if you feel like your question hasn't been answered adequately.
