### ISSUE TITLE
postgres connection

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#52]

**Comment by nevi-me** [comment]
Hi Ritchie, I've done some work at https://github.com/nevi-me/rust-dataframe/tree/master/src/io/sql/postgres, which might be useful as a starting point. The binary reader and writer work, but I haven't benchmarked them nor worked on improving allocation (I do a lot of allocations).

`rust-dataframe` is more exploratory, and given my sporadically available time (I'm interestingly mostly an accountant), I often prefer working on Arrow instead, as that time yields more benefit for more people.
The last time I was working on `rust-dataframe`, I was trying to generalise an API for database access, so that one could support more SQL engines (ideally at runtime). I haven't pushed those changes though.

If you'd be interested, what we could maybe do is work on putting together the above in a separate repo (I had https://github.com/nevi-me/rust-arrow-sql) or maybe in Arrow (as there'd def be a lot of people interested in this).

I'm also pinging @andygrove @paddyhoran for visibility

**Comment by ritchie46** [comment]
Hi Wakahisa, I think that is definitely useful. It seems like a good starting point. Shall I merge that in, and mention your codebase as source?

I am glad you reach out, as I think Apache Arrow and a DataFrame lib implementation have a lot of functionality that could benefit from each other. I've seen your guys issue tracker in Jira, but to be honest, it is pretty daunting to me. Do you also have a chat or something where you discuss things?

**Comment by nevi-me** [comment]
> Shall I merge that in, and mention your codebase as source?

You can, if you don't mind changing to an external implementation in future. The main benefit of extracting functionality from individual codebases and sharing it, is that we can support more use-cases, and in so doing get more people looking at the code.

> as I think Apache Arrow and a DataFrame lib implementation have a lot of functionality that could benefit from each other

DataFusion depends on Arrow, and much of the compute functionality in DF comes from Arrow, or can be moved to Arrow. Being developed in the same repo has the added benefit of keeping both in sync, and someone interested in DataFusion ends up getting Arrow exposure by extension.

In terms of JIRA, I can understand as there's lots of components involved. Perhaps if you look at planned functionality in Arrow's Rust implementation, you could find something that you'd need, or that you'd be able to contribute upstream to Arrow. Here's a JIRA filter showing open/unresolved Rust Arrow + DF issues (https://issues.apache.org/jira/browse/ARROW-10030?jql=project%20%3D%20ARROW%20AND%20status%20%3D%20Open%20AND%20component%20in%20(Rust%2C%20%22Rust%20-%20DataFusion%22)).

Please feel free to ask questions, I can also go through some of your codebase and open issues to suggest what you could do/use. For example, we've landed some very impressive performance improvements to the `arrow::compute` module, which you'll notice in your benchmark when the `2.0.0` release comes out.

**Comment by ritchie46** [comment]
> For example, we've landed some very impressive performance improvements to the arrow::compute module, which you'll notice in your benchmark when the 2.0.0 release comes out.

Ah, sweet. You've just landed 1.0. Is the next arrow release 2.0? What is Arrow's release cycle btw? Is it once every `n` weeks, or will there be released once some milestones are implemented?

**Comment by nevi-me** [comment]
Sorry, I forgot to reply to this. There's no fixed cycle, but the project tries to release every 2-3 months.
The different language implementations are released in sync, the version mainly signifies the format version, and some implementations (like Rust) can sometimes be behind.

For example, the IPC IO in Rust is only *compliant* to version 0.15.0, so newer things like buffer compression aren't yet impemented.

**Comment by nevi-me** [comment]
Hi Ritchie, here's the draft PR adding PostgreSQL support to Arrow (proposed as a separate crate) https://github.com/apache/arrow/pull/8731

**Comment by ritchie46** [comment]
Great news. I saw your RFC. I think that an implementation in Arrow is also more suitable than in Polars.

**Comment by ritchie46** [comment]
Added with connector-x

**Comment by benmaier** [comment]
is there a `to_sql` planned, or is there an easy way to upload to postgres already?

**Comment by ritchie46** [comment]
There is a section on this in the user guide: https://pola-rs.github.io/polars-book/user-guide/howcani/io/postgres.html

**Comment by benmaier** [comment]
thanks!
