### ISSUE TITLE
append row to datafrme?

### ISSUE THREAD

**Issue by kkonghao** [pola-rs/polars#5277]
### Problem description

Hi thanks for your contribution to Polars and I have been watching this project for a while. 
When I read Polars code row.rs, I found Polars should have a method append row to dataframe (empty or not empty dataframe). For in most real time scenes almost all data are row format,though append a row to dataframe which performance is poor compared with series.In python Pandas we can use different method to append a row to an exist dataframe.

**Comment by mcrumiller** [comment]
You have two choices:

1. Gather your rows into a list:

    ```python
    rows = []
    for _ in data:
        rows.append(get_new_row(...))
    df = pl.DataFrame(rows, columns=[('a', pl.UInt8), ('b', pl.Date), ...], orient="row")
    ```

2. Use `vstack`. You'll probably want to do a `rechunk` every once in a while

    ```python
    df = pl.DataFrame(...make an empty dataframe)
    for idx in range(N):
        if(mod(idx, 1e4)==0):
            df = df.rechunk() # make contiguous
        row = pl.DataFrame(get_new_row(...), *args, **kwargs)
        df.vstack(row)
    ```

**Comment by zundertj** [comment]
@kkonghao : we have the option to concat individual rows as shown by Mcrumiller. 

You also mention performance, and that it is poor. As Polars is based on Arrow, which is a columnar Arrow format, it will not be the fastest solution possible. However, you also mention Pandas, which is also columnar as far as I know. Two questions I have on that:

1) Your question, and this is my interpretation of it, suggests that Pandas is sufficiently fast for your use case. Have you benchmarked the Polars solution versus a Pandas soltuion?  I would encourage you to do the benchmarking, and not be put off by the warning that performance is not optimal. Polars will not be the fastest possible solution in this scenario, but if it is sufficiently fast, that may be enough in your use case.
2.) Which method in Pandas are you referring to? Note that `DataFrame.append())` [has been deprecated since Pandas 1.4.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append), and that the alternative suggested is [pd.concat](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html#pandas.concat).
