### ISSUE TITLE
Fail to install on macOS ARM64

### ISSUE THREAD

**Issue by tisonkun** [pola-rs/polars#5407]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://www.npmjs.com/package/nodejs-polars) of Polars.

### Issue description

```
$ yarn add nodejs-polars

➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: nodejs-polars-android-arm64@npm:0.6.0: No candidates found
    at ce (/Users/chenzili/.cache/node/corepack/yarn/3.2.2/yarn.js:439:7864)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async go (/Users/chenzili/.cache/node/corepack/yarn/3.2.2/yarn.js:390:10446)
➤ YN0000: └ Completed in 1s 159ms
➤ YN0000: Failed with errors in 1s 161ms
```

### Reproducible example

```javascript
yarn add nodejs-polars
```

### Expected behavior

Successfully install.

**Comment by tim-habitat** [comment]
Similar issue when trying to install with `poetry` on an x_86 mac - package tries to compile locally but fails. 
However, when downloading using `pip` it "just works".
This issue is from version `0.14.25` - previous versions worked fine with `poetry`


I believe the compiling error is `error: linking with `cc` failed: exit status: 1`

**Comment by ritchie46** [comment]
Can you ope this issue here? https://github.com/pola-rs/nodejs-polars

**Comment by tisonkun** [comment]
@ritchie46 as https://github.com/pola-rs/nodejs-polars/issues/16.
