### ISSUE TITLE
Regression - Arithmetic operations on categoricals lead to Panic Exceptions - used to give null

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars#5437]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

As late as 0.14.24 arithmetic operations on a categorical column gave a null. With 0.14.26 it gives a PanicException. I'd say the former behaviour is preferable. 

### Reproducible example

```python
import polars as pl
df = (
    pl.DataFrame(
            {"strings": ["c","b","a","c"], "values": [0, 1, 2, 3]}
    )
    .with_column(
        pl.col("strings").cast(pl.Categorical).alias("cats")
    )
    .select(
        pl.all().max()
    )
)
```

### Expected behavior

Give a `null` instead

### Installed versions

```
---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Linux-5.10.104-linuxkit-x86_64-with-glibc2.28
Python: 3.10.1 (main, Dec 21 2021, 09:50:13) [GCC 8.3.0]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.5.1
numpy: 1.23.4
fsspec: 2022.10.0
connectorx: 0.3.0
xlsx2csv: 0.8
matplotlib: 3.6.1
```

**Comment by ritchie46** [comment]
I think it should give an error. Computing the max of categoricals doesn't make sense.

**Comment by braaannigan** [comment]
> I think it should give an error. Computing the max of categoricals doesn't make sense.

Won't this by annoying if you do `df.describe()` and have to start filtering out categoricals?

**Comment by mcrumiller** [comment]
@braaannigan this should be a separate issue whereby `df.describe()` should be updated to exclude categorical columns from the min/max.

I understand that categoricals have you no well-defined ordering for the end-user, but since categoricals must be strings, which have a well-defined ordering, wouldn't the API benefit from an `ordered=True` categorical parameter that maintains lexical ordering of the underlying categories? This would add a bit of overhead when joining categories, but I can see some legitimate use cases, i.e. allowing `sort()`, `min()`, `max()` etc.

**Comment by alexander-beedie** [comment]
> wouldn't the API benefit from an `ordered=True` categorical parameter that maintains lexical ordering of the underlying categories? 

Already possible:
```python
df.with_column(
    pl.col("colx").cast(pl.Categorical).cat.set_ordering("lexical") 
)
```

**Comment by mcrumiller** [comment]
That makes sense. In that case, if categoricals always have an explicit ordering set, why does computing the max and min of categoricals not make sense? Especially if `sort` is defined.

**Comment by alexander-beedie** [comment]
> why does computing the max and min of categoricals not make sense?

Probably because Categoricals aren't lexically-ordered by _default_, and how they work really is an internal implementation detail rather than a public attribute of the type.

(Having said all that I've actually mandated lexically-ordered categoricals internally within our master data APIs across all backends that support them because it causes too much avoidable confusion for users when they look like strings, can -mostly- be treated as strings, but then don't _behave_ like strings when you sort them).

**Comment by slonik-az** [comment]
There are two types of categorical variables -- ordinal (that have ordering) and nominal (no ordering whatsoever). In polars there are two "natural" ordering schemes for categoricals: (1) lexicographical or (2) by physical index (an `int`) that maps the categorical value. Ordering by index corresponds to insertion order. With global StringCache one can "pre-initialize" categoricals to be ordered by index in whatever way one wants it to be.
