### ISSUE TITLE
use_pyarrow=True does not work with multiple files with glob*

### ISSUE THREAD

**Issue by franz101** [pola-rs/polars#5450]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When running:
df = pl.read_parquet("/data/*.parquet")
I have no issues
When running:
df = pl.read_parquet("/data/*.parquet",use_pyarrow=True  )
It will try to look for the file locally

### Reproducible example

```python
pl.read_parquet("/data/*.parquet",use_pyarrow=True  )
raises
FileNotFoundError: /data/*.parquet
```

### Expected behavior

Use glob under the hood

### Installed versions

---Version info---
Polars: 0.14.26
Index type: UInt32
Platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
Python: 3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
---Optional dependencies---
pyarrow: 6.0.1
pandas: 1.3.5
numpy: 1.21.6
fsspec: 2022.10.0
connectorx: 0.3.1
xlsx2csv: 0.8
matplotlib: 3.2.2

**Comment by zundertj** [comment]
`read_parquet` with `use_pyarrow=True` is a thin wrapper around [pyarrow.parquet.read_table](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_table.html). It does not support passing a glob pattern indeed, but you can give it a directory rather than a specific file name, which would achieve the same if there are only `.parquet` files in your directory. If that does not work, you could yourself wrap glob parsing `pl.read_parquet(..., use_pyarrow=True)`, concatenating the data coming out of the individual files.

I don't think that functionality belongs in Polars though, as it would not really be PyArrow anymore, but a hybrid.
