### ISSUE TITLE
window function with shift gives wrong result

### ISSUE THREAD

**Issue by liu-hanwen** [pola-rs/polars#5499]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

For a not sorted dataframe, using 'shift' on a column with 'sort_by' and 'over' to produce a groupby + sort shift gives unexpected result.

`df.with_column(pl.col('close_price').shift(1).sort_by('ts').over('uid').alias('last_close_price'))`

output:
| ts | uid | close_price | last_close_price|
| --- | --- | --- | --- |
| 2022-11-01 00:00:00 | 79869211846408 | 11.52181    | null             |
| 2022-11-03 00:00:00 | 79869211846408 | 11.76181    | 11.76181         |
| 2022-11-02 00:00:00 | 79869211846408 | 12.02181    | 11.52181         |
| 2022-11-03 00:00:00 | 54047868453564 | 1184.05335  | 1184.05335       |
| 2022-11-01 00:00:00 | 54047868453564 | 1214.96205  | 1214.96205       |
| 2022-11-02 00:00:00 | 54047868453564 | 1231.44669  | null             |

### Reproducible example

```python
import numpy as np
import polars as pl

data = np.array([[1.66726080e+15, 7.98692118e+13, 1.15218100e+01],
       [1.66743360e+15, 7.98692118e+13, 1.17618100e+01],
       [1.66734720e+15, 7.98692118e+13, 1.20218100e+01],
       [1.66743360e+15, 5.40478685e+13, 1.18405335e+03],
       [1.66726080e+15, 5.40478685e+13, 1.21496205e+03],
       [1.66734720e+15, 5.40478685e+13, 1.23144669e+03]])
df = pl.from_numpy(data, columns=['ts', 'uid', 'close_price'])\
       .with_columns([
              pl.col('ts').cast(pl.Datetime),
              pl.col('uid').cast(pl.UInt64),
              pl.col('close_price').cast(pl.Float64),
       ])

result = df.with_column(pl.col('close_price').shift(1).sort_by('ts').over('uid').alias('last_close_price'))
print(result)
```

### Expected behavior

| ts | uid | close_price | last_close_price|
| --- | --- | --- | --- |
| 2022-11-01 00:00:00 | 79869211846408 | 11.52181    | null             |
| 2022-11-03 00:00:00 | 79869211846408 | 11.76181    | 12.02181         |
| 2022-11-02 00:00:00 | 79869211846408 | 12.02181    | 11.52181         |
| 2022-11-03 00:00:00 | 54047868453564 | 1184.05335  | 1231.44669       |
| 2022-11-01 00:00:00 | 54047868453564 | 1214.96205  | null       |
| 2022-11-02 00:00:00 | 54047868453564 | 1231.44669  | 1214.96205 |

### Installed versions

<details>

```
---Version info---
Polars: 0.14.10
Index type: UInt32
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
---Optional dependencies---
pyarrow: 8.0.0
pandas: 1.4.3
numpy: 1.19.5
fsspec: 2022.5.0
connectorx: 0.3.0
xlsx2csv: <not installed>
pytz: 2022.1
None
```

</details>

**Comment by deanm0000** [comment]
I don't think this is a bug.  I think you're expecting the `sort_by` to do something that it isn't doing.  You're doing the `sort_by` on a single column rather than the whole `df`.

If you do:

`df.with_row_count('origorder').sort('ts').with_column(pl.col('close_price').shift(1).over('uid').alias('last_close_price')).sort('origorder').select(pl.exclude('origorder'))` then you get your expected output.

Essentially what this does is first it creates a column to preserve the original order, then it sorts the whole `df` by the `ts` column.  Once the df is sorted by the thing you want to shift then it does that shift.  Afterwards, it just puts the df back in the original order and then excludes the `origorder` helper column.
