### ISSUE TITLE
Add Set Operations (union, intersection, difference)

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#5559]
### Problem description

I have recently been working with data of several million articles from different data sources. I had to analyze which articles are available in total, which are available in both sources and which are only available in certain sources (all typical set operations).
In pandas this is quite easy, because these operations are available on the index (of Series and DataFrame).

```python
import pandas as pd

s1 = pd.Index([1, 2, 3, 4, 5])
s2 = pd.Index([3, 4, 5, 6, 7])

s1.union(s2), s1.intersection(s2), s1.difference(s2), s2.difference(s1)
```

Moving to polars I ended up with two solutions which work fine but are not as good in my opinion:
```python
import polars as pl

s1 = pl.Series([1, 2, 3, 4, 5])
s2 = pl.Series([3, 4, 5, 6, 7])

# use python set
set1 = set(s1)
set2 = set(s2)
set1.union(set2), set1.intersection(set2), set1.difference(set2), set2.difference(set1)

# using polars 
pl.concat([s1, s2]).unique()
s1.filter(s1.is_in(s2))
s1.filter(~s1.is_in(s2))
```

I think an implementation would have the benefit of creating a **clear intent** which to me is super important when reading/writing code.
"union of a and b" (clear intent) VS "concatenate a and b and give me the unique values" or
"intersection of a and b" VS "filter a where a values are in b"

At first, the implementation could also look like above. In the future, optimized algorithms could be used depending on the demand.

**Comment by zundertj** [comment]
> I have recently been working with data of several million articles from different data sources. I had to analyze which articles are available in total, which are available in both sources and which are only available in certain sources (all typical set operations).

In which form does this data come? The reason I ask is because these operations are in Polars very simple on a dataframe (`pl.col("s1").is_in(pl.col("s2"))`), your second solution. However, you introduce your case with Pandas indices, suggesting the data is completely separate. Polars doesn't have indices, and as you have found out, Polars `Series` have limited functionality, in particular for doing operations on other `Series`. Conversions to sets (your first solution) would work. I would like to understand a bit better the problem, so feel free to add some more realistic snippets. Not saying your request is not valid, but operating on individual series is a sign to me that there are probably better ways to tackle the problem.

**Comment by ritchie46** [comment]
Sounds like you want semi/anti joins. Have you tried:

```python
df.unique().join(df2, how="semi")
```

**Comment by JulianCologne** [comment]
Thanks for your help!
I often still think in the "pandas-way" and not in the "polars-way" which sometimes quite different.
It is not 100% perfect but `join` with the different `how=...` parameters works quite good. ;)
