### ISSUE TITLE
Add DataFrame.write_excel

### ISSUE THREAD

**Issue by rth** [pola-rs/polars#5568]
### Problem description

The read_excel file was added in https://github.com/pola-rs/polars/pull/3567 and it would be nice if there was also a `DataFrame.write_excel` function, maybe using [xlsxwriter-rs](https://github.com/informationsea/xlsxwriter-rs).

**Comment by dominikpeter** [comment]
We have this requirement as well. Currently, we convert the Polars dataframe to Pandas and export it from there. Would be great, of course, if we didn't have to take this detour.

**Comment by jmcnamara** [comment]
Another option would be to use the pure rust [rust_xlsxwriter](https://github.com/jmcnamara/rust_xlsxwriter) library. The [rust_xlsxwriter roadmap](https://github.com/jmcnamara/rust_xlsxwriter/issues/1) explains the rationale and the current features.

I wrote the initial `xlsxwriter` [integration to Pandas](https://xlsxwriter.readthedocs.io/working_with_pandas.html) so I could help out.

**Comment by bvanelli** [comment]
Hello,

I'm currently working on this feature using a wrapper around opepyxl. MR should come still this week, as all is working and I'm fixing tests.

**Comment by bvanelli** [comment]
Made a draft merge request, if any of you can take a look and suggest changes/improvements.

**Comment by alexander-beedie** [comment]
> Another option would be to use the pure rust [rust_xlsxwriter](https://github.com/jmcnamara/rust_xlsxwriter) library. The [rust_xlsxwriter roadmap](https://github.com/jmcnamara/rust_xlsxwriter/issues/1) explains the rationale and the current features.
> 
> I wrote the initial `xlsxwriter` [integration to Pandas](https://xlsxwriter.readthedocs.io/working_with_pandas.html) so I could try a PR with some input from the core devs.

@jmcnamara / @ritchie46: I believe I have a [one line PR](https://github.com/jmcnamara/XlsxWriter/pull/566) in the python XlsxWriter, heh ;) Kudos on making a Rust port - the python version is genuinely excellent! I used it to add remarkably a surprisingly Excel export option to one of our major internal data APIs when I worked at JPMorgan, and it was very well thought of.

I'd certainly be interested in helping shape our usage, having done it once before - could start prototyping something with the python API, and once that looks good we can see how best to adapt it on the Rust side. Having the same core library features available in both languages seems like a big win, and I can speak to the quality of XlsxWriter.

**Comment by jmcnamara** [comment]
> I believe I have a [one line PR](https://github.com/jmcnamara/XlsxWriter/issues/565) in the python XlsxWriter repository, heh ;)

Cool. :-)

> I'd certainly be interested in helping shape our usage, having done it once before - could start prototyping something with the python API, and once that looks good we can see how best to adapt it on the Rust side.

That sounds like a good approach.

**Comment by alexander-beedie** [comment]
Finally started on this (in Python) ...

**Comment by jmcnamara** [comment]
@alexander-beedie good news. If there are any enhancements to XlsxWriter (within reason) that would make integrations with Polars easier/better let me know.

**Comment by alexander-beedie** [comment]
@jmcnamara: so far it's a breeze, much as I remember  ;)

Have integrated dtype and/or per-column formatting, float precision, conditional formatting (all flavours), table styling, total row, and so on... Almost ready for a first cut; need to polish-up what's there and then take care of docs and do some more validation/testing. (Sparklines can wait for a second iteration, though I definitely want to integrate those too).

Sample output from a single call to `df.to_excel(...)`

<img width="224" alt="polars_excel_integration" src="https://user-images.githubusercontent.com/2613171/221432716-9c790381-f93a-4400-8197-9f2394dfbcf6.png">

**Comment by jmcnamara** [comment]
Wow. Looks great. I'm looking forward to it. :-)

**Comment by alexander-beedie** [comment]
> Wow. Looks great. I'm looking forward to it. :-)

Here we go... https://github.com/pola-rs/polars/pull/7251

**Comment by jmcnamara** [comment]
@alexander-beedie That is great work. Really strong option support from the start.

**Comment by alexander-beedie** [comment]
@jmcnamara: I am a conduit for your remarkable library, orchestrating access across the breadth of the xlsxwriter API... ;)

Once it has settled in a version or two, what would you think about adding some Polars-specific help pages to the xlsxwriter site, equivalent to the existing Pandas ones? (I'd be more than happy to write/commit them, assuming that the docs are part of the repository).

**Comment by jmcnamara** [comment]
> what would you think about adding some Polars-specific help pages to the xlsxwriter site, equivalent to the existing Pandas ones?

Absolutely. I had actually typed a suggestion like that with my previous comment and then thought that might be insensitive because you have already provided some nice examples in your polar docs. :-) From my point of view the [Working with Python Pandas and XlsxWriter](https://xlsxwriter.readthedocs.io/working_with_pandas.html) were necessary because I kept seeing/answering the same types of questions on StackOverflow. 

I'll take a stab at creating a  "Working with Polars and XlsxWriter" chaper in the next week or two and hook you in. When do you think this feature will be in a public Polars release?

**Comment by alexander-beedie** [comment]
@jmcnamara: it's out [now](https://github.com/pola-rs/polars/releases/tag/py-0.16.10) - just had time to squeeze-in [sparkline](https://github.com/pola-rs/polars/pull/7333) support too ;)

**Comment by jmcnamara** [comment]
@alexander-beedie Excellent. I'll start on the docs and hook you in once I have a basic framework (in the next couple of days).

**Comment by jmcnamara** [comment]
I've added initial docs for this at [Working with Polars and XlsxWriter](https://xlsxwriter.readthedocs.io/working_with_polars.html) in the main documentation.  See also https://github.com/jmcnamara/XlsxWriter/issues/961

**Comment by alexander-beedie** [comment]
> Any performance measurements against xlsxwriter (in pandas) and especially against PyExcelerate?

@leonkosak: Feel free to run some and let us know how it goes ;)
(If there's anything obviously suboptimal I can try and optimise further).

As for comparisons, given that we are leveraging `xlsxwriter` I'd imagine we'll be similar to anyone else doing the same, though I have taken pains to try and choose the available fast-paths where possible, so we could be a _bit_ faster?

**Comment by jmcnamara** [comment]
I've uploaded a new Rust crate called [`polars_excel_writer`](https://crates.io/crates/polars_excel_writer) for serializing Polars dataframes into Excel Xlsx files using [`rust_xlsxwriter`] as a backend engine.

It provides two interfaces for writing a Polars Rust dataframe to an Excel Xlsx file:

- [`ExcelWriter`] a simple Excel serializer that implements the Polars [`SerWriter`] trait to write a dataframe to an Excel Xlsx file. This is similar to the [`CsvWriter`] interface.

- [`PolarsXlsxWriter`] a more configurable Excel serializer that resembles the interface options provided by the Polars Python [`write_excel()`] dataframe method. There is still [work in progress] for this interface. 
 
  One useful feature of `PolarsXlsxWriter` is that you can mix Polars and `rust_xlsxwriter` code to [access Excel features] not available in the current interface.

Note, this is for Rust dataframes rather than Python dataframes so folks on this thread may not be as interested. If you are and you try it out you can leave some feedback [here](https://github.com/jmcnamara/polars_excel_writer/issues/1).

 [`ExcelWriter`]: https://docs.rs/polars_excel_writer/latest/polars_excel_writer/write/struct.ExcelWriter.html
[`PolarsXlsxWriter`]: https://docs.rs/polars_excel_writer/latest/polars_excel_writer/xlsx_writer/struct.PolarsXlsxWriter.html
[`SerWriter`]:https://docs.rs/polars/latest/polars/prelude/trait.SerWriter.html
[`CsvWriter`]:https://docs.rs/polars/latest/polars/prelude/struct.CsvWriter.html
[`polars_excel_writer`]: https://crates.io/crates/polars_excel_writer
[`rust_xlsxwriter`]: https://crates.io/crates/rust_xlsxwriter
[`write_excel()`]: https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_excel.html#polars.DataFrame.write_excel
[work in progress]: https://github.com/jmcnamara/polars_excel_writer/issues/1
[access Excel features]: https://docs.rs/polars_excel_writer/latest/polars_excel_writer/xlsx_writer/struct.PolarsXlsxWriter.html#interacting-with-rust_xlsxwriter

**Comment by jmcnamara** [comment]
Just to note, in case anyone finds it useful, with version 3.2.2 of XlsxWriter you can format boolean values in Polars dataframes as checkboxes in Excel:

```python
import polars as pl

# Create a Pandas dataframe with some sample data.
df = pl.DataFrame(
    {
        "Region": ["North", "South", "East", "West"],
        "Target": [100, 70, 90, 120],
        "On-track": [False, True, True, False],
    }
)

# Write the dataframe to a new Excel file with formatting options.
df.write_excel(
    workbook="polars_checkbox.xlsx",

    # Set the checkbox format for the "On-track" boolean column.
    column_formats={"On-track": {"checkbox": True}},

    # Set an alternative table style.
    table_style="Table Style Light 9",

    # Autofit the column widths.
    autofit=True,
)
```


![Image](https://github.com/user-attachments/assets/849cb9f4-8a95-457b-b8ba-052f3870f0b9)
