### ISSUE TITLE
Adding week and weeks in Python Polars

### ISSUE THREAD

**Issue by dimasliu123** [pola-rs/polars#5840]
### Problem description

Hello Ritchie, can you add a function in Python where week and weeks differs where week returns the week of month and weeks return year of week ?

[https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.dt.week.html](url)

```
weeks : pl.Series = pl.col("Date").dt.weeks() # returns 0 -> 53
week : pl.Series = pl.col("Date").dt.week() # returns 0 -> 3
```

Thanks !

**Comment by zundertj** [comment]
Two questions/remarks and one suggestion:

First, note that the current behavior for `week` is that it represents the week of the year (1-> 53). Are you suggesting to change that to week of the month, and introduce a new `weeks` to represent the old behavior? That seems unnecessarily breaking to me. Is there prior art that suggests this is the way to go?

Second, according to [wikipedia](https://en.wikipedia.org/wiki/ISO_week_date#Weeks_per_month), ISO does not define a week of the month. I have also not seen this particular method in other libraries before. For example, Python's `calendar` module does not support it directly either, nor does Pandas. Is it fair to say this is very niche? Doesn't mean your request is invalid, but if there is no standard, and there is seemingly very little demand (otherwise it would be in base Python and/or Pandas) would it make sense to include this in Polars at all?

Third, for the time being, maybe you can use Polars expressions to implement one of the suggestions on [StackOverflow](https://stackoverflow.com/questions/3806473/week-number-of-the-month)?

**Comment by stinodego** [comment]
For the reasons @zundertj gave, I will close this issue for now.
