### ISSUE TITLE
Allow `assert_frame_equal` to ignore row/column order

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6077]
### Problem description

I write a lot of tests for preprocessing pipelines. Some Polars operations result in random or unexpected row/column order, which a lot of the time doesn't matter. So I want to be able to assert equality ignoring these unimportant aspects.

```python
expected = pl.DataFrame({'a': [1, 2], 'b': [3, 4]})

# Columns ended up shuffled
result1 = pl.DataFrame({'b': [3, 4], 'a': [1, 2]})
assert_frame_equal(result1, expected)  # Fails
assert_frame_equal(result1, expected, ignore_column_order=True)  # Succeeds

# Rows ended up shuffled
result2 = pl.DataFrame({'a': [2, 1], 'b': [4, 3]})
assert_frame_equal(result2, expected)  # Fails
assert_frame_equal(result2, expected, ignore_row_order=True)  # Succeeds
```

**Comment by thomasfrederikhoeck** [comment]
I can see the point in `ignore_column_order` (as you can map colum name to column name) but how would `ignore_row_order` even work in the case of more than 2 rows? Have each row check against all rows in the other dataframe? :-)

**Comment by stinodego** [comment]
> I can see the point in `ignore_column_order` (as you can map colum name to column name) but how would `ignore_row_order` even work in the case of more than 2 rows? Have each row check against all rows in the other dataframe? :-)

You would sort both dataframes first, then do the check. Or maybe there's a better way.

**Comment by thomasfrederikhoeck** [comment]
Hmm I think it would be better to sort in the cases where it is relevant (explicit > implict IMO :-D ). 

There is also a problem with with structs and list which would need some rule set for sorting since you can't sort on a list today:
```python
import polars as pl 

df = pl.DataFrame({"a": [[1,2],[3,4]],"b":[3,4]})
df.sort(pl.all()
```
`
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_32272/1131772113.py in <module>
      2 
      3 df = pl.DataFrame({"a": [[1,2],[3,4]],"b":[3,4]})
----> 4 df.sort(pl.all())

c:\Users\tfh\Miniconda3\envs\norden_prefect\lib\site-packages\polars\internals\dataframe\frame.py in sort(self, by, reverse, nulls_last)
   2831         """
   2832         if not isinstance(by, str) and isinstance(by, (Sequence, pli.Expr)):
-> 2833             df = self.lazy().sort(by, reverse, nulls_last).collect(no_optimization=True)
   2834             return df
   2835         return self._from_pydf(self._df.sort(by, reverse, nulls_last))

c:\Users\tfh\Miniconda3\envs\norden_prefect\lib\site-packages\polars\utils.py in wrapper(*args, **kwargs)
    369         def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    370             _rename_kwargs(fn.__name__, kwargs, aliases)
--> 371             return fn(*args, **kwargs)
    372 
    373         return wrapper

c:\Users\tfh\Miniconda3\envs\norden_prefect\lib\site-packages\polars\internals\lazyframe\frame.py in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, common_subplan_elimination, streaming)
   1161             streaming,
   1162         )
-> 1163         return pli.wrap_df(ldf.collect())
   1164 
   1165     def sink_parquet(

PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(Borrowed("Cannot cast list type"))
`

**Comment by stinodego** [comment]
> explicit > implict

This doesn't really hold ground in this case. I explicitly state that I want to check equality ignoring row order. It's then up to the assert function itself to figure out how to do that efficiently.

Maybe there is no good way to do it, then we won't implement it. Maybe there is a way to do only in some cases, then we could implement that and throw an error in the other case.

In any case, the functionality would be nice to have.

**Comment by mcrumiller** [comment]
This is a weird definition of equality and IMO shouldn't be a parameter. Can you just do this?

```python
assert_frame_equal(df1.sort(by=df1.columns), df2.sort(by=df2.columns))
```

**Comment by stinodego** [comment]
> This is a weird definition of equality and IMO shouldn't be a parameter. Can you just do this?
> 
> ```python
> assert_frame_equal(df1.sort(by=df1.columns), df2.sort(by=df2.columns))
> ```

Yes, that's possible. And ignoring column order can (sort of) be done like so:

```python
assert_frame_equal(df1, df2.select(df1.columns))
```

Except it will discard extra columns in `df2`.

**Comment by mcrumiller** [comment]
@stinodego why not write an extra function to the sorting/comparison for you?

```python
def assert_frame_equal_sorted(df1, df2):
    assert(df1.columns == df2.columns))
    assert_frame_equal(df1.sort(by=df1.columns), df2[df1.columns].sort(by=df1.columns))
```

**Comment by alexander-beedie** [comment]
It makes perfect sense to have this mode built-in to the assert; the expectation that frame operations will always result in the same row ordering is an assumption that can potentially get you into trouble.

This is the same with database queries; absent  an _explicit_ ordering directive (for polars that could be a `sort`, the `maintain_order` param, etc) you shouldn't have a hard dependency on a given result ordering being consistent over time; internal changes may split the work across different numbers of threads, return rows interleaved, etc...

This is exactly why SQLite (for example) has a dedicated [`reverse_unordered_selects`](https://www.sqlite.org/pragma.html#pragma_reverse_unordered_selects) PRAGMA so that you can run it during your unit/integration tests and see exactly where you were making unwarranted assumptions.

So... gets my vote as a first-class (opt-in) param on `assert_frame_equal`, heh ;)

**Comment by alexander-beedie** [comment]
@stinodego - FYI: `check_column_names` already does what you wanted `ignore_column_order` for. I think we might want to deprecate that name in favour of your newer suggestion though as it's quite little vague - as proven by it not being spotted, heh.

**Comment by thomasfrederikhoeck** [comment]
Aften sleeping on it I like the idea. Apologies if coming of a bit negative @stinodego 😀
