### ISSUE TITLE
Add timezone-aware `dt.date` and `dt.time` properties

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#6130]
### Problem description

As far as I can tell, the simplest way to extract the date and time from a `pl.Datetime` column is by casting to `pl.Date` and `pl.Time`. However, neither of these operations interact with timezone-aware columns correctly. For example:

```python
from datetime import datetime

df = (
    pl.DataFrame({"datetime": datetime(2022, 1, 1, 23)})
    .with_column(pl.col("datetime").dt.tz_localize("America/New_York"))
    .with_columns(
        [
            pl.col("datetime").cast(pl.Date).alias("date"),
            pl.col("datetime").cast(pl.Time).alias("time"),
        ]
    )
)

shape: (1, 3)
┌────────────────────────────────┬────────────┬──────────┐
│ datetime                       ┆ date       ┆ time     │
│ ---                            ┆ ---        ┆ ---      │
│ datetime[μs, America/New_York] ┆ date       ┆ time     │
╞════════════════════════════════╪════════════╪══════════╡
│ 2022-01-01 23:00:00 EST        ┆ 2022-01-02 ┆ 04:00:00 │
└────────────────────────────────┴────────────┴──────────┘
```

To get the correct timezone-aware behavior, my current workaround is to add an intermediary `cast_time_zone` call before casting to `pl.Date` and `pl.Time`:

```python

df = (
    pl.DataFrame({"datetime": datetime(2022, 1, 1, 23)})
    .with_column(pl.col("datetime").dt.tz_localize("America/New_York"))
    .with_columns(
        [
            pl.col("datetime").dt.cast_time_zone("UTC").cast(pl.Date).alias("date"),
            pl.col("datetime").dt.cast_time_zone("UTC").cast(pl.Time).alias("time"),
        ]
    )
)

shape: (1, 3)
┌────────────────────────────────┬────────────┬──────────┐
│ datetime                       ┆ date       ┆ time     │
│ ---                            ┆ ---        ┆ ---      │
│ datetime[μs, America/New_York] ┆ date       ┆ time     │
╞════════════════════════════════╪════════════╪══════════╡
│ 2022-01-01 23:00:00 EST        ┆ 2022-01-01 ┆ 23:00:00 │
└────────────────────────────────┴────────────┴──────────┘
```

 Not only is this verbose, but the danger is that the intermediary `pl.Datetime` column ` pl.col("datetime").dt.cast_time_zone("UTC")` contains nonsense values. It would be nice to just access a `pl.Date` and `pl.Time` column with `dt.date` and `dt.time` like in pandas, that correctly respect timezones.

**Comment by stinodego** [comment]
I bumped into this yesterday. I completely support adding this functionality!

**Comment by ritchie46** [comment]
The `date` and `time` dtypes don't have a timezone. But I think we could argue that we must respect local time in the cast right? This would make current behavior flawed and I'd flag this as a bug.

**Comment by stinodego** [comment]
> we must respect local time in the cast

Well, I think it could be argued that when casting it makes sense to respect UTC time. Not sure about this.

But I AM sure that I would like a `dt.date` and `dt.time` method that does respect the local time.

**Comment by ritchie46** [comment]
So `dt.local_date` and `dt.local_time`?

**Comment by alexander-beedie** [comment]
> So `dt.local_date` and `dt.local_time`?

Probably just `dt.date` and `dt.time`, no? It's more like just getting the component parts _as they appear_, rather than doing a localising translation (even if that's required under the hood) - at least, if I'm understanding the request correctly.

**Comment by stinodego** [comment]
> Probably just `dt.date` and `dt.time`, no? It's more like just getting the component parts _as they appear_, rather than doing a localising translation

That's what I was thinking, and also what the original issue requests.

**Comment by erinov1** [comment]
I don't think any additional arguments are needed either — the original request is also consistent with how python's native datetime functionality works:

```python
print(my_dt)
print(my_dt.date())
print(my_dt.time())

2022-01-01 23:00:00-05:00
2022-01-01
23:00:00
```

As for the behavior of `pl.col("datetime").cast(pl.Date/pl.Time)`, I think you could argue that it is currently doing the right thing, since it is consistent with doing 

```python
pl.col("datetime").cast(pl.Datetime).cast(pl.Date/pl.Time)
``` 

I think it would be confusing if that diagram did not commute. Arguably though, you should be able to call 

```python
pl.col("datetime").tz_localize(None)
``` 

which would be equivalent to 

```python
pl.col("datetime").dt.cast_time_zone("UTC").cast(pl.Datetime)
```

This would convert a tz-aware datetime to a tz-naive datetime:

```python
df = (
    pl.DataFrame({"datetime": datetime(2022, 1, 1, 23)})
    .with_column(pl.col("datetime").dt.tz_localize("America/New_York"))
    .with_columns(
        [
            pl.col("datetime").dt.cast_time_zone("UTC").cast(pl.Datetime)
        ]
    )
)

shape: (1, 1)
┌─────────────────────┐
│ datetime            │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 2022-01-01 23:00:00 │
└─────────────────────┘

```

This would also be consistent with pandas `dt.tz_localize(None)` functionality.

**Comment by MarcoGorelli** [comment]
How about:
- `.cast(pl.Datetime)` returns the datetime as it appears
- `.cast(pl.Date)` returns the date as it appears
- `.cast(pl.Time)` returns the time as it appears

For converting to UTC or making timezone-naive, there's `.dt.with_time_zone`

**Comment by MarcoGorelli** [comment]
Actually, sorry, going to go back on the above suggestion, it wasn't a good idea.

It seems natural that:
- `.cast(pl.Int64)` return the number of [unit] since the 1970-01-01 in UTC
- `.cast(pl.Datetime).cast(pl.Int64)` should probably be the same as `.cast(pl.Int64)`

If `pl.Datetime` were to return the `datetime` as it appears, then the second property above would not be respected

And if `.cast(pl.Date)` were to return the date as it appears but `.cast(pl.Datetime)` didn't, then that might look inconsistent

Perhaps the current behaviour is OK, and all that's needed is to document that if you want to get the date or time as they appear, then you should first do `.dt.cast_time_zone('UTC')`?

**Comment by erinov1** [comment]
@MarcoGorelli calling `pl.col("datetime").dt.cast_time_zone("UTC")` modifies the underlying timestamps; they longer represent the original offset from epoch. If someone wrote code like

```python
df.with_column(pl.col("datetime").dt.cast_time_zone("UTC").cast(pl.Time).alias("time"))
```
this would be fine, but the danger is that someone could split the code up like

```python
# Prepare the datetime column before casting to `pl.Time`
df = df.with_column(pl.col("datetime").dt.cast_time_zone("UTC"))

# Add the time column
df = df.with_column(pl.col("datetime").cast(pl.Time).alias("time))
```
If another developer then accidentally inserted code that acted on the "datetime" column in between the two original lines of code, they would operating on nonsense timestamps. So it seems important that the conversion + casting logic be wrapped in a single atomic computation, something like a `dt.time` function.

**Comment by FObersteiner** [comment]
Just came across this issue, and the title mislead me :) It's not that date and time types should be tz-aware, e.g. because of
- time zone rules depend on dates, so having tz-aware time seems incomplete to me. You cannot unambiguously convert to another time zone or perform duration arithmetic on it.
- time zone rules affect certain times on certain dates, so if you have a tz-aware date, you can end up in undefined situations - for instance on a DST transition date, would you use DST active or inactive? How would you unambiguously convert to another tz? You could assume date =  midnight, but then you'd have datetime again...

...but extracting date and time from tz-aware datetime should yield date and time in that tz (local time). IMHO, the conversion here should be implicit - the explicit  `.dt.cast_time_zone('UTC')` doesn't seems intuitive to me, or might even be error-prone as @erinov1 points out.

So +1 for @MarcoGorelli 's
 
>     * `.cast(pl.Date)` returns the date as it appears
> 
>     * `.cast(pl.Time)` returns the time as it appears

Not sure about 
>     * `.cast(pl.Datetime)` returns the datetime as it appears

IIUC that would give naive datetime, i.e. also modify the underlying Unix time? If so, a cast_time_zone to None might be more clear?

**Comment by MarcoGorelli** [comment]
Hi @erinov1 (and others) - would this look good to you?
```python
In [1]:  ser = pl.Series(['2021-03-28 02:00']).str.strptime(pl.Datetime('us', 'Asia/Kathmandu'))

In [2]: ser
Out[2]: 
shape: (1,)
Series: '' [datetime[μs, Asia/Kathmandu]]
[
        2021-03-28 02:00:00 +0545
]

In [3]: ser.dt.datetime()
Out[3]: 
shape: (1,)
Series: '' [datetime[μs]]
[
        2021-03-28 02:00:00
]
```

I think `datetime`, `time` and `date` returning local values would be intuitive, because `.dt.hour` / `.dt.year` / etc. already return local values.

I think it would be more intuitive than changing the result of `cast`, because then:

- `ser.cast(pl.Datetime).cast(pl.Int64)`
- `ser.cast(pl.Int64)`

would differ, and I don't think that would be expected.

Unless there's objections, I'll put together a PR to add `dt.datetime`, `dt.time`, and `dt.date`. I don't think there'd be any need to prefix them with `local_`

**Comment by erinov1** [comment]
That looks great! I agree that changing the casting behavior is not the right thing to do.
