### ISSUE TITLE
Implement `is_nan` and `is_not_nan` for non-float dtypes

### ISSUE THREAD

**Issue by Hoeze** [pola-rs/polars#6153]
### Problem description

I find it very inconvenient when I want to check whether the data type is invalid to first need to check whether my column is actually float or integer.
Otherwise, I get a warning: `InvalidOperationError: 'is_not_nan' not supported for series with dtype Int32`.
Also, lazy columns do not support `col.is_float()`.

Would it be possible to have those methods just return a Series of `True`s instead?

**Comment by mcrumiller** [comment]
I think a better title would be `Implement is_nan and is_not_nan for integer dtypes`, as `is_nan` and `is_not_nan` *do* return series of True/False, just not where the methods aren't defined (obviously).

This raises a question about functions being implemented outside of their domain: NaN is a floating-point value, so does it make sense to implement NaN-related functions for integer dtypes? Maybe, since numerical data is often coerced into integer by I/O readers when no decimals are present and dtypes aren't explicitly specified.

**Comment by stinodego** [comment]
It currently does work for integer types. Not for non-numeric types, and we do not plan on supporting that.

```python
import polars as pl

lf = pl.Series("a", [1, 2, 3]).to_frame().lazy()

result = lf.select(pl.col("a").is_nan())
print(result.collect())
```
```
shape: (3, 1)
┌───────┐
│ a     │
│ ---   │
│ bool  │
╞═══════╡
│ false │
│ false │
│ false │
└───────┘
```
