### ISSUE TITLE
Rename `closed` argument to `inclusive`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6180]
### Problem description

This might purely be a personal preference, and might not be worth changing the API for, but I wanted to throw it out there anyway.

Open/closed is the mathematical term for specifying the bounds of an interval. So there's nothing wrong with having `closed` as a parameter name. But I always think about the bounds in terms of 'inclusive' or 'exclusive'. Somehow that makes more sense to me; with 'closed' I always think exclusive, when it's the other way around.

So I'd prefer to have these parameters named `inclusive` instead.

The input strings can remain the same; although `neither` instead of `none` makes more sense as the opposite of `both` (regardless of the renaming).

If this is not deemed worthy of an API change, we can probably already help by being just a little more verbose in the parameter description.

**Comment by ritchie46** [comment]
When we have a wikipedia page and clear roots in mathematics I really think we should favor that:

https://en.m.wikipedia.org/wiki/Interval_(mathematics)#terminology

We could even link to that.

**Comment by stinodego** [comment]
I'll do a small update of the docstrings then to help people like me who can't keep their terminology straight 😄

**Comment by alexander-beedie** [comment]
As an anecdotal data point, the param name `closed` was deemed sufficiently counterintuitive here to all of the non set-theorists (a group that probably maps well to the set of "most people" ;) that we actually _have_ called it `inclusive` in our own API and map that through to polars `closed`. My best guess is that there's something counterintuitive about the _normal_ meaning of "closed" that makes you think it _wouldn't_ include the bounds? 🤷 

I'd argue that `inclusive` describes it well to both groups - those familiar with set theory _and_ those who are not. `closed` is only obvious to one group, meaning the other lot will definitely have to go looking for a definition, and probably more than once. 

Since we already went with `inclusive` it's not a big deal here, but I do think renaming it to a more "inclusive" (groan) term would have merit ;)

**Comment by stinodego** [comment]
Good to hear it's not just me 😄
