### ISSUE TITLE
Deprecate `avg` in favor of `mean` or expose them at all levels

### ISSUE THREAD

**Issue by ghuls** [pola-rs/polars#6204]
### Problem description

Deprecate `avg` in favor of `mean` or expose them at all levels

For Discord:
> I just bumped my head on this, but is there a reason why col("name").avg() isn't a thing?
> 
> Is there logic for having [aggregation expressions](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/aggregation.html), and then [separate functions](https://pola-rs.github.io/polars/src/polars_plan/dsl/functions.rs.html#695-728) that don't quite overlap?
> 
> Ex. .avg() isn't a thing, but avg("name") is, and .std() is a thing, but std("name") isn't a thing as far as I can tell.

**Comment by stinodego** [comment]
I don't really mind having a few aliases that help people more easily find the functionality they need.

In this case, I agree it's strange that the alias exists as a separate function, but not as an expression method.

In this case, I'd lean towards adding it as an expression method, rather than removing the function.

**Comment by gfmartins** [comment]
Mathematically speaking average and mean are not the same thing... I guess it depends on what type of mean you are speaking about.
That would be an cool improvement to the API.

Types of Mean:
* Arithmetic Mean
* Geometric Mean
* Harmonic mean

**Comment by gfmartins** [comment]
this is why for example sql server or postgresl use AVG

this is from postgresql documentation
AVG() -> the average **(arithmetic mean)** of all input values
https://www.postgresql.org/docs/8.2/functions-aggregate.html

In a way using mean to get the average is incorrect, because mathematically it can refer to more that one thing. Unless specified in the documentation that the polars mean is the arithmetic mean

**Comment by ritchie46** [comment]
I understand that it seems a bit random which expressions have aliases and which not. I am in favor of removing them as well. This improves the readability as polars written by different users will pool from the same function names and leaves less room for personal preferences.
