### ISSUE TITLE
Python: Support complete `lazy` API in `eager`

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#621]
This is already almost true, but from now on, let's consider it a bug when this is not the case.
If we support the complete `lazy` API in `eager`, the expressions can be used in both API's, and there will be one idomatic way to do things in Polars. 

The pandas like masking etc. will still work, but would not be considered idiomatic use of python polars.

**Comment by FlorianWilhelm** [comment]
Currently, the Python docs demonstrate Polars features using the Pandas subscription syntax like [here](https://pola-rs.github.io/polars-book/user-guide/dsl/intro.html#count-unique-values). This does not work with `LazyFrame`.  I think a lot of Python users will just jump on the subscription syntax as they already know Pandas. Then they will get confused when starting to work with lazy execution.

My suggestion would be to either

1. completely get rid of the subscription syntax for the selection of columns and advocate the use of `select` instead,
2. also implement the subscription syntax for `LazyFrame`.

IMHO option 1 would be the cleanest since the concept of selecting columns with `select` and subscription to slice and index would then be clearly separated.

**Comment by ghuls** [comment]
@ritchie46 This is 98% completed now, no (except a few things that require materialization)?

**Comment by ritchie46** [comment]
> @ritchie46 This is 98% completed now, no (except a few things that require materialization)?

Yeap.. :+1:
