### ISSUE TITLE
Issue in iterrows(named=True) when a column starts with a number

### ISSUE THREAD

**Issue by gam-phon** [pola-rs/polars#6292]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Thank you for the great library. You are awesome.

Here is the issue with `df.iterrows(named=True)` or `df.rows(named=True)`  when a column starts with a number.

- I think it is related to #5935 

Maybe instead of using as a variable. it should use a dictionary instead to handle any name. Right now it must be a valid variable name in python
 
Here is the Exception:  
```
Traceback (most recent call last):
  File "path.py", line 12, in <module>
    for v in pl.DataFrame({"7_days": [1]}).iterrows(named=True):
  File "/virtualenvs/lib/python3.11/site-packages/polars/internals/dataframe/frame.py", line 6638, in iterrows
    Row = namedtuple("Row", self.columns)  # type: ignore[misc]
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py", line 393, in namedtuple
    raise ValueError('Type names and field names must be valid '
ValueError: Type names and field names must be valid identifiers: '7_days'
```

### Reproducible example

```python
import polars as pl

# No issue
for v in pl.DataFrame({"days": [1]}).iterrows(named=True):
    print(v)

# No issue
for v in pl.DataFrame({"n_days": [1]}).iterrows(named=True):
    print(v)

# Here is the issue
for v in pl.DataFrame({"7_days": [1]}).iterrows(named=True):
    print(v)
```

### Expected behavior

It should handle if the column's name starts with a number

### Installed versions

<details>

```
---Version info---
Polars: 0.15.15
Index type: UInt32
Platform: macOS-13.1-arm64-arm-64bit
Python: 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: 0.3.2_alpha.1
xlsx2csv: <not installed>
matplotlib: <not installed>
None
Row(days=1)
Row(n_days=1)
```

</details>

**Comment by gam-phon** [comment]
Here is my work around this:
```py
df = pl.DataFrame({"7_days": [1]})
for v in df.iterrows():
    d = {}
    for i, column_name in enumerate(df.columns):
        d[column_name] = v[i]
    print(d)
```

I can use the column name and get the value

**Comment by alexander-beedie** [comment]
The `named` option creates a `namedtuple` Row object, so the names _have_ to be valid python identifiers (as they are accessed as class attributes - consequently anything that isn't a valid python identifier won't work).

@stinodego / @ritchie46: we fixed this same issue in our API at work by offering the equivalent of a `named = dict` option; you still get named access as the param indicates, but as a dictionary instead of a namedtuple. This fully solves the problem shown here, as _any_ column name is a valid dictionary key. If no objections, I can add that later tonight.

**Comment by stinodego** [comment]
It feels a bit convoluted to have all these options. Maybe `namedtuple` was a bad idea, because it does not support this usecase (I had completely overlooked this).

Maybe we should just replace the current functionality with your dictionary proposal? Then anyone who wants named access will just have to type `row["mycolumn"]`. I think that's better than having multiple 'named' options.

**Comment by ritchie46** [comment]
It should be dictionary IMO. I already tried namedtuple in structs as well and got the same issue.

Dictionaries are the best fitting python std library datastructures for this.

**Comment by stinodego** [comment]
Then let's add a `FutureWarning` to the current methods, and make a breaking PR to introduce the named functionality as a dictionary.
