### ISSUE TITLE
Build versioned API reference

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6373]
Our [Python API reference](https://pola-rs.github.io/polars/py-polars/html/reference/index.html) currently always points to the `master` branch. This has a number of drawbacks:

* Users may see unreleased features in the API reference, and find out they cannot use them when running the latest version of Polars (as happened in #6371). This is confusing for users.
* Users that work with earlier versions of Polars cannot find matching documentation.

I propose we do the following:
* Add a CI workflow (or adjust the current docs workflow) that triggers when we release a new version. This builds the documentation for that version and stores it somewhere next to the master docs.
* Add a version dropdown menu to the docs that can switch between versions (similar to [pandas](https://pandas.pydata.org/docs/index.html)).

**Comment by thomasfrederikhoeck** [comment]
This [SO question](https://stackoverflow.com/questions/47643881/github-pages-maintaining-multiple-versions) has a step-by-step guide which looks like it should work. The pattern is to have a separate branch which have the full history of all released history. The same pattern is also used here at https://glebbahmutov.com/blog/versioned-doc-pages/

An alternative is to use ReadTheDocs which natively support docs versioning https://docs.readthedocs.io/en/latest/versions.html

**Comment by thomasfrederikhoeck** [comment]
numpy do it similar to the SO question where they have a separate repo (instead of a branch) for the whole history of docs which they push to when they release.

Numpy:
- script: https://github.com/numpy/numpy/blob/29cb0ef6bb47a942d77bf7479a870a0c88af6fc7/.circleci/config.yml#L134
- repo: https://github.com/numpy/devdocs

pandas instead pushes a new version to the server each time: 
- prod: https://github.com/pandas-dev/pandas/blob/3f3102b55458959481f4337e699ccd3b90460544/.github/workflows/docbuild-and-upload.yml#L80
- dev: https://github.com/pandas-dev/pandas/blob/3f3102b55458959481f4337e699ccd3b90460544/.github/workflows/docbuild-and-upload.yml#L76

It looks like the both keep a static file which is used for creating the versions in the dropdown:
https://numpy.org/doc/_static/versions.json
https://github.com/numpy/devdocs/blob/82714a20a7df2aa08cd922d81c74b0470b530386/index.html#L172

https://github.com/pandas-dev/pandas/blob/main/web/pandas/versions.json

**Comment by stinodego** [comment]
Thanks a lot for the references! Will take a look at this.

**Comment by stinodego** [comment]
The new setup is good enough for now, but in the future we might want to support multiple versions (e.g. `1.x`, `2.x`, ...) rather than just the latest release and the master branch.

When we do, it will also become more important to implement a nice dropdown to switch versions.

**Comment by timreuscher** [comment]
> The new setup is good enough for now, but in the future we might want to support multiple versions (e.g. `1.x`, `2.x`, ...) rather than just the latest release and the master branch.
> 
> When we do, it will also become more important to implement a nice dropdown to switch versions.

Completely agree, but if anything it's more important to have something like that when things are changing quickly. I tend to update my code every few months or so, and when I update polars it's easy to be lost in what's changed and how.

**Comment by stinodego** [comment]
Re-opening this as we're getting more requests for properly versioned docs for each major release.
