### ISSUE TITLE
Unify temporal expression functions

### ISSUE THREAD

**Issue by romanovacca** [pola-rs/polars#6445]
### Problem description

A couple functions are called similar, while having different behaviour e.g. `Expr.dt.microsecond()` and `Expr.dt.microseconds()`.

These functionality of these could be unified. See [#6413 ](https://github.com/pola-rs/polars/pull/6413) for more information

**Comment by MarcoGorelli** [comment]
The current names were (probably?) taken from pandas, but they behave differently:
```python
In [31]: pd.Series([timedelta(days=1, hours=1)]).dt.seconds
Out[31]:
0    3600
dtype: int32

In [32]: pl.Series([timedelta(days=1, hours=1)]).dt.seconds()
Out[32]:
shape: (1,)
Series: '' [i64]
[
        90000
]

In [41]: pd.Series([timedelta(days=1, hours=1)]).dt.total_seconds()
Out[41]:
0    90000.0
dtype: float64
```

The Python standard library behaves in the same way:
```python
In [49]: timedelta(days=1, hours=1).seconds
Out[49]: 3600

In [50]: timedelta(days=1, hours=1).total_seconds()
Out[50]: 90000.0
```

So, rather than unifiying temporal `.dt.microseconds` and datetime `.dt.microsecond`, maybe the former just needs renaming `.dt.total_microseconds` (similarly for second / millisecond / etc.)?
