### ISSUE TITLE
`vstack` fails because of column order but shouldn't

### ISSUE THREAD

**Issue by gab23r** [pola-rs/polars#6504]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

it's like `join` in `anti` mode has a weird behavior on the column order

### Reproducible example

```python
import polars as pl
df1 = pl.DataFrame(columns=['A', 'B']).lazy()
df2 = pl.DataFrame(columns=['B']).lazy()

pl.concat([
    df1,
    df2
    .join(df1, on = ['B'], how = 'anti') # works with left
    .with_columns([
        pl.lit(0.0).cast(pl.Float32).alias('A'),
    ])
    .select(df1.columns) # <- should reorder !
]).collect()

# exceptions.SchemaError: cannot vstack: because column names in the two DataFrames do not match for left.name='B' != right.name='A'
```

### Expected behavior

No exception

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(), leave the backticks in place
```

</details>

**Comment by gab23r** [comment]
Beyond this bug, IMO, I think It would be nice to be able to concat vertically 2 dataframes even if their columns are not in the same order.

**Comment by ritchie46** [comment]
> Beyond this bug, IMO, I think It would be nice to be able to concat vertically 2 dataframes even if their columns are not in the same order.



> Beyond this bug, IMO, I think It would be nice to be able to concat vertically 2 dataframes even if their columns are not in the same order.

See #6516. I think we could add a keyword argument that allows this. But IMO, you should always error when schemas don't align.

**Comment by gam-phon** [comment]
I think it is ok to raise the error to the user, so he can put more efforts on his data and clean them and align them in a way that is consistent with each other. If the library handle every things for you it will be slower in the long term because it will check for consistency and do pre-works behind, before doing the actual things. So sometime it will work fast and sometimes it will not it depends of the hidden pre-works needed. for the user the pre-works is hidden from him and he do not know why it is taking sometime in some cases. Maybe if there were some pre-works and some warning printed to tell the users that there are some pre-works is done here so he could later clean up his data and that warning will go away.
