### ISSUE TITLE
`sort` after `Series.cat.set_ordering("lexical")` does not work as expected

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#6513]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Calling `sort` after `set_ordering("lexical")` gives incorrect results.

### Reproducible example

```python
import polars as pl

s = pl.Series(["a", "c", "a", "b", "a"], dtype=pl.Categorical)
result = s.cat.set_ordering("lexical").sort()

print(result)
```

The result has "b" and "c" swapped, but the "a" is left alone:

```
shape: (5,)
Series: '' [cat]
[
        "a"
        "b"
        "a"
        "c"
        "a"
]
```

### Expected behavior

I expect the series to be sorted lexically:

```
shape: (5,)
Series: '' [cat]
[
        "a"
        "a"
        "a"
        "b"
        "c"
]
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.18
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: 0.8
deltalake: <version not detected>
matplotlib: <not installed>
```

</details>

**Comment by stinodego** [comment]
@ritchie46 Any clue what this might be?

Should be in here somewhere:
https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/chunked_array/ops/sort/categorical.rs#L32

**Comment by ritchie46** [comment]
Yes! Can't see what's wrong immediately. But that's the code.

**Comment by sorhawell** [comment]
I believe know the issue, but I struggle to wrangle chunkedArrays in a clean and fast way.
Conceptually lexical and physical sort are not strictly mutual exclusive.

I define a physical sort as one that yields the index array sorted.
I define a lexical sort as one that yields the category name table sorted.

A correct Physical sort is simply vanilla sorting the index-array. However, naively sorting the CategoryNameTable is only a correct lexical sort if all categories have equal counts. Otherwise counts and/or ordering of Categories will become incorrect. By above definition we can describe four outcomes and recipies:

 - No sort: Status quo, no change
 - Physical sort:
  1. vanilla sort of the idx-array as in current code
 - Physical + Lexical sort:
  1. arg_sort category name array
  2. make value counts of index array
  3. reorder value_counts by arg_sort output
  4. make a null count and write them in front/back of new idx array
  5. write 0u32 count_0 times to new idx array, then write 1 count_1 times to array .... until last count has been filled in
  6. permute category name array by arg_sort
 - Lexical sort:
 1. arg sort category name array
 2. make value counts of index array
 3. make a null count and write them in front/back of new idx array
 4. write argsort_0  count_0 times to new idx array, then write 1 count_1 times to array .... until

**Comment by stinodego** [comment]
That's great! I'm pinging @ritchie46 for this one, as I'm not yet the best person to go to for Rust implementation advice.

**Comment by stinodego** [comment]
@ritchie46 @orlp Could either of you take a look at this one? It's relevant for implementing the DataFrame protocol.

**Comment by ritchie46** [comment]
Coming up!
