### ISSUE TITLE
`.take()` indices are out of bounds when using `pl.col("row_nr")`

### ISSUE THREAD

**Issue by cmdlineluser** [pola-rs/polars#6580]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I was experimenting with a a conditional `.take()` using `.when/then`

Using a single `.take()` with `when/then` inside produces no error.

Using `.when(take).then(take)` produces an out of bounds index error.

Guessing it has something to do with `row_nr` being unsigned - I tried casting `row_nr` and it works without error.

I would have thought both approaches were equivalent - but perhaps I'm mistaken.

Thank you.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"value": ["a", "b", "c"]})

# OK
df.with_row_count().with_columns(
   pl.col("value").take(
      pl.when(pl.col("row_nr") > 0)
        .then(pl.col("row_nr") - 1)
        .otherwise(0)
   )
)
"""
shape: (3, 2)
┌────────┬───────┐
│ row_nr | value │
│ ---    | ---   │
│ u32    | str   │
╞════════╪═══════╡
│ 0      | a     │
│ 1      | a     │
│ 2      | b     │
└────────┴───────┘
"""

# Out of bounds
(df.with_row_count()
   .with_columns(
      pl.when(pl.col("row_nr") > 0)
        .then(pl.col("value").take(pl.col("row_nr") - 1))
        .otherwise(pl.col("value").take(0)))
)
"""
ComputeError: Take indices are out of bounds.
"""

# OK
(df.with_row_count()
   .with_columns(row_nr = pl.col("row_nr").cast(pl.Int64))
   .with_columns(
      pl.when(pl.col("row_nr") > 0)
        .then(pl.col("value").take(pl.col("row_nr") - 1))
        .otherwise(pl.col("value").take(0)))
)
"""
shape: (3, 2)
┌────────┬───────┐
│ row_nr | value │
│ ---    | ---   │
│ i64    | str   │
╞════════╪═══════╡
│ 0      | a     │
│ 1      | a     │
│ 2      | b     │
└────────┴───────┘
"""
```

### Expected behavior

No out of bounds exception.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Python: 3.10.9 (main, Jan 14 2023, 16:56:26)
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.3
numpy: 1.23.5
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: 0.8
deltalake: <not installed>
matplotlib: 3.5.1
```

</details>

**Comment by mcrumiller** [comment]
Your starting `row_nr` is a `u32`. When your 2nd when/then/otherwise channel attempts to do a `pl.col("row_nr")-1` you're running into an unsigned overflow error. See this:

```python
import polars as pl

df = pl.DataFrame({"value": ["a", "b", "c"]}).with_row_count()

df.select(pl.col("row_nr")-1)
```
shape: (3, 1)
┌────────────┐
│ row_nr     │
│ ---        │
│ u32        │
╞════════════╡
│ 4294967295 │
│ 0          │
│ 1          │
└────────────┘
```

Oopsies! When you cast to `pl.Int64`, this leads to giving you a `-1` instead of that crazy number. Both are invalid, but if you check, you'll see that negative indices give you a `null` and out-of-bounds indices give you an Exception:

```
>>> df["value"].take(-1)
shape: (1,)
Series: 'value' [str]
[
	null
]

>>> df["value"].take(213957915)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mcrum\AppData\Local\Programs\Python\Python310\lib\site-packages\polars\internals\series\series.py", line 2118, in take
    return self.to_frame().select(pli.col(self.name).take(indices)).to_series()
  File "C:\Users\mcrum\AppData\Local\Programs\Python\Python310\lib\site-packages\polars\internals\dataframe\frame.py", line 5446, in select
    self.lazy().select(exprs).collect(no_optimization=True)._df
  File "C:\Users\mcrum\AppData\Local\Programs\Python\Python310\lib\site-packages\polars\utils.py", line 337, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\mcrum\AppData\Local\Programs\Python\Python310\lib\site-packages\polars\internals\lazyframe\frame.py", line 1154, in collect
    return pli.wrap_df(ldf.collect())
exceptions.ComputeError: take indices are out of bounds
```

@ritchie46 is this intended behavior? Should an exception be raised in both cases?

**Comment by ritchie46** [comment]
Thanks for the breakdown @mcrumiller. We need to raise an error in the negative case as well. Negative indices are not allow in our `take` expression.

**Comment by cmdlineluser** [comment]
@mcrumiller Appreciate the detailed explanation - thank you!

I'm still a little confused - if it's inside a `.then()` - should that not prevent it from being passed to `.take()` - making it equivalent to the first example?

```
(df.with_row_count()
   .with_columns(
      pl.when(pl.col("row_nr") > 0)
        .then(pl.col("row_nr") - 1)
        .otherwise(0)
        .alias("idx"))
)
```
```
shape: (3, 3)
┌────────┬───────┬─────┐
│ row_nr | value | idx │
│ ---    | ---   | --- │
│ u32    | str   | u32 │
╞════════╪═══════╪═════╡
│ 0      | a     | 0   │
│ 1      | b     | 0   │
│ 2      | c     | 1   │
└────────┴───────┴─────┘
```

**Comment by cmdlineluser** [comment]
@mcrumiller Hmm, my original first example does use `.take`?

```
df = pl.DataFrame({"value": ["a", "b", "c"]})

df.with_row_count().with_columns(
   pl.col("value").take(
      pl.when(pl.col("row_nr") > 0)
        .then(pl.col("row_nr") - 1)
        .otherwise(0)
   )
)
```

I guess it's an order of operations thing? In this example `-12345, 0, 1` is turned into `0, 0, 1` first which is then passed to `.take`

Whereas with
```
pl.when(pl.col("row_nr") > 0)
        .then(pl.col("value").take(pl.col("row_nr") - 1))
        .otherwise(pl.col("value").take(0)))
```
It would be `.take([-12345, 0, 1])` and `.take(0)` executed first - hence the error.

**Comment by mcrumiller** [comment]
Sorry, I thought you had re-posted your original example. So, my guess for the following:

```python
df = pl.DataFrame({"value": ["a", "b", "c"]})

df.with_row_count().with_columns(
   pl.col("value").take(
      pl.when(pl.col("row_nr") > 0)
        .then(pl.col("row_nr") - 1)
        .otherwise(0)
   )
)
```
is that `take` only evaluates on the result on the when/then/otherwise branches, and that result has no issues. In other words:

1. `pl.col("row_nr") - 1` evaluates just fine, and returns (4294967295, 0, 1).
2. `0` also evaluates just fine, and returns (0, 0, 0)
3. The `pl.when()` logic is then applied to select the items from the respective branches above, returning (0, 0, 0).
4. `pl.col("value").take(...)` is then applied to the result from #3, so no errors occur.

**Comment by cmdlineluser** [comment]
@mcrumiller Makes sense when it's written out step-by-step like that.

I'm not sure why my brain was trying to parse both examples as equivalent.

Thank you for the help.
