### ISSUE TITLE
Python polars often needs to recompile between running tests

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#6613]
Calling a `make pre-commit` leads to a full recompilation of a subsequent `make test` in the python module.

@stinodego any idea what this could be?

**Comment by stinodego** [comment]
No idea, probably something related to that `build.rs` thing again. I can look into it but I don't think I'll have time before Friday.

**Comment by stinodego** [comment]
A related issue: I don't really like the fact that `make test` always tries to re-compile. Even if compilation is fully cached and takes 0.1 seconds, the creation of the `polars.abi3.so` file takes about 5 seconds, which is longer than the whole test suite takes to run.

Would you be open to manually specifying re-compilation like so:

```
make test  # Run tests without recompilation
make build test  # Re-compile and run tests
```

That would solve my 'issue' - though it's not a big issue as I can just run `pytest` (without the make command).

**Comment by slonik-az** [comment]
> make test  # Run tests without recompilation
make build test  # Re-compile and run tests

This approach was proposed a while back in PR #5137 ([see discussion](https://github.com/pola-rs/polars/pull/5137#discussion_r1015892302)) but it was rejected. I think polars coming full cycle to realization that test target should not unconditionally depend on build target. For speed in intercative development I would suggest having `tt` target in Makefile
```
tt: build test
```
so that running `$ make tt` runs `build` followed by `test`.

**Comment by ritchie46** [comment]
> A related issue: I don't really like the fact that `make test` always tries to re-compile. Even if compilation is fully cached and takes 0.1 seconds, the creation of the `polars.abi3.so` file takes about 5 seconds, which is longer than the whole test suite takes to run.
> 
> Would you be open to manually specifying re-compilation like so:
> 
> ```
> make test  # Run tests without recompilation
> make build test  # Re-compile and run tests
> ```
> 
> That would solve my 'issue' - though it's not a big issue as I can just run `pytest` (without the make command).

I also just run pytest in such a case.

**Comment by stinodego** [comment]
I cannot reproduce this 😕
