### ISSUE TITLE
Handle ambiguous datetimes in `cast_time_zone`

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#6672]
### Problem description

The following raises:
```python
ts = ['2018-10-28 01:30:00',
 '2018-10-28 02:00:00',
 '2018-10-28 02:30:00',
 '2018-10-28 02:00:00',
 '2018-10-28 02:30:00',
 '2018-10-28 03:00:00',
 '2018-10-28 03:30:00']

pl.Series(ts).str.strptime(pl.Datetime).dt.cast_time_zone('Europe/Brussels')
```

```python-traceback
thread '<unnamed>' panicked at 'Ambiguous local time, ranging from 2018-10-28T02:00:00CEST to 2018-10-28T02:00:00CET', /home/marcogorelli/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.23/src/offset/mod.rs:189:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/marcogorelli/polars-dev/py-polars/t.py", line 17, in <module>
    pl.Series(ts).str.strptime(pl.Datetime).dt.cast_time_zone('Europe/Brussels')
  File "/home/marcogorelli/polars-dev/py-polars/polars/internals/series/utils.py", line 98, in wrapper
    return s.to_frame().select(f(*args, **kwargs)).to_series()
  File "/home/marcogorelli/polars-dev/py-polars/polars/internals/dataframe/frame.py", line 5672, in select
    self.lazy()
  File "/home/marcogorelli/polars-dev/py-polars/polars/internals/lazyframe/frame.py", line 1146, in collect
    return pli.wrap_df(ldf.collect())
pyo3_runtime.PanicException: Ambiguous local time, ranging from 2018-10-28T02:00:00CEST to 2018-10-28T02:00:00CET
```

pandas has a lot of complexity for dealing with this. Not sure all that complexity is warranted here, but opening this in the meantime to break it off from https://github.com/pola-rs/polars/issues/4679

Workaround for now (which requires users to know how far their time zone is from UTC):
```python
>>> pl.Series(ts).str.strptime(pl.Datetime).dt.cast_time_zone('UTC').dt.with_time_zone('Europe/Brussels').dt.offset_by('-1h')
shape: (7,)
Series: '' [datetime[μs, Europe/Brussels]]
[
        2018-10-28 02:30:00 CEST
        2018-10-28 02:00:00 CET
        2018-10-28 02:30:00 CET
        2018-10-28 02:00:00 CET
        2018-10-28 02:30:00 CET
        2018-10-28 03:00:00 CET
        2018-10-28 03:30:00 CET
]
```

**Comment by MarcoGorelli** [comment]
@sm-Fifteen curious to hear your thoughts here - is all the complexity in pandas warranted, or is the workaround here a realistic-enough solution (at least, for your use-case)?

**Comment by sm-Fifteen** [comment]
> @sm-Fifteen curious to hear your thoughts here - how do you deal with this in pandas? Do you provide a boolean array to `ambiguous`?

I would, but I realized on the last DST fold (back in October) that the main data source I'm personally using this for behaves *extremely* erratically during that time period, reports the duplicated timestamp only once, and I (as a human reading the logs and the step-by-step data dumps I'd setup for *this specific moment of the year*) can't even tell whether this data is supposed to be from before or after the fold, or even confirm that it's not garbage. So right now, the fold data is being lost, something that makes me very mad but that's difficult to solve properly at the moment, because there's like 4 points in the data pipeline upstream of me that mess it up in their own different way.

The data I'm being fed has no UTC offset, and all I know is that it's "supposed to be at local time", so using the tzdb name works most of the time. Given I'm importing a batch of CSV files, that each contain data for a 15 minute interval (imported every 15 minutes, a timeframe too short to just `infer` the timezone even if the source was monotonic and well-behaved), I could implement logic to get the creation time for each file (which is either UTC or Unix Epoch, but either way an "absolute timestamp") and deduce whether to count the data inside these as pre-fold or post-fold. That's where an escape hatch feature like the boolean array would hypothetically come in handy in my case, even though I don't know if I would personally be able to use it for the time being. It might still serve other people, though.

The joys of putting so much time, thought and effort in handling something that only affects 0.0114% of the data in a year!

**Comment by olivier-lacroix** [comment]
Hi there, being able to infer the TZ for ambiguous datetimes would indeed be very useful. Maybe this could start with handling the 'cleanest cases', for instance when the timeseries is ordered and timestamps are repeated?

**Comment by MarcoGorelli** [comment]
Hi @olivier-lacroix - just to understand, do you have a usecase for this, when `ambiguous='infer'` in pandas would've worked for you?

**Comment by olivier-lacroix** [comment]
Sure @MarcoGorelli 

```python
import pandas as pd
idx = pd.DatetimeIndex([
           '2023-04-02 01:30:00',
           '2023-04-02 02:00:00',
           '2023-04-02 02:30:00',
           '2023-04-02 02:00:00',
           '2023-04-02 02:30:00',
           '2023-04-02 03:00:00',
           '2023-04-02 03:30:00',
          ])
idx.tz_localize('Australia/Melbourne',ambiguous='infer')

# DatetimeIndex(['2023-04-02 01:30:00+11:00', '2023-04-02 02:00:00+11:00',
#                '2023-04-02 02:30:00+11:00', '2023-04-02 02:00:00+10:00',
#                '2023-04-02 02:30:00+10:00', '2023-04-02 03:00:00+10:00',
#                '2023-04-02 03:30:00+10:00'],
#               dtype='datetime64[ns, Australia/Melbourne]', freq=None)
```

**Comment by olivier-lacroix** [comment]
btw, thx @MarcoGorelli  for working on all things datetime and TZ in polars. This is one of the areas where pandas is still better than polars. hopefully not for long :-)

**Comment by MarcoGorelli** [comment]
@olivier-lacroix just for my understanding, is
```python
           '2023-04-02 01:30:00',
           '2023-04-02 02:00:00',
           '2023-04-02 02:30:00',
           '2023-04-02 02:00:00',
           '2023-04-02 02:30:00',
           '2023-04-02 03:00:00',
```
the format in which you find the data in your database / spreadsheet / whatever? As in, do you just get such a list of local datetimes, or do you also get a column indicating whether they are before or after DST?

**Comment by olivier-lacroix** [comment]
Just a list of local datetimes @MarcoGorelli

**Comment by MarcoGorelli** [comment]
@olivier-lacroix thinking about this further, I think all that's needed is an optional boolean argument, like `is_earliest`

Then, if you have sorted regularly-spaced datetimes with repetitions, then you can mimic `ambiguous='infer'` with
```python
df.with_columns(
    ts_converted=pl.when(pl.col("ts").is_first())
    .then(pl.col("ts").dt.replace_time_zone("Europe/Brussels", is_earliest=True))
    .otherwise(pl.col("ts").dt.replace_time_zone("Europe/Brussels", is_earliest=False))
)
```

**Comment by sm-Fifteen** [comment]
@MarcoGorelli: Seems like a fair solution for the some cases, but I'm not convinced it works for all of them. Consider the main use cases of `ambiguous` in Pandas:

* DST change may occur over the time series, but data is *temporally* sorted, so a repetition in the monotonic order of the timestamps would mark the DST fold. This assumes that the time series has a large enough range and a sufficent resolution that data from both before and after the fold appear when the clock is moved backwards.
* DST change may occur over the time series, and an external data source (such as the timestamps indicating file creation) can be used to discriminate whether or not a line was before or after the fold if there's ambiguity.
* DST change is considered insignificant, and data points that fall on the fold with either be assumed to be always before the fold, always after the fold or invalid.

Your PR for `is_earliest`/`use_earliest` does a fair job at dealing with the latter two use cases, but the first may not be adressed by your example all that well, because it assumes not just pre-sorted, but also pre-quantized data. Checking if this timestamp has been encountered before is all well and good if they can be assumed to be well-behaved on a grid, but to me, that seems akin to checking for equality on floating point numbers (in that relying on this leaves about a dozen different ways in which this could subtly go wrong).

I don't think a user can properly implement something equivalent to `infer` without a `lag()`/`lead()` window function to compare the timestamp on the current row to the one on the previous row and make sure that the time series is monotonic over your window (which would also prove useful when your source data is temporally sorted, but potentially interleaved across different groups). Even then, if you only have, say, a 30 minutes sample that happens to fall completely during either ambiguity period, but not the fold (i.e: from 2:00 to 2:45 in 15 minutes intervals), your code could silently assume that this is all from before the fold instead of throwing, which will give you undesirable results if it ends up running on both the pre-fold 2:00-2:45 interval and the post-fold 2:00-2:45 interval.

**Comment by MarcoGorelli** [comment]
thanks

yeah to be fair, `ambiguous='infer'` does work on the first example you gave
```python
In [6]: dates
Out[6]:
['2018-10-28 01:30',
 '2018-10-28 01:39',
 '2018-10-28 01:51',
 '2018-10-28 02:02',
 '2018-10-28 02:30',
 '2018-10-28 02:58',
 '2018-10-28 02:05']

In [7]: pd.to_datetime(dates).tz_localize('Europe/Brussels', ambiguous='infer')
Out[7]:
DatetimeIndex(['2018-10-28 01:30:00+02:00', '2018-10-28 01:39:00+02:00',
               '2018-10-28 01:51:00+02:00', '2018-10-28 02:02:00+02:00',
               '2018-10-28 02:30:00+02:00', '2018-10-28 02:58:00+02:00',
               '2018-10-28 02:05:00+01:00'],
              dtype='datetime64[ns, Europe/Brussels]', freq=None)
```

I'll come back to this, but `use_earliest: Option<bool>` is just the beginning, and not the final product

**Comment by MarcoGorelli** [comment]
Anyway, for your problem at hand, if you know that the datetimes are sorted, then you could do something like:
```python
dates = (
    pl.date_range(datetime(2017, 1, 1), datetime(2020, 1, 1), "1h1min")
    .tz_localize("UTC")
    .tz_convert("Europe/Brussels")
    .strftime("%Y-%m-%d %H:%M:%S")
    .tolist()
)
df = pl.DataFrame({"ts": pl.Series(dates).str.strptime(pl.Datetime)})
df = df.with_columns(
    use_earliest=(pl.col("ts") <= pl.col("ts").shift(1)).fill_null(0) % 2 == 1
)
df = df.with_columns(
    pl.when(pl.col("use_earliest") == True)
    .then(pl.col("ts").dt.replace_time_zone("Europe/Brussels", use_earliest=False))
    .otherwise(pl.col("ts").dt.replace_time_zone("Europe/Brussels", use_earliest=True))
)
```

I then get
```python
In [69]: df.filter(pl.col('ts').dt.datetime()>=datetime(2018, 10, 28)).head(9)
Out[69]:
shape: (9, 2)
┌───────────────────────────────┬──────────────┐
│ ts                            ┆ use_earliest │
│ ---                           ┆ ---          │
│ datetime[μs, Europe/Brussels] ┆ bool         │
╞═══════════════════════════════╪══════════════╡
│ 2018-10-28 00:37:00 CEST      ┆ false        │
│ 2018-10-28 01:38:00 CEST      ┆ false        │
│ 2018-10-28 02:39:00 CEST      ┆ false        │
│ 2018-10-28 02:40:00 CEST      ┆ false        │
│ 2018-10-28 03:41:00 CET       ┆ false        │
│ 2018-10-28 04:42:00 CET       ┆ false        │
│ 2018-10-28 05:43:00 CET       ┆ false        │
│ 2018-10-28 06:44:00 CET       ┆ false        │
│ 2018-10-28 07:45:00 CET       ┆ false        │
└───────────────────────────────┴──────────────┘
```

**Comment by sm-Fifteen** [comment]
@MarcoGorelli: I can't help but notice that, with a `"1h1min"` period, the detection actually fails and the `02:39:00`, `02:40:00` sequence is detected as consecutive, (somewhat reasonably, I'd say, since `replace_time_zone` doesn't know the expected period). `"59m"` might work better. The general strategy is interesting, though, and forgoes the need for lead/lag window functions. The documentation should probably include it.

**Comment by MarcoGorelli** [comment]
>  the detection actually fails and the 02:39:00, 02:40:00 sequence is detected as consecutive

ooh you're right, thanks. I'll flesh it out a bit more, but I'm hopeful that something can be done
