### ISSUE TITLE
Unexpected behaviour using Series.str.concat

### ISSUE THREAD

**Issue by TheWizier** [pola-rs/polars#6919]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Using .str.concat concatinates "null" into the string, which is dangerously silent. Also is inconsistent with str_concat. 

### Reproducible example

```python
>>> a = pl.Series("A", [None, 1,2,3])
>>> a.str.concat("")
shape: (1,)
Series: 'A' [str]
[
	"null123"
]
```

### Expected behavior

Exception or null

### Installed versions

<details>

```
>>> pl.show_versions()
---Version info---
Polars: 0.16.5
Index type: UInt32
Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.4
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>

```

</details>

**Comment by ritchie46** [comment]
Inconsistent with which `str_concat` do you mean?

I don't think it is all that bad. It concatenates the values in the array, and `null` is also such a value.

You can easily call `a.drop_null().str.concat("")` to get other behavior.

**Comment by TheWizier** [comment]
Its more that I don't want the action to succeed as imo null is not a concat-able value. Say you create some error in your code that results in nulls in this column, then ideally this should fail. I would also be ok with it returning just null, beacase atleast then any subsequent operations on the string would fail due to it not being a string. In other words I think its REALLY bad.

**Comment by JulianCologne** [comment]
@ritchie46 , I agree with @TheWizier that this is unexpected behavior.
You can really shoot yourself in the foot with this if you imagine having millions of rows and some of them have null values and you don't event notice it.

The problem imo is that there are multiple sensible behaviors for concat with null values.

```python
s = pl.Series(["null", "a", "", "c", None])
```

### Replace nulls with "null" (current behavior) -> `null_a__c_null`
- Con: the word "null" is just a word for humans representing **nothing here**. Replacing **nothing here** with "null" is not a good idea imo
- Con: no distinction between "null" string and null value

### Replace nulls with empty string -> `null_a__c_`
- Pro: reasonable behavior
- Con: no distinction between empty string and null

### Ignore nulls -> `null_a__c`
- Pro: reasonable behavior
- Con: fewer parts than expected?

## Possible solutions
- exception or null if nulls are present (I think this is the best solution)
    - raise nice error message that `concat` does not support nulls and that you can use `s.fill_null("XX")` or `s.drop_nulls()` to explicitly deal with nulls
- add additional parameter to specify how to handle nulls
    - `s.str.concat("_", null_behavior="ignore")`
    - `s.str.concat("_", null_behavior="replace", replace_with="XX")`
    - `s.str.concat("_", null_behavior="error")`

**Comment by alexander-beedie** [comment]
@JulianCologne: nice summary

**Comment by mcrumiller** [comment]
@JulianCologne I like the idea of an additional parameter, but I don't like `null_behavior`: it's too long, even though it's descriptive. One could use `null_strategy` to maintain consistency with other functions like [`sum()`](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.sum.html). pandas uses the `errors` keyword for things like this, and they usually have `raise`, `coerce`, and `ignore`, but I also don't like this parameter keyword either. I think using just `nulls` would be obvious enough, since we're in the context of a string concatenation, or alternatively have separte keywords `ignore_null` and `fill_null`. For example:

* * `s.str.concat("_", ignore_null=False)` # default, raise Exception if nulls present
* `s.str.concat("_", ignore_null=True)` # ignore nulls
* `s.str.concat("_", fill_null="XX")` # more common terminology

The last one keeps in line with the `fill_null` function.

I'm not particularly wedded to any option, but my vote lies for consistency in naming within polars.

**Comment by cmdlineluser** [comment]
[pandas.str.cat](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.cat.html) has the `na_rep` parameter to control this behaviour. (not that the name is particularly good)

**Comment by ritchie46** [comment]
I would accept a PR with `"ignore"` and `"raise"` as `null_behavior` arguments.

I don't want `"replace"`. I strongly feel that we should avoid putting unnneeded compute into `kwargs`. For some cases it is worth the extra complexity and bloatedness of API because it saves a lot of compute, but I don't think this is such a case. 

Filling can be done by the expression itself: `pl.col().fill_null("fill_value").str.concat(..)`, not by an extra keyword argument.

**Comment by avimallu** [comment]
+1. Coming from #8750 after being directed to #3534.

Fully echo on the need to do this, since `pl.sum` provide arguments such as `null_strategy`. It would help to be consistent, and really help avoid surprises especially because of the silent behavior of null propagration.
