### ISSUE TITLE
Left and right suffixes for join

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#7037]
### Problem description

I have seen #4893, so I am aware that additional join complexity is not desired.
I would just like to point out two things:

(1) Almost every time I use polars for a real project, I end up rewriting the same function:
```python
def join(df_1: pl.DataFrame, df_2: pl.DataFrame, on: list[str], suffix_1: str, suffix_2: str):
    common_cols = set(df_1.columns).intersection(df_2.columns)
    df_1 = df_1.rename({x: f"{x}{suffix_1}" for x in common_cols})
    df_2 = df_2.rename({x: f"{x}{suffix_2}" for x in common_cols})
    return df_1.join(df_2, on=on)
````

(2) Users coming from pandas will probably expect this functionality, and join is one of the very basic operations that new users will try right away.

**Comment by zundertj** [comment]
This seems a trivial ask, however:

1. your specific example won't work, because you just renamed the columns that are in `on`, so there are no merge keys. Would you want to automatically rule out the `on`, `left_on`, and `right_on` keys?
2. very quickly there is more complexity to be added if we go down this road: 
   a. sometimes you want suffix on every non-merge key, sometimes only on the conflicting columns (your example), so we need to add a flag for that
   b. some people likes suffixes, others prefixes, so that is another flag
   c. we need to roll this out over all join operations, so not just `join`, but also `join_asof` and `merge_sorted`

So very quickly we end up in a big increase of the API size. I fully agree with Ritchie's assessment in #4893 that this is best left to the user. There is no performance gain from bundling this (in contrast to some of the things that are on the list for joins, like outputting indicators for the origin of the row), and it is totally fine for users to create their own wrapper around `join`, as you have just done here.
