### ISSUE TITLE
Interoperability improvements

### ISSUE THREAD

**Issue by ml31415** [pola-rs/polars#7200]
### Problem description

I'm referring to the recent changes to the indexing behaviour in polars, namely the changes https://github.com/pola-rs/polars/pull/5085 and considerations in https://github.com/pola-rs/polars/issues/3749 . I think that these changes are a regression. Let me kindly explain why I think, that this is not just my personal preferrence and also suggest a better solution.

Polars promises to new users on its website: "Familiar from the start". And I agree, this is a great thing to have, that every potential new user loves to hear. It means a short time span to get used to work with and quick integration into already existing code. In more technical terms, this promise translates to API compatibility and interoperability with previously existing libraries.

And that's clearly something that you want to have from a new package of software on the market. If someone would write a new HTTP client for python nowadays, he'd be well advised to shamelessly copy the `requests` API, so that any user of this new package would just go with `import magichttpclient as requests` and be done with the changes to his previous code base.

I guess this translates well to numpy arrays and the API it brings when modifying array data. The `Series` should be as interchangeable with numpy arrays as possible, so that the users probably wouldn't even notice which one they're currently feeding into their code. This means, especially the indexing, `__getitem__` and `__setitem__` need to work as expected.

Now of course there may be reasons to not exactly copy a previous API. There may be no such clear previous market leader or there may be issues with the previous API, that you don't want to repeat and uglify your own code with. That's understandable. The second best option in such a case would be, to at least try to provide a compatibility layer. This might ideally just look like `from polars.compat import pandas as pd` from a user point of view. In that case, people could slowly migrate to the new API whenever they feel like or want to make use of new features. At the same time, they'd instantly profit from ditching their previous dataframe implementation, having a decent speed gain and less memory issues, with a simple one line change in their codebase.

If you don't even want to do that, maybe because the burden of maintaining that compatibility layer is too high, it should at least be very easy to customize the API in such a way, that users can integrate it into existing code. That would mean, that it should be possible to easily subclass `Series` and `DataFrame`. For what I saw so far, this would currently mean:

- Replacing all occurrences of `Series` inside the class definition of Series with `type(self)`
- Replacing all occurrences of `DataFrame` inside the class definition of DataFrame with `type(self)`
- Introducing the class attribute `DataFrame.series_cls` for easy subclassing and defining, which subclass of `Series` to use internally
- Replacing all occurrences of `Series` inside the class definition of DataFrame with `series_cls`
- Extending `DataFrame.__init__` in such a way, that it takes instances of DataFrame and subclasses as an argument for easy conversion.

These changes would be non-intrusive, easy to maintain, and I'd be happy to provide a PR for that. It could also serve as foundation for a possible compat layer afterwards.

### About indexing DataFrames

DataFrames, as I see it, are a happy hybrid between a dictionary of columns on the one side and array-like objects on the other. When implementing or using `__getitem__`, it's currently hard to express, if you want to address columns or rows. The confusion and complexity in the current `__getitem__` implementation stems mainly from the fact, that it accepts integers for identifying columns, which is ambiguous.

If you really want to simplify `__getitem__` introducing breaking change as done in https://github.com/pola-rs/polars/pull/5085, I'd recommend to accept only a single argument.

- **Column access:** String, list of strings or range of strings: Return a single column or a dataframe with full columns, having near zero overhead on construction.
- **Row access:** Any usual numpy array indexing, namely a single integer, list of integers, a boolean array or a slice, constructing a dataframe having the given selection applied to each column.

`df[X][Y]` would still be the same as `df[Y][X]`, only differing in execution speed. No confusion, intuitive interface, not a single new function name to learn, as it feels exactly like a dict or array in daily use.

You could even keep the two argument option. In that case, the order, if addressing columns or rows first, wouldn't matter anymore. Accessing the columns by index can still be done with the current interface of `df.get_columns([0,1])` or `list(df)[0]`. There would be no additional methods required, no further extension on the API. `df.filter()`would become redundant and might be deprecated.

**Comment by s-banach** [comment]
I agree that some of the proposals in #5085 were extremely confusing. Imagine if `df[0]` selected a column and `df[0:1]` selected a row! I'm glad they chose not to go that way.

When you say "`df.filter()` might be deprecated", it shows a real lack of familiarity with polars. Off the top of my head, there are at least three reasons why `.filter` would never be deprecated, and I'm not even a power user:

(1) Methods like `.select()` and `.filter()` allow us to method-chain a long sequence of operations into a single query across multiple lines. Polars can optimize long queries, especially in `lazy` mode.  This is one of the main advantages of polars over pandas.

(2) `.filter()` works in other contexts besides filtering full DataFrames.

(3) One of the main advantages of breaking `df[boolean_array]` is to help new users. Pandas taught them the bad habit of allocating a boolean array every time they want to filter a DataFrame, and polars tries to help them learn a better pattern.

Here's a pretty trivial example of how `.filter` works better than the pandas pattern:

```python
import polars as pl

df = pl.DataFrame({
    "x": [0, 1] * 300_000,
    "y": [0, 1] * 300_000,
    "z": [0, 1, 2] * 200_000,
})
x = pl.col("x")
y = pl.col("y")
z = pl.col("z")
predicate = (y>0) & (z>0)

# Pandas style
%%timeit
predicate = (df["x"] > 0) & (df["y"]>0)
df.filter(predicate).select("x")
"1.29 ms ± 47.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)"

# Naive polars
%%timeit
predicate = (y>0) & (z>0)
df.filter(predicate).select("x")
"931 µs ± 38.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)"

# Optimized polars
%%timeit
predicate = (y>0) & (z>0)
df.select(x.filter(predicate))
"691 µs ± 18.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)"
```

**Comment by ml31415** [comment]
Yes, sorry. I was referring to having to use `filter` as the only way of applying a boolean array to select rows. I'm totally fine with `filter` staying as it is, I'm merely against `__getitem__` not supporting the full range of common numpy indexing functionality.

**Comment by s-banach** [comment]
I think you can still do `df[list of indices]` or `df[array of indices]`, and they probably don't plan to remove that.
But the boolean indexing is definitely breaking with numpy/pandas.
I'm not 100% sure what the justification was for removing it, besides forcing the users to learn `.filter()`
Maybe one of them will chime in.

**Comment by ml31415** [comment]
As you're specifically mentioning performance, which I forgot to mention in the beginning, I'd like to add:

For interoperability considerations and for the question, if someone might want to migrate his code from another dataframe implementation to polars, performance might be of lesser importance than compatibility. Let's stick with your example above:

- If the code passage in question already _was_ a performance bottle neck, chances are, it would have been optimized already, e.g. using `numba.vectorize`, which gives roughly the same speed as polars.
- If the code passage _was not_ a bottle neck, you might care more about the programmers brain cycles spent for changing large amounts of code compared to the small fraction of speed gain. As long as it's not getting slower, that's fine.

It might actually make sense, to allow the predicates as valid input for accessing the dataframe along the rows using good old `__getitem__`.  Your example above would then look like `df["x"][(y > 0) & (z > 0)]` and be intuitively understandable for anyone with some previous numpy experience.

**Comment by zundertj** [comment]
@ml31415 : I think these are some good thoughts, for instance to see if we can make indexing less confusing, but I do disagree with the main message of sticking to the Pandas api and only deviate where necessary, let me try to explain.

First, Polars has `lazy`, Pandas does not, which results in different design decisions. You could argue that we should with "eager" Polars copy the Pandas api, but that will either mean we have to adapt the lazy api to Pandas as well if we want to keep eager close to lazy, which may be difficult or impossible in places, or we have a break between the lazy and eager api. One of the appeals in the current Polars api is that lazy is seamless and well designed. The discouragement of being able to do too many things with `__getitem__` and `__setitem__` contributes to that massively. It has weaned me off from my Matlab-y habits of using arrays for filtering and masking for example. I don't think we should compromise on lazy vs eager compatibility.

Second, Pandas has indexes as a core component, Polars does away with indexes and supports an `index_column` where needed, such as in `groupby_dynamic`. The Pandas indexing completely changes the logic of `__getitem__` and `__setitem__`, which you can only replicate if you create indices in Polars as well. Pandas indexes are great when it your data has a natural single index, timeseries data in finance comes to mind, but is a major PITA otherwise. Way too many people have spent countless hours trying to figure out why appending a series from one dataframe to another shuffles rows or what not, because the dataframes happen to have different indexes, whilst they never needed indexes to start with. Also, implementing indexes in Polars is a big project in itself.

Three, on the compat layer idea, you mention maintenance as one potential downside, but there are two bigger worries imo:
1. we cannot support in any way the same behaviour as Pandas, given we use Arrow as the backend. When a user assigns a numpy array with `nan`s in it, should we interpret that as `null` or as the floating point `NaN`? We currently offer both behaviours in  [pl.from_pandas](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.from_pandas.html#polars-from-pandas) with a flag, but if you want a general compat layer that you can just drop in, you need to pick one and have to accept that users who want the other behaviour are left out.
2. We prefer to nudge users to use Polars in as much as possible in one (obvious) way, as this simplifies learning the api (less to learn) and makes it easier to read Polars code from others. If we start adding multiple different ways of doing the same thing, we effectively fragment the user base, that is not a desirable outcome.

Four, I think the Pandas api is overall just not very coherent. This is all anecdotal, although there are plenty of others with the same experience, that you have to refer to the docs a lot when using Pandas; I find myself doing this less with Polars. This is, in part due to the history and wide usage Pandas has that has driven api design decisions, but I think it is therefore a bad idea to try to cover as much as possible from the Pandas api. You refer to `requests`, which has a well designed api as you say. In fact, you might as well replace your hypothetical library with [httpx](https://github.com/encode/httpx). For `httpx` it works, because the `requests` api is well designed and the "new stuff" (async, etc) fits in well with the `requests` api. That is, as explained above, not the case for Polars vs Pandas.

Five, I think users migrating a code base from Pandas to Polars should do that piecemeal, and use `from_pandas` and `to_pandas` (with the right nan handling flags) to glue the pieces together. That will lead to a much more predictable outcome, as the libraries are different enough that you can't really replace one for the other without too much thought. It would be great if we could just drop it in, but there are good reasons it is not, and trying to sell to users that they should try to use Polars as a drop-in replacement will only lead to disappointment.

**Comment by ml31415** [comment]
@zundertj thanks for your detailed answer. We absolutely share the concerns about the pandas API and I didn't intend advocating for it. Though, many people use it and I think it would make sense to have a compatibility layer to address those previous pandas user and make it easier for them to switch.

The main and underlying point I tried to make was, to make polars interface easier to customize, to subclass `DataFrame` and `Series` _in general_, not only for pandas users. E.g. in our lab we wrote our own dataframe-like container class at about the same time pandas came out, improved it now and then and still use it today. If we'd want to replace it, there would be ton of code to adapt. And that's just our lab. To make that easy, the closer I could adapt polars to behave more like the previous dataframe, the less hazzle when migrating.

About the two points you made:

- No `null` in pandas, so by default for a compat layer, no automatic conversion from `nan` to `null` either.
- Fragmenting the user base: Yes, that's a valid point from a developer point of view. But otherwise, polars might never be used in many existing projects. The harder it is, to integrate polars into existing code, the more you'll see it applied only to greenfield projects. So the question is: Larger user base vs. non-fragmented user base.

About "nudging" people to a new (lazy) API, I honestly think, that's a bad idea. There are a lot of occasions, when eager API is "just good enough" or fast enough, or has more concise code etc. It's great to have the lazy API on top if you need it. But why discouraging the eager API? Why pressure people to stop using, what they used to use for maybe even more than ten years now, namely standard numpy indexing? It's the opposite of being "familiar from the start". If something is better or required for their use case, people will start to use it by themselves, no worries. :)

Also, I don't think the compat layer would need to be perfect or complete. It would be totally fine to have loud warnings, to avoid any disappointments. E.g. it might have no direct write access to the arrays. Though, it would make life much easier, if after a migration, you'd have to fix only 20% and not 80% of your test cases. It would make the migration not only easier, but more likely to happen at all.

About `to_pandas` and `from_pandas` or converting forth and back between different dataframe implementations in general: That's of course possible, but I think not the way you'd happily go. It would mean to have substantial amounts of code either being compatible with both implementations, or duplicating and adapting lots of code for certain dataframes. Also, one of the key selling points of polars is, that it avoids lots of memory limitations. So if you already feel the memory limitations with pandas (or any other eager dataframe) and therefore want to migrate, I'm afraid this might make things even more complicated due to further copying.

**Comment by ritchie46** [comment]
Holding "familiar from the start" against us is not completely fair IMO. It could be argued from a SQL point of view as well. The phrase was coined by someone who helped me setup the website initially and we never changed it. If you think it is wrong, I am happy to remove it.

You may hold our API against this list: https://github.com/pola-rs/polars/issues/6120#issuecomment-1374911565

And then have a discussion more fruitful than "library X" does it that way. I want to be free of that baggage to make a technical optimal solution. Our API should serve our goals, likewise the API of numpy should serve their goals.

Why I think using `__getitem__` for passing masks of type `List<Boolean>` is bad is because it is less explicit than `filter`. `__getitem__` should not serve as a garbage can for different types.

Being explicit greatly improves readability. Take two functions that are badly named with badly named variables. Polars forces you to make that readable. The `getitem` can only selection by index so that is a `take`, The `filter` can only accept a boolean mask so that is, well a `filter`. 

```python
def my_function(df: pl.DataFrame, s: pl.Series) -> pl.DataFrame:
    return df[s]


def my_function(df: pl.DataFrame, s: pl.Series) -> pl.DataFrame:
    return df.filter(s)
```

We are willing to make API changes. But I don't think there is a compelling reason to use getitem for boolean mask if we take our API goals https://github.com/pola-rs/polars/issues/6120#issuecomment-1374911565 in mind.

**Comment by zundertj** [comment]
One clarification on my previous post: if your goal is to make the Polars Python api easier to subclass, without any downsides for other users, I would not see anything against that. I know there have been requests on that topic before, and changes been made, to accommodate that use case. 

If you think the subclassing changes put your lab onto to path of bringing in Polars as the "engine" for your dataframe library, i.e. to create your own compat layer, you should do so. I would personally recommend against that for reasons described in my previous post, but there are other places which do this, so maybe I am simply wrong on this being a bad idea for migrating an existing code base.

However, my points against the introduction of a compat layer *for everyone*, i.e. an official Polars-Pandas compat layer, still stand, it fragments the user base and makes learning Polars more difficult, where with "learning Polars" I mean learning the actual api, not the compat layer. The supposed benefit is also quite small given this will be a "80%" solution, which sets up users for disappointment.

**Comment by ml31415** [comment]
Hello again! I attached a suggestion, how this easier subclassing might look like in detail. I understand, that touching API is always a sensitive topic, so mb this PR is something, that you could live with as well.

**Comment by ml31415** [comment]
To add some more perspectives to the discussion:

Pandas had the same discussion about making subclassing easy or not, starting as early as https://github.com/pandas-dev/pandas/issues/60 . After lots of forth an back and several different suggestions about how to implement it followed, e.g. https://github.com/pandas-dev/pandas/pull/2865 and https://github.com/dalejung/pandas-composition . For some time now there is this central constructor method for frames and series in the code, which makes subclassing easy enough, without having to rewriting a ton of frame and series methods.

```python
    @property
    def _constructor(self) -> Callable[..., DataFrame]:
        return DataFrame

    _constructor_sliced: Callable[..., Series] = Series
```

I'd also like to remind about the former inability of Python to subclass `list` and `dict` directly, trying to tell people to use `UserDict` and `UserList` instead. This got finally fixed, so that subclassing these standard containers was straight forward.

In both cases, ease of use finally won over concerns about implementation details. Subclassing is a popular feature for good reason.

**Comment by MarcoGorelli** [comment]
> The second best option in such a case would be, to at least try to provide a compatibility layer

You might be interested in https://data-apis.org/blog/dataframe_standard_rfc/

It's not ready yet, but hopefully it'll allow third-party libraries (e.g. feature engineering / visualisation / data cleaning) to support polars (and other dataframe libraries) without having to convert to pandas internally

**Comment by alexander-beedie** [comment]
This appears to have become more of a discussion than an Issue with an actionable item; for the sake of clarity I'll close it out. I think it's clear from the last few months that the API (and specifically its clarity) has received a lot of positive attention, _specifically_ in comparison to pandas, so any desire to make parts of it more pandas-like is probably zero at this point ;)

If something actionable remains, please feel free to make a new Issue 👍
