### ISSUE TITLE
dtype arg for `DataFrame.to_numpy()`

### ISSUE THREAD

**Issue by s-banach** [pola-rs/polars#7283]
### Problem description

`DataFrame.to_numpy()` automatically determines the dtype of the output:
https://github.com/pola-rs/polars/blob/d80cebfd0c1ae8c33f36f836374ff3decdc75f30/py-polars/src/to_numpy.rs#L152-L159

Many statistical models (especially linear models) only use float64 dtype internally.
So we have to do something like `DataFrame.to_numpy().astype(np.float64)`.
In some cases, this creates two copies of the data.

It would be a nice feature to allow the user to specify the dtype of the output, rather than inferring it automatically.

**Comment by zundertj** [comment]
Just to be sure I understand the request, you want to be able to do
```python
df.to_numpy(dtype=np.float64)
```
i.e. pass in a numpy dtype,  and have this be syntatic sugar for

```python
df.select(pl.all().cast(pl.Float64)).to_numpy()
```
?

On your benchmark, it does not seem fair to measure the numpy cast from `int32` to `float64`, but not do the same with the Polars solution? I.e. in the `df2` timing you do not measure the cast?

**Comment by s-banach** [comment]
When I create `df2`, I am casting one column to `float64`.
When I call `df2.to_numpy()`, I am casting the other `999` columns to `float64`, because `numpy` arrays are homogeneous.

**Comment by s-banach** [comment]
I'm sorry I don't know understand rust very well, but here's what I'm talking about.
https://github.com/pola-rs/polars/blob/af2a1247f0af5b7152067a9c4f6d88627e266182/py-polars/src/dataframe.rs#L644
Right now, this function automatically determines the supertype `st`.
I wish the user had the option to manually specify `st` as well.

**Comment by stinodego** [comment]
For Series, this will not save you any copies over casting manually except for when working with String data. But string data will not be zero copy anyway, so I don't think a dtype parameter is worth it.

For DataFrame, this may save a copy because the DataFrame columns will usually not be contiguous in memory, in which case the `to_numpy()` call is not zero-copy.

Potentially useful, will have to think about it.

**Comment by stinodego** [comment]
I have decided to mark this as "not planned". It's not that we'll never want to support this, but I don't see it happening because:

1. You can already get the desired _outcome_ by using `.astype(np.float64, copy=False)` afterwards or `.cast(pl.Float64)` before the conversion.
2. In a lot of situations, specifying the dtype will not have a benefit over using `.astype(np.float64, copy=False)` after the fact.
3. We would have to implement all kinds of additional custom casting logic to handle things like `pl.Series([-1, 1, 100]).to_numpy(dtype=np.uint8)`. This might end up being more expensive than paying the memcopy.
4. The additional memcopy cost is not _that_ expensive.

I don't think this is worth adding.
