### ISSUE TITLE
Remove automatic pandas imports that slow import times

### ISSUE THREAD

**Issue by sslivkoff** [pola-rs/polars#7534]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Looks like this automatic pandas import from #4493 is back in the current polars version, and it's now slowing down polars imports by hundreds of ms

Looks like the relevant files are:
- `py-polars/polars/internals/construction.py`
- `py-polars/polars/convert.py`
- `py-polars/polars/internals/dataframe/frame.py`
- `py-polars/polars/internals/series/series.py`

Each contains the line `from polars.dependencies import pandas as pd`, which makes it so that pandas is imported whenever polars is imported. This can be avoided by lazily importing pandas only in the places it is actually used, or by wrapping the import in a `if typing.TYPE_CHECKING` block

Looks like not all of these new imports can be wrapped under a simple `if typing.TYPE_CHECKING` because `pd` is being used for some `isinstance()` checking. in those cases pandas could be imported lazily or type checks could be performed in an alternate way (like either 1) a TypeGuard that lazily imports pandas or 2) checking the names of the modules in `type(...).__mro__`)

### Reproducible example

```python
import sys
import polars as pl

assert 'pandas' in sys.modules
```

### Expected behavior

```
import sys
import polars as pl

assert 'pandas' not in sys.modules
```

### Installed versions

<details>

```
Polars: 0.16.13
```

</details>

**Comment by alexander-beedie** [comment]
Thanks for the heads-up! However, the line `from polars.dependencies import pandas as pd` _is_ a lazy import, so that isn't the proximate cause. I've just re-profiled imports...

![polars_imports](https://user-images.githubusercontent.com/2613171/224921197-a858d55f-e852-445c-94b0-d8ea44f289fa.png)

...which should help track it down 🤔

**Comment by ritchie46** [comment]
Somehow `numpy` is in there again. We should try to get that out of there. The `emails.utils` also is suspect to me. We were on 75ms, now back on 200ms. 

Let's add a benchmark for this in CI. As this is something I think is totally worth keeping low.

**Comment by alexander-beedie** [comment]
> Somehow `numpy` is in there again. We should try to get that out of there. The `emails.utils` also is suspect to me. 

Yup... I can track it all down tonight when I get home.

**Comment by alexander-beedie** [comment]
Ahhhh, I suspected as much earlier, but now I'm back home it was easier to confirm how all these imports leaked back in (the import graph in a clean env is worse than the above, as it includes pandas). 

Unfortunately it's the new `singledispatch` constructors; if you have pandas/numpy _available_, that is sufficient to trigger import via the registering decorators (a bit obvious in hindsight...)

eg: _(polars/internals/construction.py)_
```python
if _NUMPY_AVAILABLE:   # << if it's available...

    @_sequence_to_pydf_dispatcher.register(np.ndarray)  # << ...the lazy loader has to invoke numpy here
    def _sequence_of_ndarray_to_pydf(
```
There are also registrations for `pd.Series` and `pd.DatetimeIndex`, hence pandas reappearing too. However, I can easily rearrange it all tomorrow so that we get our super-fast import times back, and I'll try to minimise potential `isinstance` spaghetti...

**Comment by sslivkoff** [comment]
awesome. fast import times make polars very suitable for CLI tools where latency matters. also more cost-effective for short-lived faas jobs

**Comment by alexander-beedie** [comment]
> awesome. fast import times make polars very suitable for CLI tools where latency matters. also more cost-effective for short-lived faas jobs

@sslivkoff: Bonus reduction in import time for you, following the previous fix... see: https://github.com/pola-rs/polars/pull/7584  ;)
Also created some dedicated test coverage to ensure no regressions going forward.

Thanks for the report!

**Comment by jakob-keller** [comment]
Mea culpa and thanks for the fix!
