### ISSUE TITLE
`.head()`/`limit()` consistency between eager/lazy syntax

### ISSUE THREAD

**Issue by markfairbanks** [pola-rs/polars#769]
In polars there is a `.head()` method for eager evaluation, but a `.limit()` for lazy evaluation.

Should these be called the same thing?

```python
import polars as pl
from polars import col
import numpy as np

df = pl.DataFrame({'x': np.arange(1, 4),
                   'y': ['a', 'b', 'c']})

# Eager uses .head()
df.head(2)

# Lazy uses .limit()
df.lazy().limit(2).collect()
```

And a side question - is there an advantage to using the lazy API other than query planning?

Thanks again for all the work on this great package.

**Comment by ritchie46** [comment]
No, there is indeed an inconsistency. I think there should be aliases for both in eager as well as lazy. Pandas users will be accustomed to `head` and in lazy, I want to have the SQL-like syntax. I will add aliases. :+1: 

> And a side question - is there an advantage to using the lazy API other than query planning?

Mostly query planning. But because I run the queries in a runtime/query engine, I also can make last minute decisions that I cannot make in `eager` (Not entirely true, because a lot of eager is syntactic sugar for lazy).

An example is the groupby algorithm. Just before executing the groupby, I sample the keys that are used to group and if the cardinality is low, I choose a partitioned groupby, which is a lot faster in a low cardinality case.

> Thanks again for all the work on this great package.

You're welcome, spread the word! :smile:

**Comment by ritchie46** [comment]
Added and released :+1:
