### ISSUE TITLE
Sink to csv

### ISSUE THREAD

**Issue by jhahnfeld** [pola-rs/polars#7905]
### Problem description

Hi, it would be nice to have a `sink_csv()` function for the streaming mode of Polars.
This would be helpful for the downstream use of tools which only support csv/tsv inputs.

**Comment by fernandocast** [comment]
Hello, I'm new to Polars and I would like to contribute 😄 
Can I work on this issue?

**Comment by thomasaarholt** [comment]
@fernandocast I am sure there are many who would appreciate you working on it, I think you can just go ahead.

**Comment by fernandocast** [comment]
> @fernandocast I am sure there are many who would appreciate you working on it, I think you can just go ahead.

Hi @thomasaarholt, I just started to work on this, do you know if someone could please assign me the issue?

This is the fork where I will start to publish the code:
https://github.com/fernandocast/polars

**Comment by fernandocast** [comment]
Hello @ritchie46,

I think this is not cool, because I already spent one week working on this feature. I think we should define a better way to collaborate to avoid duplication of efforts. Making a better use of developers time will be beneficial for the Polars project.

Perhaps assigning the ticket with daily/weekly updates in the progress can help to avoid these situations in the future.

**Comment by thomasaarholt** [comment]
@fernandocast I take some responsibility here (just fyi, I'm not part of the core polars team, just a random developer). Unfortunately, github repos often get posts like "can I work on this", with no further comment or update. Since you hadn't posted anything (not even a link to the branch other than your fork), I actually assumed that this was one of those cases. For what its worth, I'm really sorry that this happened this way.

In general, I would highly encourage you to open a PR in draft mode whenever you start working on something - this is something I could have suggested to you above, but also something that I think is an expected thing to do - I don't know from your post whether this is your first PR to open source or whether it is your 100th PR, so I didn't want to assume either way when you linked to your fork.

If you're still interested in contributing - especially with the work that you have been doing, then I suggest you take a look at @svaningelgem's PR, and even though it is merged, you might perhaps have done something that they haven't thought of - after all, it was their first PR in rust, and I'm sure they will welcome any thoughts.

**Comment by ritchie46** [comment]
I am sorry @fernandocast. I didn't realize this. I reviewed a PR that was ready and merged it when I thought the changes were ok. I did not realize there was contention.

Again sorry.

**Comment by svaningelgem** [comment]
My apologies @fernandocast , I needed this (fast) for my project at work so I started to tap away at my keyboard. Didn't even bother to check if I could assist you in bringing that fork to be merged. My bad!
I'll try to see in the future if someone has already an open fork where I can chime in/base myself on.

**Comment by fernandocast** [comment]
Hello Guys,

Thanks a lot for your support and comprehension, it makes me feel welcome to the Polars project, I really appreciate your words @ritchie46 @svaningelgem @thomasaarholt.

In the feature I'm going to include my working branch so everyone sees my progress and avoid any misunderstandings.
