### ISSUE TITLE
Support expression inputs in all expression functions

### ISSUE THREAD

**Issue by wangkev** [pola-rs/polars#8065]
### Problem description

It looks like only a subset of expression functions support expression inputs, e.g. `pl.sum`, `pl.all`, `pl.cov`. Other expressions only support string inputs, e.g. `pl.count`, `pl.std`, `pl.var`. Can we support expression inputs in all the functions?

**Comment by zundertj** [comment]
Been looking into this, and it is a simple change. However, I feel that allowing expressions as inputs is not great for trying to be the api as succinct as possible, and maybe these functions are  unnecessary API surface altogether.

Take `pl.std` as an example, this is basically what it does:
```python

def std(column: str | Series, ddof: int = 1) -> Expr | float | None:
    if isinstance(column, pli.Series):
        return column.std(ddof)
    return col(column).std(ddof)
```
So either dispatch to `Series.std` or to `Expr.std`. `Series.std` will cast the Series to  a Dataframe and use `Expr.std` ultimately.

Probably the reason these functions have been created is that you can write `pl.std("a")` rather than `pl.col("a").std()`, accepting expression inputs is defeating that short-cut: `pl.std(pl.col("a"))`. Given the Polars api is so much about creating and modifying expressions, the added value of these functions is actually quite limited, unless we indeed allow `pl.std(pl.col("a"))`, but that goes against the idea of keeping the API limited. So there are conflicting goals here, and I am more leaning towards removing these functions altogether rather than allowing expression inputs.

@ritchie46 @stinodego : Any thoughts?

**Comment by stinodego** [comment]
I agree with @zundertj here.

The use case outlined here seems quite niche to me (though I may be wrong on that).

For now, I'd prefer to just have `pl.sum(x)` and similar as a shortcut for `pl.col(x).sum()`. I'll close this as 'not planned' for now - although I can see myself change my mind on this one.
