### ISSUE TITLE
Please clarify if a single column can contain multiple timezones

### ISSUE THREAD

**Issue by blais** [pola-rs/polars#8289]
### Research

- [X] I have searched the above polars tags on Stack Overflow for similar questions.

- [ ] I have asked my usage related question on [Stack Overflow](https://stackoverflow.com).

### Question about Polars

Polars appears to support a single timezone id (e.g. `America/New_York`) with distinct timezone records (`EDT`, `EST`).
I was hoping that Arrow (and thus Polars) might support columns with mixed timezones.

It would be really useful to add to the documentation the particular treatment of timezones---how many can there be, and for example, what's the distinction of a column with timezone `EDT` and `America/New_York` (are they both timezones? If so, there must be a concept of timezone-within-timezone to account for DST, the terminology is unclear).

**Comment by MarcoGorelli** [comment]
Hi @blais 

> Polars appears to support a single timezone

That's right, each column must have a single time zone. EDT and EST appear to the same time zone (`America/New_York`) so they're fine

If your input data contains mixed offsets, what you can do is pass `utc=True` so they'll all be converted to UTC https://pola-rs.github.io/polars-book/user-guide/howcani/timeseries/parsing_dates_times.html#mixed-offsets

**Comment by deanm0000** [comment]
I'm not sure what the correct term to use but EST and EDT aren't timezones, they're labels or abbreviations. The timezone is, singularly, America/New_York. That you see values labeled as both EST and EDT doesn't mean there are mixed timezones just that your timezone observes daylight savings.

**Comment by blais** [comment]
@deanm0000 I understand. I'm surprised how poor the terminology for these objects are. AFAICT America/New_York is a "timezone identifier". For EST/EDT I've found the terms "timezone record" or "timezone abbreviation" (as you mention).

FWIW, my ticket is about genuinely mixed columns of different timezone identifiers.  Clarifying the docs about these things would be beneficial for those of us finding themselves halfway through the timezone rabbit hole.  The world would possibly have been a better place if a 64-bit type had been defined that reserved 127 bits for a timezone, and we wouldn't have to coerce a column to a single one (this remains a special case everywhere I look).

What's more, is that it might be an improvement if columns were prevented from being associated with a timezone abbreviation, that is, restricted to a timezone identifier.  Pandas allows timezone identifiers, abbreviations, and other zones like "LMT" or even "FixedOffset". IMHO it would be improved if it failed instead of allowing those, requiring instead the user to provide a timezone identifier where there's none.  (But then someone would have to take the users for a visit down the rabbit hole...)

**Comment by MarcoGorelli** [comment]
thanks, I've opened https://github.com/pola-rs/polars-book/pull/297 to try to clarify the docs

> that it might be an improvement if columns were prevented from being associated with a timezone abbreviation

not sure what you mean, sorry - could you give an example of what's currently allowed in polars which you'd like to disallow?

**Comment by MarcoGorelli** [comment]
can this be closed? I don't think there's anything actionable here

**Comment by blais** [comment]
I've been meaning to test if polars allows a timezone abbreviation to be
set on a column.  That would be suboptimal (ideally only timezones IDs
should be allowed; do you agree?). Been busy. You can close, I'll reopen
when I find the time to check

**Comment by MarcoGorelli** [comment]
thanks - it doesn't, no, only `Location/Area` or fixed offsets are allowed

**Comment by blais** [comment]
Try this: ```
df.select([
    pl.col("date"),

    (pl.col("date").dt.convert_time_zone(time_zone="Europe/London").alias("ldn")),
    (pl.col("date").dt.convert_time_zone(time_zone="GMT").alias("gmt")),   # Does not fail.
    #(pl.col("date").dt.convert_time_zone(time_zone="BST").alias("bst")),  # Fails (good)

    (pl.col("date").dt.convert_time_zone(time_zone="America/New_York").alias("nyc")),
    (pl.col("date").dt.convert_time_zone(time_zone="EST").alias("est")),   # Does not fail.
    # (pl.col("date").dt.convert_time_zone(time_zone="EDT").alias("edt")),   # Fails (good).
    
    #(pl.col("date").dt.convert_time_zone(time_zone="Asia/Hong_Kong").alias("hkg")),   # Does not fail.
    # (pl.col("date").dt.convert_time_zone(time_zone="HKT").alias("hkt")),   # Fails (good).
])
```

"EST" appears to be grokked. So does "GMT".

**Comment by blais** [comment]
![image](https://user-images.githubusercontent.com/336019/235372334-a55f4c33-aa6d-4c2b-b13b-be04bbab6d7f.png)

**Comment by MarcoGorelli** [comment]
thanks, wasn't aware - under the hood it's just [chrono-tz](https://docs.rs/chrono-tz/latest/chrono_tz/), if it passes `time_zone.parse::<chrono_tz::Tz>()` then it's currently allowed (I mistakenly thought that would only be 'Area/Location' strings, but as you've pointed out they also allow abbreviations like 'EDT')

**Comment by MarcoGorelli** [comment]
for reference, here's a related discussion in pandas: https://github.com/pandas-dev/pandas/issues/50887#issuecomment-1536583101

thoughts on mirroring the pyarrow behaviour here too, and then only allowing `'area/location'` time zones as dtypes?

**Comment by MarcoGorelli** [comment]
cc the extremely knowledgeable @FObersteiner

**Comment by MarcoGorelli** [comment]
Concrete suggestion:

- `to_datetime` converts to `'datetime[μs]'` if input is time-zone-naive, and to `'datetime[μs, UTC]'` if input is time-zone-aware
- argument `utc` disappears
- only `None`, `'UTC'` and `'Area/Location'` time zones would be accepted in `replace_time_zone` / `convert_time_zone` (and other places which accept time zones).
  In particular, support for fixed offsets (e.g. '+01:00') in dtypes would be deprecated.

Warning wise:
- warn if `utc` in `to_datetime` / `strptime` is anything other than `True`, but note that it will be removed in a future version
- warn if `time_zone` is not `None`, `'UTC'`, or `'Area/Location'`, asking users to use the corresponding `'Area/Location'` name instead

Benefits:
- if parsing datetime strings with multiple offsets, then users would have had to pass `utc=True` first anyway. So this would save them a step;
- if parsing datetime strings with a single offset, then users now get a dtype like `'datetime[μs, +01:00]'`, which could be misleading: multiple time zones have `'+01:00'` offset at some point during the year. By 'forcing' them to convert to their 'Area/Location', they can save themselves from future bugs due to DST
- consistency with pyarrow
- for developers: this would remove a lot of complexity, as all these
  ```rust
      match parse_offset(&tz) {
          Ok(_) => Ok(()),
          Err(_) => match tz.parse::<Tz>() {
              Ok(_) => Ok(()),
              Err(_) => polars_bail!(ComputeError: "unable to parse time zone: '{}'", tz),
          },
      }
  ```
  could just become
  ```rust
      match tz.parse::<Tz>() {
          Ok(_) => Ok(()),
          Err(_) => polars_bail!(ComputeError: "unable to parse time zone: '{}'", tz),
      }
  ```

**Comment by FObersteiner** [comment]
+1 for supporting and recommending `Area/Location` time zone names. That's the clear and unambiguous way to specify time zones IMHO.

It basically means a subset of the [IANA db identifiers](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). IANA tz db supports a lot of obsolete identifiers (see comments in Paul Eggert's tz repo, [e.g. here](https://github.com/eggert/tz/blob/main/northamerica)), for example "US/Eastern" for the now recommended "America/New_York". I'm not sure however, how excluding *some* identifiers would work out, having chrono-tz as backend. I suppose chrono-tz provides full IANA db support.

Regarding [tz name abbreviations](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations) such as EST/EDT - although commonly used, technically they just give you offsets from UTC, not time zones with associated rules when DST transitions happen etc. They come with pitfalls like
- What if you encounter a date/time string that specifies "EST" but the date is in northern hemisphere summer?
- What if you encounter a date/time string that specifies "BST" - is that "Bangladesh Standard Time"? Or "British Summer Time"? etc.

To my knowledge, pandas supported some of those abbreviations in the past, but now raises warnings. Not supporting those in the first place seems more efficient to me.

Pure UTC offsets (such as +01:00) would be fine for me; you cannot apply time zone rules, but you can convert to UTC without issues. 
> if input is time-zone-aware

In this case, I would not say "tz aware", just "offset aware"... Btw. I still like the `utc=True` keyword since it clarifies what's happening ;-) But it would become kind of obsolete if the conversion to UTC is enforced as I understand your suggestion @MarcoGorelli ?

**Comment by MarcoGorelli** [comment]
thanks for your thoughts!

> Pure UTC offsets (such as +01:00) would be fine for me; you cannot apply time zone rules, but you can convert to UTC without issues.

Yeah exactly - the only use of `+01:00` timezones in dtypes is after parsing and before converting to UTC or some area/location time zone. If the conversion to UTC happened by default, then there'd be no need for them

You are correct, "offset-aware" would be more accurate. But that's right, `utc=True` would become obsolete

**Comment by blais** [comment]
On Sat, May 6, 2023 at 3:59 AM Marco Edward Gorelli <
***@***.***> wrote:

> Concrete suggestion:
>
>    - only None, 'UTC' and 'Area/Location' time zones would be accepted in
>    replace_time_zone / convert_time_zone (and other places which accept
>    time zones).
>
> SGTM!


>
>    - In particular, support for fixed offsets (e.g. '+01:00') in dtypes
>    would be deprecated.
>
> Sounds reasonable to me to.

In other words, my view is that if someone attempting to use a fixed offset
or timezone abbreviation instead of a timezone identifier faces a failure
or error, that's desirable behavior. Users having to go through the very
small hurdle of providing a valid timezone identifier is an exercise that
would simplify the understanding of timezones and bring clarity.

**Comment by ritchie46** [comment]
I think I like it. I am not knowledgeable enough about time-zones to understand all intricacies, but I understand `"+01:00"` is ambigious during the year.

And, I am very much in favor of reducing complexity for us and the user. :+1: Let's do this. :)
