### ISSUE TITLE
What's the performance difference of polars when used with rust vs python

### ISSUE THREAD

**Issue by MeRahulAhire** [pola-rs/polars#8391]
I'm just getting start with data analysis and recently discovered Polars. I saw there's two kinds of language support - rust and python. 

I wanted to know is there any performance difference between using python as compared to natively using Rust?

Your help would be highly appreciated, Thanks...

**Comment by ritchie46** [comment]
I'd say run your benchmark. It depends on the query. If you only use polars primitives, most of the time python is faster because we compiled with aggressive optimizations.

**Comment by MeRahulAhire** [comment]
In generally what's the scenario? If python is faster then is there any reason if I should use rust version of this library? Anyone will assume that rust is faster. 
Q 1. Are you and other maintainer focused more on python as most people use python in their work
Q 2. Is the python library a wrapper for compiled rust binary of this polars?

**Comment by ritchie46** [comment]
Run your benchmark and decide for yourself. Both python polars and rust polars are fast. I don't know which suits your use case best.

**Comment by alexander-beedie** [comment]
> Is the python library a wrapper for compiled rust binary of this polars?

More or less... the entire engine and all of the heavy lifting is done in Rust. Python-side idioms are accounted for on the Python side, eg: pythonic slice syntax like `df[x:y:z]`, which doesn't have a direct Rust counterpart (but that still just redirects directly to the underlying Rust core where all of the "real work" is being done).

* I'd say if you're already using Rust, use the Rust version.
* If you're using Python, use the Python version.
* If you haven't made up your mind, start with whichever you feel most comfortable with or with what best integrates with your wider project/ecosystem.

What surprises some people is that the Python version can actually be faster - however, as Ritchie says, this is only because we know that the version of the engine shipped with Python will _always_ be compiled optimally and with all the features turned on. We have no control how other projects choose to compile their Rust libraries/code, so cannot make the same guarantees - and therefore cannot give you a simple "X version is Y% faster/slower" answer. However, neither version _has_ to be meaningfully slower than the other, so you can choose the one that suits you best without any FOMO.

**Comment by MeRahulAhire** [comment]
Thanks for the detailed overview @alexander-beedie . I'll test it initially in python and then see if there's any benefit of rust - comparison.
