### ISSUE TITLE
Consistent implementation of LazyFrame column-wise max, min, sum, etc.

### ISSUE THREAD

**Issue by mishpat** [pola-rs/polars#8505]
### Problem description

This borders on a bug but I believe is consistent with the documentation as written. In 17.18,
```
    ldf = ldf.select([
        pl.max([pl.col("^x.*$")]).alias('x_max'),
        pl.sum(pl.col("^x.*$")).alias('x_sum')]
    )
```
runs as expected, dropping the iterable from the max operator and using any expression that pulls multiple columns fails:

```
    ldf = ldf.select([
        pl.max(pl.col("^x.*$")).alias('x_max'),
        pl.sum(pl.col("^x.*$")).alias('x_sum')]
    )

ValueError: could not convert value 'COLUMNS(["^x.*"])' as a Literal
```

The logic for parsing input across these aggregations is slightly different in py-polars/polars/lazyframe. Arguably, identical logic for parsing input types should be implemented across all the column-wise aggregation functions.
This should be an easy fix and I intend to work on it, but I am documenting it here for completeness.

**Comment by stinodego** [comment]
I am aware of this bug - I think I introduced it. But it's not quite trivial to work out what the correct behaviour should be.

Behaviour is either row-wise or column-wise. Logically, you'd say passing a single column would result in row-wise computation, while passing multiple columns results in column-wise behaviour. But determining when that is, is not that easy.

Single input:
* Regular string -> row-wise
* Regex string -> column-wise
* Single-column expression -> row-wise
* Multi-column expression -> column-wise

Iterable input:
* Of length one -> same behaviour as above
* Of length two or more -> column-wise

But then again, maybe this is not very intuitive either. The problem is really that one function is trying to do two things.

**Comment by mishpat** [comment]
Yes, ideally the functionality would get moved out into another name, e.g. "rowmax" or so. I didn't even think of the case where the regex only matches one column, which is worse. That example makes me think that splitting the names is the best long-term solution; presently perhaps we should enforce that row-based aggregations require an actual iterable. With this change, the behavior of my first example above would fail because of the sum while the second example would operate like pl.col(regex).sum() currently does

**Comment by stinodego** [comment]
After thinking on it a bit, I think it should work like this (for now, at least):

* `pl.min` will compute the column-wise minimum of the inputs
* Special case: when given a single string input, `pl.min(s)` is an alias for `pl.col(s).min()`
* Special case: when given a single Series input, `pl.min(s)` is an alias for `s.min()`

I am already writing some tests / adjusting code.
