### ISSUE TITLE
Add "scan_excel" as a lazy way to read multiple XLSX files (like scan_csv)

### ISSUE THREAD

**Issue by Marmeladenbrot** [pola-rs/polars#8552]
### Problem description

I wish I could use polars to read a folder of xlsx files into a dataframe the same way I can do it via scan_csv like in this tutorial: https://pola-rs.github.io/polars-book/user-guide/multiple_files/intro.html

Could look like:

```
import polars as pl
import glob

queries = []
for file in glob.glob("*.xlsx"):
    q = pl.scan_excel(file)
    queries.append(q)

dataframes = pl.collect_all(queries)
print(dataframes)
```

**Comment by deanm0000** [comment]
polars uses the xlsx2csv library to convert xlsx files to csv so the benefit of a lazyframe is sort of shot by then since it already would have read the xlsx file by then. I might be wrong there.

You could just do `q=pl.read_excel(file).lazy()`

or alternatively you could batch the xlsx2csv on all the excel files creating a csv copy of each on disk then use `scan_csv` directly on those copies.

It's not clear from your request if what you really need is the syntax from above or if, in the name of brevity, you're excluding some operations that you actually perform on `q` which are memory intensive and you really need the frames to be lazy until the `collect_all`.

**Comment by alexander-beedie** [comment]
There will never be a true `scan_excel` as it is not possible to read Excel files lazily; the Excel file format is actually a compressed ZIP file containing an internal directory structure full of interrelated XML files ;)

However, you could certainly make the result of the reads lazy and go from there:
```python
import polars as pl
import glob

# read excel files, creating a single lazy result frame
frames = [pl.read_excel(file).lazy() for file in glob.glob("*.xlsx")]
lf = pl.concat(frames, how="vertical")

# do stuff with 'frame'
# lf = lf.<do_stuff>

# finally collect the result
df = lf.collect()
```

**Comment by kgutwin** [comment]
I did some very trivial testing of openpyxl's [constant memory read-only mode](https://openpyxl.readthedocs.io/en/latest/optimized.html) and I think it might be possible to use the new IO Plugins feature in Polars to implement `scan_excel`. It would be substantially slower than `read_excel` with the default `calamine` engine, but it would have advantages in memory usage and processing time when only a small amount of data is needed from a large Excel file. I'll try to give it a shot and will report back if I can get it to work.

**Comment by daviewales** [comment]
Is it strictly true that you must read _all_ of an Excel file to extract the data?
I believe it's possible to extract single files from zip archives without reading the whole zip.
For example, this library can read single files from online zip archives, without downloading the whole archive(!):
https://github.com/saulpw/unzip-http

This leaves the question of whether it's possible to extract just the metadata which might be required for `scan_`, and whether that provides any benefit.
