### ISSUE TITLE
Chained filter raises ShapeError

### ISSUE THREAD

**Issue by LdRoW** [pola-rs/polars#8694]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Using chained filters on expression leads to ShapeError. Looks like second filter operation is executed on source column but applied to already filtered.
```python
exceptions.ShapeError: filter's length: 8 differs from that of the series: 2
```

### Reproducible example

```python
import polars as pl

with pl.StringCache():
    df = pl.DataFrame(
        {
            "a": pl.Series(["a", "a", "b", "b", "c", "c", None, None], dtype=pl.Categorical),
            "b": pl.Series(["a", "a", "c", "b", "c", "c", None, None], dtype=pl.Categorical),
            "val": pl.Series(range(0, 8)),
        }
    )

    flt = pl.col("a") == "b"
    plan = df.lazy().select(
        [
            pl.col("val").filter(flt).filter(pl.col("b") == pl.lit("c")).sum().alias("sum"),
        ]
    )
    res = plan.collect()
```

### Expected behavior

```python
shape: (1, 1)
┌─────┐
│ sum │
│ --- │
│ i64 │
╞═════╡
│ 2   │
└─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.12
Index type:  UInt32
Platform:    Linux-5.15.0-53-generic-x86_64-with-glibc2.35
Python:      3.11.3 (main, Apr  7 2023, 16:20:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.2
pandas:      2.0.0
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

**Comment by mcrumiller** [comment]
Yeah, that's how references to other columns work. We should probably improve the docs on `filter` for this.

You're saying "first filter column `val` by `a == b`." So now `val` is smaller. None of the other columns have changed since this expression operates on `val` only. Next, you say "filter by `b == c`". This doesn't work because `b == c` has the height of the first full dataframe.

You have two options here: either filter your second filter with the first, or use an `&` to join them, which will probably be faster and easier to read:

## 1. Filter the filter
```python
df.select(
    col("val").filter(flt).filter(
        (col("b") == pl.lit("c")).filter(flt)
    ).sum().alias("sum"),
)
```

## 2. Use an `&`
```python
df.select(
    col("val").filter(
        flt & (col("b") == pl.lit("c"))
    ).sum().alias("sum"),
)
```

Both return the same results.
