### ISSUE TITLE
I need to create a column with the distance between two coordinates in polars

### ISSUE THREAD

**Issue by lautarortega** [pola-rs/polars#8868]
### Research

- [X] I have searched the above polars tags on Stack Overflow for similar questions.

- [X] I have asked my usage related question on [Stack Overflow](https://stackoverflow.com).

### Link to question on Stack Overflow

https://stackoverflow.com/questions/76262681/i-need-to-create-a-column-with-the-distance-between-two-coordinates-in-polars

### Question about Polars

I am trying to test whether polars is faster for my use case. I am trying to create a feature that would be the distance between two coordinates. 
I am already struggling trying to create a new column with a tuple of the latitude and longitude.

Also, later I need to create bins, I know there is a cut function for polars Series, how can I use it to add columns in a lazyframe?

**Comment by avimallu** [comment]
You should be able to create a `struct` instead of a `tuple`. Or a `list` column. Or a `np.array` column. Here's my personal preference (with benchmarks from [this Stackoverflow question!](https://stackoverflow.com/questions/4913349/haversine-formula-in-python-bearing-and-distance-between-two-gps-points)), where I create a `list` column:

The benchmark from the linked Stackoverflow question:

```py
def distance(s_lat, s_lng, e_lat, e_lng):

    # Approximate radius of earth in km
    R = 6373.0
    s_lat = s_lat * np.pi/180.0
    s_lng = np.deg2rad(s_lng)
    e_lat = np.deg2rad(e_lat)
    e_lng = np.deg2rad(e_lng)

    d = np.sin((e_lat - s_lat)/2)**2 + np.cos(s_lat)*np.cos(e_lat) * np.sin((e_lng - s_lng)/2)**2

    return 2 * R * np.arcsin(np.sqrt(d))
```

Create two Polars functions that returns **expressions**:

```py
def d2r(deg: str):
    return pl.col(deg) * np.pi / 180

def polars_haversine(s_lat: str, s_lng: str, e_lat: str, e_lng: str) -> pl.Expr:
    R = 6373.0

    s_lat = d2r(s_lat)
    s_lng = d2r(s_lng)
    e_lat = d2r(e_lat)
    e_lng = d2r(e_lng)

    return (2 * R * (
        (e_lat - s_lat).truediv(2).sin().pow(2) + 
        (s_lat.cos() * e_lat.cos()) * (e_lng - s_lng).truediv(2).sin().pow(2))
            .sqrt().arcsin())
```

Create some dummy data for benchmarking:

```py
s_lat = np.random.randint(-90, 90, 1000000)
s_lng = np.random.randint(-180, 180, 1000000)
e_lat = np.random.randint(-90, 90, 1000000)
e_lng = np.random.randint(-180, 180, 1000000)

DF = pl.DataFrame({
    "s_lat": s_lat,
    "s_lng": s_lng,
    "e_lat": e_lat,
    "e_lng": e_lng})
```

Verify that both functions return similar results (similar because we have floating point multiplication, so values will not always be exact, and rounding to five decimal points):

```py
np.all(
    np.round(DF.select(polars_haversine("s_lat", "s_lng", "e_lat", "e_lng")).to_numpy()[:, 0], 5) == 
    np.round(distance(s_lat, s_lng, e_lat, e_lng), 5))
```

Finally, running benchmarks (on my modest machine):

```py
>>> %timeit distance(s_lat, s_lng, e_lat, e_lng)
40.3 ms ± 725 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
>>> %timeit DF.select(polars_haversine("s_lat", "s_lng", "e_lat", "e_lng"))
19.9 ms ± 58.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Looks like Polars is about twice as fast, which is pretty great in my opinion. You chose helluva nice question to learn Polars with! :D

**Comment by lautarortega** [comment]
Great feedback!

Thanks for your help!
