### ISSUE TITLE
Large performance regression in `align_frames` in 0.17.14

### ISSUE THREAD

**Issue by erinov1** [pola-rs/polars#8896]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I noticed a large slowdown in my code when aligning 20 frames each with ~5 million rows on two key columns. The 20 frames are already nearly aligned.

Here is a rough replication:

```python
import string

from numpy.random import rand

df = pl.concat(
    (
        pl.DataFrame({"key_1": [a] * 200_000})
        .with_row_count("key_2")
        .with_columns(pl.Series("value", rand(200_000)))
        for a in string.ascii_lowercase
    )
)

# These frames are nearly aligned
frames = (df.slice(10_000 * i, len(df) - 10_000 * 20) for i in range(20))
```

Aligning these frames takes about 4 seconds in `0.17.13` but over a minute in `0.17.14` (on my 12-core laptop):

```python
pl.align_frames(
    *frames,
    on=["key_1", "key_2"],
)
```

@alexander-beedie this seems to have been introduced by https://github.com/pola-rs/polars/pull/8825? I'm guessing the corrected handling of duplicate keys is responsible for the slowdown?

### Reproducible example

```python
import string

from numpy.random import rand

df = pl.concat(
    (
        pl.DataFrame({"key_1": [a] * 200_000})
        .with_row_count("key_2")
        .with_columns(pl.Series("value", rand(200_000)))
        for a in string.ascii_lowercase
    )
)

frames = (df.slice(10_000 * i, len(df) - 10_000 * 20) for i in range(20))

pl.align_frames(
    *frames,
    on=["key_1", "key_2"],
)
```

### Expected behavior

Ideally speed should be comparable to versions < 0.17.14.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.14
Index type:  UInt32
Platform:    macOS-13.2-arm64-arm-64bit
Python:      3.11.1 (main, Feb  8 2023, 16:32:14) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
numpy:       1.23.5
pandas:      1.5.3
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.1.0
matplotlib:  3.7.0
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

**Comment by alexander-beedie** [comment]
Ouch, that's certainly not ideal... (indeed, on the smaller number of joins I tested with it actually got faster!) I'll see what I can do to get the best of both worlds - correctness plus speed. Thanks for the test case 👍

**Comment by kpberry** [comment]
I noticed this yesterday, and tl;dr: I think one reasonable solution would be to add an "ignore_duplicates" argument to align_frames, or something similar. 

There are basically two scenarios:
1. In the case that "on" contains no duplicates, things are simple. The previous algorithm is fast because it constructs the full index once in linear time and performs one join per DataFrame, so the runtime is just the cost of index construction + (number of DataFrames * cost of join with full index). Because there are no duplicates, the full index is of size at most: number of DataFrames * size of longest index present, which is not bad.
2. In the case that "on" contains duplicates, the situation is much more complicated, and (as far as I can tell), there is no fast algorithm. One way to deal with the duplicates is to repeatedly do outer joins, which is the current algorithm causing the slowdown. For non duplicated keys, this outputs the same values as the previous algorithm. For each duplicated key, the full index will now have a number of entries equal to the product of the number of times that element shows up in each original DataFrame. For instance, if the key "b" shows up 3 times in each DataFrame, then the full index will have 3^n entries for "b", where n is the number of DataFrames. Since the number of outputs is exponential in the number of duplicates across DataFrames, there is no algorithm for handling duplicates that can run in less than exponential time, so the algorithm technically performs reasonably well here. However, joining repeatedly is also quadratic in the number of DataFrames being joined, since the size of the data increases with every join and the data is copied in every join (the argument here is a little subtle, and I can explain more if it's unclear). This means that in the best case, without duplicates, the runtime is quadratic, where before it was essentially linear.

Since there is no good algorithm for 2 in general, I think it should be an opt-in to use the slower algorithm when duplicates are present, and use the faster algorithm when they are not (which I imagine is the more typical use case). This could either be done with a flag where the caller asserts they have no duplicates, or a check for duplicates in align_frames, which would add a linear cost to the call.

**Comment by alexander-beedie** [comment]
@kpberry indeed, all makes sense; I've recovered a lot of the original performance without having to do anything too exotic, and added a new mode that exposes _how_ the frames are joined - if your data is suitable for left-joining off the first frame then this can actually net a significant speedup over the original algorithm, which is a nice win.

It probably also makes sense to add a flag allowing the caller to indicate that they know whether duplicates are present or not, but I'm not sure I'd want to default to potentially incorrect behaviour 🤔 I'll get the first patch out and return to this...

**Comment by kpberry** [comment]
Thanks for the quick response/patch!

I agree that defaulting to incorrect behavior is not ideal. An opt-out flag would probably make more sense, then.

**Comment by alexander-beedie** [comment]
Merged the first patch, which mitigates the worst of it and adds the new `how` param; started on implementing an opt-in `no_duplicate_keys` param to fully-recover the original speed where valid (just needs a bit of extra work to integrate properly with the new `how` param...)
