### ISSUE TITLE
How I can import (read) / export (write) Big Query tables directly from Polars API

### ISSUE THREAD

**Issue by emilianomm** [pola-rs/polars#8998]
### Research

- [X] I have searched the above polars tags on Stack Overflow for similar questions.

- [X] I have asked my usage related question on [Stack Overflow](https://stackoverflow.com).

### Link to question on Stack Overflow

https://stackoverflow.com/questions/76316690/how-i-can-import-export-big-query-tables-directly-from-polars-api

### Question about Polars

I've recently start working with polars API in python and pretty much satisfied with what it can achive.

Now I need to integrate some processes with Big Query. I'll be writing some results and reading raw data aswell.

Polars very own documentation on the topic is practically non existent and of course I would like to avoid a solution in the like of

```python
polars.DataFrame().to_pandas()
```

and then using pandas methods described in gcp docs.

There is a polars native solution to this?

**Comment by alexander-beedie** [comment]
> There is a polars native solution to this?

There is an arrow-native solution when reading data from BigQuery, which essentially means that there is also a polars-native solution - or close enough. Instead of loading your data to pandas with `to_dataframe`, use `to_arrow`[^1] instead and initialise polars with that, using `pl.from_arrow( your_bigquery_result )`. This should be a zero-copy operation, and _significantly_ more efficient than going via pandas.

[^1]: `to_arrow` support was added back in 2019: https://github.com/googleapis/google-cloud-python/pull/8609

**Comment by stinodego** [comment]
Closing this in favor of the question on Stack Overflow.
