### ISSUE TITLE
Formalize relationship between `Expr` and `WhenThen`/`WhenThenThen`

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#9031]
### Problem description

A lot of our functions/methods look something like this:

```python
def do_stuff(input: int | Expr) -> Expr:
    if isinstance(input, Expr):
        ...
    else:
        ...
```

This looks fine, but it does not handle when/then inputs properly. If I input `pl.when(True).then(1)`, I want it to be treated as an expression.

We can fix the type hint pretty easily - there is already a type alias for it (`PolarsExprType`). But the `isinstance` check is a bit more tricky. I considered:
* making `WhenThen` inherit from `Expr` -> I think this will result in unexpected behaviour
* creating an abstract superclass that both inherit from -> Could work, but what should it be named?
* using a metaclass for both

I'm looking for input on how to handle this elegantly. Maybe @alexander-beedie has an idea?

**Comment by zundertj** [comment]
Basically you are running into the problem that currently the whole `When/WhenThen/WhenThenThen` is treated special, but in some ways, but not all, are like normal expressions.
 
I can't find my comment on an issue on `WhenThen` anymore, but I have proposed before a syntax to allow
```python
expr.whenthen(<if True>, <value if True>, <value if False, default to expr>)
```
which you could chain and use like normal expressions. This can currently be replicated by doing:

```python
pl.when(<if True>).then(<value if true>).otherwise(expr).alias(expr.meta.output_name())
```
which returns a normal expression. If we were to only have that, your problem would not exist.

So to me it seems we should give it a thought whether we like the current `WhenThen` enough to keep it around, or use a `whenthen()` method on the `Expression` class per the above.

Some cons I can think off (apart from removing existing valid syntax):
1. the syntax is slightly less intuitive, `pl.when().then().otherwise()` reads like `if-else`
2. the order of evaluation on chained `WhenThens` switches around (rightmost takes precedence), which may be confusing, or not? Although I dont think 
3. Possibly less efficient, as there is always the `Otherwise`? But that is a requirement to make it a proper expression on the way out.

Pro's of the new syntax:
1. if you want to override a field based on a condition, `.whenthen()`, due to original field being the default, is more intuitive vs `pl.when().then().otherwise()` which has `null` as the placeholder.

I realise it is probably not so simple, and I'm sure someone will chime in here to stop me from removing API surface...

**Comment by stinodego** [comment]
Thanks for the great input, @zundertj. I'm going to let this sink in a bit.

**Comment by ritchie46** [comment]
I really don't want to change the syntax. I really like the `if {branch} else {branch}` analogy ( a lot).

**Comment by zundertj** [comment]
Had not realized we already have the automatic  behaviour on the `otherwise`, but obv that does not solve the issue you are running into that an unfinished `WhenThen` expression and a normal expression are not the same still. 

@ritchie46 : there are pro's and cons, just pointing out that we have a very special construct here and that there are alteratnvies that come with pro's and cons.

I think, given the requests for it before, that there is room for a `Expr.whenthen(<if>, <value if true>, <value if False, default=expr>)` in addition to what there is, we should not necessarily have to choose one over the other. I.e., right now there is support for `if {branch} else {branch}` , and the automatic addition of `otherwise(pl.lit(None))` means there is also `if {branch} else {None}` but not for `if {branch}`. Of course, one can do `pl.when(expr1).then(<value True>).otherwise(expr2).alias(expr2.meta.output_name())` but `expr2.whenthen(<value True>, expr1)` is much more readable.

**Comment by rben01** [comment]
I don't think this functionality has to fall under the `WhenThen` umbrella at all. I think a function like `expr2.replace_with_if(value_expr, predicate_expr)` would be easier to read.

**Comment by henryharbeck** [comment]
I agree it makes sense to treat the result of a `.then()` as an expression that additionally has support for the `when` and `otherwise` methods. Obviously much easier said than done.

@stinodego - When you mention unexpected behaviour caused by inheriting from Expr, for my own understanding, what would that be? Or what would be an example of it?

I think there's also an additional consideration in that after chaining, both `when()` and `then()` return an instance of `WhenThenThen`

E.g. 
```python
(
    type(pl.when(True).then(True).when(True)) == 
    type(pl.when(True).then(True).when(True).then(True))
)
```

If you want treat the result of a `.then()` as an expression, then by extension, an instance of `WhenThenThen` would need to be that. But, at the same time, I don't think you'd ever want the result of `when()` (i.e. also sometimes instance of `WhenThenThen`) to behave as an expression...
You could alternatively "allow" it to have expression methods and just throw an error at run time.

This is kind of the same as what happens when you do `pl.when().then().when().otherwise()`. 
`otherwise` is a hinted method at this stage but it panics at run time. The error message is pretty clear/unambigious though.

What is the purpose of the `WhenThenThen` class?
Would it be possible instead to create an instance of `When` (instead of `WhenThenThen`) when calling `WhenThen.then()`?

In theory, if you were able to just oscillate between `When` and `WhenThen`, you would also not provide completion/highlighting for the invalid `pl.when().then().when().otherwise()`

Any thoughts or answers much appreciated

**Comment by stinodego** [comment]
I just looked at this, and it can be fixed by making WhenThen / WhenThenThen inherit from Expr. I have a PR in the works.
