### ISSUE TITLE
Should py-polars LazyFrame's __repr__ return its schema?

### ISSUE THREAD

**Issue by MartinBernstorff** [pola-rs/polars#9100]
### Problem description

I wish that the polars LazyFrame's `__repr__` would return its schema.

When I'm developing in debug mode, I frequently call a dataframe's `__repr__` method to see its current state, do an operation on it, then call `__repr__` again to see the change. This works excellent with Pandas' dataframe, Polars' dataframe etc.

However, for the `LazyFrame`, the `__repr__` currently tells me that it's an instance of the `LazyFrame` class and its position in memory. This doesn't help me develop my application at all, and is inconsistent with the `DataFrame`.

IMO, the closest we can get is to show the schema.

What do you guys think? I've submitted a PR at #9101.

Also, thanks a tonne for an **excellent** library! It's made my job a lot more fun 🥳

**Comment by MartinBernstorff** [comment]
Yeah, that makes sense! 

> I don't think conflating the schema and the frame is the way to go

I agree with the sentiment! OTOH, I think the schema is super informative, and extremely handy during development.

Perhaps we could return a helpful message, and a subset of the schema? Looking forward to what you think when you're back 👍

**Comment by alexander-beedie** [comment]
Even something simple like `<LazyFrame [10 cols, 4 dtypes] at 0x1206139D0>` would be a meaningful improvement...? 😅

**Comment by MartinBernstorff** [comment]
Definitely all an improvement! I wonder what the use case is, though?

I hope I've described my use case sufficiently above; every time I query a DataFrame during debugging, I do it to see the result of an operation on the schema. Let me know if anything there is unclear. 

I'm very much still a novice in this domain! But I wonder why we'd care about the memory address?

For the reasons above, I'd prefer any version which prints as much of the schemas as possible 👍

**Comment by datapythonista** [comment]
I personally find the Vaex of collecting the top rows approach extremely convenient.

When thinking about Polars to build a pipeline and debugging it makes sense a show a summary as the ones above. But I think an important use case is also to use Polars for exploratory data analysis in a notebook, and in that case I think something like this makes a lot of sense (not literally, since the representation should fetch and show a subset but report the actual size):

```python
class LazyFrame:
    def __repr__(self):
        return repr(self.limit(8).collect())
```

This way users can use a lazy dataframe as if it was an eager dataset. And in particular for users not from a computer engineering background such as scientists, data analysts... this makes their learning curve much more accessible.

One can argue that they can just use an eager dataframe. But I do see at least one main advantage in using a lazy one. If a dataset contains millions of rows, an eager dataframe may take a significant time to load, and the memory requirements are big. By being able to use lazy Polars in a notebook in an easy way (without having to manually call `collect` and possibly `limit`) makes the experience much better.

I've been using Polars with the simple implementation above to see if there was any issue, and seems to work quite well.

**Comment by ritchie46** [comment]
> I personally find the Vaex of collecting the top rows approach extremely convenient

This is potentially extremely expensive. Many operations need to process all data before they are able to produce a top row. For instance full table sort, Even if you pass a limit, you still need to have a full pass over the data. And if the data doesn't fit into memory, this will cause an out-of-core query that have several IO round trips. The same counts for a groupby + agg, or a normal aggregation for that matter.

A `__repr__` should be very cheap in my opinion, triggering a query can be very expensive.

For people who want to quickly see a lazyframe's output for debugging purposes, we have `fetch`. `fetch` just takes `n` rows from the source and pushes it into the query. This isn't a correct result, as it pretends there are only `n` rows in the dataset, but it can help debugging and is fast.

**Comment by alexander-beedie** [comment]
I've seen some libraries have an opt-in "interactive" flag (the sort of thing we could put into `Config`) that would modify lazy reprs into eager reprs... It enables the exploration part in the lazy engine without compromising production code, but it's still a bit odd (and, as mentioned, potentially very expensive). 

Providing such a flag and making it opt-in at least constrains usage to people who would _expect_ the cost if they have a heavy data set, and the previously suggested default updates above could offer a little more cheap information to everyone else.

**Comment by ritchie46** [comment]
But why not go eager in that case? You would do your cpu a favor.

**Comment by datapythonista** [comment]
Those are very good points. Personally, I see at least two main use cases for dataframe libraries. Building a pipeline/query, where all query optimizations make a huge difference. And also exploratory data analysis, where in most cases each operation will be run independently and the result will be visualized at every step.

I'm not so familiar with a use when building a pipeline and using `__repr__` much, I'd generally just write the pipeline in a Python file and at the end of it the data will probably be exported, not printed.

But for the EDA part, the way I work, and I assume most people work, would imply calling `fetch` at every notebook cell, that's why I suggested calling it directly in `__repr__` (or maybe it would make sense to only call it in `_repr_html_`).

Having this opt-in sounds like a good trade off to me. I'd probably have this as default, as I think the less experienced/knowledgeable users are the ones who will have to learn how to set the option, but either way seems reasonable.

> But why not go eager in that case? You would do your cpu a favor.

That's a good point, I quote from above why I think there is still an advantage. From your comment, not in all cases, like with a full sort, but I guess in those cases the memory usage shouldn't be higher than the alternative of using an eager dataframe, is it?

> One can argue that they can just use an eager dataframe. But I do see at least one main advantage in using a lazy one. If a dataset contains millions of rows, an eager dataframe may take a significant time to load, and the memory requirements are big. By being able to use lazy Polars in a notebook in an easy way (without having to manually call collect and possibly limit) makes the experience much better.

**Comment by alexander-beedie** [comment]
Indeed... maybe just to examine existing pipelines and not rework it? And of course you could just call `.collect()` at any time. Let's add the simple/cheap part with a bit of extra info now, and we can revisit an "interactive" flag later if it becomes more compelling.

**Comment by alexander-beedie** [comment]
> in those cases the memory usage shouldn't be higher than the alternative of using an eager dataframe, is it?

It's more that each time you visualise a new operation against your lazy frame it'll have to run the pipeline from scratch; with an eager frame it'll only be applying the latest op.

**Comment by ritchie46** [comment]
> That's a good point, I quote from above why I think there is still an advantage. From your comment, not in all cases, like with a full sort, but I guess in those cases the memory usage shouldn't be higher than the alternative of using an eager dataframe, is it?

No, but we only do one operation at a time. Whereas with lazy, we would evaluate that full query on every interaction, which kills the point of interactivity, as peoply won't like using polars anymore in that case. It would be slow because we run a whole query every time. 

Though, I think the current repr in a notebook is pretty nice and shows how you should think about `LazyFrame`s. They show the tree of operations in graphviz. I think that encourages the mental model that a `LazyFrame` is a promise on a computation that still needs to happen in the future. 

For me it is very important that we keep that distinction between a promise `lazy` and a dataset that is materialized `eager`.

I would encourage users to use `eager` during EDA and then when they convert to a pipeline that needs to run in production or the whole query they should change to `lazy`, which is swapping out `read_x` for `scan_x` most of the time. :)

**Comment by alexander-beedie** [comment]
Let's add the extra cols/schema info into the vanilla (non-notebook) LazyFrame `repr` and leave it there; unless some killer use-case presents itself (that I can't think of at the moment) there are too many downsides to an "interactive" lazy mode - especially as visualising the table explicitly is just a `collect()` away.

**Comment by datapythonista** [comment]
Fair point, seems reasonable.

JFYI With 1M rows, many string operations, and a decent but 5 year old laptop, the experience re-executing the query every time in lazy mode is just fine, almost immediate results (< 1 sec) :)

**Comment by ritchie46** [comment]
> time in lazy mode is just fine, almost immediate results (< 1 sec) :)

Great to hear, but I have seen people make huge query plans (1000s of joins) that would stress test your machine. ^^
