### ISSUE TITLE
Issue in AnyValue conversion from timezone-aware Datetime objects

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#9103]
When Python objects are parsed into AnyValues, time zones are considered, but the resulting data is not timezone-aware.

Consider the following example:

```python
from datetime import datetime
from zoneinfo import ZoneInfo
import polars as pl

result = pl.repeat(
    datetime(2023, 1, 1, 10, tzinfo=ZoneInfo("Europe/Amsterdam")), n=1, eager=True
)
print(result)
```

Which prints:
```
shape: (5,)
Series: 'repeat' [datetime[μs]]
[
        2023-01-01 09:00:00
]
```

This is surprising to me, as I would expect to get a timezone-aware Series. Inputting the same data into the `Series` constructor DOES result in timezone-aware data:

```python
result = pl.Series([datetime(2023, 1, 1, 10, tzinfo=ZoneInfo("Europe/Amsterdam"))])
print(result)
```
```
shape: (1,)
Series: '' [datetime[μs, UTC]]
[
        2023-01-01 09:00:00 UTC
]
```

When looking at the AnyValue conversion, you can see that the time zone is always set to None. We should probably try to find out whether the original `datetime` object is timezone-aware, and if so, set this to `UTC`.

Actually, I would say that keeping the original time zone is ideal, but I see a warning that suggests we will not be doing this in the future. @MarcoGorelli could you elaborate on this decision / link to the relevant discussion?

**Comment by ritchie46** [comment]
AnyValues cannot hold onto the timezone. They are stored in the `DataType` and the `AnyValue` has a reference to them, they don't own the timezone.

If we want to make that work on `repeat` we have to take the timezone out explicitly, we cannot count on the `AnyValue` conversion. It was not meant to do that.

**Comment by stinodego** [comment]
Yep, I just ran into that while trying to implement this 😅 I'll have to think on this one. I thought it would be great to expand the usage of AnyValue for parsing inputs in the Rust bindings, but now I'm not so sure.

**Comment by ritchie46** [comment]
Ping me tomorrow, could come up with some utilities. We still can use Anyvalue I think.

**Comment by MarcoGorelli** [comment]
Hey

Agree that `pl.repeat` not preserving tz-awareness could be considered a bug (probably same root cause as the skipped `from_dicts` test). For the Series constructor, if the first element is tz-aware, then the time zone is set to UTC, but it's done on the Python side

https://github.com/pola-rs/polars/blob/832f9ae2cc3a4035c160cb59b411a152c7993eb6/py-polars/polars/utils/_construction.py#L477

Regarding converting to UTC, here's the tracker issue, everything relevant should be linked somewhere there https://github.com/pola-rs/polars/issues/8860

Motivation:
- pyarrow converts to UTC, so this would be consistent with that
- there may be multiple `tzinfo`s (e.g. due to daylight savings time), and so they can't all be parsed to the first element's time zone. If everything is converted to UTC, then elements with multiple offsets can be allowed - users can then convert them back to whatever the local time zone is (which might not even be one of the elements' time zones!). E.g. if you have European datetimes crossing DST
  ```python
    [
        datetime(2018, 10, 28, 2, 00, tzinfo=timezone(timedelta(hours=2))),
        datetime(2018, 10, 28, 2, 30, tzinfo=timezone(timedelta(hours=2))),
        datetime(2018, 10, 28, 2, 00, tzinfo=timezone(timedelta(hours=1))),
        datetime(2018, 10, 28, 2, 30, tzinfo=timezone(timedelta(hours=1))),
    ]
  ```
  then the correct time zone would be something like `'Europe/Amsterdam'`, rather than `'+02:00'` (which is what taking it from the first element would give you)
- if the first value's `tzinfo` might not be in the IANA database (`zoneinfo.available_timezones()`). In the above example, it's `'02:00'` taking care of those introduced a huge amount of complexity, along with some perf hits from not being able to use concrete types
- as a dtype can only have a single column, each element's tzinfo needs to be compared with the inferred time zone of the column (as opposed to just converting to UTC), which has performance implications

If someone really wants to retain the old behaviour, they can always just do something like
```python
pl.Series(dates).dt.convert_time_zone(str(dates[0].tzinfo))
```

**Comment by stinodego** [comment]
Thanks Marco, makes complete sense! @ritchie46 any idea how we could parse timezone-aware datetimes through AnyValues?

**Comment by ritchie46** [comment]
The timezone should not be owned by `AnyValue` it is a column level parameter and the `DataType` should own it.

We could use a helper struct/enum in the python bindings.

```rust
struct Argument {
  value: AnyValue,
  dtype: DataType
}
```

And then implement the conversion traits for this.

**Comment by stinodego** [comment]
That should work. I'm going to see if I can set this up nicely!

**Comment by stinodego** [comment]
This seems to have been fixed.
