### ISSUE TITLE
s == x should evaluate to False when s is null and x is not None

### ISSUE THREAD

**Issue by mcrumiller** [pola-rs/polars#9268]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Regardless of whether `None == None` it should always be the case that `x == None` evaluates to False when x is not None.

### Reproducible example

```python
import polars as pl

# this should evaluate to False, but evaluates to null
pl.Series([None]) == 3
```

### Expected behavior

Should evaluate to False.

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.0
Index type:  UInt32
Platform:    Windows-10-10.0.19045-SP0
Python:      3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     11.0.0
connectorx:  0.3.2a5
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    0.8.1
xlsxwriter:  3.0.9
```

</details>

**Comment by avimallu** [comment]
This was the original behavior, and was changed in https://github.com/pola-rs/polars/pull/9053, because by itself not returning `null` was inconsistent with changes made in https://github.com/pola-rs/polars/issues/8183, and was brought up in https://github.com/pola-rs/polars/issues/9132. To get the old behavior back, it was advised to use `eq_missing` and `ne_missing`.

**Comment by mcrumiller** [comment]
@avimallu thanks for the background. I understand pros and cons of each so I'll drop this. I wasn't aware of `eq_missing` and `ne_missing`, which are of great help.
