### ISSUE TITLE
Confusing `fill_null`

### ISSUE THREAD

**Issue by JulianCologne** [pola-rs/polars#9284]
### Research

- [X] I have searched the above polars tags on Stack Overflow for similar questions.

- [ ] I have asked my usage related question on [Stack Overflow](https://stackoverflow.com).

### Question about Polars

Hi all,
looking at the `fill_null` function (especially the `strategy` parameter), I was quite surprised by a few things that might require some adjustments or at least some explanations in the documentation.

## `forward` / `backward`

works as expected!

## `min` / `max`

```python
df = pl.DataFrame({
    "a": [1, None, 3, None, 5],
    "b": ['a', None, 'c', None, 'e'],
})
```

1. works with integers and floats, but not with strings (did not try with other types).
    - Integer (both work):
    - `pl.col('a').fill_null(pl.col('a').min())`
    - `pl.col('a').fill_null(strategy='min')`
    - String (value works, strategy does not):
    - `pl.col('b').fill_null(pl.col('b').min())`
    - `pl.col('b').fill_null(strategy='min'),  # >>> InvalidOperationError`
2. having `min`, `max` and `mean` but not `median` is a bit surprising/inconsistent. I would expect either all of them or none of them. This is definitely a matter of taste because where to stop (mode, std, quantiles, ...)? Honestly, the only required ones for strategy in my opinion are `forward` and `backward` (pandas only has those 2 in `fillna`). The rest can be achived with `value` and composition of polars expressions. (not sure if there might be some performance benefits though?)

## `zero` / `one`

- I have honestly no idea why they are required? Are they special in some way? Do they have crazy performance benefits? I would expect them to be just a special case of `value` with `0` and `1` respectively? However, testing this got me confused:
    - `df.fill_null(0)`
        - integer column is filled with 0 (as expected)
        - string column is unchanged (no error, no change)
    - `df.fill_null(strategy='zero')`
        - InvalidOperationError: fill-null strategy Zero is not supported 
- I would love to see some detailed explanations in the docs about this!

**Comment by ritchie46** [comment]
The strategies other than `forward`/`backward` exist for performance benefits. They are in a dedicated `fill_null` function that doesn't have access to the expression, so they cannot use that.

They are additional. If you want to fill with `zero` you can also use the expression engine, but utilizing the zero strategy will be more resource friendly. We are not going to add `median`, `std` etc. 

They for one don't exist because the `strategy` engine only does a single pass over the data and only holds a single value as state. That's why `min` and `max` are supported and `median` not (that is not a single value and requires a complex algorithm to compute).

Maybe we should add a sentence about the `strategys` being specialized. If you need something else, use the expression engine?

**Comment by mcrumiller** [comment]
@ritchie46, I think the issue in the #1 point is that `min` and `max` strategies don't work for string columns.

```python
pl.Series(['a', 'b' ,'c', None]).fill_null(strategy="min")
```
```
exceptions.InvalidOperationError: fill-null strategy Min is not supported
```

**Comment by stinodego** [comment]
I opened a feature request:
#10666
