### ISSUE TITLE
Polars' parallelization doesn't work with joblib loky or multiprocessing backend.

### ISSUE THREAD

**Issue by shenrun** [pola-rs/polars#9410]
### Research

- [X] I have searched the above polars tags on Stack Overflow for similar questions.

- [ ] I have asked my usage related question on [Stack Overflow](https://stackoverflow.com).

### Question about Polars

I have a large pl.DataFrame df, and I test the performance like following:
'''
```python
def f(i):
    return df.select(pl.col('close').rolling_mean(6).over('code'))
res = joblib.Parallel(n_jobs=8)(joblib.delayed(f)(i) for i in range(8))
```
When I set n_jobs = 1 or backend = 'threading', polars' parallelization works using all cores normally (inspected with htop in terminal). However, the parallelizaion seems not to work and use only 1 core when setting n_jobs > 1 and backend = 'loky' or 'multipreocessing'. Is there any instruction for using polars with joblib and multiprocessing? I found a related issue https://github.com/pola-rs/polars/issues/8032, but the link in the answer https://pola-rs.github.io/polars-book/user-guide/howcani/multiprocessing.html has gone.

Many thanks for your time and help in advance!

**Comment by cmdlineluser** [comment]
https://pola-rs.github.io/polars-book/user-guide/misc/multiprocessing/ is the current location.

**Comment by ritchie46** [comment]
See @cmdlineluser link

**Comment by arogozhnikov** [comment]
@ritchie46 
[loky](https://github.com/joblib/loky) backend for multiprocessing is usually considered safe because they use fork-exec model. I am actually not sure why polars would block this case.

FYI I'm using polars with joblib, but polars used only in workers (though it is *imported* in main process). And it works ok for a long time until it somehow blows up with OOM
