### ISSUE TITLE
Literal string dtype i8 i16 i32 in constructer are not recognize correctly

### ISSUE THREAD

**Issue by aploium** [pola-rs/polars#9490]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

see below

### Reproducible example

```python
import polars as pl

pl.Series(values=[1,0], dtype="i32")

#shape: (2,)
#Series: '' [i64]  #<--- dtype i32 becomes i64, wrong
#[
#	1
#	0
#]

pl.Series(values=[1,0], dtype=pl.Int32)
# However, using the pl.Int32 works correctly
#shape: (2,)
#Series: '' [i32]  <---- correct
#[
#	1
#	0
#]
```

### Expected behavior

`i8` `i16` `i32` etc literal dtype shortcut are correctly recognized

### Installed versions

<details>

--------Version info---------
Polars:      0.18.3
Index type:  UInt32
Platform:    Linux-6.2.1-060201-generic-x86_64-with-glibc2.35
Python:      3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     11.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      2023.5.0
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

</details>

**Comment by alexander-beedie** [comment]
Interesting; the string form of the dtype _isn't_ actually a valid polars dtype at all; however, the parsing appears to get caught-up in some related logic (associated with [pl.from_repr](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.from_repr.html)), which is why it appears to half work... 

While I could at least make it behave consistently here, you shouldn't use strings as if they were dtypes - they are not, and you'll immediately run into trouble with nested dtypes such as structs, which would not be recognised by this method.

**Comment by aploium** [comment]
In the pydata ecosystem, such as numpy/pandas/torch, they all support use string as dtype. I thought it already become a customer habbit. 
Because in interactive environment, such as jupyter, when user is explorering the data, convince and **easy to type** are truely valueable.

Thus I think keep it as an feature may be better.

**Comment by ritchie46** [comment]
I don't think we should support this. We already have one way to declare data types. Let's keep the API surface small and recognizable.
