### ISSUE TITLE
Add Snowflake ADBC Driver Support

### ISSUE THREAD

**Issue by ryantaylor406** [pola-rs/polars#9569]
### Problem description

In the user guide it states that only Postgres or SQLite are supported for reading from databases via ADBC at the moment. On the ADBC website, there is a [Snowflake driver listed](https://arrow.apache.org/adbc/0.5.0/driver/snowflake.html).

This would be incredible to have as I'm currently having to use pandas as a middle man when reading data from Snowflake.

**Comment by alexander-beedie** [comment]
> I'm currently having to use pandas as a middle man when reading data from Snowflake.

Well, we can't have that... ;)

I've slightly overhauled the ADBC connectivity so that it's a bit more generalised; _should_ now work with snowflake connections, though since I don't have access to a snowflake instance it would be great if you can test and let us know how it goes.

**Comment by mkleinbort-ic** [comment]
I have snowflake - if you send me a few commands to run against it I'm happy to let you know the result.

**Comment by mkleinbort-ic** [comment]
Ps. this is how I currently read from Snowflake:

```python

from snowflake.connector import connect as snowflake_connector

def get_snowflake_connection(warehouse:str, 
                             database:str, 
                             schema:str):
    '''Generate a snowflake connection''' 
    
    conn = snowflake_connector(
            user=SNOWFLAKE_USERNAME,
            password=SNOWFLAKE_PASSWORD,
            account=SNOWFLAKE_ACCOUNT,
            warehouse=warehouse, 
            database=database,
            schema=schema
        )

    return conn

def get_snowsql(q:str, 
                warehouse:str='MY_WHAREHOUSE', 
                database:str='MY_DATABASE', 
                schema:str='MY_SCHEMA', 
               )->pl.DataFrame:
    '''Runs SQL query against Snowflake'''
        
    conn = get_snowflake_connection(warehouse=warehouse, database=database, schema=schema)

    with conn.cursor() as c:
        df_response = c.execute(q)       
        df_response = pl.from_arrow(df_response.fetch_arrow_all())
        
    return df_response 
```

I find this is very fast, but I'll test the ADBC driver

**Comment by alexander-beedie** [comment]
> I have snowflake - if you send me a few commands to run against it I'm happy to let you know the result.

Just merged a first cut improvement that slightly generalises our ADBC connections, so you should find it now works with snowflake; @jonashaag was kind enough to take it for an initial spin to confirm! If you can compare with what you're doing now that would be great - we can overhaul things later if there are obvious fast paths or beneficial tweaks that we can make, though we're really just deferring to ADBC at this point, so that we'll benefit as upstream support evolves.

I think the only initial sticking point was making sure to assign a warehouse; it wasn't clear to me how to do that via the URI, so if you have an example of it then I can include a note in the docstring for everyone's benefit 👍

**Comment by mkleinbort-ic** [comment]
Does this help:
```python
conn_string = f"snowflake://{SNOWFLAKE_USERNAME}:{SNOWFLAKE_PASSWORD}@{SNOWFLAKE_ACCOUNT}/{database}/{schema}?warehouse={warehouse}"
```

**Comment by alexander-beedie** [comment]
Oh, it's as simple as that? Good stuff, that's pretty much what I was hoping it might be 😁
