### ISSUE TITLE
Support more DataTypes for deltalake

### ISSUE THREAD

**Issue by danielgafni** [pola-rs/polars#9631]
### Problem description

I'm testing reading/writing Polars DataFrames with `deltalake`. 
Currently not all dtypes work, here is the list of unsupported dtypes (found them with `hypothesis` testing):

```python
[
    pl.Categorical,
    pl.Duration,
    pl.Time,
    pl.Datetime("ns", None),
]
```

`UInt` types are currently a little broken #9627

Also, `Infinity` values are not supported.

**Comment by stinodego** [comment]
The problem here is that Deltalake does not support all our data types. See [here](https://docs.databricks.com/sql/language-manual/sql-ref-datatypes.html) for the list of supported types.

We do automatic casting for some types (e.g. unsigned integers). For others, we cannot guarantee sensible outcomes after casting. For example, there is no good type to cast `Time` to. So we just error and leave it up to the user to cast to a supported type they find sensible. For example, you could cast `Time` to an integer yourself, or maybe to a `Datetime`.

Perhaps `Datetime("ns")` should be cast to `Datetime("us")` though, which is supported. And `Categorical` to either `Utf8` or `UInt`? I am open to suggestions. Most of this will be implemented in the `deltalake` package though.

Tagging @chitralverma , maybe he has some input here.
