### ISSUE TITLE
Implement "Pydantic protocol"

### ISSUE THREAD

**Issue by Kludex** [pola-rs/polars#9710]
### Problem description

I'd like polars structures to implement the "Pydantic protocol", as mentioned [here](https://docs.pydantic.dev/latest/usage/types/custom/#creating-custom-classes-using-__get_pydantic_core_schema__).

The idea here is to avoid people to do what is mentioned in the link on their code source.

As an alternative, we can implement it on [pydantic-extra-types](https://github.com/pydantic/pydantic-extra-types).

**Comment by MarcoGorelli** [comment]
Sounds like a good idea to me, but cc'ing Alexander "Pydantic expert" Beedie @alexander-beedie

**Comment by Kludex** [comment]
Are you everywhere @MarcoGorelli ? 🤣 

(Thanks!)

**Comment by alexander-beedie** [comment]
> Sounds like a good idea to me, but cc'ing Alexander "Pydantic expert" Beedie @alexander-beedie 

I can definitely take a look into this; travelling around a lot at the moment, so limited (though not zero) time for the next few days ;)

**Comment by Kludex** [comment]
> > Sounds like a good idea to me, but cc'ing Alexander "Pydantic expert" Beedie @alexander-beedie
> 
> I can definitely take a look into this; travelling around a lot at the moment, so limited (though not zero) time for the next week or so - in the meantime I’ll assign it to myself as a reminder :)

Thanks.

This is the `pandas` implementation, for reference: https://github.com/pandas-dev/pandas/pull/54034#issuecomment-1625167489 - should be analogous here.

**Comment by sm-Fifteen** [comment]
@Kludex: I've used Pydantic v1 a fair amount over the last 4 years (admittedly I haven't started looking into Pydantic V2 just yet), and I'm having a hard time telling what the intent for this change is, even having read pandas-dev/pandas#54034 and pandas-dev/pandas#53999. I *think* this is about making it so users can create models with the strict requirement of containing ~~Dataframes and~~ Series objects, so that Pydantic can assert that they are list-like, I don't know the ergonomics implications of that in terms of Pydantic user code, but that seems like a strangely specific thing to implement inside Polars and inside Pandas directly.

 It doesn't seem to generate any schema data, or contain any code to make serialization faster (like orjson does with numpy arrays), so these would be "private types", as far as I can tell. I'm also not seeing any code in the PR or example code to validate the internal data type of the Series or do constrained type verification. Even if there was, I don't think one should aim to have hooks like this added to a bunch of other libraries to provide Pydantic with a barebones(?) support that users may actually want to override to make practical use of it anyway. Wouldn't Pydantic be better off trying to support [the array_interface protocol](https://numpy.org/devdocs/reference/arrays.interface.html#arrays-interface) or other efforts like these to both be compatible with all such libraries in the future instead of a restricted set, and implement support for it within its own code instead of leaking it to external libraries?

Maybe everyone else here is just that much better at reading comprehension than I am and I'm just completely missing the point, but I am completely lost reading these issues and PRs.

**Comment by Kludex** [comment]
I did a poor job explaining things here. I'll update this tomorrow. Sorry.

**Comment by alexander-beedie** [comment]
> I did a poor job explaining things here. I'll update this tomorrow. Sorry.

Sounds good! I’ll be back home this weekend, so if there’s more detail and a good rationale I can dive in deeper. Thx.

**Comment by deanm0000** [comment]
> I did a poor job explaining things here. I'll update this tomorrow. Sorry.

It'd be helpful to explain things in the context of 'polars falls short in _____ way that pydantic would help solve'

My only experience with pydantic is in fastapi where it essentially validates that jsons are typed and table like (I'm sure that only scratches the surface of pydantic's usefullness) but dataframes are already strongly typed tables and Series are also typed. In that context I'm thinking that pydantic can enforce that columns in a pandas df are typed appropriately since pandas doesn't otherwise care about typing.

**Comment by sm-Fifteen** [comment]
@Kludex: Any news about this?

**Comment by alexander-beedie** [comment]
I'll close this out as unclear/inactive for now.
If something more concrete can be proposed then we can re-open though 😎👍

**Comment by Teut2711** [comment]
```python
from pydantic import BaseModel

class MySchema(BaseModel):
    name: str
    age: int

df = pl.DataFrame({"name": ["Alice", "Bob"], "age": [30, 40]})

records: list[MySchema] = df.to_pydantic(model=MySchema)
```

If something liike this can be there, it would be great. Rather better to use SQLModel.
