### ISSUE TITLE
The documentation is too brief

### ISSUE THREAD

**Issue by ztsweet** [pola-rs/polars#988]
polars function coverage is not clear enough

**Comment by ritchie46** [comment]
Hi, I am working day at night at this and I do what I can. Any help on improving the documentation would be welcome.

**Comment by potter420** [comment]
Hi @ztsweet , @ritchie46, I have been working with polars for our ETL and "educate" my team mate on it, tell me how can I help regarding the documentation?

**Comment by ritchie46** [comment]
@potter420 , any input would be great. Especially from a user side of things. Any document on expressions, folds, etc. would be very welcome. Here is the [user-guide](https://github.com/pola-rs/polars-book). I think there are probably chapters missing.

Have you got an idea of what you'd like to see?

**Comment by potter420** [comment]
@ritchie46 I think l'll do it pandas style, which provide explanation of the function and each variables and add some example. Also provide some gotcha if I can during experimenting.

**Comment by ritchie46** [comment]
> 

@ritchie46 I think l'll do it pandas style, which provide explanation of the function and each parameters and add some example. Also provide some gotcha if I can during experimenting.

Of course, I think that woulf be valuable for users. The more the better. :)

**Comment by ztsweet** [comment]
> @ritchie46 I think l'll do it pandas style, which provide explanation of the function and each parameters and add some example. Also provide some gotcha if I can during experimenting.

nice!!!come on !!!

**Comment by alexander-beedie** [comment]
I think this can be safely closed now - not because more contributions to improved documentation aren't always welcome (they are!), but because it has come on _significantly_ in the last year ;)

The API docs are looking pretty good now (kudos to a lot of people for that, especially some great contributions from @braaannigan in recent months), almost every function now has at _least_ one associated example (and often more), and so on. 

We can probably add some more "See Also" blocks to better-link areas of functionality, but if there are any remaining areas considered lacking then lets turn them into dedicated issues.
