### ISSUE TITLE
Add `from_clipboard` and `to_clipboard` methods

### ISSUE THREAD

**Issue by lucazanna** [pola-rs/polars#9902]
### Problem description

One of the functionality I use often in Pandas is the `read_clipboard` and `to_clipboard`.
It's a fast way to copy a table and paste it to Excel, or paste to a Word document or vice-versa.

This can be today in Polars with the following syntax:
```python
import clipboard
from io import StringIO

# read from clipboard
df = pl.read_csv(StringIO(clipboard.paste()), separator='\t') 

# write to clipboard
clipboard.copy(df.write_csv(separator='\t'))
```

However I wish it would be something easier to write/remember such as : 
```python
# read from clipboard
df = pl.from_clipboard()

# write to clipboard
df.to_clipboard()
```

The arguments would be the same or similar to the CSV I/O functions

**Comment by zundertj** [comment]
Trying to figure out what the best way would be to implement this:

* `clipboard` hasn't had an update since 2014, and tagged for Python versions up to 3.3
* Pandas vendors `pyperclip`: https://github.com/pandas-dev/pandas/blob/v2.0.3/pandas/io/clipboard/__init__.py. I dont like vendoring, so it would be another optional dependency to add for us.
* Alternative suggestion would be to use the stdlib `tkinter`: https://stackoverflow.com/a/4203897/5504925, which is an interesting suggestion

If people agree this is a sensible feature, I could give it a go using tkinter.

**Comment by lucazanna** [comment]
One possible option might also be to wrap the Pandas method. but if tkinter is a default Python library, that seems like a better option

**Comment by zundertj** [comment]
Did some more exploration, and tkinter seems to work well on my system, but would be great if others could give it a try in particular on Windows and MacOS, I am on Linux: https://github.com/pola-rs/polars/pull/9905

**Comment by cmdlineluser** [comment]
Seems to work on macOS @zundertj 

It may be useful to be able to specify `separator=` 

I'm not sure if it's a consideration issue or not, but when installing python via homebrew (and macports I believe?), it does not include tkinter by default, it requires installing `python-tk` separately.

**Comment by zundertj** [comment]
I am aware tkinter is not always installed (on Windows it is a tick boxed that is ticked by default if I recall correctly), but most of the times people will have it on their dev systems. I.e. usually, although I wasn't aware of the homebrew situation, you have to opt out. 

I could add Pandas as a fall back, but that would mean going from delimited text to Pandas dataframe to Polars DataFrame, rather than directly from delimited text to Polars.

**Comment by mcrumiller** [comment]
Matlab uses a single function `clipboard` with usage `clipboard("copy", data)` and `s = clipboard("paste")`. Not a suggestion just throwing the idea out there. I think I'd probably prefer separate functions since the single-function usage, while pretty simple, muddies up the inputs/outputs.

**Comment by zundertj** [comment]
Looking into (Python-only) some more:
1.  Tkinter works, but is not always available and difficult to test in CI due to needing a display, a complexity which we should not want. So I don't think my PR is the way to go.
2.  `pyperclip` has its share of issues, not the least not being tested for the recent Python versions, last release 2.5 years old. I am not sure it makes sense to have such a dependency, you want your dependencies to work on the recent Python versions we support. 
3. An alternative would be  https://github.com/spyoungtech/pyclip, which also needs some work, but probably less given it supports Python 3.7+ and has a better test suite.

**Comment by stinodego** [comment]
I think this would be a nice-to-have if we can implement it in a way that doesn't result in too much code bloat.

**Comment by stinodego** [comment]
I don't think this feature makes too much sense on the Rust side, seeing as it's a compiled language. Having it only on Python is fine, in my opinion.

**Comment by mcrumiller** [comment]
Functionality for using the clipboard is only something that someone doing an "interactive session" with polars would use. Seeing as that's only possible via python, it makes sense to me to have a python-only implementation. I can't really see someone using the clipboard from the rust side.

How does pandas do it?

**Comment by lucazanna** [comment]
Quick thought : why not simply wrapping Pandas methods ?

Like what is done for write_database if I understand correctly 

advantages : 
Few lines of code, no worries that Pandas will no longer be maintained 

using the Pandas methods adds one more transformation: Polars df to Pandas df, however with the arrow extension it will often be a zero copy 

also- the data copied to clipboard is small on the vast majority of cases. The goal is to take the data, then analyse it in Excel , or paste it in an email, etc
