### ISSUE TITLE
(Python) Series constructor improvements

### ISSUE THREAD

**Issue by stinodego** [pola-rs/polars#995]
I've mentioned this before in issue #960: the ordering of the Series constructor arguments. I think this is an important issue that we should fix sooner rather than later, so allow me to write down my thoughts on the issue.

### The issue

The Series constructor expects `name` before `values`, like so:

```python
pl.Series('a', [1,2,3])
```

However, it also allows the user to input just the values:

```python
pl.Series([1,2,3])
```

Which is weird, from a Python standpoint. But it works through a dirty hack under the hood:

```python
if not isinstance(name, str):
    if values is None:
        values = name
        name = ""
```

### Why it's an issue

* The implementation is not clear from the usage. If I look at some usage examples, I cannot figure out how the code actually works under the hood.
* Since documentation isn't that extensive yet, people will probably be checking the source code to see how stuff works. This trick  is very untransparent and hard to interpret.
* Looking at this dirty hack should make any programmer's skin crawl (no offense 😅 ).
* Any auto-doc tools we use will be thoroughly confused by the current setup and incorrectly represent parameter types.
* Any complexity we add to the handling of input is going to double because we have to make sure this hack keeps working.
* `values` are the most important part of a Series; it makes sense that it should come first.
* It's inconsistent with other DataFrame libraries like `pandas`.

### How to fix the issue

* Change around the arguments in the constructor; I suggest `values`, `name`, `dtype`, `nullable`.
* Update tests for the new syntax
* Update the docs - encourage people to use keyword arguments for anything other than the main `values` argument.
* Add a check in the Series constructor for the contents of the `name` and `values` arguments. If the 'old' syntax is detected, throw a DeprecationWarning, and switch the arguments. In `0.9.0` we drop the support for the old syntax.

### Other constructor improvements

I honestly feel the issue above is the most pressing. But besides that, I have two major wants:

* Allow `None` as a Series name. That way it's more transparent that no name has been given, and it can be handled better. I give an example in issue #993 how this impacts DataFrame creation. This might be tricky though, as I believe it hits the Rust implementation.
* Allow an empty sequence for the `values` argument. No particular reason; just makes sense to me. This also hits the Rust implementation.

These last two issues would be difficult for me to pick up, because of the tie in to the Rust code. But the first issue I'd be happy to fix.

**Comment by ritchie46** [comment]
The decision to make `Series` named was a design choice that goes back deep into the Rust implementation. 
I honestly don't feel that bad about that hack. I think that if we document it, and maybe change the `args, kwargs`, it can be documented and viewed as an overloaded `__init__`

## key, value
`__init__(name: str, values: List[float])`

## value
`__init__(values: List[float])`

Where I'd like to document `pl.Series([1,2,3])` as an anti-pattern, and prefer a named version as idiomatic.

## Motivation

Reasons I don't like `name` as second:

* Values are often literals and the `name` will be somewhere on the end of the line, obscuring readability
* Key Value are almost always in key value order. Think hashmaps, keyvalue databases.
* Rust API is similar

## Other

> The implementation is not clear from the usage. If I look at some usage examples, I cannot figure out how the code actually works under the hood.
    Since documentation isn't that extensive yet, people will probably be checking the source code to see how stuff works. This trick is very untransparent and hard to interpret.
    
I think the above concerns can be taken away by improving the docstring. Describing the two behaviors with code snippets, the expected behavior and the implications this may have when creating a DataFrame (in case of un-named Series).
   
> Looking at this dirty hack should make any programmer's skin crawl (no offense sweat_smile ).
  Any auto-doc tools we use will be thoroughly confused by the current setup and incorrectly represent parameter types.

In the absence of generics/ overloading constructors in Python, I think a duck typing approach like this is valid. Looking at the implementation of the @overload decorator it seems to be the same syntatic sugar. I do agree that generics over 2 arguments vs 1 arguments is more confusing, but I think its surmountable with documentation.
  
 >   It's inconsistent with other DataFrame libraries like pandas.
 
 That's ok. :slightly_smiling_face: 

> Allow None as a Series name. That way it's more transparent that no name has been given, and it can be handled better. I give an example in issue
(Python) DataFrame constructor improvements #993 how this impacts DataFrame creation. This might be tricky though, as I believe it hits the Rust implementation.

This would be possible. But would go indeed be a large refactor in Rust. The main pro it would have is that in case of DataFrame creation with a `None` we could replace it with `column_<column_count>`. 

Allow an empty sequence for the values argument. No particular reason; just makes sense to me. This also hits the Rust implementation.

> Agree! This should definitely be possible.

**Comment by ritchie46** [comment]
#998

**Comment by stinodego** [comment]
OK, I will try to improve the documentation on this. I'll extend the docstring with some usage examples.

I do agree with your reasoning for putting `name` first, by the way.

If you consider values first an anti-pattern, why not deprecate it?

**Comment by ritchie46** [comment]
> If you consider values first an anti-pattern, why not deprecate it?

People want to hack and slash away in notebooks and sometimes don't care for the name of the `Series` (myself included). It exists for that reason. Polars thinking: "Ok, its not how it should be, but I understand what you mean :wink:"
